### ISSUE TITLE
[Desktop][Android] Tabs not being sync'd between Android and Desktop

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10707]
## Description 

Creating a sync chain between Desktop and Android doesn't transfer open tabs between devices

## Steps to Reproduce

   1. Create a sync chain on desktop
   2. Create a standalone sync chain on Android and reset it 
   3. Join Android to desktop sync chain using the code words from step 1
   4. Ensure `Sync all` is enabled on both Android and Desktop
   5. Verify bookmarks/history get sync'd between devices
   6. Open tabs from Android is not sync'd to desktop and vice versa

## Actual result:

No tabs sync on either device on the chain

## Expected result:
Without any change to settings done, by default tabs should be sync'd as Sync all is enabled

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Nightly

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the dev channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA 
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@AlexeyBarabash mentioned once he turned on `History` and `Opened tabs`,  he could see opened tabs on all devices.

**Comment by Martina-Neumayer** [comment]
Simiar on my brave.
Stable - don't even start to synchronize Android <-> Arch. You can wait hours or days and nothing happens.
Beta - android browser FC's by setting up the sync chain. Tap on "synchronisation" menu and bums! Force close.

**Comment by AlexeyBarabash** [comment]
Like with issue N10533 I have tried twice with today's master Android and desktop builds  - cannot reproduce.

@srirambv , could you also try it again? Maybe this was fixed be recent PRs for desktop and android.

**Comment by jangorecki** [comment]
@AlexeyBarabash I am having same issue with V1.12.114 on PC. I setup sync (again, so it is probably v2) on android and PC, then my bookmarks got duplicated into mobile bookmarks directory. I clean all up on mobile, but they are not being updated on PC.

**Comment by SandeepJoelFreshdesk** [comment]
Sync still doesn't seem to happen. In MacOS Catalina, in the history section of the brave browser, `tabs from other devices` section is not shown. Can somebody please help ?

**Comment by jangorecki** [comment]
It eventually started to work now. Maybe it needed more time?
Anyway, we need a "sync log" access for understanding status and for debugging.
Please put there as much info as possible.

Also minor thing is that "Bookmarks bar" directory on Android is "Bookmarks" directory on PC, it should have exactly the same name. And I don't thing we need "Mobile bookmarks" directory there, if we sync bookmarks there is no difference, isn't it?

**Comment by urbenlegend** [comment]
I am also hitting this issue. Most of the time, tabs are not synced from Android. The Android device does not show up at all in the Menu -> History section. In very rare occasions, the tabs will be synced and then it will stop syncing again.

Also, if I attempt to send a tab from PC to my Android device, sometimes it takes an hour for the notification to actually arrive, rendering it effectively useless.

**Comment by urbenlegend** [comment]
@jangorecki I discovered that there is a `chrome://sync-internals` page that shows a lot of Sync debug info. I discovered that whenever I have sync issues on Android, the device will show a bunch of `Model Types` listed under `Type Info` with a status of `Backed Off`. Under `Status from Last Completed Session`, it shows that the network was disconnected. However, I am on Wi-Fi most of the time (quarantine, of course), yet this issue of Android not syncing happens quite often!

Also it took quite a while for Brave to attempt a resync after displaying those messages, even though I had the browser active with Wi-Fi connected. Perhaps Brave is waiting too long to re-attempt sync?

**Comment by jangorecki** [comment]
Would be nice to link that page from Brave Sync options then

**Comment by AlexeyBarabash** [comment]
This is a similar issue  https://github.com/brave/brave-browser/issues/12391 

And this is a PR https://github.com/brave/brave-core/pull/7121, will be on Nightly soon.

**Comment by AlexeyBarabash** [comment]
PR https://github.com/brave/brave-core/pull/7121 is merged to Nightly, closing this issue.
