### ISSUE TITLE
[Android] Monthly budget dropdown missing after CR84 upgrade

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10727]
## Description 
Monthly budget dropdown missing after CR84 upgrade

## Steps to reproduce 

   1. Enable Rewards on 1.10.95
   2. Upgrade to 1.11.95
   3. Open rewards settings page, the monthly budget dropdown is missing

## Actual result 
![monthly-budget](https://user-images.githubusercontent.com/17010094/87422216-27cf7c00-c5d0-11ea-9b0d-3899971e2709.gif)

## Expected result
Should show monthly budget dropdown 

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version:10
   
## Brave version
1.11.95

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by NejcZdovc** [comment]
@srirambv this should be fixed in new RC as just today we merged this fix https://github.com/brave/brave-browser/issues/10438

**Comment by SergeyZhukovsky** [comment]
Closing it as it has been fixed in that issue https://github.com/brave/brave-browser/issues/10438

**Comment by srirambv** [comment]
Reopening the issue as it is not fixed on Android and still reproducible on  1.11.98 build

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.11.100 x64 build
- Verified monthly budget dropdown is visible in AC page and settings on a clean install
- Verified monthly budget dropdown is visible in AC page and settings on upgrade from 1.10.99
- Verified changing the monthly budget value is retained between launches
-------------
Verification passed on Samsung Tab A with Android 10 running 1.11.100 x64 build
- Verified monthly budget dropdown is visible in AC page and settings on a clean install
- Verified monthly budget dropdown is visible in AC page and settings on upgrade from 1.10.99
- Verified changing the monthly budget value is retained between launches
