### ISSUE TITLE
[Desktop] Unable to delete/remove created wallet in Crypto wallets

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#10999]
## Description 

Some users are unable to delete/remove a created wallet in crypto wallets. Once reaching the appropriate menu, the `Save` and `Cancel` options disappear and the user is returned to the main page, the wallet is not actually deleted.

## Steps to Reproduce

1. Go brave://wallet/.
2. Click on your profile avatar
3. Click on Settings
4. Click on Contacts
5. Click on My Wallet Accounts
6. Select the wallet you want to view
7. Click Edit
8. Click Delete Account

## Actual result:

User is returned to main page, deleted wallet remains.

## Expected result:
Wallet/account should be removed.

## Reproduces how often: 

Easily (for the user)

## Brave version (brave://version info)

Windows 10 64 Bit Home. Brave Version - [Version 1.11.101 Chromium: 84.0.4147.89 (Official Build) (64-bit)]:

## Version/Channel Information:

- Can you reproduce this issue with the current release? Y
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

Original user report:
https://community.brave.com/t/i-cant-delete-my-2nd-wallet/146316

@ryanml mentions a likely fix in upcoming version update, when we rebase to MetaMask v8:
https://bravesoftware.slack.com/archives/CBP2ZKC0H/p1596040670372800

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.12.114 Chromium: 84.0.4147.135 (Official Build) (64-bit)
-- | --
Revision | `c42bd09b3f24da1698d71d3b4f57402137163566-refs/branch-heads/4147@{#1102}`
OS | Windows 10 OS Version 1809 (Build 17763.1397)
Component | `0.1.68`

- Verified no `Delete account` option is shown in contacts
![image](https://user-images.githubusercontent.com/17010094/90855124-add0a680-e376-11ea-8331-3787d9e24586.png)

-----------------------------

Verification passed on 

Brave | 1.13.75 Chromium: 85.0.4183.69 (Official Build) beta (64-bit)
-- | --
Revision | `4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}`
OS | Linux
Component | `0.1.68`

- Verified no `Delete account` option is shown in contacts
![image](https://user-images.githubusercontent.com/17010094/90854993-5cc0b280-e376-11ea-826d-7ce87f3f5bf8.png)

-----------------------------

Verification passed on 


Brave | 1.14.55 Chromium: 85.0.4183.69 (Official Build) nightly (64-bit)
-- | --
Revision | `4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}`
OS | macOS Version 10.15.5 (Build 19F101)
Component | `0.1.68`

- Verified no `Delete account` option is shown in contacts
![image](https://user-images.githubusercontent.com/17010094/90855118-a7422f00-e376-11ea-834a-f2e73d9a42a3.png)

**Comment by srirambv** [comment]
Fixed via https://github.com/brave/ethereum-remote-client/commit/b6a9d98f2918d1576d67861ee5dd500483ee6f12

**Comment by minimedj** [comment]
The issue is still here.
Tested on: Version 1.16.76 Chromium: 86.0.4240.198 (Official Build) (x86_64)

**Comment by Heten-Daiya** [comment]
@srirambv This issue #10999 has reappeared  for me in Brave Version 1.19.92 Chromium: 88.0.4324.152 (Official Build) (64-bit) on Windows 10 Home Version 20H2 Build 19042.804

![braveWalletErrorReproduce0](https://user-images.githubusercontent.com/34357376/107520033-f86d0600-6bd6-11eb-80b8-d571aa77abd5.jpg)

![braveWalletErrorReproduce1](https://user-images.githubusercontent.com/34357376/107519592-75e44680-6bd6-11eb-90cf-09e057371252.jpg)

On clicking the edit button, there's no delete button there.

![braveWalletErrorReproduce2](https://user-images.githubusercontent.com/34357376/107519624-81377200-6bd6-11eb-92aa-4395a5e252a3.jpg)

**Comment by urbenlegend** [comment]
This is happening to me too. This issue needs to be reopened.

**Comment by unpaid** [comment]
Hello, I am using Brave Version 1.20.103 Chromium: 88.0.4324.152 (Official Build) (64-bit) on Windows 10 Pro Version 20H2 (OS Build 19042.804) and am having the same issue, however it seems I can get the delete button to appear by making the account appear as a contact, though the button does nothing other than delete the contact. I am unsure if this functionality is intentional or not, or perhaps another bug altogether, but I encountered it while trying to delete the wallet. The steps I used to reproduce this is as follows:
1. Go to brave://wallet/
2. Click on your profile avatar
3. Click on Settings
4. Click on Contacts
5. Click on My Wallet Accounts
6. Select the wallet you want to delete
7. Click Edit
8. Click Save
9. Click on Contacts
10. Select the wallet you want to do delete
11. Click Edit

![Screenshot 2021-02-18 043129](https://user-images.githubusercontent.com/35709143/108253804-e88c8d80-71a5-11eb-8670-d03e72f0671b.png)

**Comment by bsclifton** [comment]
cc: @bbondy

**Comment by srirambv** [comment]
Added a note from @unpaid in #14141 so we can continue the conversation there. This issue was specifically to remove the delete button.

**Comment by ranrinc** [comment]
I dont see any delete wallet button. Is this feature have been disable? Need to remove the wallet

**Comment by megmaltese** [comment]
Why is this closed?
I find it incredible that the easiest thing of all, to remove the wallet altogether, is not implemented.
And the issue here closed!
What the hell?

**Comment by bsclifton** [comment]
This issue was for the older "MetaMask" fork version of wallet (Crypto Wallet). There is a new Wallet feature in Brave which is not an extension.

Under brave://settings/wallet you can pick `None` for `Default cryptocurrency wallet` and you should be good to go
![image](https://user-images.githubusercontent.com/4733304/142822421-622e8922-d5a3-47ea-9262-5b9cae49d4d2.png)

cc: @jamesmudgett

**Comment by bbondy** [comment]
Yes to the default cryptocurrency wallet setting mentioned above and you can also turn off the Show Brave Wallet icon on toolbar if you want to get rid of it

**Comment by anishp55** [comment]
how do we DELETE/REMOVE an existing wallet.  not disable the whole extension.   I am quite surprised this is still an issue after a year.

**Comment by Ayern12** [comment]
No..

Pada Ahd, 28 Nov 2021, 12:52 anishp55 ***@***.***> menulis:

**Comment by anishp55** [comment]
no what?

**Comment by Ayern12** [comment]
Don't delete My wallet..

Pada Ahd, 28 Nov 2021, 12:55 anishp55 ***@***.***> menulis:

**Comment by anishp55** [comment]
no one is deleting your wallet.  this is a feature request to be able to delete a wallets inside of the brave browser.

**Comment by zvikasdongre** [comment]
Any update, guys?

**Comment by afuego** [comment]
Reset the Brave wallet, make sure you back up your data.

**Comment by lumos7** [comment]
is this still not possible?
