### ISSUE TITLE
Next payment date is null in Ads panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#11062]
## Description 

Next payment date is null in Ads panel

## Steps to Reproduce

   1. Clean profile 1.14.x
   2. Enable rewards
   3. Next payment date is null in Ads panel

## Actual result:

Next payment date is null in Ads panel
![image](https://user-images.githubusercontent.com/38657976/89214747-02d59400-d5e5-11ea-90de-e024ffcf5be9.png)

## Expected result:

Next payment date should not be null in Ads panel
## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.14.12 Chromium: 84.0.4147.105 (Official Build) nightly (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Windows 10 OS Version 1903 (Build 18362.959)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @tmancey @NejcZdovc @emerick

**Comment by LaurenWags** [comment]
@tmancey is this related to the issue you mentioned with confirmations not being initialized on Nightly?

**Comment by tmancey** [comment]
This is related and will be resolved when we merge https://github.com/brave/brave-core/pull/6248 hopefully later today

**Comment by tmancey** [comment]
Resolved by https://github.com/brave/brave-browser/issues/9870

**Comment by kjozwiak** [comment]
@tmancey I don't think this is resolved.. I'm still running into the same thing with https://github.com/brave/brave-browser/releases/tag/v1.14.21 which includes https://github.com/brave/brave-core/commit/58668b77f117119491634a985cee725a4b382624. Used the following build:

```
Brave | 1.14.19 Chromium: 84.0.4147.105 (Official Build) nightly (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.15.6 (Build 19G73)
```

<img width="809" alt="Screen Shot 2020-08-06 at 2 04 14 AM" src="https://user-images.githubusercontent.com/2602313/89497272-00606f00-d78a-11ea-8d96-d6e6e4ba4280.png">

I don't see anything related to confirmations other than the following when attempting to view an ad:

```
[86763:775:0806/020438.570178:VERBOSE1:ads_impl.cc(337)] Browser state changed to idle
[86763:775:0806/020439.570132:VERBOSE1:ads_impl.cc(346)] Browser state changed to unidle
[86763:775:0806/020439.571556:VERBOSE1:ads_impl.cc(1047)] Ad notification not shown: Confirmations not ready
```

@GeetaSarvadnya can you still reproduce on `Win x64` using https://github.com/brave/brave-browser/releases/tag/v1.14.21?

**Comment by GeetaSarvadnya** [comment]
@kjozwiak Issue is still reproducible on both `1.14.19` and `1.14.21` nightly builds.

**Comment by kjozwiak** [comment]
Just tried the above using `1.14.21 CR: 84.0.4147.105` on a call with @tmancey and things are working as expected 👍 Confirmed a several times.

* `1.14.19 CR: 84.0.4147.105` - Reproduced the issue several times
* `1.14.21 CR: 84.0.4147.105` - Couldn't reproduce after several attempts

Build used:

```
Brave | 1.14.21 Chromium: 84.0.4147.105 (Official Build) nightly (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.15.6 (Build 19G73)
```

**Comment by GeetaSarvadnya** [comment]
The issue is partially fixed on `1.14.21` - Issue is still reproducible in `Windows 10 x64`

As soon as enabling rewards, Ads panel shows the empty `Next payment date` for a few seconds. After that date will reflect in the `Next payment date` filed. Logged an issue https://github.com/brave/brave-browser/issues/11107.

**Comment by kjozwiak** [comment]
Awesome, thanks @GeetaSarvadnya 👍 Going to close this off and move it into `1.12.x` as it was fixed by https://github.com/brave/brave-core/pull/6248 as per https://github.com/brave/brave-browser/issues/11062#issuecomment-669197891 which was also uplifted into `1.12.x`.

**Comment by NejcZdovc** [comment]
@kjozwiak this needs to stay in 1.14 as https://github.com/brave/brave-core/pull/6248 was merged in 1.14 and will not be uplifted

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.14.67 Chromium: 85.0.4183.83 (Official Build) dev (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

```
- Verified the issue from the description
![image](https://user-images.githubusercontent.com/38657976/91594540-b41ae000-e97f-11ea-92b2-3136005b2faa.png)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.14.82 x64 build
- Verified steps from issue description
![image](https://user-images.githubusercontent.com/17010094/93429754-8efffa00-f8b9-11ea-95b6-84e7ccb58759.png)
