### ISSUE TITLE
[Desktop] top sites should not move when toggling clock on/off

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#11484]
## Description 

Top sites position on the new tab page changes when toggling the clock widget on/off.

## Steps to Reproduce

   1. Open a new tab page
   2. Open "Customize Dashboard" panel
   3. Navigate to "Clock" section
   4. Toggle clock on/off to see top sites shifting position

## Actual result:

![2020-08-27 12-10-40 2020-08-27 12_12_55](https://user-images.githubusercontent.com/2388823/91484854-c05b4c00-e85e-11ea-8568-fef2d5e13b73.gif)

## Expected result:
Top sites should not move

## Reproduces how often: 

Easily reproduced

## Desktop Brave version:

latest build - Version 1.15.15 Chromium: 85.0.4183.83 (Official Build) nightly (64-bit)

## Android Device details:
N/A

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes 
- Can you reproduce this issue with the beta channel?  yes
- Can you reproduce this issue with the nightly channel?  yes

Reproducible on all channels

Last channel which didn't have this issue was Release Version 1.11.101 Chromium: 84.0.4147.89 (Official Build) (64-bit) - after I updated the Release build to latest this issue appeared

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A 
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by cjwijtmans** [comment]
imo brave stats should also not move upwards.

**Comment by SamuelScotts** [comment]
I'm going to try and take a look at this.

**Comment by jte0711** [comment]
Hi, is there anyone working on this? if not, can I take this (my first issue)?

**Comment by ryanml** [comment]
Hi @jte0711 feel free to take a stab at it! You can ping me if you have any questions.

**Comment by jte0711** [comment]
Hi @ryanml, I think I find out how to fix it, but while doing `npm run init` for the repo I got an error. Should I ask about it here or should I post it somewhere else?

**Comment by ryanml** [comment]
@jamesgeorge007 what is the error you’re getting?

**Comment by ryanml** [comment]
@jte0711 you may actually be able to fix and test this by just using our front end storybook. 

You can do `git clone https://github.com/brave/brave-core && cd brave-core/ && npm install && npm run storybook` - live reloading is supported. This will be much less cumbersome then compiling the whole thing :)

**Comment by jte0711** [comment]
@ryanml This is the error I got:

`1 failed patches:
chrome/VERSION

- Patch applied because: No corresponding .patchinfo file was found.
- Error - Program git exited with error code 1.
error: patch failed: chrome/VERSION:1
error: chrome/VERSION: patch does not apply

---

Done applying patches.
Exiting as not all patches were successful!
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brave-core@1.16.39 sync: `node ./build/commands/scripts/sync.js "--init"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the brave-core@1.16.39 sync script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\username\AppData\Roaming\npm-cache\_logs\2020-10-07T09_22_49_872Z-debug.log
null
null
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brave@1.16.39 init: `node ./scripts/init.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the brave@1.16.39 init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\username\AppData\Roaming\npm-cache\_logs\2020-10-07T09_22_50_019Z-debug.log`



> @jte0711 you may actually be able to fix and test this by just using our front end storybook.
> 
> You can do `git clone https://github.com/brave/brave-core && cd brave-core/ && npm install && npm run storybook` - live reloading is supported. This will be much less cumbersome then compiling the whole thing :)

Oh cool, thanks for letting me know. I'll try it.

**Comment by bsclifton** [comment]
Not sure what fixed it - but this is definitely fixed now 😄

**Comment by karenkliu** [comment]
I'm still getting this issue :( 

Version 1.25.13 Chromium: 90.0.4430.70 (Official Build) nightly (x86_64)

![design QA 8](https://user-images.githubusercontent.com/2388823/114615106-1f3ccc80-9c5a-11eb-8727-4bfcbc0de4be.gif)

**Comment by LaurenWags** [comment]
@karenkliu does it still reproduce for you in 1.29.x? I couldn't reproduce with 

```
Brave | 1.29.65 Chromium: 92.0.4515.159 (Official Build) dev (x86_64)
-- | --
Revision | 0185b8a19c88c5dfd3e6c0da6686d799e9bc3b52-refs/branch-heads/4515@{#2052}
OS | macOS Version 10.15.7 (Build 19H1323)
```

**Comment by LaurenWags** [comment]
Thanks @karenkliu - I can reproduce on Nightly 1.31.10 Chromium 93.0.4577.58 but not Beta 1.30.58 Chromium: 93.0.4577.58. Maybe related to something on Nightly channel.

**Comment by fallaciousreasoning** [comment]
Hey, this seems to be fixed in 1.58.32 - I'm not sure what by because I remember seeing this recently.

**Comment by MadhaviSeelam** [comment]
Reproduced the issue of top sites move when toggling clock on/off in Win 11 x64 in 

- `1.68.131 Chromium: 127.0.6533.73 (Official Build) (64-bit)` &
- `1.69.125 Chromium: 127.0.6533.73 (Official Build) beta (64-bit)`

However, if I turned off cards via Customize dashboard and toggle clock on/off, top sites remain intact and doesn't move

**Enabled Rewards & Brave Talk cards**
- enabled and disabled clock
- top sites moved

1.68.x 
------
https://github.com/user-attachments/assets/ae944dfa-2956-4aaf-b8dc-235c641c1841


**Disabled Rewards & Brave Talk cards**
- enabled and disabled clock
- top sites did not move

1.69.x 
-----
https://github.com/user-attachments/assets/59b6c267-a81c-46a8-8c9b-4d17c501af86

**Comment by rebron** [comment]
Closing as wontfix, no longer applicable with new design https://github.com/brave/brave-browser/issues/41483
