### ISSUE TITLE
[Desktop] Poor performance on Fedora 32 after upgrade to Brave 1.13.82

### ISSUE THREAD

**Issue by mbacchi** [brave/brave-browser#11510]
## Description 

After upgrading to 1.13.82 overall performance will degrade to the point that switching between tabs takes 3 seconds, tabs crash frequently after being open for some time(especially tabs with sites like gmail, twitter), and clicking dropdown menus takes a long time. Restarting the browser often helps but sometimes within 5 minutes switching between tabs can take as long again.

This was first noticed after the upgrade to the 1.13.82 version on 2 machines running Fedora 32. Sync was enabled for the first time on both machines in the last week, and both machines are currently running sync(for bookmarks and plugins only.) On one machine I have 2 profiles, and on the other machine I only have 1 profile. All profiles seem to be slowed down by this issue.

I have started Brave from the commandline and when things get slow there is nothing in the STDOUT/STDERR that seems to be related but I am pasting that here for reference. I also looked at the output of the `top` command when things got slow and there doesn't seem to be any brave processes that are using a lot of RAM or CPU, nothing currently more than 1.9% of RAM and 5.9% of CPU.

```
[user@host]$ brave-browser &
[1] 676873
[user@host]$ [676912:676912:0829/170128.808838:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[676884:676884:0829/170129.093692:ERROR:sharing_service.cc(260)] Device registration failed with fatal error
[676912:676912:0829/170131.437566:ERROR:gl_surface_presentation_helper.cc(259)] GetVSyncParametersIfAvailable() failed for 1 times!
[676912:676912:0829/170131.478615:ERROR:gl_surface_presentation_helper.cc(259)] GetVSyncParametersIfAvailable() failed for 2 times!
[676912:676912:0829/170131.485287:ERROR:gl_surface_presentation_helper.cc(259)] GetVSyncParametersIfAvailable() failed for 3 times!
[676912:676912:0829/170151.644034:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x193cdcf28500] GL_INVALID_OPERATION: Framebuffer is incomplete.
[676912:676912:0829/170151.644525:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x193cdcf28500] GL_INVALID_OPERATION: Framebuffer is incomplete.
[676912:676912:0829/170151.648205:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x193cdcf28500] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
[676884:676884:0829/170222.712701:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data. Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[676884:676884:0829/170222.712793:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data. Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[676884:676884:0829/172850.440317:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data. Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[676884:676884:0829/172850.440375:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data. Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[676884:676884:0829/172850.440418:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data. Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[676884:676884:0829/172857.624937:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: No tab with id: 489.", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/_generated_background_page.html (0)
[676884:676884:0829/172859.649082:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: No tab with id: 489.", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/_generated_background_page.html (0)
[676884:676884:0829/172859.649139:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: No tab with id: 489.", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/_generated_background_page.html (0)
[676884:676884:0829/172859.650327:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: No tab with id: 489.", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/_generated_background_page.html (0)
[676884:676884:0829/173827.629278:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data. Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[676884:676884:0829/173827.629348:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data. Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[676884:676884:0829/173827.629380:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data. Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
```
 
I'd be willing to perform debugging if there is anything that I can assist with.

## Steps to Reproduce

   1. Start Brave
   2. Wait some time
   3. Performance degrades after 5 minutes (I have not determined the exact amount of time, or if the time before degradation varies)

## Brave version (brave://version info)

Version 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit)

## Version/Channel Information:

Release (Have not tried other channels)

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Haven't tried
- Can you reproduce this issue with the nightly channel? Haven't tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? Not enabled on either machine
- Is the issue reproducible on the latest version of Chrome? No

**Comment by ewoks** [comment]
I see described performance issue with Google Chrome 85.0.4183.83 (exactly same version) so most probably it is chromium fault

**Comment by mbacchi** [comment]
Thanks @ewoks it looks eerily similar to Issue [1121782: Chrome on Linux unusably slow after upgrading to 85.0.4183.83](https://bugs.chromium.org/p/chromium/issues/detail?id=1121782). I'm running Wayland, using multiple windows and many tabs in each window. I'll try this on Brave Beta channel and see whether I get better performance.

**Comment by bsclifton** [comment]
I believe this is a duplicate of https://github.com/brave/brave-browser/issues/11504 - but not sure... @mbacchi can you check the notes there? Basically, there are shared objects missing from the .zip; seems like upstream problem that we'll need to address. Thanks for finding/sharing the upstream bug 😄

**Comment by mbacchi** [comment]
Sorry just saw your comment @bsclifton. It doesn't look like the same problem to me during a cursory investigation. Unlike #11504(which appears to be Deb and zip packages not RPM) I have the shared libraries `libEGL.so` and `libGLESv2.so` in the `/opt/brave.com/brave/swiftshader/` directory. I also see in brave://gpu that Hardware acceleration is enabled for both WebGL and WebGL2. It appears to me to be more like the Chromium bug https://bugs.chromium.org/p/chromium/issues/detail?id=1121782. I'll try some more testing with the Chromium bug suggestions when I have a moment.

**Comment by ewoks** [comment]
any updates on this issue?

**Comment by bsclifton** [comment]
@ewoks if the fix from https://bugs.chromium.org/p/chromium/issues/detail?id=1121782 solves this, it'll be available in version 1.15 which we're aiming to ship October 6th. Should already be solved on Beta / Nightly. Hang tight 😄

**Comment by rebron** [comment]
@ewoks The fix for this is live with 1.15.72. Can you let us know if you're still having issues?

**Comment by mbacchi** [comment]
I still see the same performance on 1.15.72. If I pass the arguments `--use-cmd-decoder=validating --use-gl=desktop`, I see much better performance when running a 2nd window. Without those arguments the `GL_RENDERER` is ANGLE, with them it is Mesa.

I'm using Wayland, I could also test on Xorg but would have to logout.

**Comment by Pyrollisahfiros** [comment]
Came here because I have the same issues as mbacchi has. However, I've noticed this issue started when I upgraded from Fedora 30 to Fedora 32 and I initially thought it was because of the upgrade (I usually have bad experience with upgrading, rather than doing a clean install) so I decided to do a clean install of Fedora 32 on another HDD. Tried Brave again and it appears to be doing the same issue mbacchi described. 

Browsing with one window would go smoothly and normally but when I open a 2nd window, the browser appears sluggish for a few seconds (on both windows, not just one) then back to normal but every time I open a new tab, it becomes sluggish. Closing the 2nd window reverts the original browser window back to normal. This instance has been repeated on the upgraded Fedora 32 HDD and the clean install Fedora 32 HDD (total of 2 HDDs on the same computer). Did not have this issue on Fedora 30 but before I upgraded, I didn't look at the build number for Brave. I had assumed it was current so I can't tell you if I was using an older Brave build prior to upgrading to Fedora 32 or not. Both versions of Fedora are on Wayland. 

Let me know if you need additional info on Fedora but it's just a vanilla install. I didn't modify the kernel prior to installing Fedora or anything. I just used the .ISO that I downloaded off Fedora's website. Also the upgrade took place a week before this comment (10/19) and the clean install took place today (10/25).

**Comment by Pyrollisahfiros** [comment]
> I still see the same performance issue on 1.15.72. If I pass the arguments `--use-cmd-decoder=validating --use-gl=desktop`, I see much better performance when running a 2nd window. Without those arguments the `GL_RENDERER` is ANGLE, with them it is Mesa.
> 
> I'm using Wayland, I could also test on Xorg but would have to logout.

@mbacchi Thanks for this! Tried it out and it works for now! Hopefully the bug gets fixed soon!

**Comment by mbacchi** [comment]
This is still an issue FYI, and I see a comment in the above Chrome bug https://bugs.chromium.org/p/chromium/issues/detail?id=1121782#c65 that a new issue was opened to track problems with VSync control, but I cannot see that issue (which is https://bugs.chromium.org/p/chromium/issues/detail?id=1137851, I get "Permission denied" so it must be security related?)

Just wanted to point out that there is a new issue that maybe someone here can view although I cannot.

**Comment by Redbatman89** [comment]
On Pop os 20.04 Im also getting the [shields]: can't request shields panel data. error: no tab url specified", source: chrome-extension:/

Why is this happening?

**Comment by mbacchi** [comment]
This appears to me to be resolved. I can now have multiple windows open with no obvious performance problems. @bsclifton

**Comment by bsclifton** [comment]
Thanks for the update, @mbacchi! 😄
