### ISSUE TITLE
[Desktop] MacOS right command key closes bookmarks bar folders

### ISSUE THREAD

**Issue by dentistformyeye** [brave/brave-browser#11687]
## Description 

When opening a folder from the bookmarks bar, including the overflow folder, pressing the right command key on a MacOS keyboard closes the folder and any outer folders. The command key is useful for opening bookmarks in a new tab without having to reopen a folder each time.

## Steps to Reproduce

   1. Click to open a bookmarks folder.
   2. While holding the left command key, click a bookmark in the folder.
   3. Tap the right command key.

## Actual result:

Step 2 works as expected. Step 3 closes the folder.

## Expected result:
Step 2 opens the clicked bookmark in a new tab but doesn't close the folder. Step 3 does nothing.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | macOS Version 10.15.6 (Build 19G73)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Haven't tried.
- Can you reproduce this issue with the beta channel? Haven't tried.
- Can you reproduce this issue with the nightly channel? Haven't tried.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? Haven't tried.

**Comment by rebron** [comment]
This repros in Chrome. Can wait for an upstream fix when addressed with a chromium update.

**Comment by bsclifton** [comment]
@dentistformyeye do you know if this is still an issue? I didn't see this issue specifically in Chromium bug tracker, but I saw some similar ones that were fixed with Chromium 88. It might be fixed

**Comment by dentistformyeye** [comment]
It's still happening for me on Brave version 1.19.92 (CR 88.0.4324.152). It also happens on another Chromium browser I use that's on a slightly earlier version of 88.

**Comment by Brave-Matt** [comment]
@rebron any particular reason we have to wait for this to be fixed upstream? Still repros in Chrome and other Chromium browsers but seems like something we can address ourselves?
