### ISSUE TITLE
New Tip feature in Twitter constantly winks on and off.

### ISSUE THREAD

**Issue by Aionaptara** [brave/brave-browser#12040]
## Description 
Evidently, Brave added the Tip feature to Twitter and it's driving me batty. It constantly winks on and off every few seconds, shifting the icons on the bottom left and right constantly.

## Steps to Reproduce

   1. Visit Twitter. It's always on and never stops.
   

## Actual result:

<img width="608" alt="Screen Shot 2020-10-07 at 1 39 54 PM" src="https://user-images.githubusercontent.com/72518956/95367413-bb98a780-08a2-11eb-8962-7de2ed33f339.png">
<img width="613" alt="Screen Shot 2020-10-07 at 1 40 29 PM" src="https://user-images.githubusercontent.com/72518956/95367432-c2bfb580-08a2-11eb-8aab-8add9dba0574.png">

It just cycles between these two.

## Reproduces how often: 

Every second or two.

## Brave version (brave://version info)

1.14.84

## Miscellaneous Information:
Is there any way to turn this feature off, at least just for Twitter, because it's driving me nuts. I've poked around at just about every control I can find, but I cannot find an off switch.

**Comment by ccampbell** [comment]
I have it disabled, but it still shows up and starts blinking on and off! For anyone trying to disable it it is under brave://rewards and then tip settings.

<img src="https://user-images.githubusercontent.com/259316/95369380-5d20f880-08a5-11eb-8290-cf071f89a825.png" width="340" />

**Comment by chkk525** [comment]
I got the same issue from another user on Twitter yesterday.

**Comment by NejcZdovc** [comment]
this should be fixed in 1.16

**Comment by matthew-goldman** [comment]
I'm on 1.18 and this is still not fixed. I've unchecked all three tip options (reddit/github/twitter) and the BAT icon persists, even after restart of the browser.

**Comment by bsclifton** [comment]
@emerick @zenparsing do you know if this is still an issue?

**Comment by emerick** [comment]
@bsclifton No, this one's been fixed for a while - I think we can safely close it.
