### ISSUE TITLE
[BUG] mouse hover on a link brings the window to top when the window is not active!

### ISSUE THREAD

**Issue by kicsiede** [brave/brave-browser#12216]
## Description 
when having multiple brave windows open whenever i (unintentionally) hover over a link of a different brave window, that window is brought to front. (sometimes even hiding the active brave window which is extremely frustrating)

## Steps to Reproduce

   1.  open multiple brave windows with links (anchor elements in the html), make the windows overlap
   2.  activate one of the windows
   3.  move the mouse over a link on one of the bottom brave windows

## Actual result:

more often than not, the other window automatically pops to top. (the original window remains active though)

## Expected result:

window order should not be affected when not clicking the window!

## Reproduces how often: 

this happens almost every time. sometimes needs a couple seconds of fiddling on the active brave window before the issue manifests on another window.

## Brave version (brave://version info)

Version 1.15.75 Chromium: 86.0.4240.99 (Official Build) (64-bit)
(windows 7 professional)

## Version/Channel Information:

- Can you reproduce this issue with the current release? YES
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? NO
- Is the issue reproducible on the latest version of Chrome? NO

## Miscellaneous Information:
i could reproduce the issue with this simple test file attached:
[brave_bug.zip](https://github.com/brave/brave-browser/files/5409221/brave_bug.zip)

i've also tried disabling all hovering related features in the experimental settings (flags) to no avail.

**Comment by ftpguy** [comment]
I am having this issue as well, and this report accurately describes my experience in reproducing it. There are many reports of this bug, most of which are from Brave's Reddit forum. Support staff appears to be blatantly ignoring the reports. Sadly, Brave is such a good browser that I've suffered this bug for probably almost a year (this didn't always occur), but it's becoming so unbearable now that I am really considering switching exclusively to Firefox. This issue does NOT occur in Chrome which is also based on Chromium, so the issue is definitely with Brave itself.

Here's a GIF showing the problem. Notice how the left window is initially on top. I then highlight the address bar and move the cursor offscreen to the window in the background. Without me clicking anything (ie, just hovering the mouse), it brings the other window to the foreground. However, even though the window on the left is visibly in the background, it is STILL the active window as illustrated by me typing into the address bar.

![rUGGDAZ](https://user-images.githubusercontent.com/39510308/97768006-5711e680-1af6-11eb-806a-0dc2abce5bc9.gif)

If any Brave staff are actually monitoring these reports, PLEASE stop ignoring the reports and FIX IT.

**Comment by hypov8** [comment]
i getting the same issue here.
windows 7 x64.

**Comment by duc811997** [comment]
#

**Comment by bsclifton** [comment]
Looking for upstream reports (in Chromium issue tracker). Is everyone experiencing this problem on Windows 7?

Will update this issue as I find related issues:
- [Issue 1147924: Unwanted window hover activation](https://bugs.chromium.org/p/chromium/issues/detail?id=1147924)

**Comment by Scheif** [comment]
I am a new user that is also experiencing this issue, and it's driving me crazy.  Please don't ignore this bug.

I am also on Windows 7 64 (Professional).  Pretty good correlation here.

**Comment by cryptonewbiedabbler** [comment]
It appears that this problem was fixed but has come back at least with the latest release! I just started noticing this problem a maybe couple days ago and got annoyed enough to do a web search and came across this page. I'm on version 
Version 1.29.77 Chromium: 93.0.4577.63 (Official Build) (64-bit)
Please fix this problem!

**Comment by IronicTrout** [comment]
Came back for me too. Version 1.29.77 Chromium: 93.0.4577.63 (Official Build) (64-bit) on windows 10 64 bit.

**Comment by ForkedLightning** [comment]
Problem still exists with Brave 1.43.89 on Windows 7 Professional 64bit.

**Comment by hypov8** [comment]
does the chromium build cause the same issue? 
https://download-chromium.appspot.com/
the bug is not present for me in the chromium builds i tested.

is there any info on how to build and debug this in visual studio?
