### ISSUE TITLE
[Android] Supported Links not Opening in External Apps

### ISSUE THREAD

**Issue by Hazbelll** [brave/brave-browser#12330]
## Description 
When following a link that is supported (and configured to open) in an installed app, the link is not passed to that app, but instead Brave opens it instead.

For simplicity, the reproduction steps below will demonstrate the issue for YouTube specifically, however **_all_** links and their corresponding apps are affected the same way.

## Steps to reproduce 

   1. Ensure the official YouTube app is installed and set to open supported links (Settings > Apps and notifications > YouTube > Open by default > Open supported links > Allow app to open supported links).
   2. Visit a search engine (DuckDuckGo, Google, Bing, etc.).
   3. Search for something that returns video results from YouTube (Such as "cool videos").
   4. Tap on any YouTube video link to open it.

## Actual result 
The selected link will open in Brave (m.youtube.com).

## Expected result
The selected link will open in the YouTube app (com.google.android.youtube).

## Issue reproduces how often 
Easily reproduced.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version?: Yes. 
- Can you reproduce this issue with the current Play Store Beta version?: Yes (According to other users).
- Can you reproduce this issue with the current Play Store Nightly version?: Yes (According to other users).

## Device details
   - Install type (ARM, x86): ARM64
   - Device type (Phone, Tablet, Phablet): Phone (Google Pixel 3a)
   - Android version: 11 (RP1A.201005.004)
   
## Brave version
1.15.76

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?: No.
- Does the issue resolve itself when disabling Brave Rewards?: No.
- Is the issue reproducible on the latest version of Chrome?: No (According to other users).

### Additional information

Others facing the same issue can be found on Brave's Subreddit [here](https://www.reddit.com/r/brave_browser/comments/jc8spn/mobile_brave_wont_open_youtube_links_in_youtube/) and [here](https://www.reddit.com/r/brave_browser/comments/j19s8h/brave_android_how_can_i_open_links_with_different).

**Comment by Hazbelll** [comment]
Found another user who has reported this issue on Brave's own forum [here](https://community.brave.com/t/youtube-app-links-not-working-in-pixel-4a/173759).

**Comment by srirambv** [comment]
Can you try disabling `Video playback in Brave` under site settings (last option). This is enabled by default. 
![image](https://user-images.githubusercontent.com/17010094/97273380-2fd3c480-182b-11eb-9b2e-b7bd26ab6028.png)

**Comment by Hazbelll** [comment]
@srirambv This has already been disabled, and others have confirmed the same in the above links.

As stated in the OP too, this issue is **_not_** just specifically YouTube links. Wikipedia, Facebook, Twitter, etc. all suffer the same issue.

**Comment by jordanbtucker** [comment]
I have this same issue on a Pixel 3a. I also have Video playback in Brave disabled.

**Comment by Hazbelll** [comment]
@srirambv Please remove the '_needs-more-info_' tag from this issue as it has been provided, unless further clarification is required?

**Comment by Hazbelll** [comment]
Another user facing this issue can be found [Here](https://www.reddit.com/r/brave_browser/comments/jiy335/brace_can_no_longer_open_some_external_apps_bankid/).

As they mention, it seems certain links that open the Play Store to recommend the user to download an App still works.

I just tested by opening a link to a Reddit thread in Brave, to which the webpage nags me to download the official Reddit app. When tapping the link to do so, the Play Store is opened to the official Reddit app's download page successfully.

Unsure if this might be related, although following any links that would normally open a corresponding installed app still fail. Brave might incorrectly open the Play Store when following such links instead of opening in an installed app that can handle the followed link.

**Comment by Hazbelll** [comment]
@srirambv Has anyone from the Brave Team been able to successfully reproduce this issue?

Is there anything else we could do to assist?

**Comment by srirambv** [comment]
I can't reproduce with YT links. This is what I see on the current release build

@Hazbelll let me know if I am doing anything different? 
![yt](https://user-images.githubusercontent.com/17010094/97661792-3782ab80-1a6d-11eb-8f46-be540949b5e5.gif)

>  opening a link to a Reddit thread in Brave, to which the webpage nags me to download the Reddit app

Unfortunately, that is something the site has made up mind to annoy users with and opening playstore is right if you don't have the app installed. If installed it should switch to the app

**Comment by jordanbtucker** [comment]
I've followed those same steps, and it's still not opening m.youtube.com links in the YouTube app.

**Comment by Hazbelll** [comment]
@srirambv I too have followed your steps, same as @jordanbtucker and too experience links opening in m.youtube.com instead of the YouTube app.

Are you able to test with other apps other than YouTube? For example, Wikipedia using the same steps.

Very interesting to see this issue has suddenly appeared for some users, but not all. I wonder why.

**Comment by Hazbelll** [comment]
@srirambv @jordanbtucker Would you mind stating what version of Android is running on your devices?

I'm on 11 myself.

**Comment by jordanbtucker** [comment]
Android 11 on a Pixel 3a.

**Comment by Hazbelll** [comment]
Another user facing this issue [Here](https://community.brave.com/t/brave-browser-on-android-11-oneplus-8t-not-opening-mobile-banking-app/175368).

I'm starting to believe this issue only occurs for Android 11 users. It looks like everyone affected is running a device with the latest Android OS anyway.

@srirambv Please comment.

**Comment by Hazbelll** [comment]
Another report [Here](https://www.reddit.com/r/brave_browser/comments/jcqjyv/brave_on_google_pixel_4a_wont_redirect_to_proper/).

Again, running Android 11.

**Comment by Dayofthejackalope** [comment]
Same issue here. Tested with both YouTube and Wikipedia apps. Works in Chrome. 
Brave 1.15.76
Android 11; build RP1A.201005.006
Pixel 4a

**Comment by Hazbelll** [comment]
@bsclifton Perhaps you could elevate the severity of this issue?

It's affecting many users that are using a combination of Brave Version 1.15.76 (Or newer) and Android 11 (On any device).

We are happy to assist in any way possible.

**Comment by Hazbelll** [comment]
Issue persists in Brave Version 1.16.70.

@srirambv @bsclifton Would greatly appreciate this issue not be ignored considering this isn't BAT/Rewards related...

**Comment by bsclifton** [comment]
@deeppandya are you able to reproduce this on Android 11?

**Comment by srirambv** [comment]
I have tried the steps on Pixel 3xl with Android 11 and OnePlus 6T with Android 10 and can't reproduce. For YT it always switches to the YouTube app. Tried disabling and force stop Brave and tried again it works. I do notice this prompt for Wiki page and selecting Wikipedia always opens the links in the dedicated app. 
![image](https://user-images.githubusercontent.com/17010094/97829368-bff98a00-1cc1-11eb-90b9-0ab1f8ae1b96.png)


The one thing that folks can try is force stop Brave and clear storage and try again but it would be like resetting the app so everything will be nuked(bookmarks/history/rewards)

**Comment by jordanbtucker** [comment]
I have already tried resetting the app and configuring the proper settings, but it still won't open YouTube links in the YouTube app.

**Comment by srirambv** [comment]
+1 from @eturk1 via #12446

**Comment by said50** [comment]
Also banking site that has a button "Click here to pay with your banking app" doesn't work. Nothing happens when I spam that button. Disabled Brave shield, issue still persists. It's working fine on chrome. The url is bancontact.girogate.be
Same with Philips Hue app. The app asks me to sign in, it opens brave, when I sign in it doesn't redirect me back to the app.

**Comment by Hazbelll** [comment]
Thank you @bsclifton and @srirambv for casting attention to this issue! Incredibly strange you are not expecting this issue @srirambv, even on Android 11.

I and others can confirm (@jordanbtucker and a User [Here](https://www.reddit.com/r/brave_browser/comments/j19s8h/brave_android_how_can_i_open_links_with_different/)) that resetting Brave to its initial state does _not_ correct the issue.

This issue began with the release of Brave Version 1.15.76 so perhaps might be worth looking into what changed that could be causing this?

**Comment by eturk1** [comment]
@Hazbelll 
Confirmed. Removing and reinstalling stable, beta, nightly does not change the issue of Brave not opening apps.

---------------
> +1 from @eturk1 via #12446
Thanks for closing #12446 & tagging me here. 


Pixel 4 XL / Android 11

**Comment by Hazbelll** [comment]
@deeppandya Are you able to reproduce this issue?

**Comment by deeppandya** [comment]
@bsclifton @Hazbelll I tried to open YouTube link from twitter on latest build from play store and it redirected to m.youtube.com instead of opening the YouTube app.

**Comment by Hazbelll** [comment]
@deeppandya Thank you for your response! I assume you mean Twitter within Brave and not the App?

It sounds like you have successfully reproduced this issue, although I'm unsure what the real cause is now @srirambv confirmed they were unable to reproduce the issue on Android 11.

Again, this issue was introduced in Brave Version 1.15.76 and a User already confirmed [Here](https://community.brave.com/t/brave-for-android-v1-15-75-breaks-app-link-association/173121/2) downgrading to below this version resolved the issue, but of course is only a workaround and not a fix.

**Comment by Hazbelll** [comment]
Another report [Here](https://www.reddit.com/r/brave_browser/comments/jntd6z/issues_opening_up_apps_through_brave_andrpid/).

@bsclifton @deeppandya @srirambv Please provide transparency as to why this Issue appears to be of low priority/not of concern considering it's affecting many users now as is apparent from the comments and links provided here, in addition to disrupting workflow for all those affected.

I'm getting really tired of having to constantly nudge you all, as I'm sure you are too.

**Comment by bsclifton** [comment]
@Hazbelll assigned a priority 3 - definitely something we want to fix. If you look at the issue log, we have over 2,600 issues and for each report we need to assess the impact to users and prioritize. My apologies for not responding sooner on here - there have been a lot of other problems (like reCAPTCHA being shown all the time, Chromium upgrades, etc) that take priority

@deeppandya maybe you can help narrow it down. Is this Android 11 specific? Seems to be. @srirambv are you on Android 11?

**Comment by Hazbelll** [comment]
@bsclifton Thank you kindly for your response and escalating the issue. I do respect you and the team have many other concerns and must prioritise accordingly (Especially Chromium Updates/reCAPTCHA issues which are understandable), but the lack of transparency or engagement to discussion can be quite disheartening at times.

@srirambv stated in an earlier comment they failed to reproduce this issue on both Android 11 (Pixel 3 XL) and Android 10 (OnePlus 6T), but appears to be the only one so far unaffected.

**For others reading, please state your Device Model + Android Version + Brave Version if you haven't already and wish to assist!**

**Comment by eturk1** [comment]
Test example:
Amazon app not loading on nightly & v1.14.86

Example page to recreate:
https://youtu.be/72AHENDeTEI

Tap any of the Amazon links in description. Chrome first shows the youtube link then load Amazon app. Brave stays in browser.

(Pixel 4 XL on Android 11)

**Comment by Sauceee** [comment]
Same issue on pixel 3  with Android 11!

**Comment by tomocrafter** [comment]
Same here with
Pixel 4 XL and Android 11

**Comment by Hazbelll** [comment]
Issue persists in Brave Version 1.16.74.

**Comment by Hazbelll** [comment]
A reminder @deeppandya that we are awaiting your response to @bsclifton.

**Comment by deeppandya** [comment]
@Hazbelll @SergeyZhukovsky is looking into and it's our priority. We will update you soon.

**Comment by marcobeierer** [comment]
I'm having the same trouble with a mobile payment app on Android 11 too and did some research. I'm not an Android dev, but maybe my findings help anyway.

Chrome has a permission named `andoird.permissions.QUERY_ALL_PACKAGES` which seems to be newly added in Android 11 and the name may indicate a relation to the issue.

It seems the visibility of apps to other apps has changed in Android 11 and without the permission an app is no longer allowed to see all other app. See https://developer.android.com/about/versions/11/privacy/package-visibility for more details.

Not all apps may use the new permission, but browsers are allowed too. See https://developer.android.com/training/basics/intents/package-visibility#all-apps for details.

Maybe enabling this permissions for Brave might help fixing the issue.

**Comment by aaronsantamaria** [comment]
+1 from Reddit
https://www.reddit.com/r/brave_browser/comments/jp820g/brave_is_opening_youtube_and_reddit_links/

**Comment by SergeyZhukovsky** [comment]
> I'm having the same trouble with a mobile payment app on Android 11 too and did some research. I'm not an Android dev, but maybe my findings help anyway.
> 
> Chrome has a permission named `andoird.permissions.QUERY_ALL_PACKAGES` which seems to be newly added in Android 11 and the name may indicate a relation to the issue.
> 
> It seems the visibility of apps to other apps has changed in Android 11 and without the permission an app is no longer allowed to see all other app. See https://developer.android.com/about/versions/11/privacy/package-visibility for more details.
> 
> Not all apps may use the new permission, but browsers are allowed too. See https://developer.android.com/training/basics/intents/package-visibility#all-apps for details.
> 
> Maybe enabling this permissions for Brave might help fixing the issue.

@marcobeierer you are right, thanks for the reply. I just found out as well that queue on registered apps require that permission starting from Android 11. The fix will appear in the Play Store sometime next week. Thank you everyone for patience and understanding.

**Comment by marcobeierer** [comment]
@SergeyZhukovsky Thank you very much for looking into it and fixing the issue!

**Comment by Hazbelll** [comment]
Brilliant!

Thank you kindly @marcobeierer and @SergeyZhukovsky for your diligence in squashing this pesky bug and an extended thanks to everyone else for their co-operation!

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.16.75 Bravex86.apk
- Verified test plan from https://github.com/brave/brave-core/pull/7080

--------------------

**Comment by eturk1** [comment]
Please reopen this big report

It's broken again in all 3 versions: release, beta, nightly.
Facebook & YouTube failing to open in app

Test: 
go to a site with social links
Ex: https://christybhome.com/
Tap Facebook icon... 
Fail: stays in browser, doesn't even ask what app to open link with

(Yes, I even tried resetting spp by clearing date)

![Screenshot_20210726-170913](https://user-images.githubusercontent.com/525280/127075599-62f4f319-dc9b-4bd6-be1a-64e1f7badf57.png)

**Comment by blogmangit** [comment]
on android  go to settings > site settings > video playback on brave (disable this).

brave android has a default settings of running videos on browser if that's enabled then videos will not be played on external apps.

**Comment by yurighensev** [comment]
Just recently I came across this problem again. Android 11.
I found out that just disabling video playback in Brave isn't enough, you also need to allow the app to open those links. Not sure why my YouTube had that disabled, this is how I fixed it:

Settings > Apps > Default apps > YouTube > Open by default > Open supported links (enable it)

**Comment by bonecountysheriff** [comment]
`Settings -> Default Apps -> Opening Links`
All apps are supposed to be listed. Brave is the only one that seems to be missing.

**Comment by CZTeo** [comment]
Tried all the solutions listed here,none worked,Brave only opens link in browser only

**Comment by CZTeo** [comment]
for me,it seems to work some apps but not youtube.Video playback is already turned off

**Comment by spyro2000** [comment]
Deinstalled Brave, tired of this.

**Comment by nudeln** [comment]
I face the same issue since yesterday. Brave is no longer able to open links to is intended to trigger an external app. The iasue is confirmed with at least two apps, namely WhatsApp and (Swedish) BankID. It all works fine with Chrome. Made an OS update yesterday, so now I am on (Brave and Android). 
![Screenshot_20230823-070744](https://github.com/brave/brave-browser/assets/11016720/c43d6284-7f2b-4b98-a420-78b52a75ae17)
![Screenshot_20230823-070701](https://github.com/brave/brave-browser/assets/11016720/b2dbc12f-0f12-46e1-a3fa-66912eb2872f)

**Comment by nudeln** [comment]
Result from Chrome and Brave (relate to comment above):
![Screenshot_20230823-071925](https://github.com/brave/brave-browser/assets/11016720/e58750c3-331d-44c9-b875-66981c394ee2)
![Screenshot_20230823-071935](https://github.com/brave/brave-browser/assets/11016720/9d6124fd-01e4-4aad-b036-ef33a001a043)

**Comment by ZANX3Y** [comment]
> 

Must have been caused by the update two days ago, as this setting was disabled on both of my phones (also Android 13).
Glad that you figured it out though, definitely saved me some time, thanks.

**Comment by nudeln** [comment]
> > 
> 
> Must have been caused by the update two days ago, as this setting was disabled on both of my phones (also Android 13). Glad that you figured it out though, definitely saved me some time, thanks.

Glad it helped someone, maybe I wasn't the idiot after all 😊

**Comment by pateljoel** [comment]
This issue is still happening and needs to be reopened My Android phone doesn't recognise any app links so this issue isn't solved after I have tried everything here.

**Comment by pateljoel** [comment]
So I followed @nudeln's the above and links work again. 

But the UX on this is very poor from Brave's side as nobody is going to do this at all and apps that rely on external links are broken everywhere.

I'm a visual learner so if you are looking at this from the future (hi there!) and you stumble across this silly issue Brave has caused, below is how you fix this:

1. Open the Brave app
2. Go to Brave's Settings
3. Tap "Brave Shields & Privacy" (Important)
4. Scroll to "Other Privacy Settings" where you see "Allow app links to open in apps outside of Brave"
5. Turn the switch on.

I can't imagine how many support teams have had their time wasted on this issue.

![fix](https://github.com/brave/brave-browser/assets/64401775/6fb2530e-afad-4134-872e-add8bead20d5)

**Comment by ryanleec** [comment]
So turns out my issue was resolved by the guide @nudeln posted. And I agree with @pateljoel - this was handled poorly. Why was this setting turned on by default? It seems silly to _assume_ that a person only wants to use Brave for links if they have the appropriate app installed. And to do all this without any explanation or warning?

**Comment by parkgrrr** [comment]
Hello, I am at developer at SoFi. After many user reports and many hours of tracking down a sudden inability for some users to login, we will likely block users from logging in with Brave entirely, and force them to switch browsers. Please consider reversing this decision, or at least at popup so users can change their setting.

**Comment by SergeyZhukovsky** [comment]
sorry folks, we had a bug similar to that issue that happened recently and it's fixed and a new 1.57.60 version is already available in the Play Store https://github.com/brave/brave-browser/issues/32586

**Comment by ryanleec** [comment]
> sorry folks, we had a bug similar to that issue that happened recently and it's fixed and a new 1.57.60 version is already available in the Play Store #32586

The problem is that this setting *should not exist*, period. It's a huge stroke of arrogance to say that the developers know how to be more secure and private *than any other app developer in existence*. 

And then a double issue when it was turned on during an update. Multiple people, self included, know that it was off before that. If that was a mistake, it's a QA issue.

**Comment by deeppandya** [comment]
> > sorry folks, we had a bug similar to that issue that happened recently and it's fixed and a new 1.57.60 version is already available in the Play Store https://github.com/brave/brave-browser/issues/32586
> 
> Having a single master switch is still a very crappy design, especially when you're replicating a switch android already has but doing it worse with less fine grained control. Maybe a website level permission or better yet, _just respect the existing android settings_

@androidacy-user we are actively working on the feature which would provide more granular options and control to the user. Please stay tuned.

**Comment by farran** [comment]
Came here whilst searching for a solution. 
Found that it was broken by design and then fixed by overriding user's phone settings.
Joined Brave a few weeks ago in exodus from Chrome due to Google's enforcing of web DRM.
You think this is a good time to annoy new and existing users? 
There are other browsers available you know! 
I'll check back in a few days. If you haven't reverted to correct behaviour by then then, see ya ✌️

**Comment by eturk1** [comment]
1.57.60 still doesn't open many links in the installed app.

Just found problem with Nike app failing to load. 
- Search for a Nike product.
- Tap an Amazon link and app opens.
- Tap link to Nike.com and web page opens.

**Comment by gusandrianos** [comment]
Any updates on this? It's extremely annoying, I have the GitHub app but brave opens the links instead. I have the setting about opening links turned on and yet it still happens

**Comment by eturk1** [comment]
Opps, this is an old closed issue report from 2020

We need to find a current OPEN issue about installed apps here: 
https://github.com/brave/brave-browser/issues?q=is%3Aopen+is%3Aissue

> Any updates on this? It's extremely annoying, I have the GitHub app but brave opens the links instead. I have the setting about opening links turned on and yet it still happens
