### ISSUE TITLE
Do not connect to accounts.google.com on enabling sync-v2

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#12984]
## Description 

A request to accounts.google.com is initiated when enabling sync. 

## Steps to Reproduce
1. Enable sync on a fresh profile

## Actual result:
Request to accounts.google.com initiated

## Expected result:
Should not be initiated

## Reproduces how often: 
Easily

## Brave version (brave://version info)
1.19.33 Chromium: 87.0.4280.67 (Official Build) nightly (x86_64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

**Comment by diracdeltas** [comment]
cc @darkdh

**Comment by jumde** [comment]
Fix being discussed here: https://bravesoftware.slack.com/archives/C2HJYB45N/p1606867060133000

**Comment by AlexeyBarabash** [comment]
Also reproducible on stable 

Brave | 1.18.70 Chromium: 87.0.4280.101 (Official Build) unknown (64-bit)
-- | --

and beta
Brave | 1.19.60 Chromium: 87.0.4280.101 (Official Build) unknown (64-bit)
-- | --

**Comment by bbondy** [comment]
Re-opening since it was reverted due to a windows build failure here: https://github.com/brave/brave-core/pull/7470

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```

Brave | 1.20.86 Chromium: 88.0.4324.96 (Official Build) dev (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Windows 10 OS Version 2004 (Build 19041.746)


```
- Verified the STR from the description

Reproduced the issue in `1.19.86`
![image](https://user-images.githubusercontent.com/38657976/105371661-d3feb900-5c2a-11eb-95fe-f6f40777f58b.png)

The issue is fixed in 1.20.86 - ensured that the account.google.com domain isn't listed when standalone sync is initiated
![image](https://user-images.githubusercontent.com/38657976/105371718-e547c580-5c2a-11eb-8e4a-820deaf38d25.png)

- Verified the test plan from https://github.com/brave/brave-core/pull/7480

**Comment by bumjrah** [comment]
This still isn't fixed. At least on Android. Any good reason this was looked over?
