### ISSUE TITLE
site hack: xtcore.js on www.lesechos.fr is not blocked

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#1305]
## Steps to Reproduce

   1. Open www.lesechos.fr and check if xtcore.js is blocked

## Actual result:

xtcore.js is not blocked
![image](https://user-images.githubusercontent.com/34715963/46109677-9ec03880-c1e1-11e8-9f5a-0b21a3428dbb.png)
I checked through debugger that xtcore.js code is executed.
We have a site hack for blocking the script #84, but path to xtcore.js has changed 
from: `https://www.lesechos.fr/xtcore.js`
to `https://assets.lesechos.com/common/js/xtcore.js`

## Expected result:
Blocks `https://assets.lesechos.com/common/js/xtcore.js`

## Reproduces how often: 

always

## Brave version (chrome://version info)

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

### Reproducible on current release:

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

cc @bbondy @kjozwiak @LaurenWags @srirambv @GeetaSarvadnya

**Comment by LaurenWags** [comment]
reproduces on macOS

**Comment by tomlowenthal** [comment]
Does the same thing happen with Shields down?

**Comment by kjozwiak** [comment]
> Does the same thing happen with Shields down?

Yup, same results with `Shields` being disabled on all `b-c` channels. Example:

<img width="1408" alt="screen shot 2018-11-14 at 3 27 45 pm" src="https://user-images.githubusercontent.com/2602313/48510568-3cb7a300-e822-11e8-97f5-77f62f40f6c9.png">

Checked on the following builds using macOS 10.14 x64:

* 0.56.12 `release` Chromium: 70.0.3538.77 - Reproduced with `Shields` down
* 0.57.6 `beta` Chromium: 71.0.3578.31 - Reproduced with `Shields` down
* 0.57.4 `dev` Chromium: 71.0.3578.31 - Reproduced with `Shields` down

**Comment by tomlowenthal** [comment]
Just to make sure I understand the issue here: `xtcore.js` is a piece of tracking tech which we _should_ block, but don't. This issue is a request to block it. Right?

**Comment by kjozwiak** [comment]
@tomlowenthal from my understanding, that's correct 👍 We have several site hacks for a few specific websites which includes `www.lesechos.fr` which is supposed to block `xtcore.js` which isn't happening as @btlechowski mentioned in the original issue. We had these site hacks in b-l [1] which were ported into b-c [2].

* [1] https://github.com/brave/browser-laptop/blob/master/js/data/siteHacks.js
* [2] https://github.com/brave/brave-browser/issues/84

**Comment by tomlowenthal** [comment]
I'm confused — why are these implemented as site-hacks rather than being part of the regular block lists. Is there an implementation detail I'm missing?

**Comment by bbondy** [comment]
This was just a port from browser-laptop. The real fix for this is to add a ad-blocking easylist rule and remove the site hack.

**Comment by bbondy** [comment]
Fixed by https://github.com/brave/adblock-lists/commit/29671ed72bb83b43e825365802180c0668516334

**Comment by btlechowski** [comment]
Still reproducible on 

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

![image](https://user-images.githubusercontent.com/34715963/54636036-c7850480-4a85-11e9-8fef-1e7855ce3b2f.png)


@bbondy Am I missing something?

**Comment by GeetaSarvadnya** [comment]
Still Reproducible on

Brave | 0.63.15 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Linux

**Comment by btlechowski** [comment]
The website in question changes so it no longer uses `xtcore.js`. 
Setting the issue to invalid.
