### ISSUE TITLE
Can't hide Bookmarks bar on New Tab page

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#1306]
## Description 

Even with the "Show Bookmarks Bar" option set to off, Brave still displays bookmarks bar on the new tab screen. There should be an option to turn this off. Tangentially related to #1022 
Note: Chrome behaves in this same way (at the time of writing this, Chrome v69.0.3497.100) so this is more of a feature request than a bug. Would be good to have an option for this before Chrome. 

## Steps to Reproduce

   1. Add some bookmarks to the bookmarks bar
   2. Go to Settings --> Appearance --> Show Bookmarks Bar and toggle option to off
   3. Visit some website, then open a new tab

## Actual result:

Bookmarks Bar is not shown when viewing website tab as expected but new tab page still shows bookmarks bar.

## Expected result:
Bookmarks bar should not be visible anywhere until option is turned back on.

## Reproduces how often: 

Always. 

## Brave version (chrome://version info)

Version 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)

### Website problems only:  
- Is the issue reproducible on the latest version of Chrome? Yes 

### Additional Information
Screenshots:
![image](https://user-images.githubusercontent.com/3299098/46110115-862b3080-c197-11e8-94a4-1167a4de35ff.png)

![image](https://user-images.githubusercontent.com/3299098/46110063-5714bf00-c197-11e8-861a-ca719ee2f97d.png)

**Comment by Brave-Matt** [comment]
@rebron, not that I mind but to clarify, is there a particular reason you retitled and labeled it as bug? I'm just wondering because Chrome behaves this way as well on live release (also doesn't have option to change it).

**Comment by Jacalz** [comment]
I really want to see this fixed too, the bookmarks bar looks visually not pleasing and it makes the new tab page look less beutiful than it is...

**Comment by srirambv** [comment]
+1 from @NumpDeP via #1919 for private window

**Comment by StephD** [comment]
+1 also on Brave. No problem on chrome 70

**Comment by simonhong** [comment]
Do we want to make bookmark in ntp also follow bookmark visibility prefs? @rebron

**Comment by nicolinux** [comment]
If you don't have (and want) any bookmarks, you still see this annoying bar.
Version 0.56.12 Chromium: 70.0.3538.77 (Official Build) (64-bit)

![screen shot 2018-11-11 at 18 19 57](https://user-images.githubusercontent.com/1069286/48317348-c718c080-e5f0-11e8-88ba-f55b2ea16700.png)

**Comment by srirambv** [comment]
+1 from https://github.com/brave/brave-browser/issues/1306

**Comment by Ilya-MV** [comment]
I updated the browser, but the essence of the issue has not changed! It would be much more convenient if the bookmarks were located on the menu bar, not on the bookmarks bar! This allows you to remove the bookmarks bar and thereby increase the height of the main working browser window! Where h < H = absolute benefit![
![img-2018-12-05-18-32-14](https://user-images.githubusercontent.com/45652782/49569449-0662d480-f945-11e8-8206-686aecf09388.png)

**Comment by kjozwiak** [comment]
Added into the `General` project so this issue gets triaged as there's a few +1 from the community.

**Comment by jatinw21** [comment]
I would love to see this fixed too. It makes the otherwise beautiful page look ugly and is annoying.

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/hide-bookmarks-bug/43718?u=eljuno

**Comment by RomuCampu** [comment]
I would also like to see that bar gone from the browser. There is no point in opening a new window and having a dirty page with that toolbar up there asking us to import our bookmarks...

**Comment by RomuCampu** [comment]
I would also like to see that bar gone from the browser. There is no point in opening a new window and having a dirty page with that toolbar up there asking us to import our bookmarks...

**Comment by simonhong** [comment]
This is fixed by https://bugs.chromium.org/p/chromium/issues/detail?id=299167.

**Comment by kjozwiak** [comment]
> This is fixed by https://bugs.chromium.org/p/chromium/issues/detail?id=299167.

Is this targeting C75?

**Comment by simonhong** [comment]
> > This is fixed by https://bugs.chromium.org/p/chromium/issues/detail?id=299167.
> 
> Is this targeting C75?

Maybe @bbondy @rebron can answser

**Comment by bbondy** [comment]
https://storage.googleapis.com/chromium-find-releases-static/a24.html#a2465c0852f17d0f6fe989ce799d0514a2eb1d78 
Says this is landed as of C75.*.0.

https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule
Says this will be available in 0.65.x on or around June 4, 2019

**Comment by rrguard** [comment]
Brave Version 0.63.48
Chromium: 74.0.3729.108 (Official Build) (64-bit)

The issue with bookmarks bar on New tab always showing still happens.

**Comment by rebron** [comment]
@rrguard The fix for this issue will be in 65.x slated for ~June 4th. It's an issue that's been annoying to me to. Chromium version will show 75.x and fix will be making it's way through nightly/dev/beta.

**Comment by simonhong** [comment]
Fixed by merging https://github.com/brave/brave-core/pull/2401.

**Comment by btlechowski** [comment]
Still reproducible with Chromium 75.x.

Brave | 0.65.107 Chromium: 75.0.3770.38 (Official Build) beta (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Windows 10 OS Version 1803 (Build 17134.523)

![image](https://user-images.githubusercontent.com/34715963/58213422-59adc100-7cf2-11e9-9a48-69962e56536e.png)

cc @brave/legacy_qa

**Comment by simonhong** [comment]
Oh, I found that bookmark bar on NPT is only hidden when it is empty.
`BookmarkTabHelper::ShouldShowBookmarkBar()` handles it.

**Comment by NicTanghe** [comment]
Same issue here plz fix

**Comment by kjozwiak** [comment]
Moved this out of `0.65.x` as we got this for free once Brave was bumped to `C75`. However, as @btlechowski mentioned above, this is still an issue when there's bookmarks on the toolbar.

We'll need to decide if we want to fix this ourselves.

**Comment by GeetaSarvadnya** [comment]
1+ https://community.brave.com/t/bookmarks-folders-visible-regardless-of-bookmarks-bar-settings/63184

**Comment by JoshuaCarter** [comment]
Just finished migrating from Ubuntu's 'Software' version of Brave to the new src repo, and just noticed that the bookmarks bar is gone on new tabs, meaning I have to have it on all the time (waste of visual space and ugly). Any way to get it showing on just new tabs again?

**Comment by simonhong** [comment]
I think some users will want to show bookmark bar on NTP when `Show Bookmarks Bar` option is turned off. Maybe they wants options like `Always Show Bookmarks Bar on NTP`.
@rebron  WDYT?

**Comment by rebron** [comment]
@simonhong This is behavior I believe we should support and @petemill wants as well. I'll file a separate issue for it. We'll need to figure out how to display the pref for it.

**Comment by bsclifton** [comment]
@JoshuaCarter we got a new issue tracking that feature request (https://github.com/brave/brave-browser/issues/4782 - thanks, @rebron!) in case you wanted to subscribe for updates

We'll just need to find a place to land this proposed setting as I believe the default behavior we want for users would be to hide on new tab page (users who want to see it would adjust the setting).

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.68.109 Chromium: 76.0.3809.62 (Official Build) dev (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/2563
Currently bookmark bar visibility is handled by `Show bookmarks bar` toggle 
The bookmark bar is not shown on new tab till `Show bookmarks bar` is switched to `on`.

Checked the `Show bookmarks bar` toggle in settings and hamburger menu.

**Comment by mazupicua** [comment]
> Verification passed on
> 
> Brave	0.68.109 Chromium: 76.0.3809.62 (Official Build) dev (64-bit)
> Revision	7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
> OS	Ubuntu 18.04 LTS
> Verified test plan from [brave/brave-core#2563](https://github.com/brave/brave-core/pull/2563)
> Currently bookmark bar visibility is handled by `Show bookmarks bar` toggle
> The bookmark bar is not shown on new tab till `Show bookmarks bar` is switched to `on`.
> 
> Checked the `Show bookmarks bar` toggle in settings and hamburger menu.

Any idea when this is coming to windows?

**Comment by simonhong** [comment]
> > Verification passed on
> > Brave	0.68.109 Chromium: 76.0.3809.62 (Official Build) dev (64-bit)
> > Revision	7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
> > OS	Ubuntu 18.04 LTS
> > Verified test plan from [brave/brave-core#2563](https://github.com/brave/brave-core/pull/2563)
> > Currently bookmark bar visibility is handled by `Show bookmarks bar` toggle
> > The bookmark bar is not shown on new tab till `Show bookmarks bar` is switched to `on`.
> > Checked the `Show bookmarks bar` toggle in settings and hamburger menu.
> 
> Any idea when this is coming to windows?

Currently, this feature is in dev channel(0.68.x) on Windows also.
It would be in stable at `August 20, 2019`. You can check our release schedule here - https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule

**Comment by cuzer** [comment]
+1

**Comment by Curuphan** [comment]
Oh. So the bookmarks bar disappeard because it was asked for. And i didn't know where did it gone.... Do i understand correctly if it will be switcheable on new tab? I liked the way it worked. When i opened a new tab, i could load a page from the bookmarks bar (especially from the bookmarks button on the right of the bookmarks bar) , but i don't need that bar on other tabs. But now, i can turn it on only on all tabs. It's nonsense.

**Comment by rebron** [comment]
@Curuphan the fix for that is here https://github.com/brave/brave-browser/issues/4782. 

There's a setting to always show bookmarks bar and the fact that setting didn't work on the new tab page was the problem. People who don't want to use bookmarks at all don't want to see the bookmarks bar anywhere and we should honor that setting which we did.

**Comment by JoshuaCarter** [comment]
@rebron That's fine, but many of us don't want it on all the time, yet still want easy access to it, which is what a 'new tab only bookmarks bar' gives. Also this is how it's works for me for years on Chrome anyway so I took it for granted that this was the intention. It needs to be 3 options: [on, off, new-tab]. This might be a non-issue if I could find a half-decent new-tab-bookmarks-bar extension, but I can't (I last checked around the time of my last comment on this issue).

**Comment by rebron** [comment]
@JoshuaCarter See here please: https://github.com/brave/brave-core/pull/2869 
It provides a pref for the original behavior.

**Comment by JoshuaCarter** [comment]
@rebron @simonhong Outstanding, many thanks.

**Comment by bigt2000** [comment]
Are there plans to bring 3 options as mentioned by Joshua?  I preferred to only see the bookmarks bar on a new tab and agree that giving the option to pick which one you want is better than omitting an option.

**Comment by WeirdWhirl** [comment]
So this is why my NTP bookmark bar has disappeared. This sucks, I use that thing constantly.
I'm downgrading to the previous version until the NTP option is implemented.
I'm starting to feel old. I keep getting pissed off that often used software features keep getting killed without any obvious notice.

**Comment by adamreisnz** [comment]
This was a silly issue to raise. Now we can't access our bookmark bar in a new tab anymore without being forced to see the bar for every... single... tab. 

Someone please hit undo.

**Comment by simonhong** [comment]
@adamreisnz Sorry for your inconvenience.
We fixed (https://github.com/brave/brave-core/pull/2869) and I assume that it will be uplifted to beta(0.69.x).
