### ISSUE TITLE
Fake acrylic effect and stuttery scroll in Brave Today on New tab

### ISSUE THREAD

**Issue by Cyberdroid1** [brave/brave-browser#13185]
## Description 
The acrylic effect present in news tabs for Brave today looks fake and scrolls with a lot of stutter.

## Steps to Reproduce

   1. Open a new tab in Brave
   2. Scroll down and see stutter
   3. See the acrylic fake effect.

## Actual result:.
Stutter scroll and fake acrylic effect.

## Expected result:
It should scroll smooth, and the acrylic should be more life like, with better object tracking for the same

## Reproduces how often: 
All the time

## Brave version (brave://version info)

Brave | 1.18.70 Chromium: 87.0.4280.101 (Official Build) (x86_64)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | macOS Version 11.1 (Build 20C5048l)

## Version/Channel Information:

- Can you reproduce this issue with the current release? YES
- Can you reproduce this issue with the beta channel? ---
- Can you reproduce this issue with the nightly channel? YES

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? NO
- Is the issue reproducible on the latest version of Chrome? NA
 
## Miscellaneous Information:

If you ask, I am happy to provide :)

**Comment by bsclifton** [comment]
cc: @petemill

**Comment by Cyberdroid1** [comment]
Did nobody report this issue earlier? Whoa

**Comment by bsclifton** [comment]
@Cyberdroid1 not that I know of; thanks for reporting! 😄👍

**Comment by Cyberdroid1** [comment]
[Video.zip](https://github.com/brave/brave-browser/files/5695520/Video.zip)

A video (.mov) for the same.
See how the acrylic changes so aggresively and scrolling is also a bit stuttery. The video is from a Mac. Scrolling the Brave Today is even worse on Windows.

**Comment by bsclifton** [comment]
Going to close this as a duplicate of https://github.com/brave/brave-browser/issues/13194 - this will be fixed with https://github.com/brave/brave-core/pull/7433 😄

**Comment by Cyberdroid1** [comment]
What about the acrylic effect?

**Comment by petemill** [comment]
@Cyberdroid1 It's not 100% clear what you're referring to from your video, but I have on my todo list to reduce the backdrop blur amount so that the entire box doesn't take on a very small amount of pixels at a time, which shows up as flashing as you scroll. I definitely went too eager on the blur amount at first pass!

**Comment by Cyberdroid1** [comment]
Any updates?

**Comment by bsclifton** [comment]
The perf issue was fixed (per above) - for this cosmetic issue, I'll assign a P4 priority since @petemill intends to fix at some point

**Comment by urbenlegend** [comment]
Scrolling is still not smooth on lower end devices. I have a Surface Pro 7 and scrolling Brave News is a stuttery mess. It isn't just the acrylic effect that is stuttering and shimmering, pretty much the entire page lags and jumps when I scroll using my finger.

**Comment by mattmcalister** [comment]
@stephendonner can you check whether this issue is still relevant?

**Comment by jonathansampson** [comment]
@urbenlegend Can you share an update on your experience. Has anything changed for the better or worse? Also, could you please share the specs of your device so that we can more confidently work to reproduce the issue on our end. All the best!

**Comment by urbenlegend** [comment]
@jonathansampson It's better than before, but still far from what native scrolling feels like. I am using a Surface Pro 7 with an Intel i5-1035G4. It's one of the fanless models.
