### ISSUE TITLE
Local printer not available in Brave

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#13565]
A user reports on https://community.brave.com/t/no-printers-available-in-brave-ubuntu-mate-20-04/195568 that their printer isn't available in Brave, while it's properly detected in Chrome.

Ubuntu Mate 20.04.

**Comment by fmarier** [comment]
Note: I'm using Ubuntu 20.04 on two different computers and I can see my local printer just fine.

**Comment by sunejak** [comment]
I have the same issue with Version 1.19.86 Chromium: 88.0.4324.96 (Official Build) (64-bit)

**Comment by jsenner1** [comment]
I have the same issue with Version 1.19.86 Chromium: 88.0.4324.96 (Official Build) (arm64) on OSX on an M1 air. One of the system printers showed up, but not any of the others. I tried reinstalling. I wound up sharing the printer in the OS and then it appeared under the 'More...' section in the print dialog.

**Comment by veromary** [comment]
When printing from Brave I only get Save as PDF and when I click "See More" and then the "Manage" button at the bottom, nothing happens. I have a network printer which shows up in Chrome and in other applications.
Version 1.20.103 Chromium: 88.0.4324.152 (Official Build) (64-bit)
Lubuntu 20.04 lxqt

**Comment by Jusix** [comment]
Same Problem:

Version 1.21.77 Chromium: 89.0.4389.90 (Offizieller Build) (64-Bit)
Linux Mint 20.1 Ulyssa (Ubuntu 20.04.2 based)

**Comment by RobHem166** [comment]
Hi guys, any thoughts on what Brave could be doing that prevents print destination showing currently installed printers?? 
the workaround i found is to go to 'more settings' and select 'print using system dialog'...  workable, but an annoyance
thank you

**Comment by fmarier** [comment]
I don't have any ideas because it has always worked for me. Maybe @wknapik has ideas.

**Comment by tkanos** [comment]
Same here with :
Ubuntu 20.04.2 LTS 64-bit
Brave Version 1.22.70 Chromium: 89.0.4389.105 (Official Build) (64-bit)

**Comment by wknapik** [comment]
With the snap package, that would be a straightforward answer - I'm guessing `sudo snap connect brave:cups-control` would sort this out.

Otherwise, on Linux, I'd ask whether the relevant `cups` services are running. I used to print via Brave on Linux once in a while and never had issues. I don't have access to a printer anymore, so can't test at the moment.

**Comment by RobHem166** [comment]
> With the snap package, that would be a straightforward answer - I'm guessing `sudo snap connect brave:cups-control` would sort this out.


thank you for the suggestion... however i get this "error: snap "brave" has no plug named "cups-control"

since i raised this problem, I have been seeing many references to Snap installers. I have to admit that i have not come across Snap before as i have always used Synaptic or APT on Ubuntu and Linux Mint over the years... 

I want to tread carefully as this is the PC I use to run my self employed business, but is it relatively straightforward to remove an app from synaptic and reinstall using Snap and will it pickup the same settings / bookmarks / plugins etc without too much faffing around??? 

(just updated Brave to Version 1.22.71 Chromium: 89.0.4389.114 (Official Build) (64-bit)... problem still exists)

many thanks.

**Comment by Larx** [comment]
I have the same problem running a stock Ubuntu 20.10, now updated to 21.04pre. The printer is not local, but a network device accessible by CUPS. Brave is installed by repo, I dislike snap. So no permission problem.
Really any other software but Brave has absolutely no issues detecting the printer. In fact Brave is the first software since ages which does not print on Linux.

So I'd rather tend to blame Brave for not detecting the printer, and not the base system...

**Comment by w2vy** [comment]
I installed via Ubuntu Software on 20.10 and from syslog it seems it may be a snap

Apr  5 06:48:31 rnode kernel: [153113.532815] audit: type=1400 audit(1617619711.256:649): apparmor="DENIED" operation="connect" profile="snap.brave.brave" name="/run/cups/cups.sock" pid=349019 comm="ThreadPoolForeg" requested_mask="wr" denied_mask="wr" fsuid=1000 ouid=0

and yes

sudo snap connect brave:cups-control

fixed it for me

**Comment by Larx** [comment]
I don't use neither Ubuntu Software nor Snap. In fact, I have completely removed Snap from my system. Brave is installed as a conventional .deb package from https://brave-browser-apt-release.s3.brave.com/, and do not have access to my locally available printers.

**Comment by mbedded** [comment]
Same for `Version 1.24.82 Chromium: 90.0.4430.93 (Official Build) (64-Bit)`

Brave installed via "add repo" and "apt-get install" (official documentation)

**Comment by fmarier** [comment]
I'm also seeing this on one of my machines (running Debian unstable) at home now:
```
Brave	1.23.75 Chromium: 90.0.4430.93 (Build officiel) (64 bits)
Révision	4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
Système d'exploitation	Linux
```

However, it works just fine on a different machine (running Ubuntu 20.04) on the same network:
```
Brave | 1.25.53 Chromium: 90.0.4430.93 (Official Build) beta (64-bit)
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | Linux
```

The only difference I can think of is that I have AppArmor enabled on Debian (`apparmor=1 security=apparmor` boot params), but not on Ubuntu.

**Comment by w2vy** [comment]
Can you upgrade the home to Brave 1.25 ?

On May 7, 2021 2:50:49 PM EDT, Francois Marier ***@***.***> wrote:
>I'm also seeing this on one of my machines (running Debian unstable) at
>home now:>
>```>
>Brave	1.23.75 Chromium: 90.0.4430.93 (Build officiel) (64 bits)>
>Révision	4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}>
>Système d'exploitation	Linux>
>```>
>>
>However, it works just fine on a different machine (running Ubuntu
>20.04) on the same network/printer:>
>```>
>Brave | 1.25.53 Chromium: 90.0.4430.93 (Official Build) beta (64-bit)>
>Revision |
>4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}>
>OS | Linux>
>```>
>>
>The only difference I can think of is that I have AppArmor enabled on
>Debian (`apparmor=1 security=apparmor` boot params), but not on
>Ubuntu.>
>>
>-- >
>You are receiving this because you commented.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/brave/brave-browser/issues/13565#issuecomment-834690000

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by fmarier** [comment]
I disabled AppArmor and tried these versions of Brave:
```
Brave	1.24.82 Chromium: 90.0.4430.93 (Build officiel) (64 bits)
Révision	4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
Système d'exploitation	Linux

Brave	1.25.53 Chromium: 90.0.4430.93 (Build officiel) beta (64 bits)
Révision	4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
Système d'exploitation	Linux
```
Same problem: I can't see the local printer that's advertised on the network and that I can see just fine on Ubuntu.

**Comment by wknapik** [comment]
@fmarier anything in `cupsd` logs, or [webui](http://localhost:631/)?

**Comment by w2vy** [comment]
I have version 1.23.75 on laptop and desktop. 

Laptop works ok, desktop no printer found from brave, system dialogs have it

Nothing in cups access or error log 

What is webui?

On May 7, 2021 4:00:20 PM EDT, Wojciech Knapik ***@***.***> wrote:
***@***.*** anything in `cupsd` logs, or [webui](http://localhost:631/)? 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/brave/brave-browser/issues/13565#issuecomment-834738090

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dodbrian** [comment]
I've got the same issue:
- Brave is installed using `apt`
- Version 1.24.82 Chromium: 90.0.4430.93 (Offizieller Build) (64-Bit)
- Kubuntu 20.10 x86_64 - 5.8.0-50-generic 
- Using network printer

Visible in all other apps except Brave

**Comment by jasminefrost** [comment]
> I installed via Ubuntu Software on 20.10 and from syslog it seems it may be a snap
> 
> Apr 5 06:48:31 rnode kernel: [153113.532815] audit: type=1400 audit(1617619711.256:649): apparmor="DENIED" operation="connect" profile="snap.brave.brave" name="/run/cups/cups.sock" pid=349019 comm="ThreadPoolForeg" requested_mask="wr" denied_mask="wr" fsuid=1000 ouid=0
> 
> and yes
> 
> sudo snap connect brave:cups-control
> 
> fixed it for me

I am new to Linux/Ubuntu... don't know programming and have no idea what snap is, but I used your "sudo snap connect brave:cups-control" and now I can see my printers :)  

I re-opened the Brave browser and hit the print button in the web page and when the print dialog opened, where it said to print to PDF, I clicked on the "more" button and when it opened, it showed the printers.

Thank you for the solution!!

**Comment by wknapik** [comment]
Thanks for letting us know @jasminefrost. I requested auto-connection for this plug, so in the future, users won't have to do this manually after each reboot. It will likely take about a week for the request to be granted and it will take effect for all users after the next snap package release after that.

**Comment by Larx** [comment]
And what about the .deb packages which also suffer from this (or a similar) problem?

**Comment by fmarier** [comment]
Yes, there are two problems here:
1. missing snap connection, which @wknapik took care of
2. something else which affects the `.deb` and that we haven't been able to identify yet

**Comment by vdahmane** [comment]
Same problem:
Brave version: 1.24.84

lsb_release -a:
Distributor ID:	Linuxmint
Description:	Linux Mint 20.1
Release:	20.1
Codename:	ulyssa

**Comment by wknapik** [comment]
I don't have access to a printer, but I had one configured from a while back. I do see it show up on the list when trying to print and I assume it would work (?), but if I click "Manage" to possibly add a new printer, nothing happens and the following is printed on stderr:
```
[1383082:1383092:0514/134532.400235:ERROR:printer_manager_dialog_linux.cc(85)] Failed to open printer manager dialog 
```

PS. The auto-connection for cups-control has been granted. This will take effect for users after the next snap release.

**Comment by CaptainRedHat** [comment]
Same issue here on Brave 1.24.85 on Ubuntu 21.04, installed via the deb package. My system can see and print to my hp network printer just fine, but brave only shows the save to pdf option.

**Comment by terrencec1** [comment]
Any fix for this yet? deb install and no printers seen by brave...Kubuntu 20.04 LTS Brave 1.25.68

**Comment by brianjcohen** [comment]
I can also reproduce this on Manjaro, installed via AUR.

**Comment by terrencec1** [comment]
UPDATE: I deleted my printers, added the back in, rebooted and now they are showing up in Brave.

**Comment by RobHem166** [comment]
> A user reports on https://community.brave.com/t/no-printers-available-in-brave-ubuntu-mate-20-04/195568 that their printer isn't available in Brave, while it's properly detected in Chrome.
> 
> Ubuntu Mate 20.04, using the official packages, not the Snap.
> Version 1.18.78 Chromium: 87.0.4280.141 (Official Build) (64-bit)

O.P of the post in the above link....
it appears that I am now able to print directly from Brave.... not sure exactly what fixed it, but i just allowed Ubuntu to install a backlog of updates including a kernel update (which knackered up my grub boot loader and needed rolling back to previous kernel then forcing reinstall of 5.4.0-73-generic)... next i tried to use Brave to do a bit of online banking, but that was a bit glitchy so i used firefox instead. I then couldnt print my transactions, and found the print queue was grumbling about cups-browsed not running... i removed ALL printers and reinstalled my Epson ET-4750.... went back into Brave and hey presto, printer visible and usable.... 

i assume that the system update must have had an update to Brave, so i assume either that and/or deleting/re-adding printer solved it for me...

thank you to everyone who has commented and contributed their ideas :-)

**Comment by bmansfie** [comment]
I have various system running Linux Mint 20.1 (Cinnamon).  Brave usually doesn't show the printer, but occasionally it shows up (as I type this one is actually working).  It is installed via the official package repo for ubuntu.  I have also have Chrome installed on several of these computers, sometimes Chrome will similarly fail to display the printer, and sometimes it works.  Chrome and Brave sometimes both fail but sometimes have different results.  If I were to guess Chrome is somewhat more reliable but I don't really have it quantified, just a feel.  This has been the case for months on numerous builds.

The printer is a network printer that works pretty much everywhere else on the systems in question.

The here again gone again nature of this is frustrating.  I usually end up just saving the PDF and then printing using 'Document Viewer'.  Extra steps but it works for now.  It would be nice if this is could be tracked down and fixed.

**Comment by bloritsch** [comment]
> Pop!OS 21.04, Brave Version 1.28.105 Chromium: 92.0.4515.131 (Official Build) (64-bit) using deb install

Same issue for me.  I would rather not have to uninstall and reinstall my printers.

**Comment by fmarier** [comment]
I hope we can get to the bottom of this because it's really annoying, but I have found a work-around:

1. In the print dialog, click on "More settings".
2. Then click on "Print using system dialogue...".
3. The OS printing dialog should have all printers.
![Screenshot from 2021-08-17 16-20-08](https://user-images.githubusercontent.com/167821/129813022-3e4864ba-dea6-4587-8ccb-a7110866d089.png)

**Comment by w2vy** [comment]
Recently I noticed that under "Save to PDF" in the pull-down a new 
option appeared

"See more..."

When I selected my printer THAT way it was saved and always appears, 
usually as the default

I say this is Solved!

Tom

**Comment by bloritsch** [comment]
It's not solved... at least reliably.   Had the issue today with the
current version.

**Comment by NicoBeyer** [comment]
Same problem on windows with the latest version on brave.

Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)
Edition	Windows 10 Pro
Version	21H2
Installed on	‎23.‎07.‎2021
OS build	19044.1415
Experience	Windows Feature Experience Pack 120.2212.3920.0

Some printers are showing (probably older installs) but new printers are missing form the menu. Clicking on "See more..." in the printer selection shows an empty list.

**Comment by TechCowboy** [comment]
Version 1.45.116 Chromium: 107.0.5304.91 (Official Build) (64-bit)](https://brave.com/latest/
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
Installed as a snap

Local printer not accessible, only PDF
Can print from Chrome (not a snap)

**Comment by WillGibson** [comment]
I am experiencing the same problem on MacOS 13.2 with Brave Version 1.47.171 Chromium: 109.0.5414.87 (Official Build) (arm64).

I can print from all other application including other browsers, but not Brave, which is the application I am most likely to want to print from.

The problem existed before I upgraded to 13.2.

If it makes any odds, I am not logged in as an admin user.

**Comment by jnahansen** [comment]
Same problem on Ubuntu 22.04.3 LTS using Brave: Version 1.57.62 Chromium: 116.0.5845.180 (Official Build) (64-bit)

I SOLVED IT by pulling down and using the Nightly Build of Brave: [Version 1.60.3 Chromium: 117.0.5938.35 (Official Build) nightly (64-bit)](https://brave.com/latest/)

Now, my local printer shows up fine as expected.

**Comment by w2vy** [comment]
I received an update and got disconnected, had to do the connect reported above (see my comment above)
This time I saw a snap warning from 16 days ago, likely when I got disconnected

  snap "brave" has bad plugs or slots: content (content plug must contain target path)

I see the nightly build seems to work better, just in case this helps.

**Comment by ahydronous** [comment]
Not sure if its related, but in the main printing dropdown, the Brave Flatpak doesn't show the printer I have configured as my default printer. I have to click "see more" first, at which point I can select it.

**Comment by fabiengagne** [comment]
I have the same issue on Ubuntu 22.04.3 LTS with Brave v 1.62.153.
Running `sudo snap connect chromium:cups-control` and then restarting Brave allowed me to see my printers in "See more..." and then print successfully.
I do not know yet if this workaround will "stick" across a reboot.

**Comment by jamincollins** [comment]
I'm seeing the same issue here:
![image](https://github.com/brave/brave-browser/assets/1904577/92e322a6-c746-4798-8d22-4daf1c67f6c8)
![image](https://github.com/brave/brave-browser/assets/1904577/a8e68db3-8278-4572-9e9e-27b0ab95fbeb)

And if I click **Manage**:
![image](https://github.com/brave/brave-browser/assets/1904577/8e6c17b2-a7d3-4baa-98c0-e8f0d0a094b2)

Arch Linux, Version 1.66.115 Chromium: 125.0.6422.112 (Official Build) (64-bit)

**Comment by fmarier** [comment]
I'm not seeing it anymore. Tested on Ubuntu 22.04 and Debian unstable.

I did have to sort out my mDNS settings locally though: https://feeding.cloud.geek.nz/posts/proper-multicast-dns-handling-network-manager-systemd-resolved/

**Comment by mbedded** [comment]
Can confirm: The issue was fixed some time ago, I guess. It was some intermediate version which had the "no printer" bug. Tested with Linux Mint 21 and 22.

**Comment by ItchyBugReporter** [comment]
I am having the same issue on openSUSE Leap. I am using Brave's official RPM repository via zypper. My printer is listed but "is not available or not installed correctly". Printing to the same printer on the same computer works in every other program, including Chromium and Firefox. [Version 1.76.82 Chromium: 134.0.6998.178 (Official Build) (64-bit)]

**Comment by axel-gdll** [comment]
I have the same problem as @jamincollins except for the fact that my printer is a different type.

Versión 1.77.95 Chromium: 135.0.7049.52 (Official build) (64 bits)
Flatpak installed from Software Store at Linux Mint 22.1
No extensions installed
Brother HL-1200 printer connected on USB working well
All other applications print well (Calc, Writer, Chrome)

**The only workaround is:**

flatpak override --user --device=all com.brave.Browser

**Comment by sk8board** [comment]
@wknapik I created an issue with Flatpak, https://github.com/flatpak/flatpak/issues/6275 , regarding this matter of Brave browser not finding a USB printer. 

The Flatpak team informed me that Brave would need to support the xdg-desktop-portal project, which would allow Brave to use a sandbox portal for USB printing. Documentation for the xdg-desktop-portal project can be found here:

https://github.com/flatpak/xdg-desktop-portal

https://flatpak.github.io/xdg-desktop-portal/docs/index.html

Do you expect Brave could support this Flatpak sandbox portal for USB printing?

**Comment by axel-gdll** [comment]
Thank you @wknapik for your reply.
As I am not an expert on this I would not know who needs to do what.
All I need is Brave to work with my printer. As others do.

**Comment by sk8board** [comment]
> [@wknapik](https://github.com/wknapik) I created an issue with Flatpak, [flatpak/flatpak#6275](https://github.com/flatpak/flatpak/issues/6275) , regarding this matter of Brave browser not finding a USB printer.
> 
> The Flatpak team informed me that Brave would need to support the xdg-desktop-portal project, which would allow Brave to use a sandbox portal for USB printing. Documentation for the xdg-desktop-portal project can be found here:
> 
> https://github.com/flatpak/xdg-desktop-portal
> 
> https://flatpak.github.io/xdg-desktop-portal/docs/index.html
> 
> Do you expect Brave could support this Flatpak sandbox portal for USB printing?

@kjozwiak Kamil, would you know who could help with this long term problem?

**Comment by wknapik** [comment]
@sk8board do you mean that for the brave flatpak package to work correctly, xdg-desktop-portal should be installed on the host system, or something else?

**Comment by sk8board** [comment]
> [@sk8board](https://github.com/sk8board) do you mean that for the brave flatpak package to work correctly, xdg-desktop-portal should be installed on the host system, or something else?

@kjozwiak Based on this information, I believe the Brave Browser Flatpak needs to be configured to allow USB access to Brave.

https://docs.flatpak.org/en/latest/sandbox-permissions.html

I started a discussion at xdg-desktop-portal to help with understanding.

https://github.com/flatpak/xdg-desktop-portal/discussions/1796

**Comment by sk8board** [comment]
@GeorgesStavracas could you help @fmarier and @wknapik with understanding how to enable the Flatpak USB Printing Portal for Brave Browser?

There appears to be more than one solution to this problem. Since the following command provides a temporary solution, `$ flatpak override --user --device=all com.brave.Browser` and the [portal documentation](https://docs.flatpak.org/en/latest/sandbox-permissions.html#sandbox-permissions) states the following:

_Most applications will need access to some of these resources in order to be useful. This is primarily done during the finishing build stage, which can be configured through the finish-args section of the manifest file (see [Manifests](https://docs.flatpak.org/en/latest/manifests.html))._

Could a solution be as simple as providing a change to the Flatpak Manifest to allow USB printing?

**Comment by lbell** [comment]
Still seeing this issue. Fresh install of Ubuntu 25.10. Brave 1.88.136 (Official Build) (64-bit) Chromium: 146.0.7680.164

Installed from the Brave repo, not Flatpack, so don't have that workaround option.

One thing of note:
- If the only printer connection listed is the network printer that Ubuntu discovers automatically, it does not show in Brave.
- If I add the same printer, using "dirverless" it then shows in Brave

In this screenshot, these are both the same printer. The top was automatically added and does not show in brave, the bottom I added and it shows (and prints) in Brave.

<img width="800" height="450" alt="Image" src="https://github.com/user-attachments/assets/98aefea1-45e0-4732-b980-33db95d886fa" />
