### ISSUE TITLE
allowing users to save .torrent files via `Save Link As`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#1436]
## Description 

Currently the only way to save a `.torrent` file is by clicking on the download link, which will open a new tab and load `webtorrent` where you can click on `Save Torrent File`, which is annoying. Users should have the ability to download the `.torrent` file via the context menu without needed to go through `webtorrent`.

There's currently no way of disabling `webtorrent` either so it's currently a pain if you're using another application for torrents.

## Steps to Reproduce

   1. open https://webtorrent.io/ in a new tab
   2. right click on `sintel.torrent` and select `Save Link As..`

## Actual result:

You'll notice that instead of download the `.torrent` file, brave downloads the `HTML Text` link.

## Expected result:

Should be able to download the `.torrent` file via `Save Link As..` as other browsers.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (chrome://version info)

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta(64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Mac OS X

### Reproducible on current release:

- Does it reproduce on brave-browser dev/beta builds? 

Yes, reproducible with the following builds/channels:

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta(64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Mac OS X

Brave | 0.56.2 Chromium: 70.0.3538.35 (Official Build) dev (64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Mac OS X

- Does it reproduce on browser-laptop?

Nope, `Save Link As..` on `.torrent` links doesn't seem to be working at all under `0.24.0`.

**Comment by junkaccount** [comment]
+1 This is extremely annoying. I **love** that Brave has the torrent features built in, but I don't want to use them on my seed box. I don't want to go through all those extra clicks each time.  I just want it to download and open the torrent file instantly like Chrome does.  Feels like a step backwards if we can't disable / bypass the torrent features.

**Comment by matt812** [comment]
In addition, certain file types which the browser does not know how to open just appear as gibberish in a text box, and there is no UI option to "save as".  The "save" only works with media files that the browser knows should be rendered in the media player.  For example try downloading a torrent with an m4b file in it in brave on macos.  I get this:  
![image](https://user-images.githubusercontent.com/37491881/52894656-715d3280-3162-11e9-97ff-4c004ec4d073.png)

**Comment by feross** [comment]
I think that this bug has the same root cause as https://github.com/brave/brave-browser/issues/5361. I'm working on a fix.

**Comment by feross** [comment]
Confirmed that this is the same issue as #5361 and it is fixed by this PR: https://github.com/brave/brave-core/pull/3035

**Comment by kjozwiak** [comment]
@feross this still doesn't seem to be working. Right clicking on a `.torrent` and selecting `Save Link As..` still produces the following when WebTorrent is enabled:

<img width="1027" alt="Screen Shot 2019-09-18 at 1 08 40 AM" src="https://user-images.githubusercontent.com/2602313/65113515-7791e680-d9b1-11e9-87a4-7c3e797747fc.png">

However, once you disable `WebTorrent`, it works correctly:

<img width="1029" alt="Screen Shot 2019-09-18 at 1 08 26 AM" src="https://user-images.githubusercontent.com/2602313/65113504-6d6fe800-d9b1-11e9-8ede-c4a367e5c101.png">

I tried on the following builds and managed to reproduce:

* `0.70.97 CR: 77.0.3865.65` - Reproduced
* `0.69.126 CR: 77.0.3865.65` - Reproduced

Can you see if it's working on your end?

**Comment by feross** [comment]
I'm getting the same behavior as you. I wonder if this broke in some later commit or if it never worked and I missed it because it seemed like the same issue as the other two linked from PR https://github.com/brave/brave-core/pull/3035. Should we re-open this issue and track fixing this in a future version? It's not a terrible bug that should block release or anything like that.

**Comment by kjozwiak** [comment]
@feross agreed that it's not terrible and shouldn't block the `0.69.x` release 👍I'm going to create a follow up issue and label this one as `QA/No` for the `0.69.x` release. This way it will be a lot cleaner and easier to follow rather than opening this issue and having several PR's that landed in different releases referenced.
