### ISSUE TITLE
Clicking on buy button doesn't hide the widget when landing page is loaded

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#14405]
## Description 
Clicking on buy button doesn't hide the widget when landing page is loaded

## Steps to reproduce 

   1. Connect to Binance widget
   2. Click on Buy button on .com/.us
   3. Landing page loads but the widget remains open 

## Actual result 

https://user-images.githubusercontent.com/17010094/109496906-326c5200-7a89-11eb-9b83-79f9f3acfce2.mp4

## Expected result
Widget should auto-hide once the user clicks on Buy button

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Probably

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Tablet
   - Android version: 10
   
## Brave version
1.21.70

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya

**Comment by deeppandya** [comment]
@srirambv this issue should be fixed. would you please verify it again ?

**Comment by chewy917** [comment]
Thank you! "So whether you eat or drink, or whatever you do, do it all for the glory of God."
- ‭‭1 Corinthians‬ ‭10:31‬ ‭NLT‬‬
https://www.bible.com/116/1co.10.31.nlt

**Comment by srirambv** [comment]
@deeppandya  still doesn't seem to be fixed on 1.23.63 build


https://user-images.githubusercontent.com/17010094/114004875-f7fb8f00-9856-11eb-8a71-3ffe7dbd21b4.mp4

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.25.51 x64 beta build
- Verified selecting buy button auto hides the widget menu when landing page is loaded 
------
Verification passed on OnePlus 6T with Android 10 running 1.25.51 x64 beta build
- Verified selecting buy button auto hides the widget menu when landing page is loaded
