### ISSUE TITLE
Logged out all the time

### ISSUE THREAD

**Issue by djprmf** [brave/brave-browser#14793]
**Description of the issue:**
I always had this issue with brave, but is becoming more frequently in the recent versions. The browser doesn't seems to "save" the login state in many websites...
After a couple of restarts on my computer, or the browser itself, I would suddenly be logged out of most the websites that I was logged into - even if i select in those websites the "save login" options. Also happens when all the shields from Brave are off.
‘Clear all cookies on browser exit’ in the Brave settings is disabled.

I have no other program cleaning my settings or cookies. Also, this is something that i experience almost since the first versions of Brave - and doesn't happen in any other browser that i test.

**Steps to Reproduce (add as many as necessary): 1. 2. 3.**

1. Login into different websites
2. If there is a "save login" button, check that option.
3. Restart computer or Browser multiple times (the number of which varies a lot)

**Actual Result (gifs and screenshots are welcome!):**
Logged out of all websites that were previously logged into.

**Expected result:**
Accounts login state saved

**Reproduces how often:**
+2-5 times a week, depends how much restart the computer/browser

**Operating System and Brave Version(See the About Brave page in the main menu):**
Current: Windows 10 20H1
Version 1.21.77 Chromium: 89.0.4389.90 (Compilação oficial) (64 bits)

**Comment by rebron** [comment]
cc: @Brave-Matt

**Comment by cptMikky** [comment]
I can confirm this issue has been manifesting even before v1.15.72 (Linux). Will test on the latest version as soon as it hits my distro's repos.

**Comment by cptMikky** [comment]
Confirmed on 1.25.73. 

When it manifests, it is pretty much always after a reboot and I _think_ it is also after an update but I need to confirm this first.

I'm also convinced that this is related neither to Shield nor to password manager.

Possibly related to #11981: @rebron, in your [comment](https://github.com/brave/brave-browser/issues/11981#issuecomment-765560610) you said that "you're on Linux, your issue has been fixed." - I am on Linux also but I don't see any change. What fix did you have in mind there?

**Comment by djprmf** [comment]
The issue is still happening even in the most recent versions.
I tested the browser also in Linux (Ubuntu) and i can confirm the exact same problem. 

Also adding that this happens without any extension installed. The issue happens with the default brave settings, no extensions and shields up/down for everything.
Seems related with the browser itself.

**Comment by ikariwing** [comment]
I also encountered this in recent versions for 2~3 weeks, it seems like the issue was eased after my last updated but I realized that it actually didn't.

Now I am forced to login my multiple google accounts (and other accounts) almost everyday.

My Brave version = Version 1.25.73 Chromium: 91.0.4472.106 (Official Build) (x86_64)
OS version = MacOS Big Sur 11.2.3 (20D91)

c.c. @yrliou  😛 I also found this issue which might be caused by same reason XD

**Comment by ikariwing** [comment]
This issue might be related to https://github.com/brave/brave-browser/issues/16377

**Comment by djprmf** [comment]
Note that the login details are still saved in the browser. 
In my case, the login isn't deleted at all. Is like something is clearing the cookies automatically (but no configuration to do it is active)

**Comment by cptMikky** [comment]
Happened again after an upgrade to 1.26.74. As of now I'm _pretty confident_ that this is somehow related to Brave updates. I am also convinced that it has nothing to do with saved forms data (i.e. "saved login details" like user names, passwords, etc.)

**Comment by djprmf** [comment]
I recently stop noticing this behavior. Don't know if is related, but now i use Brave with the default protections of the Shields "off". Since this i didn't notice any strange login behaviour in Google.
but, of course, this is not a solution.

**Comment by cptMikky** [comment]
I have the Shield on by default but this issue is global - all sites are affected, including those for which I have the Shield disabled.

**Comment by cptMikky** [comment]
1.29.77 and guess what?

**Comment by djprmf** [comment]
@cptMikky Since my previous post, and in recent versions also, i stop notice this.
I don't know if is really something from brave or not, but is a strange behavior.

**Comment by rebron** [comment]
@djprmf Per your last comment, are we ok to close this issue? This issue may have been addressed with an updated version of chromium. Latest version of Brave is 1.31.91 Chromium 95.0.4638.69

**Comment by djprmf** [comment]
For what i can see, yes.
If happens again i will open it 👍

**Comment by cptMikky** [comment]
As of 1.31.91 I don't see this behavior as prominent as it was before but some times, some sites still get logged out. At this point I'm not sure if it is a site problem or a browser problem. Will try to find a pattern and if I see one, I'll report back.

**Comment by lil5** [comment]
I've had these same issues on chromium every so often after an update, purely _speculation_ but this might be an upstream issue from chromium that's now been fixed

**Comment by cptMikky** [comment]
After upgrade to 1.36.111 from 1.36.109, *all* sites have been logged out, including Facebook, which usually "survived" previous updates when this bug was prominent. Not sure if it's the same bug though - @rebron reopen this issue or should I create a new one?

Linux (NixOS)

**Comment by cptMikky** [comment]
Some logins lost again after upgrade to 1.36.116 (not Facebook though).

**Comment by jficz** [comment]
@rebron still relevant for _some_ sites on 1.32.199, namely a private Nextcloud instance (logged out on almost each browser close), self-hosted Jira and Confluence and a few other webapps (such as Precoro or bob) or services (GOG _sometimes_).  Shield is off for all self-hosted services.

_Not_ logged out from Facebook, WhatsappWeb, ProtonMail, Github.

**Comment by dougbutner** [comment]
I am having this issue now. 1.40.113
