### ISSUE TITLE
Newtab tile background for favicons doesn't match theme

### ISSUE THREAD

**Issue by toastal** [brave/brave-browser#14807]
## Description 

When I go to the new tab page, a list of favicons is displayed. As more users do `responsive favicons`(https://wpguynews.com/how-to-favicon-in-2021#ii-a-single-svg-icon-with-lightdark-version-for-modern-browsers), `(prefers-color-scheme: dark)` will be increasingly common. Currently on `.bsoinH` the background is always `#fff` which does not match the browser's tab color/browrser chrome which is what favicons should be optimized for -- matching tabs and on color schemes as specified.

## Steps to Reproduce

   1. Set browser to dark theme
   2. Get a responsive site's icon in the newtab page however that's easiest
   3. Visit newtab page

## Actual result:

We can see an older static PNG version of the favicon as well in this list.
![chrome___newtab_(Moto G4)](https://user-images.githubusercontent.com/561087/111620183-48467a80-87de-11eb-8b7b-aaf5eb14a436.png)

## Expected result:
Dark background behind the icons on the dark theme (preferably matching the tab color)

## Reproduces how often: 

Always

## Brave version (brave://version info)

1.21.76 Chromium: 89.0.4389.86 (Official Build) (64-bit)
0c2dac31bc21e806a791641316e99920f84ea52c-refs/branch-heads/4389@{#1472}
Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Didn't check
- Can you reproduce this issue with the nightly channel? Didn't check

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
cc: @karenkliu

**Comment by karenkliu** [comment]
@rebron   Is this still an issue since we made the top sites tiles follow OS theming?

**Comment by bsclifton** [comment]
@toastal can you please re-check? This should be live now (as of Brave version 1.24). Any tiles there may need to be visited again to pull the newer favicon (just clicking is enough to update icon)

I'll close this issue as it should be resolved - but let us know! We can re-open and investigate if it's not resolved 😄

**Comment by toastal** [comment]
I am still seeing this in `Version 1.23.71 Chromium: 90.0.4430.72 (Official Build) (64-bit)`. When NixOS Unstable gets a later version, I can check again.
