### ISSUE TITLE
Wrong log message for promoted content ad frequency capping

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#15153]
Follow up to https://github.com/brave/brave-browser/issues/14341.
Only the log message is wrong. The promoted content ad is actually blocked.

## Steps to Reproduce

1. Follow `Brave Ads maximum promoted content ads per day - 1 per day` from https://github.com/brave/internal/issues/759
2. Watch the same promoted content ad again

## Actual result:
new tab page ad is blocked in the logs
```
has exceeded the frequency capping for new tab page ad
```
Full message:
```
[21110:21110:0330/055057.214363:VERBOSE2:exclusion_rule_util.h(26)] uuid 7370c10c8c28878793ad7b6adc2a93a79882e7878f934f172d7cfa33b8cfabc4 has exceeded the frequency capping for new tab page ad
[21110:21110:0330/055057.214431:VERBOSE1:promoted_content_ad.cc(122)] Promoted content ad: Not allowed
```

## Expected result:
promoted content ad is blocked in the logs

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.23.53 Chromium: 89.0.4389.105 (Official Build) beta (64-bit)
-- | --
Revision | 14f44e21a9d539cd49c72468a29bfca4fa43f710-refs/branch-heads/4389_90@{#7}
OS | Linux

cc @tmancey @moritzhaller @jsecretan @mattmcalister @brave/legacy_qa

**Comment by tmancey** [comment]
Closing issue as resolved by https://github.com/brave/brave-browser/issues/9805

**Comment by btlechowski** [comment]
Currently, the promoted content ads are not served on any server (prod, staging, dev) so we are blocked. I will move the milestone to 1.26.x.

**Comment by btlechowski** [comment]
The promoted content ads are still not served on any server. Setting as `QA/Blocked` for now

**Comment by btlechowski** [comment]
Promoted content ads work on staging. Removed `QA/Blocked`.

**Comment by btlechowski** [comment]
Verification passed on


Brave | 1.26.59 Chromium: 91.0.4472.101&nbsp;(Official Build)&nbsp;beta&nbsp;(64-bit)
-- | --
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | Linux



Verified test plan from the description

Verified for promoted content ads per day
```
[16559:16559:0611/184920.558648:VERBOSE2:permission_rule_util.cc(23)] You have exceeded the allowed promoted content ads per day
```

Verified for promoted content ads per hour
```
[17901:17901:0611/190335.772546:VERBOSE2:permission_rule_util.cc(23)] You have exceeded the allowed promoted content ads per hour
```
