### ISSUE TITLE
"Ipfs" should read "IPFS" in "Brave Ipfs Client Updater" in brave://components

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#15764]
## Description 

This is a super-minor bug, but "Ipfs" should read "IPFS" in "Brave Ipfs Client Updater" in brave://components

## Steps to Reproduce

   1. on `nightly`, load `brave://components`
   2. look at `Brave Ipfs Client Updater (Windows) - Version: 1.0.3`

## Actual result:

![brave-ads-resources](https://user-images.githubusercontent.com/387249/117898588-23203680-b27a-11eb-8c11-8e7a9f15b83d.png)

## Expected result:

Should read `Brave IPFS Client Updater` -- upper-case, as in https://ipfs.io/

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.26.16 Chromium: 91.0.4472.38 (Official Build) nightly (64-bit)
-- | --
Revision | 8155e7afab5d695cf0e028f4d77203287523cda9-refs/branch-heads/4472_35@{#6}
OS | Windows 10 OS Version 2009 (Build 21376.1)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by JamesThePaladin** [comment]
I'd like to pick this one up if that's okay. I'm just waiting on a build to see if tis fixed.

**Comment by srirambv** [comment]
@JamesThePaladin assigned the issue to you. Please a PR created for it once you see it fixed on your local build.

**Comment by spylogsster** [comment]
seems it is already fixed, let's recheck after updating to 0.9.0 node

**Comment by stephendonner** [comment]
> seems it is already fixed, let's recheck after updating to 0.9.0 node

Looks like it's still an issue with `0.9.0-rc1`.

<img width="1298" alt="Screen Shot 2021-06-01 at 17 10 40" src="https://user-images.githubusercontent.com/387249/120405010-6f501b00-c2fc-11eb-9c83-906a7f4055ee.png">

**Comment by stephendonner** [comment]
Verified `FIXED` using 

Brave | 1.27.42 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | macOS Version 11.4 (Build 20F71)

<img width="1075" alt="Screen Shot 2021-06-04 at 1 34 29 PM" src="https://user-images.githubusercontent.com/387249/120859894-b4ad5c00-c539-11eb-86c0-b4e00f3a3439.png">
