### ISSUE TITLE
Recaptcha issues in Brave

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#16636]
## Description 
Users are reporting recaptcha issues from https://github.com/brave/brave-browser/issues/16630

## Steps to Reproduce

   1. Open Console (Press F12)
   2. Testing 2 sites, https://patrickhlauke.github.io/recaptcha/ and https://www.google.com/recaptcha/api2/demo
   3. Solve captcha, paste console messages

## Brave version (brave://version info)

`Version 1.26.67 Chromium: 91.0.4472.114 (Official Build) (64-bit)`

## Version/Channel Information:

Test in the various Brave builds:

- Can you reproduce this issue with the current release?  
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Miscellaneous Information:

Reported by @Immow @arch-btw in https://github.com/brave/brave-browser/issues/16630

**Comment by arch-btw** [comment]
Thank you @ryanbr , and sorry I thought the original issue was the same as this one.

Here's my brave version by the way:

Version 1.28.32 Chromium: 91.0.4472.124 (Official Build) nightly (64-bit)

**Comment by Immow** [comment]
VM19:77 Uncaught DOMException: Blocked a frame with origin "https://patrickhlauke.github.io" from accessing a cross-origin frame.
    at Object.blocker.install (<anonymous>:77:17)
    at HTMLIFrameElement.get [as contentWindow] (<anonymous>:128:19)
    at Object.U [as filter] (https://www.gstatic.com/recaptcha/releases/eKRIyK-9MtX6JxeZcNZIkfUq/recaptcha__en.js:89:350)
    at V.<anonymous> (https://www.gstatic.com/recaptcha/releases/eKRIyK-9MtX6JxeZcNZIkfUq/recaptcha__en.js:384:202)
    at uG (https://www.gstatic.com/recaptcha/releases/eKRIyK-9MtX6JxeZcNZIkfUq/recaptcha__en.js:489:151)
    at a (https://www.gstatic.com/recaptcha/releases/eKRIyK-9MtX6JxeZcNZIkfUq/recaptcha__en.js:131:362)
/favicon.ico:1 Failed to load resource: the server responded with a status of 404 ()
VM19:77 Uncaught DOMException: Blocked a frame with origin "https://patrickhlauke.github.io" from accessing a cross-origin frame.
    at Object.blocker.install (<anonymous>:77:17)
    at HTMLIFrameElement.get [as contentWindow] (<anonymous>:128:19)
    at Object.U [as filter] (https://www.gstatic.com/recaptcha/releases/eKRIyK-9MtX6JxeZcNZIkfUq/recaptcha__en.js:89:350)
    at V.<anonymous> (https://www.gstatic.com/recaptcha/releases/eKRIyK-9MtX6JxeZcNZIkfUq/recaptcha__en.js:384:202)
    at uG (https://www.gstatic.com/recaptcha/releases/eKRIyK-9MtX6JxeZcNZIkfUq/recaptcha__en.js:489:151)
    at a (https://www.gstatic.com/recaptcha/releases/eKRIyK-9MtX6JxeZcNZIkfUq/recaptcha__en.js:131:362)
blocker.install @ VM19:77
get @ VM19:128
U @ recaptcha__en.js:89
(anonymous) @ recaptcha__en.js:384
uG @ recaptcha__en.js:489
a @ recaptcha__en.js:131
patrickhlauke.github.io/:1 Uncaught (in promise) Timeout
setTimeout (async)
(anonymous) @ recaptcha__en.js:183
(anonymous) @ recaptcha__en.js:90
(anonymous) @ recaptcha__en.js:89
(anonymous) @ recaptcha__en.js:395
(anonymous) @ recaptcha__en.js:396

**Comment by ryanbr** [comment]
Does Nightly and/or Beta help here? @Immow @arch-btw

**Comment by Immow** [comment]
Can I install that over my current version?

**Comment by arch-btw** [comment]
@ryanbr I'm only using nightly and it has this issue.

**Comment by ryanbr** [comment]
@Immow Nightly and Beta create seperate profiles, so won't impact your main Brave release profile

**Comment by Immow** [comment]
@ryanbr Do you want me to test it, considering @arch-btw has the same issue?

**Comment by ryanbr** [comment]
Just to confirm, do both recaptcha test pages don't work? @Immow @arch-btw

**Comment by Immow** [comment]
https://www.google.com/recaptcha/api2/demo **works**
https://patrickhlauke.github.io/recaptcha/ **fails**

**Comment by ryanbr** [comment]
Do you see the same @arch-btw from the 2 test sites?

**Comment by arch-btw** [comment]
Same result for me, google.com works, patricklauke fails.

**Comment by ryanbr** [comment]
Thanks, just investigating. Will update the ticket with any further updates

**Comment by arch-btw** [comment]
@ryanbr Thank you, it's resolved in today's nightly:


Version 1.28.33 Chromium: 91.0.4472.124 (Official Build) nightly (64-bit)


Yesterday's nightly still had the issue.

**Comment by ryanbr** [comment]
@arch-btw possible to uninstall current Nightly and re-install either of the older builds to confirm it was still an issue? Just to give us an idea which exact build fixed it and find out the possible patch?

[Nightly v1.28.32](https://github.com/brave/brave-browser/releases/tag/v1.28.32) or [Nightly v1.28.31](https://github.com/brave/brave-browser/releases/tag/v1.28.31), or [Nightly v1.28.30](https://github.com/brave/brave-browser/releases/tag/v1.28.30)

**Comment by arch-btw** [comment]
@ryanbr yes I will do that right now, please give me a few minutes 👍

**Comment by arch-btw** [comment]
@ryanbr very strange, suddenly recaptcha in all 3 versions you mentioned are working. Is it possible some files aren't downgraded when installing a previous version?

I'm 100% sure it wasn't working in Version 1.28.32. But it is now.

**Comment by ryanbr** [comment]
You could always remove the nightly profiles in `C:\Users\<username>\AppData\Local\BraveSoftware` @arch-btw 

Is it still an issue @Immow  ?

**Comment by Immow** [comment]
I did not change anything on my Brave browser and both now seem to work, does it auto update?
1.26.74 Chromium: 91.0.4472.124 (Official Build) (64-bit) seems this number did change.

**Comment by ryanbr** [comment]
No changes in Brave would've fixed this, closing the issue maybe been server side.  Lets hope it stays fixed :)
