### ISSUE TITLE
Restore session on KDE not respected

### ISSUE THREAD

**Issue by rajinder-yadav** [brave/brave-browser#17128]
## Description 

On my KDE desktop I have already have restore last session but Brave does not restore itself automatically. I have to launch Brave manually all the time.

FYI: KDE supports 1) Restore last session, 2) Restore from last "Saved session". Testing should be done for both.

Also every time I reboot my Linux PC, I am always asked if I want to restore all previous session by Brave. I would like to see an option available, even on the popup dialog, like a check-mark saying, "Don't ask again".

It's really annoying to have to click on the button each time, also the button in the dialog doesn't even have focus, so I can't just hit Enter on my keyboard to accept yes as the default option.

## Steps to Reproduce

   1. Open multiple browser windows, with many tab.
   2. Reboot PC
   3. Open Brave

## Actual result:

A popup dialog display asking to restore last session.

## Expected result:

Option to not have to click yes all the time. I am already use restore session on my Linux KDE, Brave should respect this and not bother me.

## Reproduces how often: 

All the time.

## Brave version (brave://version info)

Version 1.26.77 Chromium: 91.0.4472.164 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? na
- Does the issue resolve itself when disabling Brave Rewards? na
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

Operating System: openSUSE Tumbleweed 20210721
KDE Plasma Version: 5.22.3
KDE Frameworks Version: 5.84.0
Qt Version: 5.15.2
Kernel Version: 5.13.2-1-default (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 2700X Eight-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: Radeon RX 570 Series

**Comment by OmeCor** [comment]
I second this:

Operating System: KDE neon 5.24
KDE Plasma Version: 5.24.5
KDE Frameworks Version: 5.94.0
Qt Version: 5.15.4
Kernel Version: 5.13.0-40-generic (64-bit)
Graphics Platform: Wayland
Processors: 8 × 11th Gen Intel® Core™ i7-1195G7 @ 2.90GHz
Memory: 15,3 GiB of RAM
Graphics Processor: Mesa Intel® Xe Graphics

Brave version: 1.39.111 Chromium: 102.0.5005.61 (Official Build) (64-bit)

Same description, result and expected result as above, both in Wayland and in X11.

**Comment by Brave-Matt** [comment]
I have another +1 from Community here:
https://community.brave.com/t/why-doesnt-brave-restore-session-when-machine-is-rebooted/493705/2

**Comment by UKnau22** [comment]
I have a similar problem. Brave doesn't actually even ask to restore my last session when restarting my Linux machine. I did find the sessions data along with the tabs file in /home/USERNAME/.config/BraveSoftware/Brave-Browser/Default/Sessions
How can I restore my last session from that?

**Comment by UKnau22** [comment]
I actually found a way... When I run sudo killall brave in a terminal window and the restart Brave it will restore the last session. However, that doesn't seem right

**Comment by Tubo** [comment]
This should be resolved in plasma 6.1 and above. See https://pointieststick.com/2024/02/23/this-week-in-kde-real-fake-session-restore/.

**Comment by KhalilSecurity** [comment]
> This should be resolved in plasma 6.1 and above. See https://pointieststick.com/2024/02/23/this-week-in-kde-real-fake-session-restore/.

I had high hopes while upgrading, but the issue still exists in Plasma 6.1.3. I'm surprised Firefox and all other apps restore successfully but not Brave. In fact Brace started showing all these popups (Report to devs, restore session). It's not a major issue for me, but would be a nice convenience.

**Comment by Tubo** [comment]
Hmm it worked fine for me on KDE Neon. I did need to toggle the session settings and restart a couple of times for it to come into effect. FYI I was using the `.deb` version, but the flatpak version.

**Comment by ethanh20009** [comment]
From
> I actually found a way... When I run `sudo killall brave` in a terminal window and then restart Brave it will restore the last session. However, that doesn't seem right

For nix users with home-manager, just made, tried and tested in `home.nix`
```nix
  systemd.user.services.kill-brave-on-shutdown = {
    Unit = {
      Description = "Kill Brave browser processes before shutdown/reboot";
    };
    Install = {
      WantedBy = ["graphical-session.target"];
    };
    Service = {
      Type = "oneshot";
      stopWhenUnneeded = true;
      ExecStart = "${pkgs.coreutils}/bin/true";
      ExecStop = "${pkgs.killall}/bin/killall brave";
      RemainAfterExit = true;
      TimeoutStopSec = "3s";
    };
  };

```
Hacky, but working so far.

**Comment by rajinder-yadav** [comment]
I suggest if anyone wants this fixed, they open a bug against chromium browser. Brave is just a clone of chromium. 

For what it's worth. Firefox handles reboot and shutdown well. I've switched back to FF and stop using brave because of this annoyance. Suffice to say the brave team in incapable of fixing any bugs.

**Comment by MV10** [comment]
> This should be resolved in plasma 6.1 and above. See https://pointieststick.com/2024/02/23/this-week-in-kde-real-fake-session-restore/.

In addition to not actually restoring anything the browser was showing, this also only restores the single browser window that last had focus (I typically have three open).

It's annoying that it's "better" to do a dirty shutdown (halt or reboot) because then Brave will "notice" and prompt to restore all windows and content correctly.

**Comment by alant54** [comment]
I’m experiencing the same issue described in the precedent comment. Brave generally work well for me, but this is by far the most annoying bug, and it has been happening for a long time. I really hope it can be addressed in a future fix.

As a workaround, I’m currently using the open-source "Tab Session Manager" extension. It restores all my tabs after a reboot. The only remaining problem is that windows position/size isn’t restored correctly, which I think is related to KDE Wayland rather than Brave itself.

**Comment by MV10** [comment]
> The only remaining problem is that windows position/size isn’t restored correctly, which I think is related to KDE Wayland rather than Brave itself.

I only use X and size/position isn't _reliably_ restored.

**Comment by rudiservo** [comment]
@MV10 from what I experience this only happens in wayland, X11 or XLibre works well and also restores most of windows on their previous monitors.

Either this is a Wayland issue or a KDE issue.

**Comment by MV10** [comment]
@rudiservo I have been using KDE with X11 since I switched to Linux last year. There is a known OpenGL texture bug with Nvidia drivers under Wayland, and I do a lot of OpenGL programming.

The OP was about automatic restoration.

That still doesn't happen, but recently (past two or three releases) things have improved a lot. I'd say about 75% of the time all the windows show up on the right monitors in the right positions. For the other ~25% it reliably opens the right windows and tabs, they just aren't positioned correctly, they all get piled up on top of whatever window last had focus. Sometimes they still separate out by monitor, and other times only windows on the monitor that had focus gets restored.

Kind of odd it isn't 100% reliable under X11 by now. I understand why this is a problem under Wayland ... such ludicrous restrictions is one of many reasons I would avoid Wayland even if Nvidia fixes their drivers.

**Comment by rudiservo** [comment]
@MV10 Interesting, I didn't know that.

I actually have an AMD Card and I am using brave under flatpak in arch, has much has I like KDE, eyecandy is just about right IMO, I think I am going to try XFCE and try it out for a while to check out the behavior.

But I have the same experience that you have, about 75% and 25% also on a AMD card and that is interesting, same issue on both drivers?

X11 is being phased out, now you have XLibre and I get why some devs want Wayland, it makes some things nicer to debug and develop on one hand, but wayland is still years away from having some basic Xorg functionality and technical decisions are slower than a slug taking a nap, so I don't think things will get fixed anytime soon by either by NVIDIA (AI Slop) or wayland dev team (no decision making), but the push for Wayland is real to the point where bugfixes to X11 where frozen on purpose, that's why XLibre came out and now there is a whole drama about XLibre existence, I am honestly very disappointed the way politics got into OSS projects.

Anyway I digress.
I know the OP is about automatic restoration and I probably should do a ticket about loosing session history under wayland.

Thanks for you input ;)

**Comment by MV10** [comment]
> I am honestly very disappointed the way politics got into OSS projects.

You and me both.
