### ISSUE TITLE
Purchase intent is extracted twice on google.com

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#17294]
This is because of gdpr consent

## Steps to Reproduce

1. Clean profile
1. Enable rewards
1. Wait till ads catalog and all components are downloaded
1. Close Brave
1. search with google for a keyword (example: `conspiracy`)
1. Check `ads_serice/client.json`

## Actual result:

Purchase intent is extracted twice for both funnel site (google.com) and keyword(conspiracy)
![image](https://user-images.githubusercontent.com/34715963/127841562-c8fabc65-1359-4656-9eea-f780a1cb0918.png)

Note: notice that sometimes only keyword is extracted, still it is extracted twice

This is before gdpr consent:
![image](https://user-images.githubusercontent.com/34715963/127843985-482b5d42-deab-4435-b677-a95d37dc4112.png)
After gdpr consent, the purchase intent is extracted again
![image](https://user-images.githubusercontent.com/34715963/127844152-cbfae47e-e7b6-4701-9650-e62508758ae9.png)

Important: the purchase intent will always be extracted twice, that is on subsequent searches, even when not shown:
![image](https://user-images.githubusercontent.com/34715963/127844451-81b13352-6b5c-4169-9e1d-f6c93b141a5a.png)

## Expected result:
Purchase intent extracted once

## Reproduces how often: 

Easily reproduced

## Desktop Brave version:

Brave | 1.28.98 Chromium: 92.0.4515.115 (Official Build) beta (64-bit)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | Ubuntu 18.04 LTS

cc @tmancey @moritzhaller @iambrianfung @rebron @jsecretan @brave/legacy_qa

**Comment by tmancey** [comment]
@btlechowski resolved by https://github.com/brave/brave-browser/issues/13893

**Comment by btlechowski** [comment]
The issue is still reproducible. Per our process logging a follow up issue: https://github.com/brave/brave-browser/issues/17908

Brave | 1.30.65 Chromium: 93.0.4577.63 (Official Build) beta (64-bit)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | Ubuntu 18.04 LTS

```
[22965:22965:0907/163032.628125:VERBOSE1:conversions.cc(238)] Checking URL for conversions
[22965:22965:0907/163032.640751:VERBOSE1:purchase_intent_processor.cc(99)] Extracted purchase intent signal from visited URL
[22965:22965:0907/163032.641703:VERBOSE1:ads_impl.cc(188)] Search engine pages are not supported for text classification
[22965:22965:0907/163032.646832:VERBOSE1:conversions.cc(301)] No conversions found for visited URL
[22965:22965:0907/163046.941652:VERBOSE1:ads_impl.cc(204)] Browser state changed to idle
[22965:22965:0907/163053.964720:VERBOSE1:ads_impl.cc(221)] Browser state changed to unidle after 21 s
[22965:22965:0907/163053.965993:VERBOSE2:permission_rule_util.cc(23)] Notifications not allowed
[22965:22965:0907/163053.966093:VERBOSE1:ad_notification_serving.cc(104)] Ad notification not served: Not allowed due to permission rules
[23002:23012:0907/163101.313836:WARNING:key_storage_libsecret.cc(55)] the encryption key has been modified since it was created.
[22965:22965:0907/163102.351893:VERBOSE6:user_activity.cc(42)] Triggered event: 0B (2.5:2:3600 s)
[22965:22965:0907/163102.355119:VERBOSE6:user_activity.cc(42)] Triggered event: 06 (2.5:2:3600 s)
[22965:22965:0907/163102.409560:VERBOSE1:database_server_publisher_banner.cc(142)] Server publisher banner not found
[22965:22965:0907/163102.533974:VERBOSE1:conversions.cc(238)] Checking URL for conversions
[22965:22965:0907/163102.534479:VERBOSE1:purchase_intent_processor.cc(99)] Extracted purchase intent signal from visited URL
[22965:22965:0907/163102.534971:VERBOSE1:ads_impl.cc(188)] Search engine pages are not supported for text classification
```
