### ISSUE TITLE
Disable variations service

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#1733]
Service sends and receives information to Google servers periodically. According to https://cs.chromium.org/chromium/src/components/variations/service/variations_service.cc?l=232 it is only enabled for official Google Chrome builds, but there is also a command line switch to enable it.

At a minimum, we should ensure that the IFDEF for official Chrome builds is not being triggered, and also disable the command line switch.

As a defense-in-depth, we could also patch `VariationsService::DoFetchFromURL` https://cs.chromium.org/chromium/src/components/variations/service/variations_service.cc?l=506 to ensure it never issues a network request.

**Comment by tomlowenthal** [comment]
@jumde Could you check whether this is already fixed?

**Comment by jumde** [comment]
Not fixed yet, there are a couple of features using this service. Setting the estimate to `3` to make sure disabling this service does not cause any web-compat concerns.

**Comment by iefremov** [comment]
Now it is known as Griffin https://github.com/brave/brave-variations/

**Comment by bsclifton** [comment]
Brave experiments are publicly visible here:
https://griffin.brave.com/

The Google experiments are not being used (no calls to Google made)
