### ISSUE TITLE
Cannot disable Shield if the URL host contains port

### ISSUE THREAD

**Issue by sushilman** [brave/brave-browser#1896]
## Description 

The toggle button of the 'Shield' immediately switches back to 'Up' when trying to disable the Shield, if the URL in the address bar has some port in it.

## Steps to Reproduce

   1. Open a new tab
   2. Open localhost:8080 (does not matter even if you see 'This site can’t be reached')
   3. Try to take the 'Shield' down (immediately goes back to 'Up')
   4. Now try it on localhost without port (does not matter even if you see 'This site can’t be reached'), you can take 'Shield' down, it works fine
   5. Try on port other than 80, e.g. localhost:81, you cannot take the 'Shield' down
   6. Try it on any URL other than localhost, the result is the same.

## Actual result:

Shield cannot not be disabled on URLs with port in its host.

## Expected result:
Shield should be allowed to be disabled.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

OS: MacOS mojave 
Brave version: Version 0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)

and 

OS: Arch Linux
Brave version: Version 0.55.10 Chromium: 70.0.3538.22 (Official Build)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Haven't tried yet.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rotational467** [comment]
Is there a workaround for this?  It's causing some trouble with a number of internal sites I have.  Interestingly, I **am** able to disable shields on a site running on 8181, but any other port I see the same behavior as reported above.

**Comment by boganpaul** [comment]
> Is there a workaround for this? It's causing some trouble with a number of internal sites I have. Interestingly, I **am** able to disable shields on a site running on 8181, but any other port I see the same behavior as reported above.

I ran into this same issue and your advice about port 8181 allowed me to work around it, so thanks! Remapping the host name and port to another name on port 8181 fixed it right up. I'm on Windows and I fixed it by:

1. Download and install [Fiddler](http://www.telerik.com/download/fiddler)
2. Click 'Tools', then 'HOSTS...'
3. Tick the 'Enable remapping of requests...' box
4. Enter something like:
`localhost:1234 newdomain:8181`

Not the most elegant solution but it saves me from multiple browsers open at once.

**Comment by VMBindraban** [comment]
Still happening in:

Brave | 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

**Comment by T-Zahil** [comment]
Same here on MacOS, latest brave version. It's really annoying, because with this error + the CORS error (https://github.com/brave/brave-browser/issues/2252), it's impossible for me to use brave to do web development :/

**Comment by jspieker** [comment]
> Same here on MacOS, latest brave version. It's really annoying, because with this error + the CORS error (#2252), it's impossible for me to use brave to do web development :/

Same issue, selecting `All cookies allowed` in the Brave shield options is a temporary workaround for me.

**Comment by 2635599** [comment]
i don't know about the 8080 port but yes on certain sites i cannot disable the shield. i can't disable it at all on those sires, not just disable and it reenables, on those site i can't switch it off at all.

**Comment by ggjersund** [comment]
Would love for this to be fixed as I'm actively using Brave in web development using multiple local websites with different ports that need to interact. E.g. Angular and backend API.

**Comment by PersonalProxy** [comment]
+1 I am also experiencing this.
```
Windows 10 (10.0.17134 Build 17134)
Brave Browser (0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit))
```
Using a localhost setup and some things are simply not working correctly with Shield UP, and there is no way to turn them off.

Tested the same exact sites works in Firefox, Chrome, and Edge, even with uBlock Origin, Privacy Badger, HTTPS Everywhere and Decentralized Eyes, the issue is specific to Brave.

**Comment by kekukui** [comment]
**This bug is silently breaking various components of the web interface on millions of Network Attached Storage devices (e.g. Synology) and IPTV distribution systems (e.g. TVheadend).  Specifically, it appears that HTTPS Everywhere is interfering with page rendering.  Just wanted to document this and suggest the fix be deployed as soon as possible.**

**Comment by VMBindraban** [comment]
> **This bug is silently breaking various components of the web interface on millions of Network Attached Storage devices (e.g. Synology) and IPTV distribution systems (e.g. TVheadend). Specifically, it appears that HTTPS Everywhere is interfering with page rendering. Just wanted to document this and suggest the fix be deployed as soon as possible.**

That sounds like a new issue.

**Comment by kekukui** [comment]
> **That sounds like a new issue.**

In the online demo,* the Ad Control setting seems to be interfering too, and when it breaks, the page wont render at all, while HTTPS Everywhere disables parts of the page.  But in either case, switching the Shield off entirely should resolve the issue, if that were possible.

* https://demo.synology.com/en-us/dsm

**Comment by VMBindraban** [comment]
Can you create a new issue with the label `feature/shields/webcompat`?

**Comment by kekukui** [comment]
I dont think I can make labels because I dont have write access.  And I am not sure how to properly characterize the issue yet:  Does the global Shield control in the URL bar change any other hidden settings (besides the 5 toggles which you can see) ?

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.62.11 Chromium: 73.0.3683.39 (Official Build) dev (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used STR from the description.

**Comment by neeilya** [comment]
Got here because of the same problem.
As a temp workaround you can try disabling "Ads and trackers blocked" checkbox -> this solved my cors issues.

**Comment by mcfaith9** [comment]
Is this fixed?

**Comment by bsclifton** [comment]
@mcfaith9 issue should be fixed - QA has verified. Are you still encountering this problem?

**Comment by mcfaith9** [comment]
I'm following this issue for a while, and i lost track and forgot this. Yes its working fine now, Thank you!
