### ISSUE TITLE
Google Translate extension is missing right click context menu

### ISSUE THREAD

**Issue by 844700118** [brave/brave-browser#18994]
https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb

Why does the Google Translate plugin not have a "Google Translate" option in the Brave browser right-click menu?

**Comment by bborowin** [comment]
The issue seems resolved in 1.80.113

**Comment by GKid94** [comment]
Still a problem.

<img width="1057" height="575" alt="Image" src="https://github.com/user-attachments/assets/eed8f930-929e-4dae-b971-2ae42846e225" />
