### ISSUE TITLE
Google Hangouts / Google Meet: Screenshare feature is non-functional

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#1982]
## Description 

Initially experienced this at a talk I was giving last week that used Google Hangouts. 

 * On Windows 10 x64, I'm unable to use the screenshare feature in Google Hangouts. 
 * I'm also experiencing the same issue from Google Meet (which is the new default for meetings when I attempt to repro from Hangouts). 

When I attempt to share my screen, the screenshare button does not function as expected. The button is inactive. 

 - I've tested with and w/o Shields enabled, and I observe the same result.
 - I've tested with and w/o camera and microphone access enabled. Same result.

## Steps to Reproduce

   1.  Go to http://hangouts.google.com
   2.  Start a meeting. 
   3.  Click on the `Share Screen` (Google Hangouts) or `Present Now` (Google Meet)

## Actual result:

 - On Google Hangouts: Nothing happens. Button for `Share Screen` is inactive when engaged. 
 - On Google Meet: When the `Present Now` button is clicked, and the screen share option is selected, there is a delay, and the user is eventually presented with an error message. See below. 

![brave-ghangouts-11032018-error](https://user-images.githubusercontent.com/8979240/47958744-d499cf00-df8e-11e8-887f-782d365f45dd.JPG)

## Expected result:
Screen Share should just work. 

## Reproduces how often: 

100% 

## Brave version (brave://version info)

Brave | 0.55.22 Chromium: 70.0.3538.77 (Official Build) (32-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Windows
JavaScript | V8 7.0.276.32

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes. 
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? Functions in Chrome as expected. 

### Additional Information

@bbondy @bsclifton as a heads up - this is a bug that bites in meetings and/or public, and probably would result in a user leaving Brave when they discover it works in Chrome.

**Comment by srirambv** [comment]
Verification passed on Linux. More details here https://github.com/brave/brave-core/pull/1252#pullrequestreview-192260201

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.59.26 Chromium: 72.0.3626.64 (Official Build) beta (64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Windows

Connected Windows 7 and Ubuntu 17.10. Shared screen on Windows 7.

**Comment by Gary-Armstrong** [comment]
I believe I am having this issue but with version 0.59.35 Chromium: 72.0.3626.81
Might I need to do something on my end, since this was fixed in 0.59.26 ?

**Comment by boggle** [comment]
Confirm, still seeing this issue with version 0.66.101 Chromium: 75.0.3770.142 on Mac OS X.
(Both with shields on and off). In general, it would be great if you payed more attention to preconfiguring brave to just work out of the box with commonly used services like google meet, webex and other conferencing systems.

**Comment by boggle** [comment]
Just enabled the hangouts extensions, this seems to fix it. Why is it not enabled by default?

**Comment by bsclifton** [comment]
@boggle on a fresh install, it does appear to be enabled for me. Have you been using Brave for a while? It's possible that you used it before we changed the default value

**Comment by boggle** [comment]
Must have been that; maybe switched 2 month ago or so.

**Comment by Gary-Armstrong** [comment]
Tried enabling the Meet toggle. Video worked, they could hear me but I could not hear them. Probably just me, something wonky on my Mac? Just the one switch, yes?

**Comment by bsclifton** [comment]
@Gary-Armstrong yup- that one switch should do the trick. It's possible I think to have a different speaker and mic configured (you can check the system settings to confirm) and you may need to restart the browser after enabling
