### ISSUE TITLE
invalid or corrupted PDF file

### ISSUE THREAD

**Issue by michelecafagna26** [brave/brave-browser#2048]
## Description 
Doesn't show pdf file, showing :

PDF.js v2.0.673 (build: 31012570)
Message: Invalid PDF structure

the same pdf is correctly opened in Mozzilla, Chrome and Edges

## Actual result
![pdferror](https://user-images.githubusercontent.com/23355894/48203869-d259bb00-e368-11e8-9f25-7783a3c23315.png)

## Brave version (brave://version info)
Version 0.55.22 Chromium: 70.0.3538.77 (Official Build) (64-bit)

Wibdows 10

**Comment by avndp** [comment]
I'm facing the same issue.. I'm using Ubuntu 18.10

**Comment by Liunkae** [comment]
Please [update to the latest release version](/brave/brave-browser/releases) (0.56.12). The problem (#1287) has been fixed.

**Comment by gustavnikolaj** [comment]
This issue is still present in Version 0.61.51 Chromium: 73.0.3683.75 on macos. Let me know if you need further information.

The cookies seems to not be included on the request made for the pdf file, which ends up resulting in a redirect to a login page.

**Comment by LefterisJP** [comment]
I also see this issue with `Version 0.65.120 Chromium: 75.0.3770.90 (Official Build) unknown (64-bit)` even with all shields down.

**Comment by bsclifton** [comment]
@LefterisJP do you have more information? (not sure if the site you are using requires a login). Would be great if we had some way to reproduce on our side

**Comment by LefterisJP** [comment]
Yep. So the site is actually mine. It does require a login and it's a django website (not live yet) so the test code is all local.

The url requires login access so cookies are involved.

The response is a pdf. In python code it's the following:

```python
...
...
...
    with fs.open(internal_filename) as pdf:
        response = HttpResponse(pdf, content_type='application/pdf')
        response['Content-Disposition'] = f'attachment; filename="{external_filename}"'

    return response
```

Anything else I can do to help?

**Comment by bsclifton** [comment]
@LefterisJP nice! ok so the only thing I would ask would be: can you try Nightly? We removed PDF.js in favor of PDFium. If it works in Chrome/Chromium, it should now work for you :) 

This code will eventually make it's way into the release channel (currently, we're on 0.65.x and the fix was in 0.68.x) - estimated ship date August 20th
https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule#release-channel-dates

**Comment by LefterisJP** [comment]
@bsclifton Done. Used latest AUR nightly package in Archlinux so that makes it 0.68.60-1.

There the problem is gone. Clicking on the URL downloads the pdf, just like in Chromium and then you can click on the download to see a preview which renders just fine. :+1:

**Comment by bsclifton** [comment]
@LefterisJP awesome! thank you so much for confirming 😄 Feel free to stick with Nightly or you can ride it out (and continue to use the more stable Release channel). Thanks again 😎

**Comment by Syden10** [comment]
Issue persists.

![Screen Shot 2019-07-31 at 9 35 38 PM](https://user-images.githubusercontent.com/12631452/62257369-78f45900-b3db-11e9-978e-d93d117bc43e.png)


macOS Version 0.66.101 Chromium: 75.0.3770.142

Thanks.
