### ISSUE TITLE
Tabs falling out when moved, cant be placed into "parent" window again.

### ISSUE THREAD

**Issue by FreshOak** [brave/brave-browser#20635]
I'm not sure if this is a Cinnamon issue or a Brave issue.
Since Linux Mint updated to Una, Brave doesn't allow for any movement of the tabs.
If I try to move a tab (left or right) on Linux Mint (only tested on Cinnamon) it falls away from the tab bar and becomes its own window.
After it has been dislodged from its parent window, it can no longer be placed back into it as a tab again.

## Steps to Reproduce

   1. start new tab
   2. click and drag to move it in the tab list

## Brave version (brave://version info)

1.34.80 Chromium: 97.0.4692.71 (Official Build) (64-bit)

**Comment by ipha** [comment]
This is already fixed in v1.34.81

**Comment by Blanktank** [comment]
> This is already fixed in v1.34.81

I am on Version 1.35.89 beta and still facing this issue. Using Pop!_OS 21.10.

**Comment by Tectract** [comment]
bump I'm experiencing this on a brand new install of Brave, Version 1.34.80 Chromium: 97.0.4692.71 (Official Build) (64-bit)

Can no longer drag tabs, what happened? They just detach now and won't reattach.

**Comment by willfindlay** [comment]
Ditto, here's my affected version:
```
1.39.111 Chromium: 102.0.5005.61 (Official Build) (64-bit)
```
