### ISSUE TITLE
Follow up of PR #11931 - Payment arrived message is not shown

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#20671]
## Description 

Follow up of PR https://github.com/brave/brave-core/pull/11931 - Payment arrived message is not shown

## Steps to Reproduce

   1. Follow the STR from https://github.com/brave/brave-browser/issues/20597
   2. Payment arrived message is not shown

## Actual result:

Payment arrived message is not shown

## Expected result:
Payment arrived message should be shown

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.36.60 Chromium: 97.0.4692.99 (Official Build) nightly (64-bit)
-- | --
Revision | d740da257583289dbebd2eb37e8668928fac5ead-refs/branch-heads/4692@{#1461}
OS | Windows 10 Version 21H2 (Build 19044.1466)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Miyayes @brave/legacy_qa @LaurenWags @zenparsing

**Comment by GeetaSarvadnya** [comment]
The issue is fixed and working fine, verification note are linked in https://github.com/brave/brave-core/pull/11931#issuecomment-1022480362

**Comment by kjozwiak** [comment]
As per discussion with @LaurenWags, going to move this into `1.35.x` even though it wasn't fixed by any PRs. Labelling it as `QA/No` so no one else runs through it accidently. @GeetaSarvadnya already confirmed it's working as per https://github.com/brave/brave-browser/issues/20671#issuecomment-1022484244.
