### ISSUE TITLE
Tab mute no longer working in conventional way

### ISSUE THREAD

**Issue by Trikzbowii** [brave/brave-browser#22081]
## Description 

Tab mute now requires you to click on to the tab to mute it.

## Steps to Reproduce

   1. Play audio on a tab
   2. Leave audio playing on tab and change to a new tab
   3. Click on mute to mute the audio on tab

## Actual result:

Brave now requires you switch to the tab to mute it. So essentially a double click to mute a tab.

## Expected result:
Click on audio icon to mute audio on said tab without switching to it

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.37.109 Chromium: 100.0.4896.60 (Official Build) (64-bit) 

## Version/Channel Information:

Current and Nightly

## Other Additional Information:

N/A

**Comment by rebron** [comment]
cc: @nullhook

**Comment by tdritsas** [comment]
Do we have any news about the issue?

**Comment by GuillaumeBonnet** [comment]
### Installing an old version on windows 10:
As a temporary solution I installed an old version of Brave to get the feature back.

It's not a good idea regarding security and I don't know how to cleanly install an old version on windows 10 but it worked for me:
- got the feature back
- bookmarks are still there
- history still there
- need to login back on every sites
- brave icon in the windows task bar is now blank

Steps:
- go to an older stable release page like: https://github.com/brave/brave-browser/releases/tag/v1.36.122
- download _brave-v1.36.122-win32-x64.zip_
- go to _C:\Program Files_
- rename the _C:\Program Files\BraveSoftware_ into _C:\Program Files\BraveSoftwareNew_ (or store a backup of this folder)
- copy the content of the zip into a fresh _C:\Program Files\BraveSoftware_  folder
- start _brave.exe_
- go in brave's settings, click on _about_ and check that the version number matches.

**Comment by nullhook** [comment]
yes, I can confirm this is an issue. i believe it was introduced in cr100 update. as a workaround you can _right click > mute site_ on the tab to avoid switching context for now. 

<img width="246" alt="image" src="https://user-images.githubusercontent.com/8665427/162648286-464d1c55-d438-4300-9972-ec005cbda0ba.png">

will discuss with @rebron on the fix

**Comment by tdritsas** [comment]
Hi do we have any news about this issue?

It was so much useful feature.

Please Brave turn it back we do not want to move to other browsers for that issue.

**Comment by tdritsas** [comment]
Hi is the issue fixed?

If yes, how can we check? is there any update.

Thanks

**Comment by simonhong** [comment]
@tdritsas PR is ready but not merged yet. Needs code review.
When it's merged you can test it in advance with nightly version.

**Comment by tdritsas** [comment]
Will the fix be added to the Brave official release?

Regards

**Comment by simonhong** [comment]
@tdritsas Yes, this fix is included in `1.39.x` release.
You can get when `1.39.x` becomes stable release.

**Comment by MadhaviSeelam** [comment]
Verified `PASSED` using
Brave | 1.39.86 Chromium: 101.0.4951.41 (Official Build) beta (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Windows 11 Version 21H2 (Build 22000.613)

Verified no longer have to switch to inactive tab to mute and unmute.





![2022-04-29_11h42_31](https://user-images.githubusercontent.com/98358127/166007021-4928296f-8061-49b4-b08d-81425bc8db9a.gif)

**Comment by kjozwiak** [comment]
Removing the `QA Pass` labels as this was uplifted into `1.38.x` via https://github.com/brave/brave-core/pull/13169 and will be pushed out via the `1.38.x` maintenance release as per https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule#release-channel-dates.

**Comment by simonhong** [comment]
@tdritsas Hi, next release will include this fix.

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.38.118 Chromium: 101.0.4951.67 (Official Build) (64-bit)
-- | --
Revision | 8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}
OS | Windows 10 Version 21H2 (Build 19044.1706)

```
Reproduced the issue in `1.37.109` and upgraded the profile to `1.38.118` and confirmed the issue is fixed and working fine, user is no longer required to switch to the inactive audio tab to mute/unmute the audio

**Comment by Shadowized** [comment]
still not working correctly with `v1.38.118` when you have a large number of tabs open, depending on the size of the browser window.

**Comment by simonhong** [comment]
@Shadowized it's expected behavior. When tab's width is small, mute button is disabled to make tab itself clickable.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.38.119 Chromium: 101.0.4951.67 (Official Build) (64-bit)
-- | --
Revision | 8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}
OS | Ubuntu 18.04 LTS

Verified able to mute when tab is not the active tab
![22081](https://user-images.githubusercontent.com/34715963/168851361-72d8ece3-9fd9-4209-a544-bc0e66766c2e.gif)
