### ISSUE TITLE
Many users experiencing extremely slow load times (or no loading at all)

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#23267]
## Description 

It appears that we have a good number of users reporting that the browsers load times have slowed to a crawl, if sites load at all. There don't appear to be many common threads between reports other than that. There are several reports that I will continue to add to this issue as I dig them up. One user left a recording of the behavior (shown here: https://youtu.be/KW0dPinJKBo).

So far, we've seen that:

- A couple users seem to have better results after using switching to Shields v1 (via flag), but this does not resolve the issue for all users
- Un/reinstalling resolves the issue temporarily but after a while the issue returns
- Disabling FPP did not resolve the issue
- Disabling HWA did not resolve the issue
- Clearing cache for site(s) resolves the issue temporarily (for some users) but the issue persists after a while

## Steps to Reproduce

No official steps to reproduce just yet — seems to simply "happen" without any direct action causing it. 

## Reproduces how often: 

Frequently

## Brave version (brave://version info)

v1.39.111

## Version/Channel Information:

- Can you reproduce this issue with the current release? Y
- Can you reproduce this issue with the beta channel? Y
- Can you reproduce this issue with the nightly channel? Y

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N
- Does the issue resolve itself when disabling Brave Rewards? N
- Is the issue reproducible on the latest version of Chrome? N

## Miscellaneous Information:

User threads: 

- https://community.brave.com/t/infinity-load-in-random-pages-slow-loading-or-no-loading/398629

**Comment by rebron** [comment]
cc: @atuchin-m @goodov We still need to get investigate and get this into a reproducible state.
@nullhook Some comments that maybe shields v2 related but still need the test case to see.

**Comment by Brave-Matt** [comment]
Potentially related issues:
https://github.com/brave/brave-browser/issues/23187
https://www.reddit.com/r/brave_browser/comments/v01z1c/need_to_reload_a_page_for_it_to_actually_load/ 
https://www.reddit.com/r/brave_browser/comments/uytxb3/brave_not_loading_certain_pages_until_i_reclick/

**Comment by agalli93** [comment]
Thought I would offer a website where I can ~more consistently replicate the problem. 

Using explore mode on google flights, clicking a city destination, and then clicking a flight in the results column in the left seems to 30-50% of the time cause the problem. 

I've recorded some footage if it could help. 

Windows 10 21H2, 
Version 1.39.111 Chromium: 102.0.5005.61 (Official Build) (64-bit)

https://www.google.com/travel/explore?tfs=CBwQAxoaagwIAhIIL20vMGQ5anISCjIwMjItMDYtMjMaGhIKMjAyMi0wNi0yN3IMCAISCC9tLzBkOWpycAKCAQsI____________AUABSAGYAQGyAQQYASAB&tfu=GgIgAw

https://user-images.githubusercontent.com/3828034/172318270-be57128d-6efe-4f04-aee5-7c67b8af19b6.mp4

Reach out if I can be of assistance.

**Comment by atuchin-m** [comment]
https://github.com/brave/brave-browser/issues/23187

**Comment by atuchin-m** [comment]
Thanks you guys for the reporting.
Does the problem reproduces on [recent nightly builds](https://brave.com/download-nightly/)? It seem to be fixed in https://github.com/brave/brave-browser/issues/22610.
If not, could please collect more details (we don't have a stable reproduction of the bug yet):
1. Does it happen only on navigations from Google?
2. Does disabling De-Amp (on brave://flags) or/and Brave Shield globally resolve the issue?
3. Could you share `brave://histograms` & `brave://net-export/` when the problem happens? (make sure that you select `Strip private information`)
4. Could you please also record & share [performance traces](https://www.chromium.org/developers/how-tos/submitting-a-performance-bug/)?
<img width="581" alt="image" src="https://user-images.githubusercontent.com/45488748/172354646-9b6dd361-00bf-4e51-bade-bed020065c10.png">

**Comment by atuchin-m** [comment]
The DeAmp fix was already merged in `1.39.x` 5 days ago and a new version is scheduled in the next few days.

**Comment by DaniloRoque501** [comment]
https://github.com/brave/brave-browser/issues/23267#

**Comment by DaniloRoque501** [comment]
https://github.com/brave/brave-browser/issues/23267

**Comment by atuchin-m** [comment]
@d-j-a I believe that in most cases the problem is triggered by DeAmp, but not it yours.
Could you please collect extra details in my recent post?

**Comment by agalli93** [comment]
Disabling DeAmp did nothing for me on the release build. 

Since d-j-a said it still happens on the nightly I got some net-exports just on the release. I wasn't sure what exactly to provide of the histogram? I can look into performance traces more later.

Change the .txt to .json since github wasn't happy with me uploading json. 

[chrome-net-export-logOneMiddleFailandLastFail.txt](https://github.com/brave/brave-browser/files/8859609/chrome-net-export-logOneMiddleFailandLastFail.txt)
[chrome-net-export-log3rdAnd5thFail.txt](https://github.com/brave/brave-browser/files/8859611/chrome-net-export-log3rdAnd5thFail.txt)

**Comment by radPhil** [comment]
Just had this problem again in latest Nightly (Version 1.41.42 Chromium: 102.0.5005.78 (Offizieller Build) nightly (arm64))

Here are the requested files:

[Histograms.txt](https://github.com/brave/brave-browser/files/8860417/Histograms.txt)
[trace_Wed_Jun_08_2022_11.40.46.json.gz](https://github.com/brave/brave-browser/files/8860418/trace_Wed_Jun_08_2022_11.40.46.json.gz)
[chrome-net-export-log.json.txt](https://github.com/brave/brave-browser/files/8860424/chrome-net-export-log.json.txt)

**Comment by atuchin-m** [comment]
@radPhil thanks for the details, looking into traces.
Just one sanity check: Does disabling all the extensions solve the issue?

**Comment by valynor** [comment]
The latest update to Version 1.39.120 Chromium: 102.0.5005.99 (Official Build) (arm64) has not fixed it for me. 
Here's a way to semi-reliably trigger the bug on my system: 
Go to http://explosm.net/comics/latest  (yes, http!). This forwards you to the latest webcomic and the server also redirects you to the https version of the site (I have upgrade to https set to off in shields). 
Most of the time the tab doesn't load. On subsequent visits or Shift+CMD+R it redirects and loads immediately. If you try again an hour later it's back to not working again.

**Comment by rudolphos** [comment]
Version: [Version 1.39.120 Chromium: 102.0.5005.99 (Official Build) (64-bit)](https://brave.com/latest/)

@valynor 
I tried opening that website and it doesn't load.
![image](https://user-images.githubusercontent.com/4366810/172735200-b2974bcd-0294-4b42-9a61-7ecc824913b4.png)

**Comment by rebron** [comment]
@rudolphos Do you have other extensions installed? I'm not able to reproduce what you're seeing with shields up (or down).

<img width="1199" alt="Screen Shot 2022-06-08 at 5 00 44 PM" src="https://user-images.githubusercontent.com/5951041/172736975-eec9794a-f9f3-4ad5-83b1-584c28ca1a96.png">


Brave | 1.39.120 Chromium: 102.0.5005.99 (Official Build) (arm64)
-- | --
Revision | 870f7bcc58dfa811cc68c2186439721385e086d0-refs/branch-heads/5005@{#1125}
OS | macOS Version 12.3 (Build 21E230)
JavaScript | V8 10.2.154.7
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.99 Safari/537.36

**Comment by autonomic** [comment]
@atuchin-m here is a link you'll be able to reliably test against. I don't mind sharing it as doesn't contain any sensitive data. I just tested now and the page just sits there loading indefinitely until you manually reload the page (in my case ⌘ + R).

https://urldefense.com/v3/__https://beyondtrustcorp.service-now.com/kb_view.do?sysparm_article=KB0015891__;!!NRZJKXZLOPM!bKTuJlniIb0A319pyqIa59mxqDV9hMw2AnEcouPfX9VlGKIOzxFawQzZIP3-btq9cYoMQ-uCQVnvH-5c-spcvSFaoVncDXo$

**Comment by agalli93** [comment]
> @atuchin-m here is a link you'll be able to reliably test against. I don't mind sharing it as doesn't contain any sensitive data. I just tested now and the page just sits there loading indefinitely until you manually reload the page (in my case ⌘ + R).
> 
> https://urldefense.com/v3/__https://beyondtrustcorp.service-now.com/kb_view.do?sysparm_article=KB0015891__;!!NRZJKXZLOPM!bKTuJlniIb0A319pyqIa59mxqDV9hMw2AnEcouPfX9VlGKIOzxFawQzZIP3-btq9cYoMQ-uCQVnvH-5c-spcvSFaoVncDXo$

Clicking this link on the release build, shields up, de-amp off, loads perfectly fine for me. Even trying it 10x over.

**Comment by autonomic** [comment]
> > @atuchin-m here is a link you'll be able to reliably test against. I don't mind sharing it as doesn't contain any sensitive data. I just tested now and the page just sits there loading indefinitely until you manually reload the page (in my case ⌘ + R).
> > https://urldefense.com/v3/__https://beyondtrustcorp.service-now.com/kb_view.do?sysparm_article=KB0015891__;!!NRZJKXZLOPM!bKTuJlniIb0A319pyqIa59mxqDV9hMw2AnEcouPfX9VlGKIOzxFawQzZIP3-btq9cYoMQ-uCQVnvH-5c-spcvSFaoVncDXo$
> 
> Clicking this link on the release build, shields up, de-amp off, loads perfectly fine for me. Even trying it 10x over.

Weird, so I just tested with a new profile and that link works just fine. However in my main work profile it doesn't. I've disabled all the extensions as well and it still doesn't work in my main profile until I reload the page. I'll try with de-amp off.

**Comment by atuchin-m** [comment]
@autonomic 
This difference can be caused by variations/settings/extension.
Could you please:
1. Restart a browser on the fresh profile and check again;
2. Post brave://version/?show-variations-cmd from the main & fresh profile here?

**Comment by autonomic** [comment]
@atuchin-m So I just checked the output of the show-varations-cmd and ran a diff against both of them and the only difference is the "Profile Path". Everything else is the same (with the extensions disabled in my main profile).

With that said I was able to get that link to work in my main profile a couple of times (not sure why), but now its back to it's old tricks and not loading.

**Comment by atuchin-m** [comment]
Thanks @autonomic/
Could you and other please try to launch browser with `--disable-features=EarlyBodyLoad`?

**Comment by radPhil** [comment]
> [...] try to launch browser with `--disable-features=EarlyBodyLoad`?

Did it. No problem for now.
Will keep using it and report back.

**Comment by autonomic** [comment]
> Thanks @autonomic Could you and other please try to launch browser with `--disable-features=EarlyBodyLoad`?

Same thing. When I first launch the browser with `--disable-features=EarlyBodyLoad` that URL loads a couple of times and then stops working. After that point it just wont load anymore unless I reload the page while it's stuck.

**Comment by autonomic** [comment]
@atuchin-m Hold-up, it's now working again and consistently but I haven't changed anything. I'm still running the browser instance with `--disable-features=EarlyBodyLoad`. Not sure why it was briefly not working but it appears to be working now. I'll have to keep running it like this for a while to see if I see any other sites with the same issue.

**Comment by atuchin-m** [comment]
@radPhil sounds great, because I've discovered the problem in your traces ;) So it should help.

Unfortunately, I'm not sure that all of you have the same problem. 

@autonomic If it doesn't helps, please record the perf traces. Also check brave://crashes just in case.

**Comment by autonomic** [comment]
@atuchin-m I spoke to soon. I just tried another site that I've had issues with in the past that uses SAML for SSO authentication to Azure AD. When I click on the application to login it redirects to login.microsoftonline.com and then just hangs. I'll try to run a perf trace.

**Comment by autonomic** [comment]
@atuchin-m  Here is my perf trace
[trace_Thu_Jun_09_2022_7.06.17_AM.json.gz](https://github.com/brave/brave-browser/files/8871088/trace_Thu_Jun_09_2022_7.06.17_AM.json.gz)
.

**Comment by atuchin-m** [comment]
@autonomic Thanks, looking into it.
One extra thing to distinguish long network delays/timeout from the case I've found: for the original problem pressing the reload button should preserve the url (because the navigation is committed)

**Comment by atuchin-m** [comment]
@autonomic your case is different. I see 4 navigations, but for the last navigation no bytes were sent to renderer process. Could you please make sure that it isn't DeAmp/Speedreader/Shield/Extensions? Also it will be good to verify that other browsers work as expected.

**Comment by autonomic** [comment]
> @autonomic your case is different. I see 4 navigations, but for the last navigation no bytes were sent to renderer process. Could you please make sure that it isn't DeAmp/Speedreader/Shield/Extensions? Also it will be good to verify that other browsers work as expected.

I've disabled DeAmp/Speedreader/Shield/Extensions and still have the issue. I've tested in other browsers with the same site and it's working fine, but not in Brave.

**Comment by djprmf** [comment]
@atuchin-m This is the trace with --disable-features=EarlyBodyLoad 
[trace_trace4.json.gz](https://github.com/brave/brave-browser/files/8872090/trace_trace4.json.gz)

i can still replicate the issue with it.

**Comment by djprmf** [comment]
@atuchin-m I checked and it was there. But after more digging, i clear the cache and start tested again.
Until now, i don't see the issue anymore. the pages appear to load fine now.  👍 

I will test a little more using the browser for some time.

**Comment by djprmf** [comment]
@atuchin-m  Ok, after a little more testing, the --disable-features=EarlyBodyLoad helps, but the issue can still be notice from time to time.
There are some improvements, and most of the pages now load correctly. But at random the pages enter again in the "infinity load" state.

I left here a trace where that happend. I open the website 3 times, in different tabs. the first two times, it loaded fine.
In the third one, it enter in a infinity load state.

The trace is a little big to upload here, but i left the download here: https://mega.nz/file/09EhkIBA#kU4oFYDoazchLu8R6U8IsS059t2PLrRqEQrNQv7bouM

I can confirm that the --disable-features=EarlyBodyLoad is active in the command line

![tugatech-2022-06-09-e9c5904a-33af-4d5a-9d80-c0918ee96263](https://user-images.githubusercontent.com/6960243/172907275-62e5c696-0b4d-4da7-9578-0e563d3a840a.jpg)

**Comment by radPhil** [comment]
The problem just occurred again while I was logging into Salesforce Commerce Cloud.
With EarlyBodyLoad disabled everything was fine... until now 🤷‍♂️

**Comment by atuchin-m** [comment]
@radPhil 
I've discovered in the traces that the `DocumentLoader` doesn't get a signal about complete loading body.
It seems that `EarlyBodyLoad` doesn't solve this completely, but reduces the chance of a (possible) race in the network stack that trigger the problem. 
It's likely that the problem primary happens with a fast/local resources. That's why I can't simply reproduce it on my own.

1. During the problem have you ever seen some content (possible partition) of a hanged page?
2. In theory Speedreader/DeAmp has some code that can trigger such behavior, but disabling them doesn't help..
Could you please try to record traces without these features enabled (disable them by brave://flags as in [the comment](https://github.com/brave/brave-browser/issues/23267#issuecomment-1150074366))?

**Comment by radPhil** [comment]
Yes it is so much better with EarlyBodyLoad disabled.

1. No, the page was always empty
2. Sure! Will try to reproduce the problem and record traces.

**Comment by valynor** [comment]
Just tested on Version 1.39.122 Chromium: 102.0.5005.115 (Official Build) (arm64), infinity loading is still present. 

Cleared cache and went to http://explosm.net/comics/latest  (http!) and site forwarded me to https://explosm.net/comics/armed-teachers but with blank dark-grey page and eternal spinner/infinite loading. :-|

**Comment by agalli93** [comment]
Is there any more data gathering that needs to be done at this point with certain parameters or builds?

**Comment by djprmf** [comment]
> Is there any more data gathering that needs to be done at this point with certain parameters or builds?

Leave as many traces as possible with the issue present.

**Comment by atuchin-m** [comment]
Another traces with DeAmp/Speedreader/Shield/Extensions disabled can helps (from someone else than @autonomic , thanks).
It likely we found a reproduction in company, so I will be much easily to debug.

**Comment by atuchin-m** [comment]
I believe that the root of the problem is a race in Chromium navigation subsystem with the disabled `NavigationThreadingOptimizations` feature.  The feature is explicitly disabled in Brave because it previous had a major bug (currently, it's fixed it in Chrome).

We don't know all the details now, but something was broken in M102. In case of quickly processing a navigation in renderer (maybe onLoad handlers on the previous frame), [CodeCacheHost](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/loader/document_loader.cc;l=2965-2968;bpv=1) is incorrectly reset which leave the frame in infinite waiting state.

So guys, could you try to launch browser with `--enable-features=NavigationThreadingOptimizations`? (**without** `--disable-features=EarlyBodyLoad`, we don't need it anymore).

It resolves the problem for us and we are planning to enable it in the near future.

**Comment by djprmf** [comment]
After the --enable-features=NavigationThreadingOptimizations, i notice that the browser crashed up on startup - may have been a "one time thing".

Right now, testing and appears fine loading the pages.
After loading around 100 websites, none appear to have "pending loading". Will edit this out if appears some error.

As a note @atuchin-m , since this is a major issue for many users, i think is better to enable it "asap", not in the "near future". We have already being 2+ weeks with issues, and is causing major problems in the usage of the browser daily.

**Comment by atuchin-m** [comment]
@djprmf Do you have Crash Report ID on brave://crashes/ ?

**Comment by djprmf** [comment]
@atuchin-m Here: 13ce0300-b1ec-5608-0000-000000000000
Note that it may have been just a "one time" thing, since then i restart multiple times and don't see any issue anymore 👍

**Comment by atuchin-m** [comment]
thanks @djprmf .
"near future" means next few days. We can't change something for 100% users in one time for stability reasons. We expect enabling it for nightly today and them we should to wait a day for the feedback.
Any changes, which solves one problem, could possible trigger another, much more serious, for some part of the users.

**Comment by nintendork07** [comment]
hello @atuchin-m , if I launch now with (--enable-features=NavigationThreadingOptimizations) , will I need to change anything when the update with the fix drops later? Or will it apply it automatically? Thanks

**Comment by atuchin-m** [comment]
Hell @nintendork07. Does it help to resolve the problem?
 No, you don't need to change anything. Just in case you can delete this switch after a few weeks.

**Comment by nintendork07** [comment]
@atuchin-m 

yes it appears to be fixed!! i haven't seen any pages reloading and everything seems noticeably faster than before. 

i didn't really know how to launch with a command line but some googling led me to the brave website. 

if anyone else needs it for Mac, in terminal put:

open -a "Brave Browser.app" -n --args --incognito --enable-features=NavigationThreadingOptimizations

**Comment by Condobloke** [comment]
Any confirmation of the above "fix" ??

**Comment by kanwei** [comment]
It's fixed for me too, was getting it on Mac but now everything works great with the new flag.

**Comment by Gorxor** [comment]
Added "--enable-features=NavigationThreadingOptimizations" to my desktop shortcut (Windows 10), and no more "sometimes page doesn't load on first try" issues anymore for me as well. Also no crashes or other problems detected yet.

**Comment by Condobloke** [comment]
How do I add that to Linux Mint 20.3 ??

**Comment by xlanex6** [comment]
Fixed and all good for me also with 

MacOS - M1

`open -a "Brave Browser.app" -n --args --enable-features=NavigationThreadingOptimizations`

**Comment by sirius-c** [comment]
[This comment](https://github.com/brave/brave-browser/issues/15220#issuecomment-1155284478) might be related.

**Comment by animanoir** [comment]
I get this only in Facebook and Google links 

https://imgur.com/a/HBV849T

**Comment by wc2184** [comment]
Thank you, the flag `enable-features=NavigationThreadingOptimizations` worked for me on windows. I was having this issue cross platform on both my macbook and windows computer. 

What I did on Windows: 
I found the Brave desktop shortcut, right clicking the Brave shortcut, clicking Properties, then going to the Shortcut tab then pasting into the "Target" section this text blob: `"C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-features=NavigationThreadingOptimizations`, hit Apply and OK, I then closed my Brave window then also made sure to close Brave in the toolbars in the bottom right because it runs in the background by default even if closed for me. 

Opened Brave again and everything appears to work so far. 

My issue before was specifically that when I highlight something with cursor and right click > Search Google for "highlighted text" it would create a page with infinite loading, blank page, nothing on the screen. This happened roughly 50% of the time. Refreshing or manually typing the search term in google let it load no issues but it was a major annoyance.

**Comment by sirius-c** [comment]
I started the browser with `brave-browser --enable-features=NavigationThreadingOptimizations`, and page loading became nearly immediate.

Confusingly, afterwards I started the browser again without this flag (using the usual, unchanged desktop launcher), and pages still load fast. Unless this `--enable-features` is persistent, I don't know how to explain this. - I'll report back if the slow loading reappears.

**Comment by animanoir** [comment]
That didn't worked for me. In fact now websites apart from Google and Facebook never load...

**Comment by beigexperience** [comment]
> Added "--enable-features=NavigationThreadingOptimizations" to my desktop shortcut (Windows 10), and no more "sometimes page doesn't load on first try" issues anymore for me as well. Also no crashes or other problems detected yet.

This worked for me on Windows 10 (1909, build 18363.2274) with build [Version 1.39.122 Chromium: 102.0.5005.115 (Official Build) (64-bit)]

Dunno whats up with that flag, I guess it was disabled???

Before using that flag as a shortcut I'd have random tabs fail to load stuck on spinner not showing anything in the main browser frame. But it would instantly work if I manually refreshed the page.

**Comment by djprmf** [comment]
> That didn't worked for me. In fact now websites apart from Google and Facebook never load...

Are you sure the flag is active?
See if appears in brave://version

**Comment by sol2070** [comment]
> Are you sure the flag is active? See if appears in brave://version

Oh, I realized that the flags passed in the launcher were being ignored (due to some Flatpak thing, on Ubuntu). I fixed this, and now it seems to work.

**Comment by AkiraJkr** [comment]
@sirius-c 's suggestion worked for me somehow. Everything seems to load in nearly a instant and I no longer have this annoying bug where pages just don't load until a refresh. No matter if I open it in a new tab or not, it seems my problems are finally gone.

**Comment by KaloyanKitanov** [comment]
I recently started experiencing similar issues to the ones mentioned. Initially I noticed it with work-related services, and was advised to clear cookies. This fixed the issue for seemingly a few minutes. Anyway, here is what I have:
- Instagram loads VERY limited info
- AWS gives a generic error
- youtube videos hang

Similar hanging/partial loading on a multitude of other websites. The one thing that seems to fix the issue is to close then restore the tabs.
![1e8a9b78-4051-4b0b-af69-4d0f04889e8a](https://user-images.githubusercontent.com/80672678/174100533-a8421859-33a1-4205-aba4-66bbe425836f.png)
![8f5ab445-a983-430b-bbb3-eaeb80af644a](https://user-images.githubusercontent.com/80672678/174100538-0ed26752-d903-46b2-b98d-9471e2510690.png)

I have now tried sirius-c's proposed fix and will see if any of the issues occur in the following day(s).

**Comment by Dredd893** [comment]
Having this issue too.

**Comment by KaloyanKitanov** [comment]
> I recently started experiencing similar issues to the ones mentioned. Initially I noticed it with work-related services, and was advised to clear cookies. This fixed the issue for seemingly a few minutes. Anyway, here is what I have:
> 
> * Instagram loads VERY limited info
> * AWS gives a generic error
> * youtube videos hang
> 
> Similar hanging/partial loading on a multitude of other websites. The one thing that seems to fix the issue is to close then restore the tabs. ![1e8a9b78-4051-4b0b-af69-4d0f04889e8a](https://user-images.githubusercontent.com/80672678/174100533-a8421859-33a1-4205-aba4-66bbe425836f.png) ![8f5ab445-a983-430b-bbb3-eaeb80af644a](https://user-images.githubusercontent.com/80672678/174100538-0ed26752-d903-46b2-b98d-9471e2510690.png)
> 
> I have now tried sirius-c's proposed fix and will see if any of the issues occur in the following day(s).

 Issue still persists, perhaps it's a different altogether? Regardless it's been super giga annoying. Anything I can do to help solve this, let me know.

**Comment by animanoir** [comment]
> > That didn't worked for me. In fact now websites apart from Google and Facebook never load...
> 
> Are you sure the flag is active? See if appears in brave://version

How do I correctly write it? Right now in the Target textbox for the shortcut I have this:

`"C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-features=NavigationThreadingOptimizations`

**Comment by agalli93** [comment]
Reporting in that this does seem to have resolved the issue for me as well.  Thanks guys! 1.39.122 Win 10 21H2.

**Comment by valynor** [comment]
Version 1.39.122 Chromium: 102.0.5005.115 (Official Build) (arm64) on macOS 12.4 

Unfortunately the issue still isn't fixed completely for me. It's a lot better now but I still run into the occasional infinite loading page, e.g. I just entered https://www.apple.com/de/ into the omnibox and went to the usual dark grey page with with infinite spinner. 
Reloading immediately loaded the site. :-|

**Comment by animanoir** [comment]
It is happening a lot of times now.

**Comment by valynor** [comment]
I cleared the cache. Problem persists exactly like it was before.

**Comment by djprmf** [comment]
@valynor 
Check your extensions.
Also, test in a new profile.

**Comment by nintendork07** [comment]
doesn't look like it's implemented yet in the newest update. wasn't listed in the changelog, keep using the terminal command to open brave with the set command of enabling navigation thread optimizations

**Comment by animanoir** [comment]
This is still happening to me. Partially fixed since now  right-click Google searches load, but, let's say, docs.google doesn't.

**Comment by Condobloke** [comment]
So far a fresh download of the latest release has solved the problem.......with ONE exception

When I open brave, it loads 4 homepages (all news)
They open quickly, no dramas whatsoever.
ONE of those pages (9news.com.au) shows the constant loading/infinity load icon.....and yet the page HAS loaded successfully. If I click the 'reload' icon it turns that icon from an X to the normal half circle arrow......but it DOES NOT affect the page itself and the "infinity load' just keeps going, also with out affecting the page itself.

**Comment by Dtaggart** [comment]
The expectation isn't making everyone do a fresh install or create a "new profile" for a bug that was introduced right? Once this gets merged in and released it should be working as expected after a update and restart without any other steps to fix the issue correct?

**Comment by Condobloke** [comment]
^^^,,,@Dtaggart.......I believe that what you have said is Correct.

I fresh installed for other reasons.

**Comment by ryanbr** [comment]
Can someone confirm, if they're still having issues (copying the same Brave release profile to the beta folder)

[Beta v1.39.106](https://github.com/brave/brave-browser/releases/tag/v1.39.106) (Chromium 101.0.4951.67) Good so far 
[Beta v1.39.108](https://github.com/brave/brave-browser/releases/tag/v1.39.108) (Chromium 101.0.4951.67) Good so far  May 18, 2022
[Release v1.39.109](https://github.com/brave/brave-browser/releases/tag/v1.39.109) (Chromium 102.0.5005.50)  Bad   May 19th 2022

**Comment by animanoir** [comment]
v1.40.105 in W11 not fixed at all.

**Comment by atuchin-m** [comment]
Guys, we recently have rolled out the feature to all audiences.
We believe you shouldn't have this issue anymore.

If it seems you still have it, please **restart the browser** (to update the feature config) and check the symptoms.
The original issue had a few characteristic symptoms:
* Absolutely blank page, no **any** visible content;
* True infinite waiting loop, not a delay (nothing is changed after minutes/hours);
* Reloading the page usually helps;
* Disabling Shield/DeAmp doesn't change anything;

**If the symptoms don't look like this, please file another issue.**

If you are absolutely sure that you have this issue please post here:
* brave://version/?show-variations-cmd
* Recorded performance traces during the problem (https://www.chromium.org/developers/how-tos/trace-event-profiling-tool/recording-tracing-runs/#capture-a-trace-on-chrome-desktop)

**Comment by Dtaggart** [comment]
> Guys, we recently have rolled out the feature to all audiences. We believe you shouldn't have this issue anymore.
> 
> If it seems you still have it, please **restart the browser** (to update the feature config) and check the symptoms. The original issue had a few characteristic symptoms:
> 
> * Absolutely blank page, no **any** visible content;
> * True infinite waiting loop, not a delay (nothing is changed after minutes/hours);
> * Reloading the page usually helps;
> * Disabling Shield/DeAmp doesn't change anything;
> 
> **If the symptoms don't look like this, please file another issue.**
> 
> If you are absolutely sure that you have this issue please post here:
> 
> * brave://version/?show-variations-cmd
> * Recorded performance traces during the problem (https://www.chromium.org/developers/how-tos/trace-event-profiling-tool/recording-tracing-runs/#capture-a-trace-on-chrome-desktop)

What release should this be in. I don't see any notes on any of the tagged releases. I ask because in the last 12 or so hours there have been 5 releases tagged. It would help to know when I test that I am on a version with the fix.

**Comment by atuchin-m** [comment]
@Dtaggart 
The issue was fixed by updating [a feature config](https://github.com/brave/brave-browser/wiki/Brave-Variations-(Griffin)) that is fetched by the browser from time to time.
Any release should works fine now.

**Comment by Dtaggart** [comment]
This seems to be fixed on my end. Not that the version matters I am on v1.40.105 and the configuration seems to of updated correctly and I am no longer seeing the issue,

**Comment by valynor** [comment]
Update: the _Active Variations_ in brave://version changed for me only today (like 6 hours before this post) and since this point in time the problem seems to be fixed.
