### ISSUE TITLE
Remove button for cookies rule does not work

### ISSUE THREAD

**Issue by pashynskykh** [brave/brave-browser#24149]
## Description 

Remove button does not work for rules under Settings -> Privacy and security -> Cookies and site data -> Websites that can always use cookies/Websites that can never use cookies.
Check screenshot below.

## Steps to Reproduce

   1. Go to "Cookies and site data" page in settings
   2. Click remove button on the right from website rule

## Actual result:

Nothing happens, rule is not deleted.

## Expected result:
Rule is deleted.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

1.41.96 Chromium: 103.0.5060.114 (Offisiell delversjon) (64-bit) 

## OS
Fedora 36.

## Miscellaneous Information:

![image](https://user-images.githubusercontent.com/14852335/179940784-21301bd3-950e-4e09-8f68-4ded10640a16.png)

**Comment by pashynskykh** [comment]
Just checked on my Macbook: remove button there does not work too.
Brave v1.41.96 Chromium: 103.0.5060.114 (Offisiell delversjon) (arm64).

**Comment by rebron** [comment]
Closing as dupe of https://github.com/brave/brave-browser/issues/8604. We have this fixed in 1.42.x

**Comment by pashynskykh** [comment]
Wonderful! Thanks for update!

**Comment by pashynskykh** [comment]
@rebron just got v1.42.86 on stable channel. Remove button still does not work.
