### ISSUE TITLE
Removed folders re-synced only on toolbar (no folders structure), when two devices are still in sync

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#2458]
## Description 
Removed folders are not re-synced properly, when two devices are still in sync

## Devices
 Device 1: Windows 10 bc -`0.58.11` (Sync creator)
Device 2: VM - Windows 8 bc- `0.58.11`

## Steps to Reproduce

   1.  Sync two devices `Windows-10` and  VM `Windows-8`
   2.  Open the secret sync code on Windows 10 and copy it
   3.  Paste the secrete code on VM-Windows 8
   4. Make sure two devices are in sync
   5. Import 5k bookmarks on Windows 10
   6. Make sure 5k boomarks are synced in VM Window 8 (Folder structure is same on both devices)
   7. Delete the bookmark root folder from Windows 10
   8.  Verify that, after few minutes, the bookmarks again started re-syncing in Windows 10 (As sync chain is still established)
   9. Verify the folder structure in Win 10 after re-sync

## Actual result:
All the re-synced bookmarks are displayed on the bookmak toolbar. There are no folders under bookmarks manager.
![image](https://user-images.githubusercontent.com/38657976/49821473-88695800-fda0-11e8-94b8-aef99d70268b.png)

## Expected result:
Folder structure should be maintained after re-sync

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? NA

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information
@brave/legacy_qa

**Comment by darkdh** [comment]
it should be fixed in https://github.com/brave/brave-browser/issues/2443

**Comment by GeetaSarvadnya** [comment]
Issue still persists and reproducible on 0.59.12. Hence reopening the issue

Brave | 0.59.12 Chromium: 72.0.3626.17 (Official Build) beta (64-bit)
-- | --
Revision | 08d2140079f8db14c9eb885a803d231b1a30e817-refs/branch-heads/3626@{#315}
OS | Windows
