### ISSUE TITLE
Geolocations permission prompt

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#25]

**Comment by bbondy** [comment]
@jumde could you help define what we are missing here in comparison to browser-laptop?

**Comment by srirambv** [comment]
- [ ] Media Autoplay (Allow/Deny/Ask)

**Comment by bbondy** [comment]
I did see one of these prompts, I suspect maybe some domains are whitelisted for no prompt?

**Comment by bbondy** [comment]
I think google.com asked me but I think maps.google.com didn't.

**Comment by jumde** [comment]
On navigating to `google.com` I do see a geolocation prompt on using `browser-laptop` but, the prompt is not displayed with `brave-core`.

**Comment by srirambv** [comment]
Location prompt shows up but doesn't show user location (#783)
![image](https://user-images.githubusercontent.com/17010094/44362093-f6a2ab80-a48d-11e8-8bd9-77270cd4bf7a.png)


I think this issue can be closed as its working on master and on packaged build.

**Comment by bbondy** [comment]
This should already be implemented, there was a CI issue which should be resolved on the next build. I'll mark the QA flags to ensure that. cc @mbacchi

**Comment by GeetaSarvadnya** [comment]
Notification prompt is still not displayed for google.com. May be fix is not available in this build.

Brave | 0.54.2 Chromium: 69.0.3497.42 (Official Build) dev (64-bit)
-- | --
Revision | 9c4613c66dfeb2b76ef6dd4b15884c15db3b4969-refs/branch-heads/3497@{#655}
OS | Windows

**Comment by mbacchi** [comment]
We are building all platforms with the geolocation key and endpoint now, and I've just verified that 0.54.2 enables it on Linux:

![screenshot from 2018-08-28 10-53-44](https://user-images.githubusercontent.com/6763301/44731283-db005c00-aab0-11e8-97e1-ed2eb915889f.png)
![screenshot from 2018-08-28 10-54-02](https://user-images.githubusercontent.com/6763301/44731289-df2c7980-aab0-11e8-843e-8152ca58e47a.png)

I had to remove the preferences directory (in Linux it was: `~/.config/BraveSoftware/Brave-Browser-Dev/`) to make this prompt me as I had already allowed browserleaks to see my location in the past. Maybe you need to remove that directory and try again?

**Comment by srirambv** [comment]
still doesn't prompt for google.com. Only works on browserleaks.com/geo

**Comment by bbondy** [comment]
file a new issue pls @srirambv

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux

* Verified permission prompted on https://maps.google.com/ when clicked on location
* Verified permission prompted for https://browserleaks.com/geo
