### ISSUE TITLE
removing `Scroll for Brave News` if `brave://flags/#brave-news` has been disabled

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#25278]
## Description 

We should remove the `Scroll for Brave News` string/animation from the NTP if a user has disabled Brave News via  `brave://flags/#brave-news`. Follow up to https://github.com/brave/brave-browser/issues/25182 which fixes the crash.

## Steps to Reproduce

   1. Use the STR/Cases oulined via https://github.com/brave/brave-core/pull/15025#issue-1365071381
   2. observe that the `Scroll for Brave News` string/animation is still present/visible even though Brave News was disabled

## Actual result:

![newsError](https://user-images.githubusercontent.com/2602313/189065688-543c53c8-11c8-4f51-a91b-1b6797c622d2.png)

## Expected result:

We should remove the `Scroll for Brave News` string/animation once Brave News has been disabled.

## Reproduces how often: 

100% reproducible using the STR/Cases outlined above.

## Brave version (brave://version info)

```
Brave | 1.45.34 Chromium: 105.0.5195.102 (Official Build) nightly (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Windows 11 Version 21H2 (Build 22000.918)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by mattmcalister** [comment]
This was resolved. Closing.

**Comment by myviolinsings** [comment]
How was this issue resolved? I still have the scroll for brave news at the bottom of new page and cannot get rid of it. Flags disabled are: Enable Brave News V2 & Brave News prompts on New Tab Page.
![brave flags disabled new tab](https://github.com/brave/brave-browser/assets/42390999/32d32c1d-24f1-4e14-b75a-85b410da4581)
![brave flags disabled](https://github.com/brave/brave-browser/assets/42390999/384e491f-6aaa-4197-9f76-726a632d1146)
