### ISSUE TITLE
Issues in Twitch login

### ISSUE THREAD

**Issue by djprmf** [brave/brave-browser#25598]
## Description 
Cannot login in Twitch - https://www.twitch.tv/

## Steps to Reproduce
   1. Go to Twitch - https://www.twitch.tv/
   2. Try to login

## Actual result:
The login doesn't work, showing a error message

## Expected result:
Login to the account

## Reproduces how often: 
Easily reproduced - every try

## Brave version (brave://version info)
Version: 1.43.93 Chromium: 105.0.5195.127 (Compilação oficial) (64 bits) 
Revision 912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}
SO: Windows 11 Version 22H2 (Build 22622.601)

## Version/Channel Information:
Happens in every channel except nightly.

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel?  No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?  No

## Miscellaneous Information:
Info in Brave Community about the issue:
https://community.brave.com/t/problems-with-twitch-on-brave/433996/4

in the Brave Console, when trying to login, shows this error message:
"POST https://passport.twitch.tv/integrity 400 (Bad Request)"

**Comment by ZerGo0** [comment]
This has fixed it for me:

1. Close Brave
2. Go to your Brave Default User Data Folder (`%localappdata%/BraveSoftware/Brave-Browser/User Data/Default` for all windows users out there)
3. Open the file named Preferences in a text editor (Notepad works)
4. Search for `"braveShields"`
5. Inside the curly brackets there should be a entry starting with `"www.twitch.tv,*"`
6. Mark it from there to the next CLOSING curly bracket like this: `"www.twitch.tv,*":{"expiration":"0","last_modified":"13296300627156589","model":0,"setting":2}`
7. Delete the marked section
8. Save

The login should work after that, no idea why, but something seems to break it for some reason.

**Comment by djprmf** [comment]
As i state in the message, i don't use Brave Shields at all, they are to allow everything as default, so is not related with that.

**Comment by ZerGo0** [comment]
> @ZerGo0 As i state in the message, i don't use Brave Shields at all, they are to allow everything as default, so is not related with that.

Do you have it disabled? If so then that's the problem that I've described.

**Comment by djprmf** [comment]
> Do you have it disabled? If so then that's the problem that I've described.

I have the Brave Shields enable, but not blocking anything.
But in any case, tested with both disable and enable and doesn't work. Also not working in Beta with Shields setting as default - enable or disable.

**Comment by shadryck** [comment]
I'll just chime in to say that I seem to have got the exact same issue and enabling Brave Shields and clearing cookies worked for me as well. After disabling Brave Shields again and clearing cookies a second time I'm unable to reproduce the bad request issue anymore.

Just clearing cookies and cache, having Brave Shields disabled and no extensions installed was not enough but enabling Brave Shields suddenly solved it?

**Comment by uraimo** [comment]
The logout/clear trick didn't work for me, at all. I initially logged out only because I was seeing multiple errors in the UI (notifications non being cleared, chat points errors, etc...), so that 400 we are receiving could not be the only issue.

The body of the 400 request to https://passport.twitch.tv/integrity doesn't have any obvious indication about what failed: 

`{"error":"Oops! We encountered an unexpected error. Please try again.","errors":["Oops! We encountered an unexpected error. Please try again."],"error_code":5025,"error_description":"integrity failed"}`

**Comment by secv** [comment]
Same issue. Messing with Shield and cookies didn't work.

**Comment by secv** [comment]
Some additional information: subscribing to a channel with Twitch Prime also failed consistently on Brave but worked first try on Edge.

**Comment by secv** [comment]
Possible, but I wouldn't say "apparently" blocked. Twitch Support on Twitter probably giving the only solution until Brave makes the fix. The only people who would know if its blocked would be Twitch staff and Brave staff/contributors. No reason to jump the gun.

**Comment by djprmf** [comment]
@secv users in the opera and opera GX also have this issue. Is not related only with brave.

**Comment by jeebuscrisis** [comment]
Just to add a possible solution that I don't fully understand why, but I went into brave://flags and enabled brave-dark-mode-block

cleared cache/cookies, restarted brave and was able to use twitch normally.

![image](https://user-images.githubusercontent.com/101148966/193105678-0269076d-3b24-41ab-b359-4506b8b889df.png)

**Comment by Ben0xA** [comment]
> Just to add a possible solution that I don't fully understand why, but I went into brave://flags and enabled brave-dark-mode-block
> 
> cleared cache/cookies, restarted brave and was able to use twitch normally.
> 
> ![image](https://user-images.githubusercontent.com/101148966/193105678-0269076d-3b24-41ab-b359-4506b8b889df.png)

This worked perfectly. Twitch is using the dark mode to fingerprint brave to block the login!

**Comment by Chris92de** [comment]
> Just to add a possible solution that I don't fully understand why, but I went into brave://flags and enabled brave-dark-mode-block
> 
> cleared cache/cookies, restarted brave and was able to use twitch normally.
> 
> ![image](https://user-images.githubusercontent.com/101148966/193105678-0269076d-3b24-41ab-b359-4506b8b889df.png)

This sadly doesn't work for me in any permutation.
Could you share a screenshot of your exact settings? I have that flag enabled and I can see that the front page completely changes with aggressively blocking fingerprinting but logging in still doesn't work.

Neither on Stable [Version 1.44.101 Chromium: 106.0.5249.65 (Official Build) (64-bit)](https://brave.com/latest/) nor on Beta [Version 1.45.78 Chromium: 106.0.5249.65 (Official Build) beta (64-bit)](https://brave.com/latest/)

**Comment by jeebuscrisis** [comment]
> 

![image](https://user-images.githubusercontent.com/101148966/193143126-12742b5d-61a2-436c-b639-5a788c44b9c2.png)


I've seen everything from making sure shields are enabled before clearing cache and that even having to do it once more somehow also allowed this to work.. but these are the only two things I have enabled in the "hidden settings"

**Comment by secv** [comment]
First of all, thank you for letting me know about the Dark Mode settings. I didn't even know those existed! Second of all, I can now sign in to Twitch after doing the following:

- Enable dark mode blocking fingerprinting protection: Enabled
- Auto Dark Mode for Web Contents: Enabled
- Twitch Shield Setting: Block Fingerprinting
- Clear Cache
- Remove Cookies via searching "Twitch" and selecting Remove All
- Restart Browser
- Login With 2FA

One or more of those steps may be unnecessary, but that's the whole series of actions for full review.

**Comment by Chris92de** [comment]
> First of all, thank you for letting me know about the Dark Mode settings. I didn't even know those existed! Second of all, I can now sign in to Twitch after doing the following:
> 
> * Enable dark mode blocking fingerprinting protection: Enabled
> * Auto Dark Mode for Web Contents: Enabled
> * Twitch Shield Setting: Block Fingerprinting
> * Clear Cache
> * Remove Cookies via searching "Twitch" and selecting Remove All
> * Restart Browser
> * Login With 2FA
> 
> One or more of those steps may be unnecessary, but that's the whole series of actions for full review.

This sadly still doesn't work for me. Really not sure what I'm doing wrong.

**Comment by jeebuscrisis** [comment]
> This sadly still doesn't work for me. Really not sure what I'm doing wrong.

Out of sheer curiosity have you restored your brave to default settings just in case you have anything else you've modified and then trying this?

**Comment by Chris92de** [comment]
> > This sadly still doesn't work for me. Really not sure what I'm doing wrong.
> 
> Out of sheer curiosity have you restored your brave to default settings just in case you have anything else you've modified and then trying this? I would even consider re-installing brave and then this process?

I tried with a fresh install of Brave Beta, so unless some of the settings carried over via Brave Sync, I don't think any of my settings affect it.

**Comment by jeebuscrisis** [comment]
Why Beta? Try a stable install

**Comment by Chris92de** [comment]
I tried both.

jeebuscrisis ***@***.***> schrieb am Fr., 30. Sept. 2022,
01:34:

**Comment by secv** [comment]
> This sadly still doesn't work for me. Really not sure what I'm doing wrong.

Was the Twitch website open in your browser during any steps besides updating Shield settings?

**Comment by Chris92de** [comment]
No.

secv ***@***.***> schrieb am Fr., 30. Sept. 2022, 03:40:

**Comment by Chris92de** [comment]
I've since tried with the stable Brave Browser, also no dice. Same settings as displayed above.

**Comment by SydenX** [comment]
I've the same problem only on brave btw. Tried to do what you said but doesn't work.

> First of all, thank you for letting me know about the Dark Mode settings. I didn't even know those existed! Second of all, I can now sign in to Twitch after doing the following:
> 
> * Enable dark mode blocking fingerprinting protection: Enabled
> * Auto Dark Mode for Web Contents: Enabled
> * Twitch Shield Setting: Block Fingerprinting
> * Clear Cache
> * Remove Cookies via searching "Twitch" and selecting Remove All
> * Restart Browser
> * Login With 2FA
> 
> One or more of those steps may be unnecessary, but that's the whole series of actions for full review.

I've the same problem only on brave btw. Tried to do what you said but doesn't work.

**Comment by enumag** [comment]
Messing around with shields, cookies, local storage and brave flags about dark mode didn't work for me. Brave Nightly does work though. I wonder what's different.

**Comment by jeebuscrisis** [comment]
I also ran into twitch blocking me again. Just wanted to report another way I found that allowed me access with no issues... In brave, go to settings/privacy and security/cookies and other site data/See all cookies and site data.

In the top right where it says Search cookies type twitch .. delete every entry with twitch in the name. Not sure if you'll have to do this everytime but once I did it I was using twitch normally again.

Also make sure you do not have aggressive finger printing on.

And in case you don't have it set, type brave://flags in your address bar... search flags for #brave-dark-mode-block and enable it

**Comment by enumag** [comment]
@jeebuscrisis Tried it, still can't login. 😅

**Comment by enumag** [comment]
Hmm after a few tries it did go through actually... I'm not sure if it's related but it refused to work while I had the dev console active.

**Comment by jeebuscrisis** [comment]
> Hmm after a few tries it did go through actually... I'm not sure if it's related but it refused to work while I had the dev console active.

This is good to know if other people are having issues and have the dev console up!

**Comment by Syzuna** [comment]
Nightly used to work for me until today...
This is really starting to piss me off... not on Brave but Twitch bcs of their apparently stupid new Kasada security for anti bot stuff...

**Comment by jeebuscrisis** [comment]
maybe don't try to run bot stuff??

This was all because of a flaw in Brave that allowed bad actors to automate/script bots.. so maybe if ya'll could knock it off that'd be super awesome

**Comment by Syzuna** [comment]
You do realize that most likely nobody here did that right?
I for sure didnt...
With your argument we should ban VPNs bcs bad actors abuse them or even better ban credit cards bcs they have flaws that bad actors abuse...
So maybe knock it off yourself.

**Comment by jeebuscrisis** [comment]
Fair enough. That put to bed, it's interesting to me how this works for some but not all people. So therefore there must be disparity between our setups IN SOME WAY that is preventing one twitch user from another whilst using the brave browser and why these methods work but not keeping uniform. I often think that those on the more developer side are more customized systems vs. casual user so maybe these methods are more geared toward the casual user.

2 cents.

**Comment by Chris92de** [comment]
I managed to login now after completely resetting Brave's settings to
default.
No clue which setting it was that caused it.
I also realized that I made a mistake in my earlier testing with Brave Beta
because I put it in my Brave Sync chain before I tried logging in.


jeebuscrisis ***@***.***> schrieb am Mi., 5. Okt. 2022, 05:27:

**Comment by Syzuna** [comment]
I mean I have a dev background sure but I just maintain a library for the Twitch Third party ecosystem. No bot Scripts... my shield settings are kinda basic. Standard footprint and ads/tracking blocking, Cross origin cookies blocked.
Auto Upgrade to https.
I dont really feel like resetting my whole profile and loosing all bookmarks and so on.

**Comment by Syzuna** [comment]
Ok funny enough... I reset the nighly instance I use (still have all my stuff on the stable version) and it started working again...
settings are the same tho :D so I really dont know whats going on

**Comment by dgirgenti** [comment]
+1 for turning on shield and clearing cookies -- I can finally log in!

**Comment by tance77** [comment]
Resting the profile setting seems to be working over in the [community thread](https://community.brave.com/t/twitch-tv-log-in-getting-blocked-on-brave/433985/45?u=sirlancealot77).

**Comment by uraimo** [comment]
Yes, finally, doing a settings reset works (and preserves everything you'd want to keep, i.e. bookmarks and passwords included), no need to clear the cookies/history.

**Comment by ljford7** [comment]
Just to chime in - I can login with Guest Mode window, but not the main browser. It appears to be blocking the 2-FA popup. I have no interest in resetting my settings to login to Twitch.

**Comment by ron-wolf** [comment]
> I've the same problem only on brave btw. Tried to do what you said but doesn't work.
> 
> > First of all, thank you for letting me know about the Dark Mode settings. I didn't even know those existed! Second of all, I can now sign in to Twitch after doing the following:
> > 
> > * Enable dark mode blocking fingerprinting protection: Enabled
> > * Auto Dark Mode for Web Contents: Enabled
> > * Twitch Shield Setting: Block Fingerprinting
> > * Clear Cache
> > * Remove Cookies via searching "Twitch" and selecting Remove All
> > * Restart Browser
> > * Login With 2FA
> > 
> > One or more of those steps may be unnecessary, but that's the whole series of actions for full review.

This worked for me! I removed cookies after restarting the browser, however (by mistake). It worked regardless.

**Comment by ljford7** [comment]
Has there been any movement on this? I am on v1.45.131 and still can't login (have to use Edge unfortunately for Twitch).

**Comment by secv** [comment]
I didn't have to reset any settings other than deleting the cache and Twitch cookies via search.

**Comment by djprmf** [comment]
In the latest versions of brave i don't have any more issue.
I think this have been solved. If there is any other issue, probably is not related with this one.

**Comment by akodev49** [comment]
It's so inconsistent. I clear cookies, history, local and session storage, in various configuration... No changes. I set up a new profile, couldn't login. I even turned off 2FA, still nothing. I'm on v1.45.131 so looks like updates also don't work for me. I ain't got no idea what can test more.

**Comment by ljford7** [comment]
Just tried it again (deleting cookies, no shields, etc.) and doesn't work. Also tried in private mode and same result.
![Screenshot 2022-11-24 111844](https://user-images.githubusercontent.com/2449331/203847005-5ea757af-ac21-4d43-974b-342a7626bb9f.png)

**Comment by ljford7** [comment]
I was finally able to login today!

Brave version 1.46.140 - maybe it is fixed for good?

**Comment by akodev49** [comment]
Affirmative. v1.46.140 - can login again.

**Comment by SydenX** [comment]
I've that version and i still can't login but i have a new error: 
"Your browser is not currently supported. Please use a recommended browser or click here to learn more."

**Comment by Orbsynated** [comment]
v1.50.121 Can't login.

Getting `POST https://passport.twitch.tv/integrity 400 (Bad Request)` error when trying to login.
Response body:
```json
{"error":"Oops! We encountered an unexpected error. Please try again.","errors":["Oops! We encountered an unexpected error. Please try again."],"error_code":5025,"error_description":"integrity failed"}
```

**Comment by Digitalone1** [comment]
On 1.52.117 I still have this issue.

**Comment by jakub-gawlik** [comment]
Bit late, but this problem still exists in 2024.

For me on Arch Linux it was
```
sudo timedatectl set-timezone Europe/London  
sudo timedatectl set-ntp true
```

Assuming you've tried to log in already (otherwise skip) make sure to clear all cache and cookies through developer tools

**Comment by markdude701** [comment]
I have the same issue in v1.73.105

`POST https://passport.twitch.tv/protected_login 400 (Bad Request)`

![Image](https://github.com/user-attachments/assets/dbaa8a5e-3d03-46d2-ac8c-f5d50614dad8)

**Comment by mcrampon** [comment]
Adding to this thread, cause I'm having a similar issue. I noticed I was able to log in using a private navigation window. So I compared the two:

`POST https://passport.twitch.tv/protected_login` fails in the non-private window. The difference between the two requests seems to lie here:

```
x-kpsdk-cd
x-kpsdk-ct
x-kpsdk-v
```

Those three headers are missing in the non-private window. I don't know exactly what they're about, but apparently they have to do with a security feature. So maybe Brave is preventing those headers from being sent somehow and that breaks things?

**Comment by 0x00c** [comment]
Same here. Tried private mode, turning off dark mode fingerprinting, but nothing helps. I noticed I see multiple
 `[GraphQL] One or more GraphQL errors were detected on request 01JMDZ5DKCSSESH53TBE7GXPT5. PinnedChatSettings: unauthenticated `

in the inspector console. It's broken for me since December.

**Comment by cybernaut4** [comment]
> I have the same issue in v1.73.105
> 
> `POST https://passport.twitch.tv/protected_login 400 (Bad Request)`
> 
> ![Image](https://github.com/user-attachments/assets/dbaa8a5e-3d03-46d2-ac8c-f5d50614dad8)

Still happening. Using latest Brave on Windows 10. 
[Version 1.77.100 Chromium: 135.0.7049.100 (Official Build) (64-bit)](https://brave.com/latest/)

A fellow with MacOS isn't affected by this issue, however.

**Comment by ion1** [comment]
I am experiencing this every few months, including today (Brave 1.88.134 (Official Build) (64-bit) on Windows 11).

Edit: It turns out "Clear site data" in Developer Tools was not sufficient, but deleting the data through Settings → Privacy and security → Site and Shields Settings → View permissions and data stored across sites → Filter: Twitch allowed me to log in using the same profile.

~~Creating a new browser profile allows me to log in to Twitch.~~

~~Somehow, Twitch is able to distinguish between Brave profiles even when site data is cleared. If Twitch can do that, then other web sites can as well. This has privacy implications. @bsclifton Please consider reopening this issue, thank you!~~

~~(Are they perhaps abusing #1852?)~~
