### ISSUE TITLE
Chinese to English translation failed few times

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#25682]
## Steps to Reproduce

1. Install 1.45.75
2. launch brave
3. loaded zaobao.com.sg
4. clicked on English to translate and waited

## Actual result:

Translation failed few times and `The page could not be translated` message keep showing up.

Ex1|Ex2
---|---
<img width="700" alt="Screenshot 2022-09-28 095319" src="https://user-images.githubusercontent.com/98358127/192852259-efe57569-3cf7-4a2a-aa3e-d1b13dc5367d.png">|<img width="955" alt="Screenshot 2022-09-28 100705" src="https://user-images.githubusercontent.com/98358127/192852299-c4a5e8bf-7734-43cd-97e3-f7d8e3ee8baf.png">

https://user-images.githubusercontent.com/98358127/192852423-da802803-348c-4cf9-b97a-f7684df25da4.mp4

## Expected result:
Translation should succeed

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 1.45.75 Chromium: 106.0.5249.65 (Official Build) beta (64-bit)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | Windows 11 Version 21H2 (Build 22000.978)

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
 @atuchin-m @rebron

**Comment by atuchin-m** [comment]
Thanks for reporting this.
I belive it's the same as https://bravesoftware.slack.com/archives/C02G7LEELQK/p1663843341460519?thread_ts=1663843341.460519&cid=C02G7LEELQK
Should be fixed now.

**Comment by MadhaviSeelam** [comment]
@atuchin-m still seeing the same issue:

<img width="949" alt="image" src="https://user-images.githubusercontent.com/98358127/192891982-c31b0edf-4c55-4058-958b-fc2bb177d72a.png">

**Comment by atuchin-m** [comment]
Thanks, I'll take a look.

**Comment by atuchin-m** [comment]
@MadhaviSeelam BTW the PR is merged but not current rolled in prod environment.
