### ISSUE TITLE
Blinking cursor everywhere on Windows

### ISSUE THREAD

**Issue by angelog0** [brave/brave-browser#26525]
On Windows 10 current version of Brave (Versione 1.45.118 Chromium: 107.0.5304.91 (Build ufficiale) (a 64 bit)) shows a blinking cursor every where not only in edit fields and it is annoying when not requested. It seems that this occurs only on Windows (10, here) and not on GNU/Linux with the same Brave version...

In the following pictures the blinking cursor appears as a vertical line but it is **blinking**!

Here the pictures:

![bilinking_cursor-01](https://user-images.githubusercontent.com/35931460/199835956-172f7e76-08c7-416f-bb05-f829a67cf6b0.png)       **From your GitHub page**

![bilinking_cursor-02](https://user-images.githubusercontent.com/35931460/199835983-7b4e5b7e-9abe-415c-a2fd-bd757c9d668e.png)      **From an HTML doc**

![bilinking_cursor-03](https://user-images.githubusercontent.com/35931460/199835999-5be6a8e7-4ad7-434e-879d-9cc11a06e95e.png)   **From Emacs web site**

**Comment by angelog0** [comment]
I wonder if this is related with the fact that in that day I had a Zoom connection **with the browser** to a conference.. I just noticed this after the connection..

**Comment by impressivewebs** [comment]
I have the same problem on every web page. Wherever I click, there's a blinking cursor. Really annoying and difficult to navigate pages using up/down arrows like I normally do.

**Comment by angelog0** [comment]
@impressivewebs, I fixed the issue deleting the `BraveSoftware` folder where Brave saves cache and friends (on Windows that folder lives in APPDATA/Local/). I had to reconfigure Brave..

BTW, I noticed this issue while I was connected by Zoom with the browser to a conference...

**Comment by impressivewebs** [comment]
Seems like an overkill solution. Maybe I'll just clear my cache from the regular settings?

**Comment by impressivewebs** [comment]
FYI I've tried clearing my cache and it did not fix this problem. I really curious if this is happening for everyone or just a small number of users. Would like to get this fixed.

**Comment by angelog0** [comment]
@impressivewebs, as I wrote, you should remove the `BraveSoftware` directory and reconfigure Brave. I forgot to say that cleaning History and friends does not help. Just that radical solution worked here.

You can also rename that folder and see it this work...

**Comment by impressivewebs** [comment]
@angelog0 Oh I know what you had said, but I didn't want to do that, so I tried just clearing cookies and cache to see if that fixed it. I guess I'll try what you said, but I would rather not do that if I don't have to.

**Comment by impressivewebs** [comment]
@angelog0 Well, it's time to close this issue. I realized that this is happening because "Caret Browsing" was turned on. You can enable or disable Caret Browsing by hitting F7 on your keyboard. It was that simple.

**Comment by angelog0** [comment]
@impressivewebs, where this is documented? There is something in `Settings`? This information should not be hidden...

**Comment by impressivewebs** [comment]
@angelog0 I agree, it's bit of an annoying feature if you don't know about it. I had read about it some time ago, but forgot, so I was confused about it even though I knew the feature before.

It's documented [for Chrome](https://support.google.com/chrome/answer/10129654) but I can't find the same setting on Brave. On Brave it's just a matter of pressing F7, it doesn't seem to be documented. I can't even find it in the Brave Settings when I search for "Caret" or any other keywords mentioned on the Chrome page.

**Comment by angelog0** [comment]
Thanks, @impressivewebs ! I hope some Brave developer will take note of this fact and develop a solution so that we can close this report.
