### ISSUE TITLE
Once the Brave VPN is enabled/created the tokens are expired before the 30 days

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#26982]
## Description 

Once the Brave VPN is enabled/created token are expired before the 30 days

## Steps to Reproduce

   1. Clean profile `1.46.126`
   2. Create a Brave VPN account
   3. Make sure VPN is connected 
   4. Close the browser
   5. Set the sysstem date ahead by 29 days
   6. Relaunch the browser, token are expired and VPN is disconnected, click on VPN icon shows the `Buy vpn` and `Already purchased vpn?` message in the panel 
   
As discussed in the thread below, the tokens should expire on 32 day
https://bravesoftware.slack.com/archives/C021S0FN3V1/p1669314173558939?thread_ts=1669225513.288039&cid=C021S0FN3V1

## Actual result:

Once the Brave VPN is enabled/created the tokens are expired before the 30 days

## Expected result:
As discussed in the thread below, the tokens should expire on 32nd day
https://bravesoftware.slack.com/archives/C021S0FN3V1/p1669314173558939?thread_ts=1669225513.288039&cid=C021S0FN3V1

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.46.126 Chromium: 108.0.5359.48 (Official Build) beta (64-bit)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | Windows 10 Version 21H2 (Build 19044.2251)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @mattmcalister @husobee @bsclifton

**Comment by stephendonner** [comment]
@GeetaSarvadnya per @husobee in https://bravesoftware.slack.com/archives/C021S0FN3V1/p1670276018848019?thread_ts=1670275519.301959&cid=C021S0FN3V1 this should be fixed on staging; mind re-testing?

**Comment by GeetaSarvadnya** [comment]
@stephendonner @husobee - Issue is still NOT fixed, On 29th day (5th Jan 2023) I am getting `Edit payment` (1st) and then `Buy` (2nd) vpn modal popups.

**Comment by stephendonner** [comment]
@GeetaSarvadnya I asked @husobee about this over in https://bravesoftware.slack.com/archives/C021S0FN3V1/p1671483163089109, for reference
