### ISSUE TITLE
Brave creating junk folders in Program Files

### ISSUE THREAD

**Issue by levicki** [brave/brave-browser#28600]
## Description 
Today I have noticed some strange and suspicious looking folders in my `C:\Program Files`. You are now maybe wondering what that has to do with Brave, but it will be apparent soon enough.

The list of said folders along with that they presumably contain:
|Folder|Name|
|-|-|
|chrome_url_fetcher_8232_282155152|Brave NTP sponsored images|
|chrome_url_fetcher_8232_2027332100|Brave Local Data Files Updater|
|chrome_url_fetcher_9724_618213108|? (empty folder)|
|chrome_url_fetcher_9724_1256538110|? (empty folder)|
|chrome_url_fetcher_9788_244745220|Brave Local Data Files Updater|
|chrome_url_fetcher_9788_980226689|Brave NTP sponsored images|
|chrome_url_fetcher_11540_326675690|Brave Local Data Files Updater|
|chrome_url_fetcher_11540_510077731|Brave NTP sponsored images|
|chrome_url_fetcher_12180_973283506|? (empty folder)|
|chrome_url_fetcher_12180_1079940708|? (empty folder)|

They are all dated February 8, 2023. All extension versions are the same according to their manifest.

I never noticed such folders before, and they most definitely do not belong to `C:\Program Files`.

I have found these related discussions elsewhere:
https://groups.google.com/g/chromedriver-users/c/K9bAr_2WbC4
https://bugs.chromium.org/p/chromium/issues/detail?id=778150

## Steps to reproduce

1. Use Brave

## Expected result:

1. I expect Brave not to use my `C:\Program Files` as a `%TEMP%` folder.
2. I expect Brave not to download and install extensions for things I did not enable and do not use
3. I expect Brave to not hide its own extensions from the Extensions page.

## Reproduces how often: 

No steps to reproduce

## Brave version (brave://version info)

Brave | 1.48.167 Chromium: 110.0.5481.104 (Official Build) (64-bit)
-- | --
Revision | 46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}
OS | Windows 10 Version 22H2 (Build 19045.2604)

## Version/Channel Information:

N/A

## Other Additional Information:

N/A

**Comment by methanoid** [comment]
Six months and still doing it.... is nobody bothering to fix?

**Comment by isaak654** [comment]
@Miyayes @DJAndries Could you please assign a priority to this long-standing issue?

**Comment by methanoid** [comment]
@levicki can U also let me know how your Brave installs in Program Files cos mine doesnt

I install with WinGet and it goes C:\Users\USERNAME\AppData\Local\BraveSoftware which is a DUMB location but it might be fault of WinGet guys ;-)

**Comment by kenherbert** [comment]
This has been reported a couple of times recently on Reddit too.

https://www.reddit.com/r/brave_browser/comments/163e0ql/after_installing_brave_browser_on_my_desktop/

https://www.reddit.com/r/brave_browser/comments/15e8ymc/brave_creates_chrome_url_fetcher_folders_in/

Some interesting things to note - one user is on Windows LTSC (but they are the admin user so nothing locked down). The other user verified Brave is installed to a non-standard location (desktop).


Doing a bit of searching this appears to be an upstream issue as there are many more reports of it for Chrome/Chromium.

**Comment by levicki** [comment]
@methanoid I have reinstalled Windows in the meantime (I am now on Windows 11) which also means fresh Brave install, and so far I don't have those folders in Program Files anymore.

I am able to install Brave to Program Files because I am running as a user who is a member of Administrators group and I have UAC fully disabled (EnableLUA = 0 in registry).

**Comment by Johann999** [comment]
Since Brave-version 1.75.180 I also have such folders under C:\Program Files.
Google Chrome 133.0 and Chromium 133.0 do not create such folders.

**Comment by bsclifton** [comment]
@Johann999 I'm curious - do you have Brave set to launch as administrator?

For example, if you have Brave pinned to the taskbar - you should see this if you right click / select `Properties`. If box is ticked, it's launching as admin
![Image](https://github.com/user-attachments/assets/2b7f598a-76c9-4cb3-9c24-4d0d9b40effe)

**Comment by Pbroc** [comment]
I have this issue on Windows 11 23H2, with a non-admin account, 21 folders created just for today

**Comment by Neustradamus** [comment]
This problem has not been solved. Any progress on it?

**Comment by bsclifton** [comment]
It looks like the root cause is pretty accurately captured in https://issues.chromium.org/issues/40889020

I had asked above if person launched using Admin because it seems like that is what is causing the problem. @Neustradamus @Xetaxheb are you able to run Brave without using admin?

**Comment by bsclifton** [comment]
OK this should be solved starting with Chromium 138 which we are planning to release next week. Check here for the Chromium fix:
https://chromium-review.googlesource.com/c/chromium/src/+/6515318

The fix here de-elevates users who launched as admin. From Will Harris on Chromium Slack:
> the issue is because before a certain version of windows there was no systemtemp so no place to securely emplace temporary files. using windows\temp would be a security risk here so program files is used on these older OS

I'll bookmark this issue and we can check back in a week or two. Thanks for your patience folks!

**Comment by bsclifton** [comment]
OK this issue should be solved now as we've released Chromium 138. Closing

**Comment by amp123456789** [comment]
@bsclifton Still getting this issue. Has been an issue for several months. Makes dozens of these chrome_url_fetcher_#_# empty folders per day in C:\Program Files when I leave Brave open. I don't have any other Chromium-based browser installed. I only use a local administrator account for Windows, but I'm not manually launching Brave with "Run as administrator" in the shortcut properties or right-click launch option. UAC is off. brave.exe is located in C:\Program Files\BraveSoftware\Brave-Browser\Application.

Brave 1.81.131 (Official Build) (64-bit)
Chromium 139.0.7258.66
Windows 10 LTSC 2021 (21H2) x64

**Comment by methanoid** [comment]
> [@methanoid](https://github.com/methanoid) I have reinstalled Windows in the meantime (I am now on Windows 11) which also means fresh Brave install, and so far I don't have those folders in Program Files anymore.
> 
> I am able to install Brave to Program Files because I am running as a user who is a member of Administrators group and I have UAC fully disabled (EnableLUA = 0 in registry).


Yeah I am Admin too but still get this shit... can't believe its been over a year and no fix

**Comment by methanoid** [comment]
> OK this issue should be solved now as we've released Chromium 138. Closing

Chromium 140 (Brave 182) and STILL get this junk created
