### ISSUE TITLE
Can't connect to Server error shown when connecting to VPN after linking to Win 11 Arm64 laptop

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#28942]
## Description 

After logging into `Win 11 Arm64` with existing Prod VPN credentials, clicked `Refesh Brave VPN` button and credentials successfully loaded. When enabled VPN,  it failed with `Can't connect to server` error message 

## Steps to Reproduce

1. Install 1.49.118
2. launch Brave
3. enable `brave://flags/#brave-vpn`
4. login to `Win 11 Arm64` with already purchased Brave prod VPN credentials
5. click `Refresh VPN` button on the subscription page
6. toggle On from Disconnected to Connected in the VPN panel

## Actual result:

<img width="938" alt="image" src="https://user-images.githubusercontent.com/98358127/223549047-5e201f44-79da-4918-9439-b74f40025b60.png">

```
[21784:20716:0307/135246.586:WARNING:CONSOLE(952)] "Connection has failed", source: chrome-untrusted://vpn-panel.top-chrome/brave_vpn_panel.bundle.js (952)
```
## Expected result:
No errors should be shown. 

## Reproduces how often: 

Easily 

## Brave version (brave://version info)

```
Brave | 1.49.114 Chromium: 110.0.5481.177 (Official Build) beta (64-bit)
-- | --
Revision | f34f7ab2d4ca4ad498ef42aeba4f4eb2c1392d63-refs/branch-heads/5481@{#1239}
OS | Windows 11 Version 22H2 (Build 22621.1265)
```
## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@bsclifton 
cc: @stephendonner

**Comment by bsclifton** [comment]
Guessing this is related to the `CustomIPSecPolicies` field in the `%APPDATA%\Microsoft\Network\Connections\Pbk\rasphone.pbk` file. I'll look for a command to manually run in Powershell which can set this and then we can easily compare 🙂

**Comment by bsclifton** [comment]
@MadhaviSeelam this should be fixed now - after we switched to powershell. Can you please retest? 😄

**Comment by Brave-Matt** [comment]
Seeing some users encountering this same issue as well  — to clarify, after we pushed that fix the user should just be able to use VPN normally (no other steps are needed)?

**Comment by bsclifton** [comment]
@Brave-Matt that is correct. If they encountered the problem once, they may need to change servers and then change back. That should fix them up

**Comment by bsclifton** [comment]
Fix would have been 1.55 and higher - where PowerShell is used to set the VPN items. That should be working 100% - versus the old way which used a hardcoded bitmask (hardcoded for Win64 - likely why it failed for Win Arm64)

**Comment by MadhaviSeelam** [comment]
Verified the issue in and still seeing `Can't connect to Server error` message shown
```
Brave | 1.65.130 Chromium: 124.0.6367.159 (Official Build) (arm64)
-- | --
Revision | 67843557ad274aba4b206391773c789c174b7fad
OS | Windows 11 Version 23H2 (Build 22631.3527)
```
https://github.com/brave/brave-browser/assets/98358127/1ca14176-eaf2-4c6d-99ee-ef7c28e3377a

**Comment by bsclifton** [comment]
Happy to report that both WireGuard and IKEv2 are working great - huge thanks to @MadhaviSeelam for retesting recently 😄 

```
Brave	1.68.128 Chromium: 127.0.6533.73 (Official Build) (arm64) 
Revision	800676fd9ede2eb4174bac98c186e53749c7201f
OS	Windows 11 Version 23H2 (Build 22631.3880)
```

### WireGuard
![image](https://github.com/user-attachments/assets/87328bb9-b372-4071-805d-9007ceebf2a8)

### IKEv2
![image](https://github.com/user-attachments/assets/396a692e-0a16-4593-8390-f6c141973cd8)
![image](https://github.com/user-attachments/assets/7b644c49-1b53-43b4-8f86-d51254726b18)
