### ISSUE TITLE
block popup on medium.com and affiliated sites

### ISSUE THREAD

**Issue by 424344** [brave/brave-browser#29133]
## Description 

On medium.com and affiliated sites I always see a black popup. how to hide it?
It's showed on medium.com and affiliated sites (different domains).

## Steps to Reproduce

   1. 
   2. 
   3. 

## Actual result:

![image](https://user-images.githubusercontent.com/26486758/225880587-429e0f2d-324d-41f4-acdf-41b36167064c.png)

![image](https://user-images.githubusercontent.com/26486758/225880361-2d74498c-7b0c-4f76-96e8-36b4e1b7d40e.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
cc: @ryanbr

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/6cbaa50bc6b036c495581049984ecee292270ae0 should fix it.

Give it 24/48hrs. Will keep this open to confirm

**Comment by ryanbr** [comment]
Resolved @424344 ?

**Comment by 424344** [comment]
Hello,
it doesn't work for the sites in the screenshots that I uploaded:

https://javascript.plainenglish.io/
https://smartbrowsingsociety.medium.com/

I also looked at your rule, and tried the other websites you put in there:

In these sites the popup is blocked by your rule:

https://codeburst.io/
https://eand.co/
https://infosecwriteups.com/
https://netflixtechblog.com/
https://primegaming.blog/

These sites still show the popup, even with adblock enabled:

https://medium.com/
https://medium.engineering/
https://towardsdatascience.com/
https://uxdesign.cc/

Instead in these sites I see no popup, even with adblock disabled:

https://discord.com/blog/
https://windscribe.com/

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/e84397c15162307dc129feaebd5d4b633e9c799f

Missing only one domain;  plainenglish.io  . We're covering a few: 

`blog.discord.com,codeburst.io,eand.co,infosecwriteups.com,medium.com,medium.engineering,netflixtechblog.com,plainenglish.io,primegaming.blog,towardsdatascience.com,uxdesign.cc,windscribe.com#?#body > div:not([class]):not([id]) > div[class*=" "]:-abp-has(> div > div > div[class] > a[href^="https://policy.medium.com/medium-privacy-policy-"])`


I tested `https://uxdesign.cc/` ; https://gif.fanboy.co.nz/gif/uxdesign.gif

**Comment by 424344** [comment]
I tested again and I still get the popup for:

![image](https://user-images.githubusercontent.com/26486758/226544321-ddaa2ad9-e808-4ac1-a55f-4eed2198a73b.png)

and for:

![image](https://user-images.githubusercontent.com/26486758/226544389-908f3594-f0c8-4a89-a454-8e8387397d5f.png)

the other sites are now blocked correctly.

**Comment by ryanbr** [comment]
Should be resolved now, can you confirm @424344

**Comment by 424344** [comment]
blocked only on medium.com
instead towardsdatascience.com is still not blocked.

I see that the popup appears some seconds after the page loaded.
is it possible that the ad is created after the page is loaded, ie after the adblocker has already been executed?

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/9e09b86 was the resolution, discussed internally. I was never able to replicate it personally.

The filter is applicable too: `blog.discord.com,codeburst.io,eand.co,infosecwriteups.com,medium.com,medium.engineering,netflixtechblog.com,plainenglish.io,primegaming.blog,towardsdatascience.com,uxdesign.cc,windscribe.com`

**Comment by 424344** [comment]
it still doesn't work on towardsdatascience.com.

but it works in firefox with ublock origin, if I disable all blocks lists and manually insert the rule:
towardsdatascience.com#?#div:-abp-has(div[role='alert'] > a[href^="https://policy.medium.com/medium-privacy-policy-"])

**Comment by antonok-edm** [comment]
I think it's working now, but please let us know if it's not
