### ISSUE TITLE
Warning "--no-sandbox Stability and security will suffer" on first launch

### ISSUE THREAD

**Issue by max-l** [brave/brave-browser#2979]
I installed brave 

Version 0.56.12 Chromium: 70.0.3538.77 (Official Build) unknown (64-bit)

as a ubuntu 18.04 snap: https://snapcraft.io/brave

When the browser launches there is the warning: 

```You are using an unsupported command-line flag --no-sandbox Stability and security will suffer```

**Comment by rebron** [comment]
cc: @posix4e @diracdeltas @w0ts0n

**Comment by posix4e** [comment]
This is fixed in future snaps. The current snap needs an update.

**Comment by tomlowenthal** [comment]
How have you fixed it, @posix4e? Are you just not showing the warning any more?

**Comment by posix4e** [comment]
It was fixed here https://github.com/brave/unofficial-snap/commits/master for the last few commits. 
- [ ] We upgraded to new brave
- [ ] We re-enabled the sandbox

**Comment by hubitor** [comment]
I have installed this version (dev version from AUR):
Version 0.61.17 Chromium: 72.0.3626.81 (Official Build) unknown (64-bit)
and I'm still seeing this message.
In which version will be the fix added?

**Comment by fmarier** [comment]
@hubitor That's because the package that's in Arch Linux [explicitly disables the security sandbox](https://aur.archlinux.org/cgit/aur.git/tree/brave-dev-bin.sh?h=brave-dev-bin#n6) when it detects that user namespaces are disabled.

To fix this, follow the [instructions on the stable package page](https://aur.archlinux.org/packages/brave-bin/):

    sudo sysctl kernel.unprivileged_userns_clone=1
    echo kernel.unprivileged_userns_clone = 1 | sudo tee /etc/sysctl.d/00-local-userns.conf

**Comment by meliaas** [comment]
Hey, I followed @fmarier instructions but the error message persists on Manjaro Linux and Brave version 0.66.99-1

**Comment by fmarier** [comment]
@meliaas Could you please file a new issue for this and include:

- the version of Manjaro you are using
- the exact instructions you followed to install Brave
- the error message you are seeing when you run `brave-browser` from a terminal

**Comment by fmarier** [comment]
I'm going to set this to P5 since the original reports were about unsupported third-party packages. The Manjaro issue is potentially different so we can track that separately.

**Comment by fmarier** [comment]
Closing since this was fixed a while back: https://github.com/brave/brave-browser/issues/2979#issuecomment-457261885
