### ISSUE TITLE
Gnome Wayland Fractional Scaling Regression

### ISSUE THREAD

**Issue by Pythoner6** [brave/brave-browser#30137]
## Description 
Previously brave worked fine when `org.gnome.mutter experimental-features` was set to `['scale-monitor-framebuffer']` (necessary to get fractional scaling at the moment under gnome). Now if you set the display scaling to something larger than 100% (e.g. 150% or 200%), brave is not scaled properly, appearing much too large.

## Steps to Reproduce

   1. `gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"`
   2. Set display scaling to something larger than 100%
   4. Install latest version of brave
   3. Set Preferred Ozone platform to Wayland under brave://flags
   5. Restart brave

## Actual result:
Brave window is not sized properly, e.g. when it is "maximized" it takes up more than the full screen and is blurry.

## Expected result:
Brave is sized properly according to the desktop scaling setting and not blurry.

## Reproduces how often: 
Consistently

## Brave version (brave://version info)
Brave: 1.51.110 Chromium: 113.0.5672.77 (Official Build) (64-bit)
Revision: c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
OS: Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
  - Yes
- Can you reproduce this issue with the beta channel? 
  - Yes
- Can you reproduce this issue with the nightly channel? 
  - Yes

## Other Additional Information:

- Is the issue reproducible on the latest version of Chrome?
  - Haven't tested Chrome, but it is not reproducible in the latest version of chromium.

**Comment by henil** [comment]
same issue on KDE

**Comment by BirdInFire** [comment]
have the same problem downgraded too also fixed it.

**Comment by BirdInFire** [comment]
Can we expect an update soon or must i, go to another browser the time next version come ? (since all browser continue to see wayland as second class citizen (not even tested before making update when ubuntu/fedora etc use it by default).

**Comment by jaylittle** [comment]
> Actually, in addition, setting the preferred ozone platform to wayland when the experimental mutter setting isn't enabled, but scaling is e.g. 200% is now also blurry, where it used to not be. Perhaps scaling in wayland may just be broken in general.

No, more than likely that just means Brave is using XWayland (aka X11) instead of native Wayland.

**Comment by jaylittle** [comment]
> Can we expect an update soon or must i, go to another browser the time next version come ? (since all browser continue to see wayland as second class citizen (not even tested before making update when ubuntu/fedora etc use it by default).

FWIW I think we are close to seeing this issue resolved in Chromium based browsers.  I tried the latest Chromium Dev browser yesterday and once I set the Ozone Platform setting to use Wayland, it handled fractional scaling perfectly without anymore hacks of coaxing required on my part.

**Comment by Pythoner6** [comment]
> > Actually, in addition, setting the preferred ozone platform to wayland when the experimental mutter setting isn't enabled, but scaling is e.g. 200% is now also blurry, where it used to not be. Perhaps scaling in wayland may just be broken in general.
> 
> No, more than likely that just means Brave is using XWayland (aka X11) instead of native Wayland.

Nope, just double checked using xeyes and brave is running with wayland (when I set the ozone platform to wayland), but the scaling is wrong and it seems blurry. Almost like brave is being rendered at the appropriate resolution, but then displayed at 2x the size it should be when scaling is 200%. This wasn't an issue with the previous version and isn't an issue with the latest chromium either, so brave is doing something to break wayland scaling right now. Brave *is* also blurry running using XWayland, but that's a separate known issue (and not so much the fault of brave from what I understand).

**Comment by eifr** [comment]
I tried Chrome stable and the issue was present.
 It was also occurring a few weeks ago when I tested it on Chrome nightly, but it appears to be resolved now (on nightly).

**Comment by Pythoner6** [comment]
Hmm, interesting it'd be an issue on chrome, as it is not happening for me on chromium 113.0.5672.63 (Official Build) (64-bit)

**Comment by spockfish** [comment]
This is the corresponding thread at Fedora: https://discussion.fedoraproject.org/t/chrome-and-brave-with-ozone-wayland-fractional-scaling-stopped-working-on-f38/82077

**Comment by BirdInFire** [comment]
> This is the corresponding thread at Fedora: https://discussion.fedoraproject.org/t/chrome-and-brave-with-ozone-wayland-fractional-scaling-stopped-working-on-f38/82077

i do not use the normal version since i'm forced (silverblue) to use flatpak due to my system, and the fedora "temporary" fix do not fix the problem in my case (or maybe i do not use iris).

Really hope an hotfix very soon.

**Comment by sepehr** [comment]
I experienced this after the update to the latest Flatpak Brave today. I don't use fractional scaling as that's just hell, just straightforward 200%. 

On the latest Fedora, I have worked around this by downgrading from `1.51.110` to `1.50.125` and locking the version at the moment.

```
flatpak update --commit=2cbeea4c7ddb117f3680e6603bcf9cc799cf515f1e01ea7f1a3ff7e075115f94 com.brave.Browser

flatpak mask com.brave.Browser
```

**Comment by BirdInFire** [comment]
> I experienced this after the update to the latest Flatpak Brave today. I don't use fractional scaling as that's just hell, just straightforward 200%.
> 
> On the latest Fedora, I have worked around this by downgrading from `1.51.110` to `1.50.125` and locking the version at the moment.
> 
> ```
> flatpak update --commit=2cbeea4c7ddb117f3680e6603bcf9cc799cf515f1e01ea7f1a3ff7e075115f94 com.brave.Browser
> 
> flatpak mask com.brave.Browser
> ```

Fixing the version is not really recommended since you will avoid all security fixes that come with update.

**Comment by BirdInFire** [comment]
I have found a temporary fix (remain little blurry but at least it work on wayland instead of X11 (battery drain etc).

add : --force-device-scale-factor=1,25
you can update to 1,50 (depend if you use 125% or 150% in fractional scaling.

**Comment by BirdInFire** [comment]
> Issue persists in latest version:
> 
> Brave: 1.51.114 Chromium: 113.0.5672.92 (Official Build) unknown (64-bit) Revision: b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10} OS: Linux

Same here

**Comment by rebron** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1356014

**Comment by BirdInFire** [comment]
> https://bugs.chromium.org/p/chromium/issues/detail?id=1356014 Looks like a fix is on the way.

Simple curiosity, if you where to guess, do we will have a fix in "days, weeks" ? (only to see if i bear it a little more or if i can take time to set up another browser the time the fix arrive in your hand to be pushed) ?

**Comment by eifr** [comment]
> > https://bugs.chromium.org/p/chromium/issues/detail?id=1356014 Looks like a fix is on the way.
> 
> Simple curiosity, if you where to guess, do we will have a fix in "days, weeks" ? (only to see if i bear it a little more or if i can take time to set up another browser the time the fix arrive in your hand to be pushed) ?

Fixed for me in latest nightly, can anyone else test it

**Comment by fuelflo** [comment]
Yup, Brave Browser 113.1.53.37 nightly, seems to fix the problem for me.

**Comment by BirdInFire** [comment]
> Yup, Brave Browser 113.1.53.37 nightly, seems to fix the problem for me.

i Guess it will reach stable soon so :) thanks to tell us.

**Comment by Pythoner6** [comment]
Hmm, I'm still seeing the problem on 1.53.37. Or more specifically: with the experimental fractional scaling option enabled, scaling is still entirely wrong. With it disabled (and this seems to now be the case with even stable brave?) the window appears to be the correct scale, but is blurry (this is all running under native wayland, not through xwayland).

**Comment by Pythoner6** [comment]
Also I think I see why I didn't run into this issue with upstream chromium: I've been using the flatpak version of chromium which has some patches applied, one of which might be fixing this issue https://github.com/flathub/org.chromium.Chromium/blob/master/patches/chromium/M113-Revert-Linux-Ozone-Wayland-Support-fractional-scale-v.patch

**Comment by Pythoner6** [comment]
I haven't been able to test it, but it does look like the patch in the chromium flatpak I mentioned is from a commit in chromium upstream - just not one thats yet in a stable build I think. So I'm not surprised it'd be fixed in chrome beta.

**Comment by lubo** [comment]
This is fixed in Chrome 113.0.5672.126.

**Comment by Pythoner6** [comment]
Fixed in in the now released 1.51.118

**Comment by sepehr** [comment]
Experiencing this again on v1.52.122.

**Comment by eternal-zen** [comment]
I still get blurriness with `Release v1.53.103 (Chromium 115.0.5790.32)`.

**Comment by alongwhile** [comment]
I'm experiencing this on Fedora Silverblue running Gnome Wayland.  Both flatpak version and with rpm overlaid into the distro.  Scaling looks fine until i force Wayland under ozone flags, then all text looks blurry and low res.  Switching back to X11 under ozone doesn't even fix the problem!!

launching the rpm with `brave-browser  --force-device-scale-factor=1` does fix the problem but of course the UI and text are quite tiny.  Hoping this can be resolved somehow?

**Comment by sepehr** [comment]
Thanks for the update @alongwhile. Was this the latest v1.59.124 Brave?

**Comment by alongwhile** [comment]
> Thanks for the update @alongwhile. Was this the latest v1.59.124 Brave?

Yes.  I tried both flatpak and rpm install and it happens on both.  Had to delete all profile information to reset everything so it would stop.  Avoiding wayland for now I guess until this is resolved

**Comment by sepehr** [comment]
Still experiencing this on Fedora 40, `[Version 1.66.110 Chromium: 125.0.6422.60 (Official Build) unknown (64-bit)](https://brave.com/latest/)`

**Comment by sepehr** [comment]
Still experiencing this on Fedora 40, Flatpak-installed `Version 1.66.110 Chromium: 125.0.6422.60 (Official Build) unknown (64-bit)`. 

However, repo-installed version `[Version 1.66.110 Chromium: 125.0.6422.60 (Official Build) (64-bit)](https://brave.com/latest/)` works without any issues. Things are not blurry here.

**Comment by rathod-sahaab** [comment]
Go to `brave://flags` and set `#ozone-platform-hint` to auto, fixes it for me on hyprland

**Comment by adonig** [comment]
I can confirm that setting `#ozone-platform-hint` to `auto` fixes this issue on Fedora 41. Maybe this setting should be the default on Linux systems.
