### ISSUE TITLE
 Cannot add custom filterlists: “Download failed” 

### ISSUE THREAD

**Issue by pr1maryuser** [brave/brave-browser#30323]
## Description 

When adding custom filterlists (pulled from https://filterlists.com/), it is unable to download them, giving me an error message of “Download failed” under “Last updated.” For the purposes of this post I’ll be using [this one](https://raw.githubusercontent.com/uBlock-user/uBO-Personal-Filters/master/uPF.txt) as an example.

## Steps to Reproduce

1.  Go to [filterlists.com](http://filterlists.com/)
2.  Pick a filterlist
3.  Grab a link to the list by clicking “View” (as far as I can tell, the “Subscribe” buttons only work when you are using uBlock Origin)
4.  Go to brave://settings/shields/filters, scroll down to “Add custom filter lists”
5.  Copy/paste the link from earlier into the “Enter filter list URL” space, click “Add”
6.  The list then appears under “Custom lists,” but with the error message “Download failed” under “Last updated.”

## Actual result:

![image](https://github.com/brave/brave-browser/assets/119708452/9cfbaa2b-0c0b-4ff9-b712-df1a3ee11cf8)

## Expected result:
The list successfully downloads and Brave subscribes to it.

## Reproduces how often: 

Any time I attempt to add a new list, I’ve tried a bunch of them.

## Brave version (brave://version info)

Fedora Workstation 37 (Linux)
Version 1.51.114 Chromium: 113.0.5672.92 (Official Build) unknown (64-bit)

(I am using the Flatpak version of Brave, which I understand is third party and not officially supported. I installed it through Brave’s official Fedora repository found [here](https://brave.com/linux/#fedora-centos-streamrhel) to test if the issue persisted on that version, and it did.)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 

Yes

- Can you reproduce this issue with the beta channel? 

Yes

- Can you reproduce this issue with the nightly channel? 

Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 

The issue itself is related to Shields, so no.

- Does the issue resolve itself when disabling Brave Rewards? 

No.

- Is the issue reproducible on the latest version of Chrome? 

The issue pertains to a Brave specific feature.

## Miscellaneous Information:

I fully admit that I am not 100% certain that I am going through the correct steps to add custom lists, so I apologize if I am making some obvious mistake. The steps described are my best guess from searching for this topic.

**Comment by AmirulAndalib** [comment]
it is happening to me aswell need fix

**Comment by ramprasathasokan** [comment]
It's happening in this build too.
<img width="774" alt="image" src="https://github.com/brave/brave-browser/assets/47536066/0774f030-dd44-4890-99bd-424298fc9f6a">

**Comment by ramprasathasokan** [comment]
@rebron please help here.

I was trying to add OISD filters.

<img width="760" alt="image" src="https://github.com/brave/brave-browser/assets/47536066/cd939939-1a44-4d19-b16e-0eef49d7f913">

**Comment by wickles** [comment]
I have the same problem with the Microsoft Store version on Windows 11. I managed it get it to download a filter list once or twice but otherwise it fails almost every time.

**Comment by tazihad** [comment]
I am facing similar issue on linux with flatpak. It's a build problem. 
A temporary solution is to rollback to older version. Add your custom filter and than update browser again.  
This December 2022 version works. `[Version 1.46.134 Chromium: 108.0.5359.94 (Official Build) unknown (64-bit)](https://brave.com/latest/)`
```
sudo flatpak update --commit=aeeb1a93df6cfbe836965d437633c708977850a18b5e362d2c0aa8d2bd01c714 com.brave.Browser
```
Add your custom filter. And update flatpak again.
```
sudo flatpak update
```

Hope Brave will take over Flatpak version of Browser. Which has over 1 million Downloads.

**Comment by aidan-walden** [comment]
Can confirm this is also happening on the macOS version. 1.58.137 Chromium 117.0.5938.153 arm64

**Comment by js-d-coder** [comment]
I am facing this issue on Brave (Version 1.68.137 Chromium: 127.0.6533.100 (Official Build) (arm64)) while adding https://easylist.to/easylist/easylist.txt

**Comment by jackblk** [comment]
Same issue on `Version 1.68.137 Chromium: 127.0.6533.100 (Official Build) (64-bit)`

Tried https://easylist.to/easylist/easylist.txt, `Download failed`

**Comment by js-d-coder** [comment]
Same issue on `[Version 1.70.123 Chromium: 129.0.6668.89 (Official Build) (arm64)](https://brave.com/latest/)`

**Comment by bitsper2nd** [comment]
I have the same issue with Brave version 1.74.48 on Windows.

**Comment by Serg-VL** [comment]
Well, soon 2 years of bug present. Support haven't even look at it!
Brave is cool!

**Comment by jason-eu** [comment]
Same issue.
Windows 11
Brave Version 1.77.97 Chromium: 135.0.7049.84 (Official Build) (64-bit)

**Comment by coteyz** [comment]
Same issue on
Sequoia 15.2
Brave v1.79.123

**Comment by romw314** [comment]
Hey, I want to add this one: https://ads-for-open-source.readthedocs.io/en/latest/_static/lists/opensource-ads.txt

Supporting open source is important, so what should I do? I can't add this list!

**Comment by bsclifton** [comment]
cc: @antonok-edm @ryanbr

**Comment by Ilovecatz17** [comment]
IS THERE HOPE????

**Comment by romw314** [comment]
> IS THERE HOPE????

Maybe, it depends on the Brave Team.

**Comment by Ilovecatz17** [comment]
> > IS THERE HOPE????
> 
> Maybe, it depends on the Brave Team.

vp of engineering forwarded it, so i think there is hope

**Comment by karlemilnikka** [comment]
This is just a quick update (since it has been half a year since the last comment), confirming that the issue persists in Brave 1.86.139 (macOS ARM64).

**Comment by kenethc** [comment]
Don't have this issue. 

Initially it does say "Download failed" (for OISD Big filter list for instance) but if you give it some time - 1 min or so - it resolves automatically. 

Alternatively, click on the 3 dots and click Update manually. 

I am on latest Brave version.

**Comment by karlemilnikka** [comment]
This is just a quick update (since it has been another half a year since the last comment), confirming that the issue persists in Brave 1.92.134 (macOS ARM64).

**Comment by antonok-edm** [comment]
Hi all. Sorry for delay on this issue as we've had trouble reproducing it, but @rsuwa recently posted an issue and PR that appear to match. Could y'all check if https://github.com/brave/brave-browser/issues/55623 is relevant to your usage? We will work on getting that fix merged in the meantime.

If that's accurate, opening the "primary"/"default" browser profile before updating any custom filter list subscriptions should be viable as a temporary workaround.

**Comment by karlemilnikka** [comment]
@antonok-edm I can confirm that the bug affects me on a Mac where I’ve previously had multiple profiles, though I currently only have one profile. That profile’s library folder is called “Profile 6”. The library folder for the Default profile exists, but I cannot open or switch to that profile. My Windows computer, where I’ve ever only had one profile, is not affected.

**Comment by lazymonkey2** [comment]
still happening on windows with brave 1.93.129

**Comment by antonok-edm** [comment]
from my testing this should be fixed in v1.95 (currently Nightly)

**Comment by li12138** [comment]
Brave 1.93.138 (Official Build) (64-bit)
Chromium: 151.0.7922.173, 
This problem still exists, but the beta version can be used

**Comment by li12138** [comment]
> Hi all. Sorry for delay on this issue as we've had trouble reproducing it, but [@rsuwa](https://github.com/rsuwa) recently posted an issue and PR that appear to match. Could y'all check if [#55623](https://github.com/brave/brave-browser/issues/55623) is relevant to your usage? We will work on getting that fix merged in the meantime.
> 
> If that's accurate, opening the "primary"/"default" browser profile before updating any custom filter list subscriptions should be viable as a temporary workaround.

This method effectively solves the problem; simply switch to the default configuration profile in the browser to update the custom rule set.
