### ISSUE TITLE
`Block element via selector` context menu is not translated to other locales

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3094]
## Steps to Reproduce

1. Change locale
2. Open a page
3. Right click on the page
4. Click `Brave` from the context menu

Locales checked: Polish, Czech, German, Dutch, Danish, Finnish, Italian, Japanese, Korean, Norwegian, Russian, Spanish.

## Actual result:
Strings that are not translated:
`Block element via selector`
`Clear CSS rules for this site`
`Clear CSS rules for all sites`

![image](https://user-images.githubusercontent.com/34715963/51717013-789b8f80-203f-11e9-91aa-608bcf529d4c.png)

## Reproduces how often: 

always

## Brave version (brave://version info)

Brave | 0.59.28 Chromium: 72.0.3626.64 (Official Build) beta(64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Windows

cc @brave/legacy_qa @bbondy

**Comment by bbondy** [comment]
This is part of the brave extension so as long as it is localized there it should be fixed when we fix that localization.

**Comment by rebron** [comment]
@btlechowski While checking locales, can you revisit this one as well? cc @Snuupy

**Comment by btlechowski** [comment]
Still reproducible

Brave | 0.66.88 Chromium: 75.0.3770.87 (Official Build) beta (64-bit)
-- | --
Revision | 9dc58a2353af60ab2b48bab98a25bc43ed59085d-refs/branch-heads/3770@{#982}
OS | Windows 7 Service Pack 1 (Build 7601.24465)

Brave | 0.68.39 Chromium: 75.0.3770.87 (Oficjalna wersja)nightly (64-bitowa)
-- | --
Wersja | 9dc58a2353af60ab2b48bab98a25bc43ed59085d-refs/branch-heads/3770@{#982}
System operacyjny | Windows 7 Service Pack 1 (Build 7601.24465)

![image](https://user-images.githubusercontent.com/34715963/59385321-5d1df080-8d64-11e9-9f3c-11aaeb13bfa8.png)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.68.118 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2692 and STR from description
* Verified several languages: 
![Screen Shot 2019-08-05 at 17 18 19](https://user-images.githubusercontent.com/28145373/62496064-c723a680-b7a5-11e9-9e9d-e8422f182f9f.png)
![Screen Shot 2019-08-05 at 17 19 27](https://user-images.githubusercontent.com/28145373/62496066-c854d380-b7a5-11e9-9504-b69313a0d8f9.png)
![Screen Shot 2019-08-05 at 17 22 57](https://user-images.githubusercontent.com/28145373/62496068-ca1e9700-b7a5-11e9-932e-f7d5531ccc8a.png)
