### ISSUE TITLE
`Javascript` should read `JavaScript` in `brave://settings/system/shortcuts`

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#31554]
## Description 

`Javascript` should read `JavaScript` in `brave://settings/system/shortcuts`

## Steps to Reproduce

1. install `1.58.7`
2. launch Brave
3. open `brave://settings/system/shortcuts`
4. type `javascript`
5. note the spellings

## Actual result:

`Javascript` and `javascript`

<img width="1382" alt="Screen Shot 2023-07-10 at 4 45 03 PM" src="https://github.com/brave/brave-browser/assets/387249/c89ecca4-5319-44e8-9bfb-23e0c1aafbb3">

## Expected result:

The 1st should at least be `JavaScript` as it's initially upper-cased

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.58.7 Chromium: 115.0.5790.75 (Official Build) nightly (x86_64)
-- | --
Revision | db3af86e921baa371556e158292bc36a74aea794
OS | macOS Version 11.7.8 (Build 20G1351)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @fallaciousreasoning @rebron @brave/qa-team

**Comment by fallaciousreasoning** [comment]
Nice find! :eagle: :eye:

**Comment by jagadeshjai** [comment]
Seems this issue is fixed, Kindly check and close this issue @stephendonner

**Comment by stephendonner** [comment]
> Seems this issue is fixed, Kindly check and close this issue @stephendonner

Nope, it's not fixed;

<img width="1509" alt="Screen Shot 2024-06-10 at 9 55 39 AM" src="https://github.com/brave/brave-browser/assets/387249/7b581359-a28e-419b-9d28-c50571b4bb32">

**Comment by jagadeshjai** [comment]
> > Seems this issue is fixed, Kindly check and close this issue @stephendonner
> 
> Nope, it's not fixed;
> <img alt="Screen Shot 2024-06-10 at 9 55 39 AM" width="1509" src="https://private-user-images.githubusercontent.com/387249/338275494-7b581359-a28e-419b-9d28-c50571b4bb32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMzkwMTUsIm5iZiI6MTcxODAzODcxNSwicGF0aCI6Ii8zODcyNDkvMzM4Mjc1NDk0LTdiNTgxMzU5LWEyOGUtNDE5Yi05ZDI4LWM1MDU3MWI0YmIzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQxNjU4MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzdmZGIzYTI2MGM3NzBhY2FiZjA4NjM1MzQ3NzQyMTMwMjM0MTEwODA1ZGI2YzIzMzE0ZWM3ZTZlYmUzNThhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZewQGAZodJNo50YdnTmxdxSFA7cF8xge_nhKpPl9u7Q">

You Mean "Toggle javascript apple events" and "Toggle javascript" ?


> The 1st should at least be JavaScript as it's initially upper-cased

From your first screenshot and suggestion, i thought "Javascript console" should be "JavaScript console".

**Comment by stephendonner** [comment]
> From your first screenshot and suggestion, i thought "Javascript console" should be "JavaScript console".

One instance is fixed, but this covers the rest of them as well.

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.69.53 Chromium: 127.0.6533.17 (Official Build) nightly (x86_64)
-- | --
Revision | bedcc2e74ce45bd641d2946e0d870d68ba08b8e9
OS | macOS Version 11.7.10 (Build 20G1427)
```

#### Followed my original steps to reproduce from https://github.com/brave/brave-browser/issues/31554#issue-1797803284

### Confirmed all 3 instances of `JavaScript` are spelled correctly in `brave://settings/system/shortcuts`

<img width="1988" alt="Screen Shot 2024-06-26 at 11 40 49 AM" src="https://github.com/brave/brave-browser/assets/387249/20fd1a9d-25a2-41af-ad93-164a029ff7bd">
