### ISSUE TITLE
Connecting to Brave VPN after disabling WireGuard and upgrading still uses WireGuard, rather than IKEv2

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#33244]
## Description 

Connecting to Brave VPN after disabling WireGuard and upgrading still uses WireGuard, rather than IKEv2

Found while testing https://github.com/brave/brave-browser/issues/32280

## Steps to Reproduce

1. installed `1.58.33` (`nightly`)
2. launched Brave
3. opened `brave://flags/`
4. set `Enable experimental Wireguard Brave VPN service` to `Disabled`
5. clicked Relaunch
6. purchased, configured, and connected to `Brave VPN` using [account.bravesoftware.com](http://account.bravesoftware.com/)
7. confirmed IKEv2 connection using `BraveVPNNightly` RAS connection in the VPN panel
8. closed Brave
9. installed `1.59.95` (`beta`)
10. renamed `Brave-Browser-Nightly` profile to `Brave-Browser-Beta`
11. launched Brave
12. opened `brave://settings/system`
13. checked the setting for WireGuard

## Actual result:

Looks like `Brave VPN` is connecting via `WireGuard` (It survives restart, doesn't create a `BraveVPNBeta` RAS connection, etc.)

![image](https://github.com/brave/brave-browser/assets/387249/480f03d1-b7f4-4dfe-a834-9a754da97bc3)

## Expected result:

`Brave VPN` should be connecting using `IKEv2`

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.59.99 Chromium: 117.0.5938.92 (Official Build) beta (64-bit)
-- | --
Revision | 189010a9093526dbe96f0d187eacd29c3ba827b5
OS | Windows 10 Version 22H2 (Build 19045.3448)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @spylogsster @rebron @mattmcalister @bsclifton @simonhong @MadhaviSeelam @GeetaSarvadnya

**Comment by GeetaSarvadnya** [comment]
Reproduced the issue on

```
Brave | 1.59.101 Chromium: 117.0.5938.92 (Official Build) beta (64-bit)
-- | --
Revision | 81840f55490b042e3c7a75e0cba633580ed5a1b6
OS | Windows 11 Version 22H2 (Build 22621.2283)

```

**Comment by spylogsster** [comment]
> Reproduced the issue on
> 
> ```
> Brave | 1.59.101 Chromium: 117.0.5938.92 (Official Build) beta (64-bit)
> -- | --
> Revision | 81840f55490b042e3c7a75e0cba633580ed5a1b6
> OS | Windows 11 Version 22H2 (Build 22621.2283)
> ```
> 
> Example	Example
> ![image](https://user-images.githubusercontent.com/38657976/271038096-17d31982-89c0-45ea-bd06-14a5d8d028fc.png)	![image](https://user-images.githubusercontent.com/38657976/271017537-e164003f-40e1-430e-8b1e-69391599adf8.png)

Should be fixed in next Nightly

**Comment by stephendonner** [comment]
Setting to `QA/No` and `release notes/exclude` as the original issue in https://github.com/brave/brave-browser/issues/32280 wasn't fixed by https://github.com/brave/brave-browser/issues/33244, and should be addressed via https://github.com/brave/brave-browser/issues/33382

**Comment by stephendonner** [comment]
Now that I retested the correct way (sorry 'bout that!), I'm still seeing the same behavior when upgrading from `1.59.33` (`nightly`) -> `1.60.76` (`nightly`).

example | example | example
----------|-----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/6486f8c5-c6ed-4003-8608-a49aa4d27067) | ![image (1)](https://github.com/brave/brave-browser/assets/387249/a3dbf243-af05-420b-bf5b-2bcf8a4b41a6) | ![image (2)](https://github.com/brave/brave-browser/assets/387249/4e15a6de-f173-4efe-8dba-02140e64ca83)

### Steps:
1. installed `1.59.33` (`nightly`)
2. launched Brave
3. opened `brave://flags`
4. set `Enable experimental WireGuard Brave VPN service` to `Disabled`
5. clicked `Relaunch`
6. purchased, configured, and connected to `Brave VPN` using `account.bravesoftware.com`
7. confirmed `IKEv2` connection using `BraveVPNNightly` RAS connection in the VPN panel
8. upgraded via `brave://settings/help` to `1.60.76` (`nightly`)
9. connected to `Brave VPN`
10. confirmed I was connected via `WireGuard`
11. opened `brave://settings/system`
12. confirmed `Use WireGuard protocol in Brave VPN` was still enabled, too
