### ISSUE TITLE
`Autoplay was blocked on this site` icon is NOT shown on the URL bar when autoplay is blocked on a video

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#33309]
## Description 

`Autoplay was blocked on this site` icon is NOT shown on the URL bar when autoplay is blocked on a video

## Steps to Reproduce

   1. Clean or upgraded profile `1.60.63`
   2. Open a video 
   3. Click on the lock icon and select `Block` option for the `Autoplay` content settings
   4. Reload the video
   5. Autoplay is blocked on the video but the autoplay block icon is NOT shown on the URL bar
 
## Actual result:

`Autoplay was blocked on this site` icon is NOT shown on the URL bar when autoplay is blocked on a video

## Expected result:
`Autoplay was blocked on this site` icon should be shown on the URL bar when autoplay is blocked on a video

![image](https://github.com/brave/brave-browser/assets/38657976/688775c3-8c3c-497b-b943-b7de26df38c8)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.60.64 Chromium: 118.0.5993.21 (Official Build) nightly (64-bit)
-- | --
Revision | f05e9ca819b9af4850b13764e15631322922d47c
OS | Windows 10 Version 22H2 (Build 19045.3448)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes, works fine in Chromium: 115.0.5790.32 
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @emerick

**Comment by LaurenWags** [comment]
Reproduced with `1.60.66 Chromium: 118.0.5993.21` Nightly, `1.58.135 Chromium: 117.0.5938.140` Release,

**Comment by emerick** [comment]
This is due to this upstream bug https://bugs.chromium.org/p/chromium/issues/detail?id=1482164. This was recently fixed in upstream's master, so I think the fix will appear in 119 (120 at the latest, depending on the timing of things upstream).

**Comment by GeetaSarvadnya** [comment]
Looks like this issue still not fixed, I can reproduce the issue on the following version

```
Brave | 1.81.76 Chromium: 138.0.7204.25 (Official Build) nightly (64-bit)
-- | --
Revision | 742e47b17bc9b3e37e5b555495a6567e66fbf03f
OS | Windows 10 Version 22H2 (Build 19045.5965)

```

**Comment by MadhaviSeelam** [comment]
This is reproduced in `Brave | 1.80.110 Chromium: 138.0.7204.35 (Official Build) (arm64)`as well. However, `Autoplay was blocked on this page` icon was shown Youtube app as expected. 

![Image](https://github.com/user-attachments/assets/531dd6f9-f7ed-4ed6-b0e9-1562b7e01493)
