### ISSUE TITLE
Migrated Brave VPN IKEv2 connection switches to `WireGuard`, but should stay on `IKEv2`

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#33382]
## Description 

Migrated Brave VPN IKEv2 connection switches to `WireGuard`, but should stay on `IKEv2`

This is essentially a rehash of https://github.com/brave/brave-browser/issues/33244, which is itself a re-filing of https://github.com/brave/brave-browser/issues/32280

## Steps to Reproduce

1. installed `1.58.33` (`nightly`)
2. launched Brave
3. opened `brave://flags/`
4. set `Enable experimental WireGuard Brave VPN service` to Disabled
5. clicked `Relaunch`
6. purchased, configured, and connected to `Brave VPN` using [account.bravesoftware.com](http://account.bravesoftware.com/)
7. confirmed IKEv2 connection using `BraveVPNNightly` RAS connection in the VPN panel
8. closed Brave
9. installed `1.59.109` (`beta`)
10. renamed `Brave-Browser-Nightly` profile to `Brave-Browser-Beta`
11. launched Brave
12. opened `brave://settings/system`
13. checked the setting for `WireGuard`

## Actual result:

* `Brave VPN` connects via `WireGuard`
* `brave://settings/system` shows `Use WireGuard protocol in Brave VPN` togled to `On`/`Enabled`

![image](https://github.com/brave/brave-browser/assets/387249/b0d837a0-7ca0-42b5-9944-649b14ecf032)

## Expected result:

* Should be connected via `IKEv2`
* `brave://settings/system` should show `Use WireGuard protocol in Brave VPN` toggled to `Off`/`Disabled`

![image](https://github.com/brave/brave-browser/assets/387249/d47d4561-736d-44ed-8719-c16ed35e4f1c)

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.59.109 Chromium: 118.0.5993.21 (Official Build) beta (64-bit)
-- | --
Revision | aacb6a6f8bd916bd49f064b2137b007fa6c47b51
OS | Windows 10 Version 22H2 (Build 19045.3516)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @spylogsster @simonhong @bsclifton @brave/qa-team

**Comment by spylogsster** [comment]
I created uplift to Beta, it should fix this issue https://ci.brave.com/job/brave-core-create-uplift-prs/2842/ cc @stephendonner

**Comment by stephendonner** [comment]
Now that I retested the correct way (sorry 'bout that!), I'm still seeing the same behavior when upgrading from `1.59.33` (`nightly`) -> `1.60.76` (`nightly`).

example | example | example
----------|-----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/6486f8c5-c6ed-4003-8608-a49aa4d27067) | ![image (1)](https://github.com/brave/brave-browser/assets/387249/a3dbf243-af05-420b-bf5b-2bcf8a4b41a6) | ![image (2)](https://github.com/brave/brave-browser/assets/387249/4e15a6de-f173-4efe-8dba-02140e64ca83)

**Comment by kjozwiak** [comment]
Closing the above as it's addressed via https://github.com/brave/brave-core/pull/20295 & https://github.com/brave/brave-core/pull/20392 and will be uplifted into `1.59.x` via https://github.com/brave/brave-core/pull/20373. @stephendonner verified via https://github.com/brave/brave-core/pull/20392#issuecomment-1749979902.

**Comment by kjozwiak** [comment]
@LaurenWags @stephendonner added the `release-notes/include` label but please correct if it shouldn't be mentioned. I'm not 100% sure if this is a new regression or specific to `1.59.x`. If it's only specific to `1.59.x`, we can change to `release-notes/exclude`.

**Comment by kjozwiak** [comment]
The above requires `1.59.115` or higher for `1.59.x` verification 👍

**Comment by stephendonner** [comment]
> @LaurenWags @stephendonner added the `release-notes/include` label but please correct if it shouldn't be mentioned. I'm not 100% sure if this is a new regression or specific to `1.59.x`. If it's only specific to `1.59.x`, we can change to `release-notes/exclude`.

New regression, never worked.

**Comment by LaurenWags** [comment]
Changing to `release-notes/exclude` per discussion with @kjozwiak @rebron - will use https://github.com/brave/brave-browser/issues/32002 as the main WireGuard issue in the notes.

**Comment by stephendonner** [comment]
We've got https://github.com/brave/brave-browser/issues/33418 which has a commit and a verification on `Win10-x64` already.  Setting to `QA/No` as this issue wasn't tested correctly when it was logged.  It was tested against `nightly` -> `beta` but should've been tested from `nightly` -> `nightly`, instead.
