### ISSUE TITLE
Scroll position is not restored in the feed after navigating back if an article opened in the current tab

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#35059]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/34593.  After selecting `Current tab` to open articles in the current tab in the Brave News customize dialog, clicked an article in the feed and it opened in the current tab. Navigated back from the article, took back to the same feed but the scroll position is not restored in this mode.  This didn't happen first time, but happened subsequent iterations.  

## Steps to Reproduce

   1.  Install 1.62.123
   2.  launch Brave
   3. clicked `Customize` >>Brave News 
   4. clicked `Turn on Brave News`
   5. selected `Current tab` in the Brave News dialog
   6. followed `Forbes` 
   7. closed the dialog
   8. clicked `News` 
   9. clicked `New content available. `Reload?`
  10. clicked an article/Hero card (`Gear in Review: The Equipment...`) for `Forbes` in the feed 
  11. confirmed the article opened in the current tab
  12. navigated back to the same feed and scroll position is restored to show previous `Forbes` article.
  13. opened another article midway thru the feed (`Business Insider article`)
  

## Actual result:

Navigated back to the same feed and scroll position is not restored i.e. Same article/Hero card is not shown 

https://github.com/brave/brave-browser/assets/98358127/5e16d01f-5a4d-4a50-8acf-ab175eca2b5c

## Expected result:
Scroll position should be restored. 

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.62.123 Chromium: 120.0.6099.144 (Official Build) beta (64-bit)
-- | --
Revision | 680382264ff6ae655b3bba25e80567452f38fbee
OS | Windows 11 Version 22H2 (Build 22621.2861)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release?N/A
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@fallaciousreasoning @LorenzoMinto 
cc: @stephendonner @rebron

**Comment by fallaciousreasoning** [comment]
Couldn't reproduce in 1.63.87 or 1.62.128 - possibly this has been fixed in one of the uplifts?

**Comment by stephendonner** [comment]
I also couldn't reproduce this using

```
Brave | 1.62.128 Chromium: 120.0.6099.144 (Official Build) beta (x86_64)
-- | --
Revision | 41f5844c06c7db1017f39b5b6dc9ba81a6b1b9d6
OS | macOS Version 11.7.10 (Build 20G1427)
```

@MadhaviSeelam mind rechecking?

![Uploading scroll-position-saved.gif…]()

**Comment by fallaciousreasoning** [comment]
It might have been fixed already - I vaguely remember seeing something like this earlier (but I'm not sure)

**Comment by MadhaviSeelam** [comment]
So I still see the issue exists in `1.62.129 Chromium: 120.0.6099.144`.  Clicked on first article/hero image card and navigated back, it correctly positioned and shown the hero image card.  However, scroll position is incorrect when I clicked subsequent hero cards and/or article cards and navigated back in the current tab.

cc: @stephendonner 

Uploading 2024-01-03_13h43_07.mp4…

**Comment by fallaciousreasoning** [comment]
I wonder if this is to do with the advert? Hmmm.

**Comment by MadhaviSeelam** [comment]
It wasn't necessarily with Advert.  I just used as a pointer to test.

**Comment by fallaciousreasoning** [comment]
This issue is not actually fixed, so don't test it yet QA!

**Comment by fallaciousreasoning** [comment]
Actual fix has landed! Sorry about that QA (I'm editing the bad PR to remove the issue number).

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.62.145 Chromium: 120.0.6099.234 (Official Build) beta (x86_64)
-- | --
Revision | 431a4319968af133d1c7792ad66437061f95dd83
OS | macOS Version 13.6.3 (Build 22G436)
```
