### ISSUE TITLE
Individual key export button should be removed for ZEC/BTC

### ISSUE THREAD

**Issue by kdenhartog** [brave/brave-browser#35824]
This is an issue when attempting to export the individual keys for BTC/ZEC. Since we don't use the account model for these it doesn't really make sense to export just a single key, so I'm thinking the better solution here is to just remove this button all together. Wdyt @supermassive @cypt4 @jamesmudgett ?

https://github.com/brave/brave-browser/assets/23125059/b20fb56d-8197-4d32-9641-3bb2b2d353e6

**Comment by supermassive** [comment]
Export should not be available now. I thought that was already fixed.

But actually there is a thing like extended public/private key which allows exporting or importing whole subtree of hd keys for an account
https://learnmeabitcoin.com/technical/extended-keys

**Comment by srirambv** [comment]
This issue is still valid, Export option is still shown on account 


BTC | ZEC
-- | --
![BTC](https://github.com/brave/brave-browser/assets/17010094/04bdb915-3e0c-4c03-b293-a4a28401bb1f) | ![ZCash](https://github.com/brave/brave-browser/assets/17010094/2d02a125-24a3-4792-a718-c1dbe9424b74)

**Comment by lukemulks** [comment]
I have several users providing feedback that they're assuming something is missing because they're unable to import and export their private key. 

I agree as well. Being able to import and export are expected tablestakes for UX and when there are stability or other issues encountered with one wallet or another. 

I am sure it's well intended to not have it, but overwhelming feedback from community has been that this feels against the grain and that it's likely a blocker on adoption. I could see this being that as well. 

I have captured some of the commentary observed when this came up in a community group this evening so the team can see the reflex. I have left screennames off to avoid singling out people providing the feedback, and would be happy to arrange 1:1 or group discussion with them for feedback or Q&A if that would be at all helpful. 
![Screenshot_20240327_225019_X](https://github.com/brave/brave-browser/assets/8979240/83399db9-2a40-4eb7-889f-f801bd7347e1)
![Screenshot_20240327_224342_X](https://github.com/brave/brave-browser/assets/8979240/34e44aa4-62b8-4957-883a-5e7aabadcfaa)
![Screenshot_20240327_224326_X](https://github.com/brave/brave-browser/assets/8979240/d1690552-b081-4215-a145-d704bac0882b)

**Comment by srirambv** [comment]
This is not an issue any more as we have removed Export option for Bitcoin/ZCash

<img width="941" alt="Image" src="https://github.com/user-attachments/assets/46d8744d-9b6f-4e24-a6e9-6dc6d6021829" /> | <img width="941" alt="Image" src="https://github.com/user-attachments/assets/d0c9e1fc-da65-4a56-935b-ac532872bda5" /> | <img width="941" alt="Image" src="https://github.com/user-attachments/assets/57fbfdab-b904-4eb6-91a9-3d1c527fdec6" /> | <img width="941" alt="Image" src="https://github.com/user-attachments/assets/28c6d5a3-c7a0-4012-bb64-7fb5688dba5a" />
-- | -- | -- | --
