### ISSUE TITLE
Unable to sync passwords

### ISSUE THREAD

**Issue by francoism90** [brave/brave-browser#36190]
## Description 

It states I need to enable biometrics features/PIN first. The device doesn't have any biometrics features, however it does use encryption and I'm already using a PIN to unlock the device

## Steps to reproduce 

   1. Install any Brave version on Chromebook/Android (including Nightly, Beta)
   2. Open Sync Preferences
   3. Try to enable Password sync

## Actual result 

See error message

## Expected result

Just work

## Issue reproduces how often 

Everytime

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone (Pixel 8 - Android 15), Chromebook Lenovo Duet Tablet
   - Android version: Android 15 (beta), ChromeOS (stable, beta & dev)
   
## Brave version

Stable, Beta & Nightly

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by blmille1** [comment]
I'm also getting this on my Intel core i3 Acer Chromebook.
This is literally the first thing I tried to set up.  I don't want to switch back to Google Chrome, but this may be the clincher.

**Comment by Jefferderp** [comment]
Identical issue.

Pixel 7, Android 14, GrapheneOS, rooted w/ Magisk, lockscreen PIN enabled. Brave has been installed for 1-2 years.

**Comment by mguerrilla** [comment]
Same problem Samsung Galaxy s20fe

**Comment by FurloSK** [comment]
Same problem with Huawei P20 :-/

**Comment by francoism90** [comment]
This is actually a life safer, I moved to Proton Pass. :)

**Comment by francoism90** [comment]
@VTArxelus I have updated the issue, as the same happens on Android devices now.

**Comment by mojhale** [comment]
Soooo, should I change password managers or change browsers? There are plenty of options out there, and some of them probably work. I kind of need passwords when I'm not at my computer.

**Comment by Arora-Sir** [comment]
[**@mojhale**](https://github.com/mojhale) commented on [Aug 17, 2024, 6:04 AM GMT+5:30](https://github.com/brave/brave-browser/issues/36190#issuecomment-2294499236 "2024-08-17T00:34:24Z - Replied by Github Reply Comments"):
> Soooo, should I change password managers or change browsers? There are plenty of options out there, and some of them probably work. I kind of need passwords when I'm not at my computer.

Please let me know if you've found some workout instead of resetting the brave from phone (this solved it for a while), but again after few days brave have this same issue!

**Comment by mojhale** [comment]
@VTArxelus 
1. Shall I create another post with the same manifest problems but tag it for Android? I don't use ChromeOS and am experiencing this issue.
2. I'm not sure I'm following. Are you suggesting exporting my passwords from my laptop, transferring the file, then finding the way to import them (as the setting for importing passwords from a file isn't evident)? I _really_ try to avoid transferring files in plaintext between devices. I do have another browser that I used to use that has password management that works seamlessly...

**Comment by francoism90** [comment]
It's already tagged for both, and also assigned.

**Comment by mojhale** [comment]
Also, I just learned that there's not actually a way to import passwords into the Android app: https://community.brave.com/t/password-import-on-ipad-and-android/527932/5
I really wish I could continue using Brave, but it isn't working for me to not be able to sign in to accounts when I'm not at home.

**Comment by NicholasFlamy** [comment]
This is really really bad.
Brave 1.69.153

**Comment by NicholasFlamy** [comment]
> > Same here, unable to turn on password sync even after authenticating via fingerprint.
> > Tasted on the ff units using the Play store version:
> > Samsung  Galaxy Tab S9 Ultra Android 14
> > Samsung Galaxy S23 Ultra Android 14
> > Samsung Galaxy A55 5G Android 14
> 
> This ticket is for ChromeOS, not Android.

Is there an Android ticket?

**Comment by Saoiray** [comment]
@NicholasFlamy and @francoism90 I've been hearing mixed reviews from people. Have you recently tested Beta and/or Nightly? If so, I'd be curious to see if it works for you there. So far I'm seeing people with Android saying it works, but not necessarily people on ChromeOS.

**Comment by NicholasFlamy** [comment]
> @NicholasFlamy and @francoism90 I've been hearing mixed reviews from people. Have you recently tested Beta and/or Nightly? If so, I'd be curious to see if it works for you there. So far I'm seeing people with Android saying it works, but not necessarily people on ChromeOS.

Haven't tested. Switched to BitWarden (specifically self-hosting VaultWarden) later that day.
I'll test stable on my tablet and if I can't enable password sync, I'll test beta and nightly.

**Comment by NicholasFlamy** [comment]
Can't reproduce on OneUI 5.1.1 Android 13 Galaxy Tab S6 Lite.

**Comment by mojhale** [comment]
@Saoiray I don't use ChromeOS. I am having this problem on Android.

**Comment by wrecklass** [comment]
Same issue with Pixel 8. Latest version of Android.

Tried restarting, tried resetting "Sync Everything."
Set Sync Password, was asked to use my Fingerprint to authorize, which I did.
Still cannot sync passwords and it doesn't even show the password setting enabled still.

Also on Desktop I noticed that a newly installed Brave Browser has started asking for passwords that it already has and have not been changed. Seems they have really screwed up Password syncing all around.

**Comment by joshvito** [comment]
I have the same issue on a stock Pixel 7a. Upvoted all comments that match my issue. 

Android 14
Brave version 1.69.160

**Comment by francoism90** [comment]
Brave Beta works on my Pixel 8 with Android 15. The stable doesn't for some reason?

The Chromebook still doesn't allow syncing.

**Comment by SergeyZhukovsky** [comment]
@AlexeyBarabash is looking on what could that be

**Comment by CraigOndrak** [comment]
Same Problem on Samsung Z fold 4. Cannot turn on password sync even if I authenticate using biometrics or PIN.  The toggle button remains disabled even after authentication. 
This is Very frustrating, I changed passwords on my desktop and now cannot login to the sites using my mobile.

**Comment by AlexeyBarabash** [comment]
Hello,

I am going to look on this issue after my current task, the next week.

Today I have just rechecked all the Google Play versions - result was the same for me - I was able to see the issue on `1.69.164 stable` and wasn't on `1.70.107 beta`/`1.71.78 nightly`.

@CraigOndrak 
could you please check if the problem happens on `Brave Beta` - https://play.google.com/store/apps/details?id=com.brave.browser_beta ?

**Comment by francoism90** [comment]
@AlexeyBarabash Thanks for looking into the issue! :)

Just FYI:
- Brave Stable on Android 15 - Password Sync doesn't work
- Brave Beta on Android 16 - Password Sync does work
- Brave Stable + Beta on Chromebook Password Sync doesn't work

It's both Android and ChromeOS that have the issue.

**Comment by FernandoCCNunes** [comment]
> Hello,
> 
> I am going to look on this issue after my current task, the next week.
> 
> Today I have just rechecked all the Google Play versions - result was the same for me - I was able to see the issue on `1.69.164 stable` and wasn't on `1.70.107 beta`/`1.71.78 nightly`.
> 
> @CraigOndrak could you please check if the problem happens on `Brave Beta` - https://play.google.com/store/apps/details?id=com.brave.browser_beta ?

I'm having this issue on Brave Stable 1.70.117 but not on Brave Beta 1.71.90

**Comment by saifshahriar** [comment]
Same problem on stock `Android 12`.

`Brave Version 1.70.119`

**Comment by wegethertravel** [comment]
Same here Android 14, OnePlus Open.

**Comment by smemsh** [comment]
Password sync broken with both latest stable AND beta, Android 14 Pixel 6 Pro phone.  Other stuff than passwords syncs ok.  Desktop ok.

It looks like most posters above say Beta works for them, but it does not for me (1.71.104).  Same thing as Stable (1.70.119): says I have to use biometric/password, but there's no way to get it to take my thumb or enter any password.  I have "sync everything" enabled but password cannot be enabled and just has that message (in red).  No error is shown and no way to open a dialog to authenticate.

Fortunately all the passwords that had synced before it stopped working are still available.

**Comment by wrecklass** [comment]
> https://proton.me/pass

Advertising spam?

**Comment by huggix** [comment]
> > https://proton.me/pass
> 
> Advertising spam?

At this point I think we are many who are thinking of dropping brave as password manager.

**Comment by saifshahriar** [comment]
> [https://proton.me/pass](https://proton.me/pass)

Problem is that, I need some passwords just to be stored in my browser.

I use
![Pass: The Standard Unix Password Manager](https://www.passwordstore.org). Still, I need some stuff to be saved just on my browser.

**Comment by francoism90** [comment]
@saifshahriar I get what you mean, I use browser passwords for local development, so it doesn't fill up my password manager. But I still would like them to be synced, because I may test them on other devices.

Proton does support multiple buckets, unfortunately only in the paid version.

**Comment by NicholasFlamy** [comment]
If we're listing Password Managers as an alternative/workaround for this issue, I will say I'm happy with Bitwarden, specifically I self-host VaultWarden (and use the Bitwarden clients).

**Comment by bsclifton** [comment]
This is something @AlexeyBarabash will be checking out next

He's currently looking into https://github.com/brave/brave-browser/issues/41196 which we recently found steps to reproduce / working to solve. Thanks for your patience folks!

**Comment by sramekmichal** [comment]
Same problem here.

Samsung Galaxy S20 FE.
Android 13; Build/TP1A.220624.014
Brave 1.71.118, Chromium 130.0.6723.70

**Comment by smemsh** [comment]
Is #42003 supposed to fix this? I still have the issue with 1.74.1.

Is it possible I'd need to turn off all sync and then back on again to make this work? I have made local changes I am unable to upload to the sync chain yet until it works, so I don't want to lose those.

Still same symptoms: Passwords data type state continues to be "0 / 0 / not running", settings -> sync -> options -> "sync everything" enabled, password forcibly disabled with red text: "...you'll need to authenticate with your biometrics/passcode..." but no apparent way to do that.

**Comment by Gl4d1u5** [comment]
Asus Zenfone 10
Android 14

![Image](https://github.com/user-attachments/assets/4f7bb55d-b5c2-4a5a-b38f-cea92a088128)

**Comment by AlexeyBarabash** [comment]
@smemsh 

> [@AlexeyBarabash](https://github.com/AlexeyBarabash) is [#42003](https://github.com/brave/brave-browser/issues/42003) supposed to fix this? I still have the issue with 1.74.1.

yes, `1.74.1` includes that fix. It is supposed that now switch of the Passwords data type  is fixed.

Is that true that you still cannot switch passwords option on at Brave Sync settings on `1.74.1`?

If yes - then I need to fix something more. The problem is that I can reproduce it only on one of my device with the Release version installed from Google Play and I can't reproduce it with my own-built apks.

**Comment by AlexeyBarabash** [comment]
@Gl4d1u5 
> Asus Zenfone 10 Android 14
> 

`1.71.123` doesn't contain the fix . 

At `1.71.x` the fix is available starting from `1.71.125`:
https://github.com/brave/brave-core/pull/26385#issuecomment-2463720056

**Comment by Gl4d1u5** [comment]
> [@Gl4d1u5](https://github.com/Gl4d1u5)
> 
> > Asus Zenfone 10 Android 14
> 
> `1.71.123` doesn't contain the fix .
> 
> At `1.71.x` the fix is available starting from `1.71.125`: [brave/brave-core#26385 (comment)](https://github.com/brave/brave-core/pull/26385#issuecomment-2463720056)

The Google play store doesn't give me an update on the app.
How do I get it to update?

**Comment by smemsh** [comment]
@AlexeyBarabash no definitely not fixed in 1.74.1, as mentioned, just tried again.  These are all Google Play official builds I'm using.

Is it possible this could have something to do with SafetyNet or any kind of device attestation failure? Mine would fail due to unlocked bootloader/root, but it's otherwise a stock and up to date ROM on my Pixel 6 Pro.

Also hoping you know the answer to my earlier question:

> Is it possible I'd need to turn off all sync and then back on again to make this work? I have made local changes I am unable to upload to the sync chain yet until it works, so I don't want to lose those.

It sounds like what I may need to do is export all my passwords on all devices on the sync chain, manually diff the json and make a superset, then make a new sync chain and reimport everything.  I'm not sure what else to do, I haven't had passwords sync in over 6 months now.  I can offer to do anything to help debug though.  I do have root on my device.

It would also be helpful to hear from some others on the ticket whether it still fails for them with 1.74.1 or (1.71.125)...

**Comment by threewest** [comment]
> 
> Is it possible this could have something to do with SafetyNet or any kind of device attestation failure? Mine would fail due to unlocked bootloader/root, but it's otherwise a stock and up to date ROM on my Pixel 6 Pro.


stock Pixel 7 Pro here running w/o root and I am having the issue


> > It would also be helpful to hear from some others on the ticket whether it still fails for them with 1.74.1 or (1.71.125)...

still on 1.71.123 available on Play store for me

**Comment by AlexeyBarabash** [comment]
@smemsh 

> Is it possible I'd need to turn off all sync and then back on again to make this work?

Unfortunately, no. This issue seems related to interaction between Brave Sync prefs screen and system's screenlock screen.  Turning off and on sync unlikely will help.

**Comment by smemsh** [comment]
@AlexeyBarabash said: 

> This issue seems related to interaction between Brave Sync prefs screen and system's screenlock screen

I just tried changing all manner of screenlock settings between lax and strict, fingerprint / no fingerprint, allow apps to use fingerprint to authenticate, all combinations.  None of them allowed me to enable password sync radio button in Brave.  It's worth noting that in-app biometric secondary auth does work fine on other apps (such as banking).

As a workaround, can we add a `brave://flags/` to disable the biometric auth requirement for password sync?  Because Sync worked fine before that was added, and I personally have no need for it (although I can understand the need for some folks).  I see `#biometric-auth-identity-check` there, mine is set to "default (disabled)" but maybe it doesn't influence sync?

**Comment by NicholasFlamy** [comment]
> Brave 1.69.153 Android 14 OneUI 6.1 Samsung S22

This same device on Brave 1.73.89, Chromium 131.0.6778.69 still has this issue.


> Can't reproduce on OneUI 5.1.1 Android 13 Galaxy Tab S6 Lite.

This device still doesn't reproduce the issue.

**Comment by smemsh** [comment]
> As a workaround, can we add a brave://flags/ to disable the biometric auth requirement for password sync?

it looks like brave/brave-core#19477 is probably the one that broke this, hopefully it can be put behind a flag rather than forced on everyone, so we can work around this issue until it's fixed.

**Comment by NicholasFlamy** [comment]
I think that's only half the issue, or there's 2 different issues. For me I don't see the red text after authenticating.

**Comment by smemsh** [comment]
> I think that's only half the issue, or there's 2 different issues. For me I don't see the red text after authenticating.

What part of yours is not working then? You're able to toggle the password radio? I see the red text (that I must use biometric auth to start password sync), but no dialog to authenticate ever appears, and no apparent way to trigger it.  The password radio is completely inactive to any touch.

**Comment by NicholasFlamy** [comment]
> > I think that's only half the issue, or there's 2 different issues. For me I don't see the red text after authenticating.
> 
> What part of yours is not working then? You're able to toggle the password slider? I see the red text (that I must use biometric auth to start password sync), but no dialog to authenticate ever appears, and no apparent way to trigger it. The password slider is completely inactive to any touch.

When I tap the slider, it pops up an authentication prompt, I authenticate, and then the red text goes away but the slider is off. If I then tap the slider again to turn it off, it animates turning on and back off right away, this time without asking for authentication.

**Comment by ibaldwin** [comment]
I'm getting the same behavior as NicholasFlamy, my info from the "about brave" section: 
Brave 1.71.123, Chromium 130.0.6723.116
Android 14 Build/UP1A.231005.007

Just checked and I'm on the most recent release available to me on the Google play store.

**Comment by huggix** [comment]
I also have almost the same issue as described by NicholasFlamy.

Recorded a video.

Brave 1.71.123, Chromium 130.0.6723.116

No newer version available in Play store.

https://github.com/user-attachments/assets/9c0da8a3-5b83-4822-aa87-1ce7c9c6c32d

**Comment by smemsh** [comment]
1.71.123 does not have the fix attempt.  only 1.71.125+ and beta 1.74.1+

**Comment by huggix** [comment]
Brave was now updates to Brave 1.73.89, Chromium 131.0.6778.69

Android, Samsung S21

Still not working. Error is exactly the same as I posted a video of a few replies back

**Comment by AlexeyBarabash** [comment]
@huggix thanks

**Comment by AlexeyBarabash** [comment]
Uplifting the PR with diagnostics https://github.com/brave/brave-core/pull/26657 to see more details.

**Comment by CraigOndrak** [comment]
@AlexeyBarabash please can we have a fix soon. this is a major issue. One of my passwords was detected in an online leak and I had to change my passwords on a bunch of sites. Now I cannot sign-in on any of these sites on my mobile. quite frustrating. Please please can we have a fix soon.

**Comment by aetherealtech** [comment]
Or at least a workaround.  I don't care about protecting the passwords with biometrics, I'd rather disable that feature entirely than not have password syncing at all on Android.

**Comment by u2rcrazybaby** [comment]
Brave Tech Support,

Can you please remove any prerequisites to enable syncing passwords, or anything else, across multiple devices? This would give you time to work on why there's a problem with thinking across devices, and requiring a biometrics or other passcode. I want to be able to sync across multiple devices. 

This is totally ridiculous that it has been this long and not been fixed. Someone is not thinking this through, and how this is impacting your clients.

**Comment by user716253** [comment]
Same problem with me.

Samsung Galaxy A55

**Comment by Tbrot79** [comment]
Hi
I am having this problem too. Was sent here for the solution from Brave community. 

I don't know anything about coding but joined for the solution. 
Is there a solution yet please? 
Samsung A52s 
Brave version from Google play :
Brave 1.73.91, Chromium 131.0.6778.85
Android 14; Build/UP1A.231005.007
The video shown earlier in this thread by huggix replicates exactly what I get too.  I didn't even know you could record your screen like that!!
If you have any questions I can try answer them in simple user ways, if it helps. 

Really need this solution- how else can I remember passwords across devices? 

Any help appreciated

**Comment by AideeAmei** [comment]
> [@AlexeyBarabash](https://github.com/AlexeyBarabash) please can we have a fix soon. this is a major issue. One of my passwords was detected in an online leak and I had to change my passwords on a bunch of sites. Now I cannot sign-in on any of these sites on my mobile. quite frustrating. Please please can we have a fix soon.

That's why you shouldn't reuse passwords. With the power of synchronization, we should be able to chose different passwords without having to remember them.

**Comment by HunterMeyer** [comment]
I'm having this issue as sell. I've tried fingerprint and passcode yet nothing allows me to enable syncing passwords.

https://github.com/user-attachments/assets/a8d10033-92a8-4da2-8440-051ec56f3cbb

**Comment by shaylevi2** [comment]
@bsclifton 

You guys are creating the gold standard of how to lose customers due to technical issues dragged on for months.

**Comment by francoism90** [comment]
@shaylevi2 This doesn't fixed the built, but you could switch to Proton Pass or Bitwarden.

This also helps when you use multiple browsers, and they do have Android integration (allowing fingerprints and token generating).

I know this isn't the fix, but in the end I'm actually glad I've switched, and make my life easier. :)

**Comment by AideeAmei** [comment]
@AlexeyBarabash Bravo, sir!

**Comment by AlexeyBarabash** [comment]
Fix is merged to Nightly, must be at the next Nightly build.

Uplifts to Beta and Release are created: [link](https://github.com/brave/brave-core/pulls?q=is%3Apr+%22Uplift+of+%2326876%22+%22Fixed+issue+of+unable+to+switch+on+the+passwords+sync+on+Android%22+%22uplift+to%22+)

**Comment by Tbrot79** [comment]
Updated brave on all devices and still does not sync passwords!

Same as before asks for password/biometrics and then does not allow you to toggle the password sync button to the on position.

anyone else?

**Comment by Saoiray** [comment]
> Updated brave on all devices and still does not sync passwords!
> 
> Same as before asks for password/biometrics and then does not allow you to toggle the password sync button to the on position.
> 
> anyone else?

Umm, @Tbrot79 it's generally helpful if you can try to be more clear on things. If you look at what has been said, the fix was arriving on Nightly. Then it will be getting uplifted to others. You come and speak about updating on all devices, but you fail to mention if it's on Nightly, Beta, or Release. Nor do you even say which specific version. 

Safe to assume you're just not paying attention and are rushing things? I mean, not even sure the fix hit Nightly yet. And if you look at https://github.com/brave/brave-core/pull/26919 you'd see that the merging to 1.73.x is blocked and hasn't happened yet. Same for https://github.com/brave/brave-core/pull/26918 which is 1.74.x

And I'm now seeing your comment at https://github.com/brave/brave-core/pull/26876#issuecomment-2525192398 where you shared you're on 1.73.x. So yeah, you're just rushing and not paying attention. Patience....it's coming.

**Comment by HunterMeyer** [comment]
@AlexeyBarabash thank you for updating us and fixing this issue (🤞). Do you have a Buy me a Coffee? Would love to reward your efforts.

**Comment by u2rcrazybaby** [comment]
I've restarted, and updated Brave. The problem is still occurring.

**Comment by bsclifton** [comment]
Hi folks - thanks for the comments. This fix is not released yet. Please stay tuned- we should have a 1.73.x release with this fix in the next week or so. You can watch https://github.com/brave/brave-core/pull/26919 and when that code gets merged you'll know we're close to a release. Thanks!

**Comment by hffvld** [comment]
Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 15 BP11.241025.006 release-keys
Brave build: 1.73.100
Chromium: 131.0.6778.108 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/26876#issue-2719037463
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Passwords` can be synced successfully for the new and upgraded account.

---------------------------

`Galaxy Tab S8`

https://github.com/user-attachments/assets/722a3ce8-86b9-49a8-8489-13a522c4a0bd


`Pixel 7`

https://github.com/user-attachments/assets/1affbadb-a5fd-4d4d-ba2c-9927ea473c3a

**Comment by u2rcrazybaby** [comment]
I have restarted my phone and check for an update, but there is no update
available . Brave browser is still not syncing passwords. Here are the
stats from my device:

- Model:  Samsung Galaxy mobile phone, a54 5G
- Brave browser version: 1.73.97, Chromium 131.0.6778.108

**Comment by hffvld** [comment]
Verified on `Acer CX5400` using version(s):
```
Device/OS: Acer CX5400 / ChromeOS 130.0.6723.126 (Official Build) (64-bit) 
Brave build: 1.73.100
Chromium: 131.0.6778.108 (Official Build) (64-bit)
```

Filed follow-up issue #42816
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/26876#issue-2719037463
2. *Verify*

**ACTUAL RESULTS:**
- Observed that `Passwords` can NOT be synced successfully for the new and upgraded account.

---------------------------

https://github.com/user-attachments/assets/bae83f29-c7ac-4eca-8c9d-a84f4247ef5e

**Comment by smemsh** [comment]
> I have restarted my phone and check for an update, but there is no update available . Brave browser is still not syncing passwords. ... [I have version] 1.73.97

the fix is not present until stable >= 1.73.100 or beta >= 1.74.25

**Comment by smemsh** [comment]
Confirmed, it's now fixed for me on Pixel 6 Pro in beta 1.74.26, woohoo! Did not have to do anything to make it work, it synced immediately after upgrade, and now all sync sliders are enabled, no red

Thanks for your persistence implementing the right fix @AlexeyBarabash, and thank you @bsclifton for ensuring that this got scheduled!

**Comment by NjordCZ** [comment]
Same problem on SailfishOS
