### ISSUE TITLE
Copy issue in dialog confirming adding an extension from the Chrome Web Store

### ISSUE THREAD

**Issue by gueorgui** [brave/brave-browser#3620]
## Description 
When adding an extension from the Chrome Web Store, the extension name in the confirmation dialog is corrupted. Instead of being `Extension Name`, it's instead `Extension NameExtension NameGmail Checker`.

## Steps to Reproduce

   1. Navigate to an extension's page in the Chrome Web Site (ex: [Notion](https://chrome.google.com/webstore/detail/notion-web-clipper/knheggckgoiihginacbkhaalnibhilkk))
   2. Click the "Add to Chrome" button
   3. Read the confirmation dialog

## Actual result:

<img width="472" alt="screenshot 2019-03-07 at 18 36 43" src="https://user-images.githubusercontent.com/3792/53981738-15574f80-410b-11e9-8770-7eecf64960f0.png">

## Expected result:

Text in confirmation dialog should read `Add "Notion Web Clipper" anyway?`

## Reproduces how often: 

Every time.

## Brave version (brave://version info)

Brave | 0.60.47 Chromium: 72.0.3626.119 (Official Build) (64-bit)
-- | --
Revision | 9a65993e2cde1b5797ec98da4cd9abcea464cd7b-refs/branch-heads/3626@{#876}
OS | Mac OS X

### Reproducible on current release:

Reproduces on both dev and beta builds.

### Additional Information

My OS and Brave are both set to English (UK), but the issue still persists when setting English (US) as the top priority language in the Brave settings.

**Comment by rebron** [comment]
hi @gueorgui. 

We released an updated version 0.61.51 Chromium: 73.0.3683.75 this Tuesday (Official build). Can you check to see if it reproduces for you with that version, manually update via chrome://settings/help if not already on the current version?

I'm not seeing this happen on this version now.
![Screen Shot 2019-03-14 at 1 20 25 PM](https://user-images.githubusercontent.com/5951041/54388848-f3565380-465b-11e9-969f-724a65da2494.png)

**Comment by gueorgui** [comment]
@rebron Still happening on the latest version!

<img width="480" alt="Screenshot 2019-03-15 at 00 55 32" src="https://user-images.githubusercontent.com/3792/54399132-490f1800-46bd-11e9-8971-7f0dab55aba4.png">


Brave | 0.61.51 Chromium: 73.0.3683.75 (Official Build) (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

**Comment by gueorgui** [comment]
@rebron It might be relevant that my OS locale is British English, and so is my browser's.

<img width="732" alt="Screenshot 2019-03-15 at 01 06 27" src="https://user-images.githubusercontent.com/3792/54399412-9cce3100-46be-11e9-9f8f-a970e4862195.png">
<img width="275" alt="Screenshot 2019-03-15 at 01 07 09" src="https://user-images.githubusercontent.com/3792/54399432-b2dbf180-46be-11e9-96d5-d226486e25b0.png">

**Comment by bsclifton** [comment]
This issue hasn't had an update in a while - it's met the criteria for being stale. The issue is going to be closed for now. If this is still a problem, please leave a comment or re-open the issue. Thanks!
