### ISSUE TITLE
Download toolbar not getting notified of color theme change

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#3708]
## Steps to Reproduce

    1. Set Dark Theme in Settings
    2. Restart Brave
    3. Right-click any link, choose 'Save link as...' and press OK in file dialog.
    4. Set Light Theme in Settings

## Actual result:

![image](https://user-images.githubusercontent.com/741836/54303299-e401d800-457f-11e9-8109-ec4184f51c4e.png)

## Expected result:
Downloads toolbar uses light theme

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 0.63.4 Chromium: 73.0.3683.67 (Official Build) dev (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by simonhong** [comment]
Fixed by https://github.com/brave/brave-core/pull/1805

**Comment by LaurenWags** [comment]
Verified passed with 

Brave | 0.62.31 Chromium: 73.0.3683.75 (Official Build) beta(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

- Verified STR from description. @kjozwiak could you check the test plan from https://github.com/brave/brave-core/pull/1805 on Mojave?

**Comment by srirambv** [comment]
Issue not fixed on Linux. Logged a follow up issue https://github.com/brave/brave-browser/issues/3793
![toolbar](https://user-images.githubusercontent.com/17010094/54641725-3dc73e00-4a69-11e9-9fac-dbb1a5ad7aeb.gif)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

Used STR from the description

**Comment by kjozwiak** [comment]
> - Verified STR from description. @kjozwiak could you check the test plan from https://github.com/brave/brave-core/pull/1805 on Mojave?

Looks good on `macOS 10.14.3 x64` running Mojave 👍

**Comment by srirambv** [comment]
Adding Windows/macOS  labels as its not fixed on Linux and follow up issue #3793 logged specifically for Linux
