### ISSUE TITLE
Issue with Tune. experimental extension

### ISSUE THREAD

**Issue by Dukko** [brave/brave-browser#3742]
## Description 
I am unable to log in to the Tune. extension by Google.

## Steps to Reproduce

   1. Click on the Tune. icon after install.
   2. Click on "Sign in with Google"

## Actual result:
Nothing happens.

## Expected result:
A new window should open, allowing you to sign in with Google.

## Reproduces how often: 
Happens every time.

## Brave version (brave://version info)

Brave | 0.61.51 Chromium: 73.0.3683.75 (Official Build) (64-bit)

Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/368eta builds? 

OS | Windows 10 OS Build 17763.379

### Additional Information
This is the extension: https://chrome.google.com/webstore/detail/tune-experimental/gdfknffdmmjakmlikbpdngpcpbbfhbnp

**Comment by bsclifton** [comment]
@bbondy would the social media blocking/allowing work you did recently fix this?

**Comment by bbondy** [comment]
yes I think it'll be fixed as of 0.62.x @Dukko would you mind trying to see if this works with this dev channel build?
https://brave.com/download-dev/

**Comment by Dukko** [comment]
Hi! Unfortunately, upon trying the dev version, it still won't work. :(

**Comment by bbondy** [comment]
Thanks for checking, we'll take a look!

**Comment by ryanbr** [comment]
Just tested this in Edge (Canary), has issues also with this extension; It'll open a new tab with the following invalid url

`https://to-be-replaced.invalid/signin/chrome/sync?ssp=1&continue=https%3A%2F%2Fwww.google.com%2F`

**Comment by bsclifton** [comment]
Is this happening because we're disabling GAIA? (Google Accounts and ID Administration)

**Comment by pilgrim-brave** [comment]
I don't see that URL in any of our code or patches. Our GAIA patch uses `no-thanks.invalid`: https://github.com/brave/brave-core/blob/master/patches/google_apis-gaia-gaia_urls.cc.patch

**Comment by ryanbr** [comment]
The login issue via an extension does remind me of https://github.com/brave/brave-browser/issues/3650

**Comment by bsclifton** [comment]
This should be fixed with a new `Allow Google login for extensions` option under brave://settings/extensions available in 1.14 and newer:
![image](https://user-images.githubusercontent.com/4733304/93045915-53410800-f60d-11ea-8a59-be0f69dc7179.png)

@Dukko can you try on [Beta](https://brave.com/download-beta) or [Nightly](https://brave.com/download-nightly) to see if issue is resolved? I'll close for now since there haven't been any recent reports either - but will watch for confirmation
