### ISSUE TITLE
Brave crashes with `Split View` flag enabled when getting a popup window.

### ISSUE THREAD

**Issue by TEMP-ad** [brave/brave-browser#37447]
## Description 

@sangwoo108

I know Split View is still early WIP, but I don't see tracked in https://github.com/brave/brave-browser/issues/36986 how the browser insta-crashes when you get a popup window or Devtools is used as a separated window just by having the flag enabled, regardless if Split View is being used or not.

## Steps to Reproduce

   1. Enable `brave://flags/#brave-split-view`
   2. go to https://www.rrc.texas.gov/resource-center/research/gis-viewer/gis-popup-blocker-test/ and run the test
   3. it should immediately crash 

## Brave version (brave://version info)

1.66.71 Chromium: 124.0.6367.29 (Official Build) nightly (64-bit) 
Windows 11 Version 23H2 (Build 22631.3296)

**Comment by sangwoo108** [comment]
Hi, @TEMP-ad ! Thanks for trying the new feature. Hopefully, this could have been fixed by https://github.com/brave/brave-core/pull/22975/files . Could you try later again? Thanks heaps as always!

**Comment by TEMP-ad** [comment]
@sangwoo108 based on the commits that PR was merged for 1.66.70 and I was still getting crashes with .71 today. I still installed and tested 1.66.72 as soon as it was available few minutes ago and I am still getting the same crashes.
I tested it with a total new user data us usual and it was reproduced just the same, but I never got any crash besides this one.

Well, not really, I also got a crash when I tried to select the two split tabs, and move them to another window to see if the split view would be kept since since split view would break if you try to move just one tab, so I was doing the test but I was having the feeling it would crash. But the only constant crash I can get always is the one with popup windows.

I can't wait to see how you polish and develop Split view! great work as usual.

**Comment by sangwoo108** [comment]
Thanks for checking! Will look into it.

**Comment by TEMP-ad** [comment]
Thanks for the quick fix!
I have been using the feature since minute 1, so it is nice not to get crashes anymore, I was holding any feedback about Split View for later when it is more obvious feedback might be needed.

Most of the little quirks I get are usually when when switching tabs anyway.

Like you can see a big re-drawing/re-layout of elements when switching from non-split tabs to split view tabs and viceversa, especially if the tab(s) have tons of CSS and JS.

Also, you get some _blank tab_ behavior, if you have twitch video in a split and you are on the other split and then you click on the volume button of the twitch video, it will stay a blank screen until you release the button.
YT videos only get a tiny little flicker when you do that, so it is less noticeable.
A page like lastfm, gets the flicker if you switch between the tabs being split by their content, like you click on the other split and then on the lastfm one, it can flicker.

You can also get a flicker easily by switching between the split view tabs through the tab strip.

Search tabs button gets active/highlighted for the right split tab. Easy to replicate, you only need to click first on the content of the right split, then the content of the left split and then you click on the second/right split on the tab strip.

And then Fullscreen of videos are not being fullscreen but like it fullscreen in the split, not the worst behavior but if you try to click on the tab's content of the non-fullscreen split, it kicks you out of fullscreen.

So these are the tiny little quirks I have seen, might be Win11 specific, and you might not hear from me regardless split view ever again, because the crash was the most problematic so 👍Hope you have a good day and thanks for your amazing work.

**Comment by sangwoo108** [comment]
Thanks for the very detailed feedback. Flickering is expected to some extent, as I was trying to not to modify Chromium's logic. But that doesn't mean that I won't try, I'll definately try to find a way to alleviate it. And other things are new to me. I really appreciate your help!
