### ISSUE TITLE
There's a momentary white splash screen when you open Brave

### ISSUE THREAD

**Issue by EnterMan123** [brave/brave-browser#38214]
## Description 

Opening brave in any way will cause a white flash for a moment.

## Steps to Reproduce

1. When opening Brave from the taskbar, a bright white flash appears.
2. When opening Brave from the desktop shortcut, a bright white flash appears.
3. When creating a new tab in Brave, a bright white flash also appears.

## Actual result:

https://github.com/user-attachments/assets/573cc0c8-3ce9-4311-b9bf-d631e213149f

Whenever I turn on brave, my room looks like this👇👇(recorded with mobile phone)
![123 (1) (1)](https://github.com/brave/brave-browser/assets/107846196/7f3429c8-5b9d-45cc-a8f5-7f1a8a6d156f)

This really hurts the eyes, everyone's eyes

## Expected result:

Please permanently fix this issue.

This problem has been going on for several years, and it has seriously damaged not only my eyes, but also the eyes of many people.

For many years, many people have complained about this issue online, but it has not been taken seriously. Many people have been silently enduring the torment of their eyes. I am just one of the many people who have provided feedback, and I have also recorded numerous videos to demonstrate how the issue occurred.

I hope this issue can be properly resolved before 2024 or early next year. I don't want to leave Brave for too long, but I have to temporarily switch to protect my eyes.

## Reproduces how often: 

1000%

## Brave version (brave://version info)

Brave | 1.65.130 Chromium: 124.0.6367.159 (Official version) （64 BIT） ---- **Any latest version**
Revision | 67843557ad274aba4b206391773c789c174b7fad
OS | Windows 11 Version 23H2 (Build 22631.3527)

## Version/Channel Information:

- Can you reproduce this issue with the current release? ---YES
- Can you reproduce this issue with the beta channel? ---YES
- Can you reproduce this issue with the nightly channel? ---YES

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  ---NO
- Does the issue resolve itself when disabling Brave Rewards? --- NO
- Is the issue reproducible on the latest version of Chrome? ---YES

## Miscellaneous Information:

I've tried other browsers:

- Chrome and Edge has exactly the same situation, 100% triggered
- Firefox 50% triggered
- Vivaldi usually does not have this problem, it only occurs when using PWA

Some people say this is a Chromium problem, I don't know. This situation does not occur with the vivaldi browser, which is also built on Chromium.

**Comment by bastele7** [comment]
I can confirm this issue on Brave for Windows, Version 1.67.123
This is very unpleasant for the eyes, especially when it is dark in the room.

**Comment by Retriev3r** [comment]
Same problem here!
MacOS 13.6.6 Ventura, latest version of Brave.

Like @bastele7 said: This is very unpleasant for the eyes, especially when it is dark in the room.
Imagine you are an epileptic - these flashes could kill you.

Will switch to Vivaldi browser until this is solved.

**Comment by Retriev3r** [comment]
Forgot to mention that this flash happens every time i switch from an active tab, to an inactive tab 🙈🙈🙈

**Comment by EnterMan123** [comment]
Brave has been my main browser, and I have used it for more than 8 hours a day for several years. However, my eyes are now experiencing serious discomfort. I will stop using Brave until this problem is resolved.

I will provide more important information about this issue later.

**Comment by EnterMan123** [comment]
https://github.com/user-attachments/assets/a226cc6b-43cb-4718-8ce3-9d1af1372627


https://github.com/user-attachments/assets/234b2e87-8d38-4523-886d-4cbab5b3ad7a


https://github.com/user-attachments/assets/d8b685d7-9f24-4556-a8d5-d5cf580c0acb

**Comment by goodov** [comment]
It's a windows issue, discussed here with some workarounds [1]. Looking into fixing it.

1. https://stackoverflow.com/questions/69715610/how-to-initialize-the-background-color-of-win32-app-to-something-other-than-whit

**Comment by goodov** [comment]
> Same problem here!
> MacOS 13.6.6 Ventura, latest version of Brave.
> Forgot to mention that this flash happens every time i switch from an active tab, to an inactive tab 

@Retriev3r can you please record a video? That would be very helpful.

I was able to reproduce and fix most issues on Windows, but I can't reproduce anything close on Mac. Maybe you have animations disabled or something else non-standard?

**Comment by MadhaviSeelam** [comment]
This issue might be related to https://github.com/brave/brave-browser/issues/26114. However, I am seeing a white background for a moment before loading custom background.  
Verified in 
```
Brave | 1.67.134 Chromium: 126.0.6478.186 (Official Build) (64-bit)
-- | --
Revision | e27c9744a0ed98bfa60e287af7e5eaffde15bd57
OS | Windows 11 Version 23H2 (Build 22631.3880)
```

https://github.com/user-attachments/assets/65072dfc-eaab-43a1-ac42-21c24485da93

**Comment by goodov** [comment]
> This issue might be related to #26114. However, I am seeing a white background for a moment before loading custom background.

That's on Windows, we do have some issues there, no doubt. I'm curious about the MacOS issues @Retriev3r mentioned. I was not able to see those myself. Do we have some cases for this platform?

**Comment by goodov** [comment]
This is a Windows-only change.

To test:
1. open `brave://flags`
2. enable `#brave-workaround-new-window-flash` flag
3. restart the browser

Follow the examples from this issue to see the original problem, expect it's no longer reproduced.

**Comment by MadhaviSeelam** [comment]
Reproduced the issue in macOS arm64 machine.  White splash is more pronounced/can be seen when opening new tabs than new launch.

@LaurenWags Please feel free to reproduce on your macOS intel machine.
```
Brave | 1.68.128 Chromium: 127.0.6533.73 (Official Build) (arm64)
-- | --
Revision | 800676fd9ede2eb4174bac98c186e53749c7201f
OS | macOS Version 13.5 (Build 22G74)
```

Uploading Screen Recording 2024-07-24 at 10.55.50 AM.mov

**Comment by bsclifton** [comment]
Fix will be in 1.70.20 and higher

**Comment by goodov** [comment]
> Reproduced the issue in macOS arm64 machine. White splash is more pronounced/can be seen when opening new tabs than new launch.

Is it also reproducible in dark mode? The issue we're fixing here is when we see a white screen in the dark mode. That's bad. But if we get a white screen in the light mode (although quickly replaced with darker NTP content), then it's not that critical.

To me the MacOS issue we're seeing here sounds more like "slow NTP content loading" which lead to showing the bare NTP background first that we (humans) interpret as splash. If possible, we should also tackle this at some point, but not sure if that's easily solvable.

**Comment by LaurenWags** [comment]
@MadhaviSeelam on macOS x64/Intel looks like I'm seeing what @goodov described via https://github.com/brave/brave-browser/issues/38214#issuecomment-2249603149.

On dark theme it's not a white screen but a dark gray one for a fraction of a second before brave://welcome or NTP loads. On light theme it's a light gray or maybe white instead of the dark gray.

```
Brave | 1.70.20 Chromium: 127.0.6533.73 (Official Build) nightly (x86_64)
-- | --
Revision | 63a9d9566501645c5defb083cba496054b532d86
OS | macOS Version 13.6.7 (Build 22G720)
```


https://github.com/user-attachments/assets/20472eb4-e9ef-4f76-bdd4-0bd124e02e65

**Comment by bastele7** [comment]
@goodov The workaround works great, thank you very much!

**Comment by EnterMan123** [comment]
Tested with Brave Nightly v1.70.26.

With the BraveWorkaroundNewWindowFlash feature enabled, things seem to be better, but the main issue still exists. More information to come later.

**Comment by MadhaviSeelam** [comment]
Quick verification is done on `1.70.26 Chromium: 127.0.6533.73` and white splash screen is not shown in dark mode. 


https://github.com/user-attachments/assets/1ee8abc7-0601-423f-8649-32f8d8bb1bd4

**Comment by Retriev3r** [comment]
> > Same problem here!
> > MacOS 13.6.6 Ventura, latest version of Brave.
> > Forgot to mention that this flash happens every time i switch from an active tab, to an inactive tab
> 
> @Retriev3r can you please record a video? That would be very helpful.
> 
> I was able to reproduce and fix most issues on Windows, but I can't reproduce anything close on Mac. Maybe you have animations disabled or something else non-standard?

I will try, but i believe I have not seen any white flashes in a while. Maybe the issues is resolved already.

**Comment by goodov** [comment]
I've noticed the white splash still exists if I minimize/restore the window. Need to look into this.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.70.92 Chromium: 128.0.6613.85 (Official Build) beta (64-bit)
-- | --
Revision | 711f50838f629ac2be4d1d9592f72adecfd3c928
OS | Windows 11 Version 23H2 (Build 22631.4112)
```

1. Installed 1.70.92
2. launched Brave
3. closed Brave and relaunched Brave via the taskbar
4. closed Brave and relaunched Brave from the desktop shortcut
5. opened new tabs 

#### Confirmed no white splash shown when opened Brave


https://github.com/user-attachments/assets/76f41e9b-1259-423b-9a86-9150e9f01144


minimized/maximized screen and with custom backgrounds

#### Confirmed no white splash shown when opened Brave


https://github.com/user-attachments/assets/76799be3-4501-40b7-a7f9-2508e6385267
