### ISSUE TITLE
Cannot remove top sites from home page

### ISSUE THREAD

**Issue by jlarne** [brave/brave-browser#3852]
## Description 

I am unable to remove any of the 'top sites' thumbnails from the homepage.  I have the option to close them, however, on clicking I receive the usual message popup "Top Site Removed".  Thumbnail stay in place, none of the additional options 'undo' or 'restore all' do anything either.

## Steps to Reproduce

   1. Attempt to remove any of the top site icons.

## Actual result:

All thumbnails remain on the page.

## Expected result:
The top sites should be able to be modified.

## Reproduces how often: 

This has been an issue through several versions

## Brave version (brave://version info)

Version 0.61.52 64bit
Windows 10 Home 64bit

**Comment by rebron** [comment]
cc: @kjozwiak to check regression range

**Comment by rebron** [comment]
cc: @cezaraugusto

**Comment by stixjohno** [comment]
I have this very same issue, I cannot remove the Topsites Icon, I have 4 of the same, so not even top site

**Comment by cezaraugusto** [comment]
not related to new changes for sure as they only landed starting 0.62.x. however we should probably have a new tab initiative to cover some top sites bugs as they exist and are annoying. I'm self-assigning this one

**Comment by cezaraugusto** [comment]
assigning @imptrx and un-assigning myself. cc @rebron I think the new mechanism for top sites in NTP re-work will eventually close this as invalid but please coordinate as needed

**Comment by mobbdeep** [comment]
I'm having this issue too.

**Comment by lee-b** [comment]
+1

**Comment by tgomes95** [comment]
I am having the same issue.

## Brave version (brave://version info)
Version 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)
macOS Mojave 10.14.6

Any progress so far?

**Comment by The-Clockmaker** [comment]
Same, should be about time it get's fixed by now no? It's been a problem for several years now, it seems to think it removed it (at least it claims so), but it doesn't actually do anything.. The whole new tab page is about as customizable as internet explorer 8 was though, it's the only big issue about brave that still might turn me away some day

**Comment by chrisB28** [comment]
Still an issue here

------

Brave | 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)
------
Revision | 8d93477bd18154c67a70a67019cb8032382c55dd-refs/branch-heads/3770@{#1160}

**Comment by stingray21** [comment]
Same issue

Version 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)
Linux (Arch)

**Comment by chrisB28** [comment]
To add to this, if I try dragging a normal (not deleted) icon to one of the icons that is meant to be removed, the page adds an exponential amount of the removed icon to the list.

Example:
- Try to remove github.com icon from new tab page. Icon is not removed.
- Drag google.com icon onto github icon.
- 100s of github icons appear on dragging over original github icon.

Same stats as my comment above.

**Comment by haserbuen** [comment]
uninstalled brave until they get it together and start fixing bugs. Worse than Mozilla!

**Comment by chrisB28** [comment]
Resolved for me after updating today!

**Comment by alexandrestein** [comment]
I'm using version: `Version 0.69.132 Chromium: 77.0.3865.90 (Build officiel) unknown (64 bits)` on Arch but the bug still there for me.

**Comment by chrisB28** [comment]
> I'm using version: `Version 0.69.132 Chromium: 77.0.3865.90 (Build officiel) unknown (64 bits)` on Arch but the bug still there for me.

I had one that was still doing it then I made sure the pin was deselected and it removed correctly

**Comment by alexandrestein** [comment]
Thank you @chrisB28.
It started with have a strange behavior after unpin every items and then it started to work as expected.

:ok_hand:

**Comment by rebron** [comment]
@cezaraugusto Should we close this one out? It looks like this is working now. I can't reproduce the issue with current release channel 69.x.

@alexandrestein Can you provide specific steps to reproduce? Just clicking 'x' on one of the top site tiles isn't removing the tile for you?

**Comment by alexandrestein** [comment]
@rebron I can't reproduce it. :worried: 
It is working normally now. :smile: 

I tried long time ago to manage top sites.
Because it was not working as I expected I followed this issue and I let them as is.

Some was pined and others not. I can't remember what was the exact status of the thing.

@chrisB28 announced that it was resolved.
I tried but it was still buggy.
@chrisB28 advised me to unpin site. I unpinned all sites and then weird things happened (reorder and blinking) before returning to a working state.

Some my case is not relevant, sorry about the noise.

**Comment by yzhernand** [comment]
I had to click "restore all" after removing a pinned top site still failed with the latest update, but it showed the message that the site had been removed. Now I have one top site pinned from one of the "restored" sites, and nothing new is being suggested.

Version 0.69.132 Chromium: 77.0.3865.90 (Official Build)
EndeavourOS (Arch Linux) 64-bit

**Comment by rebron** [comment]
Closing out this issue, doesn't look like this is an issue any longer? I'll reopen if this is still an issue for @jlarne?

@yzhernand would you mind filing a new issue? That's a separate issue from what's happening here.

**Comment by jlarne** [comment]
It seems to be working for me as well!  Thanks for the follow up!

**Comment by The-Clockmaker** [comment]
Odd, still doesn't work for me, and am on the latest build on an up to date windows 10

**Comment by rebron** [comment]
@The-Clockmaker I'm testing the same on Windows 10 with the current 69.132 release and I'm able to remove top sites. We need some more info. I'm assuming you don't have any of the tiles pinned? 

Clearing browser history does reset the Top Sites list. Not sure if that's something you can help us test.

**Comment by dodzh** [comment]
ive had this same issue for a while now also.
Version 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit)

**Comment by bsclifton** [comment]
cc: @cezaraugusto on the above report by @dodzh
