### ISSUE TITLE
Missing Passwords All Of A Sudden

### ISSUE THREAD

**Issue by harvey1344** [brave/brave-browser#40156]
### Description

- Logged in today, all my passwords are missing suddenly. Whenever I log into a site I have previously saved my password I am prompted to log in again. Synced settings work fine on mobile.
- [Password Manager](brave://password-manager/passwords) is completely blank. After importing password file from chrome it appears, only to no longer be there on close of the **the tab**.

### Steps to reproduce

Bit hard to reproduce as they just disappeared overnight.
For **imported passwords** 
1. Go to [brave password manager](brave://password-manager/passwords)
2. Go _settings_ -> _import passwords_
3. Select file from desktop
4. Close tab
5. Revisit [brave password manager](brave://password-manager/passwords) -> blank again

### Actual result

re-prompted to login and save password again.
![image](https://github.com/user-attachments/assets/13adec7e-458d-443b-9bb2-ca4789711d25)

### Expected result

password should be saved and auto filled **or** stayed logged in

### Reproduces how often

No steps to reproduce

### Brave version (brave://version info)

`Brave` : 1.68.131 Chromium: 127.0.6533.73 (Official Build) (64-bit) 
`Revision` : 8167dd98e054f33ff258260aaf64d2eba8110772
`OS` : Windows 10 Version 22H2 (Build 19045.4651)

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Extension list: (None of these are new, been installed 1~2 years)
- DuckDuckGo Privacy Essentials
- Google Scholar Button
- I don't care about cookies
- Writefull for Overleaf

History still intact.

---

Is not occurring on laptop with settings sync and identical extension list with the indentical versioning:
`Brave` : 1.68.131 Chromium: 127.0.6533.73 (Official Build) (64-bit)
`Revision` : 8167dd98e054f33ff258260aaf64d2eba8110772
`OS` : Windows 10 Version 22H2 (Build 19045.4651)

**Comment by avinassh** [comment]
happening with me too :/ 

Brave: Version 1.68.134 Chromium: 127.0.6533.88 (Official Build) (x86_64)
OS: macOS Sonoma, 14.5 (23F79)

**Comment by rebron** [comment]
@harvey1344 Can you update to the latest 1.68.134? There was a specific Windows/Chromium issue effecting passwords which was addressed in 1.68.134. 
See: https://github.com/brave/brave-browser/issues/40091

**Comment by raitzjm** [comment]
I have 1.68.134-1 installed in Fedora 40 and I am still having this same issue.

**Comment by mbuening** [comment]
I had this problem on MacOS Sonoma as well, but only for non-default profiles. After reverting to 1.67.134 all passwords were back.

**Comment by Fahl-Design** [comment]
ref https://github.com/brave/brave-browser/issues/39980#issuecomment-2255592869

same for me on Debian 12.6 with "1.68.134"

my workaround is to start the browser with a feature flag:
```shell
brave-browser --enable-features=SkipUndecryptablePasswords
```

**Comment by bsclifton** [comment]
This is a duplicate of https://github.com/brave/brave-browser/issues/33548
