### ISSUE TITLE
YouTube video settings don't work in full screen mode

### ISSUE THREAD

**Issue by codey-badger** [brave/brave-browser#40553]
### Description

Since 1.68.134 version, when watching a video or even if it's paused, YouTube video settings don't work in full screen mode. I have searched the issues and didn't find one as the curent description. 

### Steps to reproduce

1. Launch Brave on Android mobile device
2. Go to YouTube
3. Play on any video
4. Enter full screen mode 
5. Select the settings cog in the upper right corner

### Actual result

Nothin happens in full screen mode

https://github.com/user-attachments/assets/c4c585c5-9be2-4957-970a-d3c221b4a58e

### Expected result

Video settings/options

### Reproduces how often

Easily reproduced

### Brave version

1.68.134

### Device

- Brand/model: Samsung Galaxy S9
- Android version: 10

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by jonathansampson** [comment]
This appears to impact Chrome as well; just verified against version 127.0.6533.105.

**Comment by ryanbr** [comment]
My thoughts here,

> I suspect when in fullscreen, it will overwrite the settings popup. The settings popup probably does open but in the background

**Comment by jonathansampson** [comment]
I filed a Chromium issue upstream: https://issues.chromium.org/u/1/issues/361750101

**Comment by jonathansampson** [comment]
The issue also exists with Firefox 129.0.2 as well, so likely not rooted in Chromium.

**Comment by codey-badger** [comment]
Hi @jonathansampson ,

ATM I'm no longer experiencing this issue, although I would like to know what fixed it, maybe YouTube change something itself?

**Comment by jagadeshjai** [comment]
Adding a point here, I also experienced the same issue even in YouTube native Android app last week.

However, it has been fixed now 😄. So, it seems like it was a YouTube bug.

CC: @jonathansampson / @codey-badger

**Comment by Tsarass** [comment]
This issue is still ongoing in android (v 1.95.101). Also happens with Mi browser so it might be a youtube issue.
