### ISSUE TITLE
Unable to open Ads from Notification center

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#4102]
## Description 

Unable to open Ads from Notification center

## Steps to Reproduce

   1. Set Focus Assist settings to `Alarm Only`
   2. Clean profile 0.63.40
   3.  Launch brave using `C:\Program Files (x86)\BraveSoftware\Brave-Browser-Beta\Application\brave.exe --enable-logging --log-level=2 --vmodule=brave_ads=3`
   4. Enable Rewards
   5. Open brave.com
   6. Keep the page idle for 15 secs
   7. Move the cursor
   8. Verify that Ads notification is displayed under the notification center
   9. Click on the Ads notification
 

## Actual result:

Clicking on the notifications within the notification slide, just dismisses the banner without opening brave or displaying the ad.

![Ads](https://user-images.githubusercontent.com/38657976/56181476-45a7dd00-602b-11e9-8552-560f8a045442.gif)

![image (5)](https://user-images.githubusercontent.com/38657976/56124756-ffa03a00-5f94-11e9-8eef-a2722057a76f.png)

## Expected result:
The user should be able to open the Ads

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 0.63.40 Chromium: 74.0.3729.61 (Official Build) beta (64-bit)
-- | --
Revision | 5df2c8936783bd7575987e45d72a92fcf528496b-refs/branch-heads/3729@{#645}
OS | Windows 10 OS Build 17134.523

### Reproducible on current release: NA
- Does it reproduce on brave-browser dev/beta builds? Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information

The issue is reported by the community
https://community.brave.com/t/unable-to-open-ads-from-notification-area/49199/4

@brave/legacy_qa @tmancey

**Comment by GeetaSarvadnya** [comment]
https://bravesoftware.slack.com/archives/C43LW5U2H/p1555318060044600?thread_ts=1555302183.044200&cid=C43LW5U2H
Comments added in above slack thread:
using undocumented and unsupported methods it is possible to detect the status of Focus Assist. 
@tmancey is investigating the issue.

**Comment by GeetaSarvadnya** [comment]
![Ads](https://user-images.githubusercontent.com/38657976/56181423-198c5c00-602b-11e9-8a23-41e7195ad6ce.gif)

**Comment by lukemulks** [comment]
I'm running win10 x64, with Focus Assist set to `Alarms Only`, and am observing the notifications in the OS Notification Tray. 

```
Brave | 0.64.47 
Chromium: 74.0.3729.61 (Official Build) dev (64-bit)
-- | --
Revision | 5df2c8936783bd7575987e45d72a92fcf528496b-refs/branch-heads/3729@{#645}
OS | Windows 10 OS Build 17134.706
```

Including a screenshot to illustrate as well. 
![brave-sys-notifications-04162019-win10x64](https://user-images.githubusercontent.com/8979240/56223423-91a25400-6022-11e9-8fb2-3201a27729a7.JPG)

**Comment by rivy** [comment]
@lukemulks , yes, the notifications are collected in the notification tray. However, they cannot be opened. Clicking on them just dismisses them without showing any ad.

**Comment by Brave-Matt** [comment]
+1 from Community too:
https://community.brave.com/t/notification-enabled-but-not-working/49594/63

Is there any particular reason we have this set to `P4`? Windows users are having enough trouble with ads/notifications as it is -- sucks to finally get them up and running only to not be able to view the ads. @rebron

**Comment by rebron** [comment]
@Brave-Matt I didn't set priority for this issue. I'm guessing that focus assist setting isn't a default windows setting and therefore fewer users are affected. Looks like @tmancey is looking at it though.

**Comment by rivy** [comment]
Notably, the ad notification doesn't open in the browser when the notification is clicked from the action center, even if "Focus Assist" is not enabled. Clicking on the floating ad works correctly, but it seems that clicking on the ad notification from within the action center slide out is generally borked.

**Comment by Brave-Matt** [comment]
A few users in Community troubleshooting thread reporting this as well:
https://community.brave.com/t/brave-ads-windows-10-troubleshooting/56730/13

**Comment by kjozwiak** [comment]
@jsecretan should we reprioritize this to maybe a `P3`? Seems like we're getting more +1 from Win users who are running into this. Imagine we'll want to get this fixed sooner than later.

**Comment by alefnull** [comment]
i've been wondering about this since installing Brave almost a week ago or so. apparently i've missed out on about 330 ads so far, and i couldn't figure out why until i finally opened the notification center (which i basically never use) and saw all the ads, started clicking on them, and nothing happened.

**Comment by tmancey** [comment]
@alefnull @kjozwiak We have identified an issue where if an Ad notification is shown and the user quits the browser, Ads will no longer open when clicked. We are working on a fix.

**Comment by alefnull** [comment]
@tmancey i actually rarely close my browser, and most of the times that i've clicked on the notifications in the notification center, my browser has been open, and nothing would happen. however, since posting my last comment, the few that i've clicked have actually opened successfully. so i'm not sure what happened, as i haven't done anything differently on my end, but it does appear to be working for me now.

**Comment by tmancey** [comment]
@alefnull Thank you for the update

**Comment by tmancey** [comment]
User also reported clicking on arrow thinking it would open up the ad when instead it closed the ad. This is confusing UI/UX, investigate further and discuss with UX

**Comment by rivy** [comment]
Clicking the arrow to initiate "move to the notification center" is normal.

In my experience, the usual windows notification idiom with most applications is to click on the message box to open the notification or click the arrow to dismiss it to the notification center. Clicking the upper right 'X' within the notification center should completely dismiss the notification, deleting it.

All of that is working correctly.

But, when in the notification center, clicking the notification doesn't open Brave and display the ad if the ad moved directly to the notification center by "focus assist" or by clicking the arrow on the desktop panel notice to move it into the center. That's the problem this issue points out.

**Comment by tmancey** [comment]
@rivy thank you, much appreciated

**Comment by rivy** [comment]
For the last few weeks, I don't remember seeing any ads at all while in "focused" mode. I hope that's not the way you are going with this... I'd like to have the ads but see them at my desired times.

IMO, they should just be like normal notifications and pull up the ad in-browser whenever clicked upon.

**Comment by Brave-Matt** [comment]
+1 https://community.brave.com/t/brave-supported-ads-on-windows-10-not-opening/84464/2

**Comment by tmancey** [comment]
Fixed by https://github.com/brave/brave-core/pull/3084

**Comment by rivy** [comment]
What revision will this go out in?

My current version updated last night and this is still broken.

**Comment by tmancey** [comment]
@rivy This fix is currently only in Nightly, are you able to test Nightly, please? Thanks

**Comment by riswyre** [comment]
give me link download 

0.63.40 Chromium: 74.0.3729.61 (Official Build) beta (64-bit)
--

**Comment by tmancey** [comment]
@riswyre @rivy https://brave.com/download-nightly/

**Comment by riswyre** [comment]
but no ads Version 1.3.39 Chromium: 78.0.3904.108 (Official Build) nightly (32-bit)

**Comment by tmancey** [comment]
> but no ads Version 1.3.39 Chromium: 78.0.3904.108 (Official Build) nightly (32-bit)

I have just updated here and I have updated to 1.3.39. Can you please explain "but no ads"? Thanks

**Comment by riswyre** [comment]
win 10 enterprise ltsc version 1809 32 bit

**Comment by tmancey** [comment]
@riswyre Do you have group policies etc. setup to block Windows native notifications? Do you have Focus Assist enabled?

**Comment by rivy** [comment]
I've just downloaded dev v1.3.57.
I'll let you know how well it works in the next few days.

**Comment by rivy** [comment]
After a few hours, I'm seeing no ads. ☹️

**Comment by rivy** [comment]
Not fixed...
No ads being displayed...

**Comment by rivy** [comment]
@tmancey ,

Please re-open this ... it's not fixed.

Further testing...

- No ads at all with either "Focus Assist" on as either "Priority Only" or "Alarms Only".
- Ads appear and do not collapse with "Focus Assist" off.
- And when collapsed to the notification area using the upper right arrow, they appear in the notification area but do not open an add in `brave` when clicked.

The desirable behavior is ...

1. With "Focus Assist" off, Ads should appear and collapse to the notification center within a reasonably short time frame (a few seconds) ... not working.
2. If the upper right arrow of a displayed ad notice is clicked, the ad should immediately move to the notification area ... works.
3. Within the notification area, the ad should be clickable causing `brave` to display the ad (opening the application if necessary) ... not working.
4. With "Focus Assist" enabled (as either "Priority Only" or "Alarms Only", the ad should immediately load within the notification area and be clickable to open as above ... not working.

**Comment by rivy** [comment]
@tmancey , this *isn't* fixed.

**Comment by tmancey** [comment]
@rivy I will update you early next, as will discuss internally. Thank you for the above testing and input. Much appreciated. Terry

**Comment by btlechowski** [comment]
Added `OS/Windows` label.

**Comment by rivy** [comment]
@tmancey , Checking back in ... are you planning to re-open this?

**Comment by GeetaSarvadnya** [comment]
@tmancey Issue is still not fixed. I am not getting any ads when `Focus Assist` is set to `Alarm Only` - Ads are not popping up or being displayed under the notification center. Let me know if I am missing anything otherwise, I will log a follow-up issue for it.

**Comment by GeetaSarvadnya** [comment]
As discussed with @tmancey over the slack - there is a change in the behavior as we no longer show ads if notification are not enabled. Also, we won't get any ads when  `Focus Assist` is set to `Alarm Only`
The detailed test plan is provided in the PR - https://github.com/brave/brave-core/pull/3084

**Comment by rivy** [comment]
Too bad, that's unfriendly behavior for a lot of early adopters and advocates.
But it's your circus.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.3.100 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from brave/brave-core#3084
-  Verified we no longer see any ads if `Focus Assist` is set to `Alarm Only` https://github.com/brave/brave-browser/issues/4102#issuecomment-577847799

**Clean profile:**

- Ensured ad notifications are NOT shown on windows when Focus Assist is enabled
`[5016:6316:0124/124645.543:INFO:ads_impl.cc(1148)] Notification not made: Notifications not allowed`
- Ensured ad notification is shown when Focus Assist is disabled
`[4428:16072:0124/124905.285:INFO:ads_impl.cc(1305)] Ad notification shown:`

**Upgrade profile:**
(Upgrade from 1.2.43 to 1.3.100)

- Viewed ads in 1.2.43 ads collected in the notification center when focus assist is enabled --> upgrade to 1.3.100 ads are not shown in 1.3.100, Verified notifications not allowed text message in logs
`[5652:4820:0124/145717.418:INFO:ads_impl.cc(1148)] Notification not made: Notifications not allowed`
- Verified ads are shown when focus assist is disabled in an upgraded profile.
`[9440:11284:0124/150629.389:INFO:ads_impl.cc(1305)] Ad notification shown:`

**Comment by pawsey18** [comment]
Still haven't fixed this issue yet?

**Comment by tmancey** [comment]
We are moving away from native notifications to brave ad notifications. Please see our nightly build for custom ad notifications, which will soon be available in other build channels. Thank you
