### ISSUE TITLE
Crash upon going to an mdn page

### ISSUE THREAD

**Issue by jacks0n9** [brave/brave-browser#41078]
Brave Version: 1.68.134 Chromium: 127.0.6533.88
Operating System: Mac OS X 14.5.0

URL where crash occurred: https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder
Reproduction steps:
1. Go to https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder
2. Scroll down a bit
It crashes

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/cb340f00-9ce4-970c-0000-000000000000

**Comment by iefremov** [comment]
@jacks0n9 pls update the browser, it should be fixed in a newer version

**Comment by jacks0n9** [comment]
browser was already updated, still crashes, unless you're referring to a beta version?

**Comment by iefremov** [comment]
@jacks0n9 can you please upload more dumps from brave://crashes and share crash ids?

**Comment by rebron** [comment]
@jacks0n9 Are you on the latest 1.69.168?

**Comment by jacks0n9** [comment]
yeah. it's fixed. what was the problem?

**Comment by bsclifton** [comment]
@jacks0n9 the root cause was due to a behavior with the local IPFS service. That was fixed with 1.69 which removes this from Brave
