### ISSUE TITLE
Devices on the same synchronization chain continue to be duplicated

### ISSUE THREAD

**Issue by poun64** [brave/brave-browser#41196]
### Description

Devices on the same synchronization chain continue to be duplicated at my place, despite this bug having been fixed a few days ago.
Tested on 2 different PCs: one running Linux Xubuntu 22.04 and the other Xubuntu 24.04.
Both run Brave Version 1.70.117 Chromium: 129.0.6668.59 (Official Build) (64-bit).
Cookies are deleted each time the browser is closed.
In use, the two synchronized devices duplicate each other, and old duplicates have to be removed manually.

### Steps to reproduce

1. Synchronize both devices on the same channel.
2. Delete cookies each time you close the Brave browser.
3. Start, browse and stop Bave several times a day.

### Actual result

Devices are automatically duplicated in the synchronization chain and must be deleted manually on subsequent days.
Note: Only duplicates from device A are visible on device B, and vice versa.

### Expected result

Devices synchronized on the same chain should not be duplicated.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

[Version 1.70.117 Chromium: 129.0.6668.59 (Build officiel) (64 bits)](https://brave.com/latest/)
Linux Xubuntu 22.04 LTS
Linux Xubuntu 24.04 LTS

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [X] in the latest version of Chrome

### Miscellaneous information

The bug raised here: https://github.com/brave/brave-browser/issues/40130#issuecomment-2354241312 is still unresolved in my case.
Am I the only one?
Translated from the French by https://www.deepl.com/

**Comment by H2SO4JB** [comment]
Exactly the same for me, this bug is still NOT fixed. It is very easy to reproduce by simply enabling the "Delete cookies and data on exit" option. I try to enable this option every time an update is released, but so far (V1.70.117) duplicates are created as soon as it is enabled, so i have to disable it again.

I'm not sure why the dev team doesn't comment on these bug reports anymore. Can we at least get confirmation that someone is working on finding this bug? Or if no one is working on it, we'd love to know that too.

@AlexeyBarabash  ???

**Comment by plexecutor** [comment]
Can confirm. I've been dealing with this issue for the past few days across 5 devices and the quantity duplicates is getting out of hand. Not having cookies and data deleted on exit is a deal breaker for me so no way I am turning that off to fix sync.

**Comment by poun64** [comment]
Here's my feedback on Brave in Version 1.70.119 Chromium: 129.0.6668.70 (Official Build) (64 bits).
Still tested on my two different PCs: Linux Xubuntu 22.04 and Xubuntu 24.04.
**Devices are not duplicated if:**
1) cookies are not deleted when Brave is closed
2) you don't activate the “Forget me when I close this site” setting in the “Protections” menu.
**Note:** What I don't understand is that, even in this case, all cookies are deleted when Brave is closed.
You can check this at: brave://settings/content/all
![Données supprimées à la sortie](https://github.com/user-attachments/assets/106e244b-55fb-4b9f-a7be-1db60ef77150)

**Comment by pokatomnik** [comment]
Same for me, I still have two or even three devices duplicated in the sync list. It's kinda annoying, and that's why I don't rely on Brave Sync anymore. Previously, I was synchronizing my passwords, but now I can't be sure that someday synchronization won't break.

**Comment by andrewteg** [comment]
I added a new device and noticed this issue, as my desktop and laptop were listed multiple times with dates going back to July 2024.  I removed everything not October and am hoping that didn't mess up any sync devices but like @pokatomnik I'm concerned about my passwords so making a CSV backup of those now!

**Comment by fmarier** [comment]
@poun64 I see that you're running 1.70 which includes the fix for brave/brave-browser#40130.

Did you manually remove the duplicated devices after upgrading to a version of Brave with the fix? Are the duplicate entries new, or they are the old ones from before that didn't get cleaned up?

**Comment by plexecutor** [comment]
I still have this issue on v1.70.123. Brand new sync chain. Only fix is changing On-device site data to 'Allow sites to save data on your device'. Having it set to 'Delete data sites have saved on your device when you close all windows' causes duplicate entries in the sync chain.

**Comment by poun64** [comment]
**@fmarier :** 
I'm now up to Version 1.70.123 Chromium: 129.0.6668.89 (Official Build) (64 bits) which I'm testing on three of my devices.
I'm still using my September 29 settings : https://github.com/brave/brave-browser/issues/41196#issuecomment-2381382522 
Since then, none of my devices have been duplicated, and cookies are deleted when I close Brave...

**Comment by fmarier** [comment]
> Only fix is changing On-device site data to 'Allow sites to save data on your device'.

@plexecutor Where is this option? And which platform/OS are you on?

**Comment by AlexeyBarabash** [comment]
thanks @plexecutor @poun64 

I was able to reproduce the bug with settings at  brave://settings/content/siteData .

The required missing step for me was to login into GMail account, otherwise device didn't duplicate.

**Comment by AlexeyBarabash** [comment]
Also these steps reproduce the problem:

1. Add devices A and B into the sync chain
2. On device B login into GMail
3. On device B logout from GMail
4. Restart browser on Device B
5. Unexpected device B is duplicated at A's list

even without need to modify browser settings.

**Comment by H2SO4JB** [comment]
@AlexeyBarabash :
Are we still talking about the same old bug (#40130) that is claimed to be fixed that several of us are still experiencing?

I don't have a Gmail account or am logged into one on any of my devices and duplicates are still being created for me immediately when I enable the option "Cookies and other site data" under brave://settings/clearBrowserData

Or is this issue about a similar bug?

**Comment by poun64** [comment]
Yes **AlexeyBarabash**, we're still talking about the same bug. As far as I'm concerned, nothing was solved with the previous fix.
Note that I'm testing Brave on Linux distributions.
Today, one of my three tested devices (the one I use a lot) was duplicated with my settings described above.
My solution is therefore not 100% effective.
Best regards

Translated from the French by https://www.deepl.com/

**Comment by H2SO4JB** [comment]
> Is this still an issue? I have avoided using sync because of this and the broken password sync... Please can these issues be prioritised higher??

Yes, this bug is still not fixed. And as soon as someone mentions it either here or in the Brave Community, no one answers. I don't know why. If the devs don't find the bug or don't know how to fix it, it's better if they just write it so we users know, I think. This silent is very strange.

**Comment by AlexeyBarabash** [comment]
PR supposed to fix this issue is published https://github.com/brave/brave-core/pull/25971 .

**Comment by lxwulf** [comment]
So when this update is merged, would you recommend creating a new sync chain or is it enough just cleaning the faulty devices?

**Comment by scottf007** [comment]
I have experienced this issue - syncing three devices - using tab groups - so I can open my desktop and have the tabs from my laptop and vice versa. 

I have noticed that the maintaining the sync is also flaky - it used to be more solid - it seems to be more prevalent since this issue started becoming more of a thing. I can not even see the sync groups from the other device anymore, and think I will need to recreate the sync chain - but my thoughts are that they might have been linked somehow to one of the duplicate devices instead of the current one. 

I wonder if other people noticed lots of synced devices because the sync was not reliable.

**Comment by poun64** [comment]
Even if it's not perfect, the devices duplicate themselves much less often by applying my settings here: https://github.com/brave/brave-browser/issues/41196#issuecomment-2381382522
I'm now testing this with three Xubuntu Linux systems.

**Comment by AlexeyBarabash** [comment]
PR https://github.com/brave/brave-core/pull/25971 was merged and uplifted to all channels.

Currently fix is available at Nightly and Beta, and will be available at Release channel with the next hotfix:

Nightly - Released in [v1.73.25](https://github.com/brave/brave-browser/releases/tag/v1.73.25) // current actual is `1.73.25`
Beta - Released in [v1.72.84](https://github.com/brave/brave-browser/releases/tag/v1.72.84) // current actual is `1.72.85`
Release - Released in [v1.71.116](https://github.com/brave/brave-browser/releases/tag/v1.71.116) // current actual is `1.71.114`

I hope this will fix the issue.

@lxwulf 
>So when this update is merged, would you recommend creating a new sync chain or is it enough just cleaning the faulty devices?

I would recommend just to clean the duplicated devices, should be enough.

**Comment by poun64** [comment]
Hello everyone!

Last night, Brave was updated in Version 1.71.118 Chromium 130.0.6723.70 (Official Build) (64 bits) on my Linux devices.

It includes the patch : Fixed certain cases where synced devices could be duplicated on the sync chain. ([#41615](https://github.com/brave/brave-browser/issues/41615)).

I'm testing this latest version by deleting my cookies when I close the browser.
I'll give you the result...

Best regards

**Comment by H2SO4JB** [comment]
I dare say that the bug is now finally gone. It was very easy to recreate the bug and get duplicates created before, but now I've been testing for two days and no duplicates have been created yet.

**Comment by poun64** [comment]
Indeed, this bug seems to have been solved for me too.
Since this latest update, my devices no longer duplicate each other.
Thanks to all you developers and contributors.
Best regards

**Comment by snowbound** [comment]
Not seeing any further duplicates in 4 days so hopefully it is fixed.

**Comment by sramekmichal** [comment]
Still can see some duplicates. 

I always delete the old ones and keep the latest.

**Comment by hugues999** [comment]
Same, I'm still getting duplicates in my `Tabs from other devices` list, it doesn't seem to be fully fixed.
It seems to start happening quickly once I sync 3 devices. They are all running the latest Brave that includes the fix (1.71.118), with one 1 on Windows and 2 on Android (phone and tablet).

**Comment by poun64** [comment]
good evening everyone!

Having found no problems on my Linux distributions, I've just added two more devices to my synchronization chain. One is running Windows 10, the other Windows 11.

That makes 7 devices on the same chain.

I'll let you know if duplicates are still being created...

**Comment by AlexeyBarabash** [comment]
> Still can see some duplicates.
> 
> I always delete the old ones and keep the latest.

Hi @sramekmichal , what is the version of Brave on the device which gets duplicated? And what OS does it run?

**Comment by AlexeyBarabash** [comment]
> Same, I'm still getting duplicates in my `Tabs from other devices` list, it doesn't seem to be fully fixed. It seems to start happening quickly once I sync 3 devices. They are all running the latest Brave that includes the fix (1.71.118), with one 1 on Windows and 2 on Android (phone and tablet).

@hugues999 , thanks for the feedback. Can you see new duplicates at sync devices list? - `brave://settings/braveSync/setup` url if on Desktop

**Comment by hugues999** [comment]
> > Same, I'm still getting duplicates in my `Tabs from other devices` list, it doesn't seem to be fully fixed. It seems to start happening quickly once I sync 3 devices. They are all running the latest Brave that includes the fix (1.71.118), with one 1 on Windows and 2 on Android (phone and tablet).
> 
> [@hugues999](https://github.com/hugues999) , thanks for the feedback. Can you see new duplicates at sync devices list? - `brave://settings/braveSync/setup` url if on Desktop

I have since created a new sync chain, and of course the duplicates have not appeared anymore in the last 2 days, now that I need to reproduce it 😆 . I'll let you know if it ever happens again, thanks!

**Comment by poun64** [comment]
Hello everyone,

I've been testing Brave on Linux and Windows for ten days now, and none of my devices have been doubled.
I consider that this problem has been solved.

Many thanks to the developers and contributors for their involvement.

Best regards

**Comment by hugues999** [comment]
Same, I have not gotten any duplicate devices since my earlier post. Looks like recreating my sync chain did the trick.
Thanks!

**Comment by lxwulf** [comment]
I can also confirm that the last update(s) fixed this issue.

Also from my side, many thanks to the developers and contributors which helped to fix this. 🚀 🤝

**Comment by AlexeyBarabash** [comment]
It seems the issue can be closed as fixed with https://github.com/brave/brave-core/pull/25971
