### ISSUE TITLE
Prev / Next button control in Playlist is very difficult to use and imprecise

### ISSUE THREAD

**Issue by nnathan** [brave/brave-browser#42474]
### Description

Prior to version 1.71 (125) as far as I can remember, the prev / next button controls on my wireless headphones or in CarPlay via my car would only require a single tap to go prev / next.

Things have since changed. Now you need to hold the button to go prev / next, and that doesn't just go to the adjacent prev / next track, but if held down too long it starts furiously skipping tracks. Therefore it's hard to go to the adjacent prev / next track, because it requires precise timing that is difficult to achieve.

Please restore the old control mechanism as that worked mostly fine, or only have the prev/next button when held only go back or forth at most 1 track.

### Steps to reproduce

N/A

### Actual result

N/A

### Expected result

N/A

### Reproduces how often

Easily reproduced

### Brave version

Brave iOS 1.71 (125)

### Device/iOS version

iPhone 16 Pro / iOS 18.1.1
Hyundai i20N for CarPlay
Sony WH1000-XM3 for wireless headphones

### Affected browser versions

- [x] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kylehickinson** [comment]
Hi @nnathan this was a bug, its been fixed here: https://github.com/brave/brave-browser/issues/42370

**Comment by nnathan** [comment]
Had this made it to brave iOS 1.73 (97)? This issue persists in both CarPlay & using my Sony wireless headset controls.
