### ISSUE TITLE
Cannot log into Instagram in Brave

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#42993]
### Description

When trying to login to Instagram using the username/password fields, the browser tells you the password you've entered is incorrect, even when it is entered accurately. Note that when testing, logging in with other browsers worked without any issue.

Logging into Instagram in Brave:

https://github.com/user-attachments/assets/a9969b39-1bc6-406e-9183-06e473300334

Logging into Instagram in Safari:

https://github.com/user-attachments/assets/22f85a9c-dbf9-4e9b-9083-0b2fc6addd89

### Steps to reproduce

1. Launch Brave
2. Try logging into Instagram.com using username/password fields

### Actual result

Browser says password is incorrect

### Expected result

Should login normally 

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Always

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Initial user report:
https://community.brave.com/t/instagram-cannot-log-in-with-brave-browser/587215

**Comment by Brave-Matt** [comment]
+1: https://community.brave.com/t/cant-login-to-instagram-even-though-the-password-is-correct/587618/3

**Comment by Brave-Matt** [comment]
+1 https://community.brave.com/t/instagram-cannot-log-in-with-brave-browser/587215/4?u=mattches

**Comment by MickCue** [comment]
Same issue, Brave Version 1.73.101 on Manjaro.

**Comment by sayan-1210** [comment]
Same issue thanks for reporting

**Comment by Shvwy** [comment]
I have same problem, any solved?

**Comment by rozmanbalazs** [comment]
same issue

**Comment by Achu1009** [comment]
same issue

**Comment by hijassageer** [comment]
same issue

**Comment by KomohanaMakani** [comment]
same issue

**Comment by ryanbr** [comment]
Try change the shields settings, possibly a fingerprint setting may need to be disabled? I couldn't repo

**Comment by banoris** [comment]
Faced the same issue. As a workaround - in Developer Tools, emulate mobile (right click > Inspect > near top left, click the "Toggle device emulation" button ).

**Comment by ryanbr** [comment]
disable any VPN also, in the case of instagram checking location/anti-fraud.

**Comment by PapiiPepe** [comment]
I managed to log in by clearing my cookies and cache via [brave://settings/content/all](url)

Once done, reload Instagram and log in to your account. (Clearing your cache must be done every time you need to log in again).

**Comment by ryanbr** [comment]
Also saw in Chrome;

![Image](https://github.com/user-attachments/assets/cef4918f-e178-48c3-a7e7-5975d7f811cf)

**Comment by Unnamed10110** [comment]
Both, clearing chace and updating didn't work.

**Comment by LocosMocos** [comment]
Same issue and it's still exist.

**Comment by sainttttt** [comment]
> I managed to log in by clearing my cookies and cache via [brave://settings/content/all](url)
> 
> Once done, reload Instagram and log in to your account. (Clearing your cache must be done every time you need to log in again).

Clearing everything in [brave://settings/content/all](url) worked for me too

**Comment by LocosMocos** [comment]
> > I managed to log in by clearing my cookies and cache via [brave://settings/content/all](url)
> > Once done, reload Instagram and log in to your account. (Clearing your cache must be done every time you need to log in again).
> 
> Clearing everything in [brave://settings/content/all](url) worked for me too
I've tried it twice and the same result can't entry to instagram.

**Comment by sainttttt** [comment]
> > > I managed to log in by clearing my cookies and cache via [brave://settings/content/all](url)
> > > Once done, reload Instagram and log in to your account. (Clearing your cache must be done every time you need to log in again).
> > 
> > 
> > Clearing everything in [brave://settings/content/all](url) worked for me too
> > I've tried it twice and the same result can't entry to instagram.

I also disabled shields and disabled uBlock Origin. That might help.

**Comment by LocosMocos** [comment]
> > > > I managed to log in by clearing my cookies and cache via [brave://settings/content/all](url)
> > > > Once done, reload Instagram and log in to your account. (Clearing your cache must be done every time you need to log in again).
> > > 
> > > 
> > > Clearing everything in [brave://settings/content/all](url) worked for me too
> > > I've tried it twice and the same result can't entry to instagram.
> 
> I also disabled shields and disabled uBlock Origin. That might help.

I do the same and it doesn't work.
Brave is shit.

**Comment by rozmanbalazs** [comment]
> > > > > I managed to log in by clearing my cookies and cache via [brave://settings/content/all](url)
> > > > > Once done, reload Instagram and log in to your account. (Clearing your cache must be done every time you need to log in again).
> > > > 
> > > > 
> > > > Clearing everything in [brave://settings/content/all](url) worked for me too
> > > > I've tried it twice and the same result can't entry to instagram.
> > 
> > 
> > I also disabled shields and disabled uBlock Origin. That might help.
> 
> I do the same and it doesn't work. Brave is shit.

my solution was to swap to firefox. 😎

**Comment by LocosMocos** [comment]
> > > > > > I managed to log in by clearing my cookies and cache via [brave://settings/content/all](url)
> > > > > > Once done, reload Instagram and log in to your account. (Clearing your cache must be done every time you need to log in again).
> > > > > 
> > > > > 
> > > > > Clearing everything in [brave://settings/content/all](url) worked for me too
> > > > > I've tried it twice and the same result can't entry to instagram.
> > > 
> > > 
> > > I also disabled shields and disabled uBlock Origin. That might help.
> > 
> > 
> > I do the same and it doesn't work. Brave is shit.
> 
> my solution was to swap to firefox. 😎

I made this and I'm pleased with that

**Comment by maprangsoft** [comment]
for me right click > Inspect > Application
click "Clear site data" button and login again work for me.

<img width="619" alt="Image" src="https://github.com/user-attachments/assets/7629108d-bff7-481a-b695-027ee91a2a40" />

**Comment by LocosMocos** [comment]
> for me right click > Inspect > Application click "Clear site data" button and login again work for me.
> 
> <img alt="Image" width="619" src="https://private-user-images.githubusercontent.com/25447955/399185395-7629108d-bff7-481a-b695-027ee91a2a40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1MTEyMjMsIm5iZiI6MTczNTUxMDkyMywicGF0aCI6Ii8yNTQ0Nzk1NS8zOTkxODUzOTUtNzYyOTEwOGQtYmZmNy00ODFhLWI2OTUtMDI3ZWU5MWEyYTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI5VDIyMjIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiYjNmZGQ0OGFmYWEwMjJjM2UwYTQxM2VhMzA0MGI0MmMyYjMzZTJkZDMyNzY1Nzk2NjQzZmJlYmFiZmYxMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HbWYF5gLq2CqHHbB8HEDjXFk2btSzLXT5j2-DYnHq9c">

I did that and still nothing.
I reinstalled and the problem still occurs. In my opinion, it is a bigger problem that appeared a few days ago

**Comment by alperencapar** [comment]
When input deliberately filled with wrong password API returns:
```
{
    "user": true,
    "authenticated": false,
    "error_type": "UserInvalidCredentials",
    "status": "ok"
}
```

When input filled with correct password API returns:
```
{
    "user": true,
    "authenticated": false,
    "error_type": "FakeIncorrectPassword",
    "status": "ok"
}
```

Well, `FakeIncorrectPassword` says all. Other browsers work fine in my tests

**Comment by AbdulSamadMalik** [comment]
> for me right click > Inspect > Application click "Clear site data" button and login again work for me.
> 
> <img alt="Image" width="619" src="https://private-user-images.githubusercontent.com/25447955/399185395-7629108d-bff7-481a-b695-027ee91a2a40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NjI0MzQsIm5iZiI6MTczNTU2MjEzNCwicGF0aCI6Ii8yNTQ0Nzk1NS8zOTkxODUzOTUtNzYyOTEwOGQtYmZmNy00ODFhLWI2OTUtMDI3ZWU5MWEyYTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDEyMzUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwMGQwMmU5YTU4YWRmZjIzMTE3ZjYwOThlM2U4ZmE5NWQ0ZjllZGUwZTRkY2IyYTQ5ZTBlYjNhNWNlYThhNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._b1QAEswP8M-Iv7EEorKXeXs5G4SbYvghLBrxZO-Iy0">

Thanks worked for me

**Comment by AbdulSamadMalik** [comment]
@maprangsoft thanks, clearing site data from Application Tab worked for me

**Comment by banoris** [comment]
Able to reproduce the same issue in both Chrome and Edge. Perhaps the aggressive adblocker / Ublock Origin is causing this.

(Clarifying my previous comment) As a workaround, open Developer Tools (right click > Inspect), emulate mobile button (see snapshot), and fill your credentials. Once logged in, close the developer console (or just open another tab, it will be the normal desktop mode, not mobile browser mode).

This works 100% for me, no need to disable ad blocker, clear cache, etc. Tested on Edge and Brave, both with aggressive adblocker settings.

![Image](https://github.com/user-attachments/assets/24ff046f-47a3-46f5-8c3a-de375f6b69be)

**Comment by slaughter3000** [comment]
NONE of the solutions described above work for me.  None. None, none, none. Waste of time.
What the heck is up with Brave - this is a diabolical issue that I'm sure has seen many of us wasting hours wondering if we are going crazy or not.  Is it time to ditch this browser?

**Comment by Unnamed10110** [comment]
I restarted and cleared cleared site data from inspector and it worked.
Still don't understand the reason, but it worked.

**Comment by slaughter3000** [comment]
Nope.  That does NOT work.

**Comment by Drexaltation** [comment]
> Able to reproduce the same issue in both Chrome and Edge. Perhaps the aggressive adblocker / Ublock Origin is causing this.
> 
> (Clarifying my previous comment) As a workaround, open Developer Tools (right click > Inspect), emulate mobile button (see snapshot), and fill your credentials. Once logged in, close the developer console (or just open another tab, it will be the normal desktop mode, not mobile browser mode).
> 
> This works 100% for me, no need to disable ad blocker, clear cache, etc. Tested on Edge and Brave, both with aggressive adblocker settings.
> 
> ![Image](https://github.com/user-attachments/assets/24ff046f-47a3-46f5-8c3a-de375f6b69be)

Only method that worked for me so far

**Comment by Gfauf** [comment]
> for me right click > Inspect > Application click "Clear site data" button and login again work for me.
> 
> <img alt="Image" width="619" src="https://private-user-images.githubusercontent.com/25447955/399185395-7629108d-bff7-481a-b695-027ee91a2a40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwMTk5ODUsIm5iZiI6MTczNjAxOTY4NSwicGF0aCI6Ii8yNTQ0Nzk1NS8zOTkxODUzOTUtNzYyOTEwOGQtYmZmNy00ODFhLWI2OTUtMDI3ZWU5MWEyYTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA0VDE5NDEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyM2JiMTlmZjJjMTc4YzViNTZjZGNmNGU0ZDQ0YTFhMWIyNjM5Nzc3OWE0MDQ5ZDg4YjBlMjhhMjdhMTNkOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7CADK-2PRiuXERlnaoJ_gkHq1dhOaBK3ynWzykKZijQ">

Thanks! This fixed it for me, but still, this  an horrendous issue and it makes me thing something else is going on there

**Comment by slaughter3000** [comment]
> > for me right click > Inspect > Application click "Clear site data" button and login again work for me.
> > <img alt="Image" width="619" src="https://private-user-images.githubusercontent.com/25447955/399185395-7629108d-bff7-481a-b695-027ee91a2a40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwMTk5ODUsIm5iZiI6MTczNjAxOTY4NSwicGF0aCI6Ii8yNTQ0Nzk1NS8zOTkxODUzOTUtNzYyOTEwOGQtYmZmNy00ODFhLWI2OTUtMDI3ZWU5MWEyYTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA0VDE5NDEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyM2JiMTlmZjJjMTc4YzViNTZjZGNmNGU0ZDQ0YTFhMWIyNjM5Nzc3OWE0MDQ5ZDg4YjBlMjhhMjdhMTNkOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7CADK-2PRiuXERlnaoJ_gkHq1dhOaBK3ynWzykKZijQ">
> 
> Thanks! This fixed it for me, but still, this an horrendous issue and it makes me thing something else is going on there

This has been repeatedly claimed as a solution, but again, it is *not*.  Doesn't work for me, and I assume many of us are still stuck.  I think it's time to dump Brave TBH...

**Comment by Unnamed10110** [comment]
> > > for me right click > Inspect > Application click "Clear site data" button and login again work for me.
> > > <img alt="Image" width="619" src="https://private-user-images.githubusercontent.com/25447955/399185395-7629108d-bff7-481a-b695-027ee91a2a40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwMTk5ODUsIm5iZiI6MTczNjAxOTY4NSwicGF0aCI6Ii8yNTQ0Nzk1NS8zOTkxODUzOTUtNzYyOTEwOGQtYmZmNy00ODFhLWI2OTUtMDI3ZWU5MWEyYTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA0VDE5NDEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyM2JiMTlmZjJjMTc4YzViNTZjZGNmNGU0ZDQ0YTFhMWIyNjM5Nzc3OWE0MDQ5ZDg4YjBlMjhhMjdhMTNkOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7CADK-2PRiuXERlnaoJ_gkHq1dhOaBK3ynWzykKZijQ">
> > 
> > 
> > Thanks! This fixed it for me, but still, this an horrendous issue and it makes me thing something else is going on there
> 
> This has been repeatedly claimed as a solution, but again, it is _not_. Doesn't work for me, and I assume many of us are still stuck. I think it's time to dump Brave TBH...

That could be the case, but I haven't found another browser with similar features to brave, and compatible with the many extensions out there for chromium based browser.
Anyone can recommend a few they know?

**Comment by MickCue** [comment]
Resetting the password is the only workaround for me. Also, before resetting my password, I tried logging in using Chrome, same error as Brave.

**Comment by Zeltrax** [comment]
Same issue for me, just moved from chrome to brave and I don't have this issue on any other browser except brave.

**Comment by 90renrocraftcracksblogspotcom** [comment]
Same issue for me on this browser. Tested on private doesn't work at all for me.
RIP can't even dm my gf anymore on PC :(

**Comment by ShivanKaul** [comment]
Looking into this

**Comment by ShivanKaul** [comment]
I'm able to fix the issue by adding a custom filter rule to remove the `ig_did` cookie for instagram.com

```bash
instagram.com##+js(remove-cookie, ig_did)
```

Specifically, it looks like the `ig_did` with value `5443AF77-1A68-4603-BF65-43BB5F664A80` was the issue.

**Comment by ryanbr** [comment]
Anyone having issues; update the lists via `brave://settings/shields/filters`  Then refresh instagram webpage.

Then sign-in normally.

**Comment by ShivanKaul** [comment]
Are we all good here?

**Comment by ShivanKaul** [comment]
Perfect, that's what we like to hear :)

**Comment by GilmarBnp** [comment]
I fixed this issue changing the username in edit profile, Personal details, username, in another browser when i can login, next im logged normally in brave browser using my new username.

**Comment by 101rakibulhasan** [comment]
Yeah, sorry to say none of the steps working for me.... I can not log in to instagram from brave but every other browser works fine

**Comment by mattc0m** [comment]
This is not fixed. Can't login to Instagram with Brave. Firefox works fine.
