### ISSUE TITLE
[Android] Error exporting bookmarks on latest version (Export failed)

### ISSUE THREAD

**Issue by system-32x** [brave/brave-browser#43443]
### Description

there's a bug in latest version 1.74.48 on android 10. the export bookmark feature is not working .see screenshot 

![Image](https://github.com/user-attachments/assets/9169cc41-6d2b-4fd3-b780-d65fed71da56)

### Steps to reproduce

1. go to bookmarks 
2. click on the 3 dots
3. click on export 

### Actual result

error "failed to export bookmark. try again"

![Image](https://github.com/user-attachments/assets/d0563c4f-f966-465d-b8eb-6f2ea6a54467)

### Expected result

export all bookmarks to html file

### Reproduces how often
every time 

### Brave version

1.74.48 

### Device

- Brand/model: samsung galaxy m20 sm-m205f 
- Android version: android 10 

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [x] with Brave Rewards disabled
- [x] in the latest version of Chrome

**Comment by tathastu871** [comment]
been for over year no one doing nothing
sucks as a browser,
after unresponsive dev behaviour i closed all those issued related to this, they never gonna do, just keeps adding ai crypto etc making brave slower and worst of all browsers day by day

**Comment by tathastu871** [comment]
been telling dev to add featire to select all bookmarks in one go
if brave allows sleecting all bookmarks at once, then we can open all of them in private tab (or regular), then select all tabs and share copy all urls

But they are very reluctant, just bunch of

**Comment by bsclifton** [comment]
@system-32x is this still an issue for you? I can confirm it's working good for me with simple bookmarks (I have over 1000 on my Pixel 8).

If it's still broken for you- I am curious if you have something like bookmarklets which could have an issue. 
You might look at the bookmarks you have - see if they have any inline JavaScript in them.  Maybe the bug is with exporting these

Please let us know!

**Comment by GuySartorelli** [comment]
I've also got this problem

**Comment by GuySartorelli** [comment]
My workaround was to sync to desktop, and export from there.

**Comment by tathastu871** [comment]
just dont use bookmark and dont exepct it to be solved
brave devs are more invested in how to  make  browser suck more, by adding vpn crypto ai which most user dont need

**Comment by dftf-stu** [comment]
@bsclifton: I don't get an error, unlike the OP, but "Export bookmarks" currently does nothing.

On my Android 12 device, I have tried each of the following:
- Brave (Release): 1.79.123
- Brave (Beta): 1.80.108
- Brave (Nightly): 1.81.86

And with each one, when I go into the Bookmarks screen and do "Export bookmarks", nothing happens.

Steps I did shown here (using Brave Nightly, which was a clean-install):

![Image](https://github.com/user-attachments/assets/da1800e9-75c9-4c37-a015-f2a731b5bbe4)


In the final screenshot (bottom-right) nothing happens: there is no error, but no file is getting exported.

Oddly, if I go to "Import bookmarks" that _does_ work and opens a file chooser window asking me to pick the file.
When I select an older export I've done previously, Brave (Beta) or Brave (Nightly) both successfully do the import.

It seems export has become broken in older versions of Android in a recent Brave release.

A user called "user-ua" claims it is working fine for them in the current "Release" version, on the newer Android 15:
[Bookmark export issue](https://community.brave.com/t/bookmark-export-issue/617526)
[Issue : Exporting Bookmarks got failed](https://community.brave.com/t/issue-exporting-bookmarks-got-failed/625830)

**Comment by bsclifton** [comment]
Also see notes in https://github.com/brave/brave-browser/issues/46386

**Comment by Gittyperson** [comment]
I confirm this issue. Must be around a month, or a bit more. Android 12, Realme 7 Pro.

No error message, but nothing happens. Import works, or at least the "pick file" prompt appears (haven't recently tested an actual import).

Please fix this important issue. Using latest Brave from the Play Store.

**Comment by dftf-stu** [comment]
Update: 23 June 2025

Still an issue on my Android 12 device, as of the latest version of each branch:
- Brave (Release): 1.79.126
- Brave (Beta): 1.81.97
- Brave (Nightly): 1.82.4

**Comment by Gittyperson** [comment]
And it still fails with today's update. Nothing happens.

Brave 1.80.115, Chromium 138.0.7204.97
Android 12; Build/SKQ1.210216.001

**Comment by dftf-stu** [comment]
Update: 11 July 2025

Still an issue on my Android 12 device, as of the latest version of each branch:

Brave (Release): 1.80.115
Brave (Beta): 1.81.112
Brave (Nightly): 1.82.71

**Comment by dftf-stu** [comment]
@SergeyZhukovsky: appreciate there is likely _loads_ of other-stuff you're working on... but is there any rough-idea when this might start to get looked-into?

The feature to export bookmarks to a local file is literally one of the main-reasons I use Brave as my main browser, as all-other ones (such as Google Chrome, Edge, Firefox, Opera and Vivaldi) require an account to do this.  With this now broken, it gives me less of a reason to stick with Brave (given Opera and Vivaldi also have built-in ad-blocking, and uBO can be added to Firefox for Android).

If I were to guess, I'd imagine that Brave used to request "All files" access, but since Google recently got more-strict around which apps can ask for that, you now ask for "Media only", which is breaking the export feature on older versions of Android.  As a possible workaround, could the local .html file that the export creates perhaps get trigged as a file-download, to save it that-way?

**Comment by Gittyperson** [comment]
This does seem like a Files permissions issue. Very recently, another excellent non-browser app started having file access issues on Android 12, and here's what I see in common with Brave:

Press and hold the Brave icon, and pick Permissions/Files and Media. The all-important "Allow management of all files" option is gone. There's only "Don't allow" and "Allow access to media only". I assume the latter is not enough for Brave to function properly.

edit: Oh, dftf-stu above mentioned the same thing.

**Comment by dftf-stu** [comment]
Latest report on the Brave Community site:
[https://community.brave.com/t/impossible-to-export-bookmarks-in-brave-browser-for-android/632033](https://community.brave.com/t/impossible-to-export-bookmarks-in-brave-browser-for-android/632033)

User running Brave (stable) v1.80.115 on Android 11

**Comment by Brave-Matt** [comment]
cc @SergeyZhukovsky seeing more users report this -- any chance we can get another pass here?

**Comment by dftf-stu** [comment]
Some reports from r/Brave on Reddit, also:

2025-May-12 -- [Can't export bookmarks(Android)](https://www.reddit.com/r/brave/comments/1kkj6gs/cant_export_bookmarksandroid/)

2024-May-12 -- [Bookmark export failing in Android](https://www.reddit.com/r/brave/comments/1cq40fi/bookmark_export_failing_in_android/)

**Comment by dftf-stu** [comment]
And some from r/Brave_Browser on Reddit too:

2025-July-07 -- [How to Export Bookmarks When Brave Won't Open](https://www.reddit.com/r/brave_browser/comments/1fes65n/comment/n1u1pog/) -- refer to selected comment

2025-June-25 -- [The export bookmark option not working in brave browser on android](https://www.reddit.com/r/brave_browser/comments/1ljz2ra/the_export_bookmark_option_not_working_in_brave/)

2024-Oct-23 -- [Android bookmark export not working](https://www.reddit.com/r/brave_browser/comments/1gamkvr/android_bookmark_export_not_working/)

2024-May-25 -- [bookmarks won't export, 'export bookmarks' page hangs](https://www.reddit.com/r/brave_browser/comments/1d0czjc/bookmarks_wont_export_export_bookmarks_page_hangs/) -- unclear if desktop or mobile

**Comment by Rahul-C50** [comment]
Yes, I guess you are right it's google (android), facing same issues in WhatsApp, Brave & Other many Apps facing same issue (where I can pick even using any other gallery or files app by clicking on 3 dots, but now only media by google files showing).

Because of Media Only instead Files and Media.

**Comment by Gittyperson** [comment]
In short, Google has messed everything up and it's up to app developers to fix their mess.

**Comment by dftf-stu** [comment]
@Gittyperson: true, but it's still on the Brave team to keep-aware of such changes, and update their app to mitigate them.

According to [APK Mirror](https://www.apkmirror.com/apk/brave-software/brave-browser/brave-private-web-browser-vpn-1-80-115-release/), the current version of Brave (stable) in the Play Store, v1.80.115, supports back-to Android 8.0 "Oreo" from 2017, so the team needs to test on the oldest OS they're supporting.  I'd hazard-a-guess that as a tech-focused company, virtually-all the staff there have very-new iPhones and Androids, so this bug was likely missed? 🤔

In the Brave Community forum, a user on Android 15 claimed when they tested, the export worked-fine.  On this ticket, user reports confirm at-least Android 10, 11 and 12 all have this issue.  I'd guess maybe html files _are_ classed as "Media" in newer versions, which is why on that user's Android 15 it did ask where to save the file?

Hopefully the Brave team can find a way to sort it, as being able to back-up bookmarks without needing to sign into the app with an account (unlike literally every-other browser) was a major selling-point for me 🙏🏻

**Comment by dftf-stu** [comment]
User ShnikeJSB on ticket [617526](https://community.brave.com/t/bookmark-export-issue/617526/6) on the Brave Community forum says on their Android 15 device, exporting bookmarks works fine in Brave (stable) v1.80.115

This backs-up what user-ua [said](https://community.brave.com/t/bookmark-export-issue/617526/2) earlier, where they tested Brave (stable) v1.79.119 on their Android 15 and also had no issue

**Comment by SergeyZhukovsky** [comment]
sorry for the silence, I was out for the past 2 weeks, going to work on that. So far I don't have a real Android 12 device, but I have Android 9 where it works ok and an emulator on Android 12 exports fine to me. But going to look on that further. I will do an extra error reporting in the worst case if can't replicate.

**Comment by dftf-stu** [comment]
Hey @SergeyZhukovsky  , no problem.  Glad it's getting looked-into now. 👍🏻

I'm sure some of us affected can test for you, on our devices.  Given I'd expect the fixes will be pushed to the nightly channel first, then I can remove or reset that as required, as I have no actual data in it, or the "beta" release.  I usually only use the "stable" one.

As of now, Brave (stable), v1.80.115, Brave (beta), v1.81.115 and Brave (nightly), v1.82.79 all have this issue.

When a fix gets pushed to the nightly channel, leave a comment here and I can check if the "export" feature now works.

**Comment by SergeyZhukovsky** [comment]
I created a separate issue to track down the problem with no dialog appearing problem as the original issue was about an error on exporting https://github.com/brave/brave-browser/issues/47721. The fix is merged to master and will be uplifted to the stable channel. @system-32x let me know if you still experience that error dialog on export.

**Comment by SergeyZhukovsky** [comment]
@gsxgmpkt9020 @0xkept @Gittyperson @Rahul-C50 @GuySartorelli the issue with a silent fail is fixed and available on beta and nightly channel per https://github.com/brave/brave-browser/issues/47721#issuecomment-3102838150. Stable channel is going to have a fix in `1.80.123` and higher.

**Comment by hffvld** [comment]
This issue is still reproducible on `Android 10` devices in all branches (RC, Beta and Nightly).

Error `Permission denied (13)` is seen via logcat when trying to export bookmarks.
```
Device/OS: 
- Pixel 2 XL / taimen-user 10 QP1A.190711.020 release-keys
- Pixel 4 XL / coral-user 10 QQ3A.200805.001 release-keys
Brave build: 1.80.123
Chromium: 138.0.7204.157 (Official Build) (64-bit)
```
-----------------------
| 1 | 2 | 3 | 4 |
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/1ff8bf10-ff27-4136-927c-1d488397df4e) | ![2](https://github.com/user-attachments/assets/da475121-e266-4bb0-8ac8-ce41649da61c) | ![3](https://github.com/user-attachments/assets/08c553f2-f6e1-40fb-871c-1e040a936add) | ![4](https://github.com/user-attachments/assets/8cf05e72-eb72-425f-af00-046e63b2ffa6) |

https://github.com/user-attachments/assets/f8e23d43-84c2-4ca6-8e3b-791e2efd6c78

cc @SergeyZhukovsky

**Comment by SergeyZhukovsky** [comment]
awesome, thanks @hffvld! I'm going to take a look on Android 10.

**Comment by kjozwiak** [comment]
The above requires `1.80.125` or higher for `1.80.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 2 XL`, `Moto G Power 5G` and `Pixel 7` using version(s):
```
Device/OS: 
- Pixel 2 XL / taimen-user 10 QP1A.190711.020 release-keys
- Moto g Power 5G - 2023 / devonn_g_sys-user 14 U1TOS34.1-157-5-4 release-keys
- Pixel 7 / panther_beta-user 16 BP31.250610.004 release-keys
Brave build: 1.81.125
Chromium: 139.0.7258.52 (Official Build) beta (64-bit) 
```
---------------------------


**STEPS:**
1. Launch Brave
2. Save a few tabs to bookmarks
3. Open `Bookmark` tab
4. Export bookmarks > *Verify*

**ACTUAL RESULTS:**
- Verified that `Bookmarks` can be exported successfully on `Android 10` and `Android 13+`.
- Verified that exported bookmarks can be `imported` successfully.

---------------------------

`Android 10`

| 1 | 2 | 3 | 4 |
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/5d03b447-d465-4607-8ee4-316e6b8d5698) | ![2](https://github.com/user-attachments/assets/2b461c47-908c-4a2e-9704-1b29f13766bf) | ![3](https://github.com/user-attachments/assets/3771c00c-92a9-474a-90cf-2f9790898acf) | ![4](https://github.com/user-attachments/assets/78bac591-b999-4159-89f3-7588951f6dd8) |

`Android 14`

| 1 | 2 | 3 |
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/5ef86801-cae4-46ea-ba13-470e9983cba7) | ![2](https://github.com/user-attachments/assets/0b1c3cd4-7d65-4778-aa09-f889ba66baf6) | ![3](https://github.com/user-attachments/assets/d14fb3d7-b019-4d8c-a787-7617f828a9fb) |

`Android 16`

| 1 | 2 | 3 |
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/388f31b4-0a61-43b0-b067-e97d753d3413) | ![2](https://github.com/user-attachments/assets/d303be2d-b98f-4b76-a429-964cf2f5ce54) | ![3](https://github.com/user-attachments/assets/6f9e44b8-6f2e-4d51-aec6-5c10ef0f2be7) |

**Comment by Rahul-C50** [comment]
@hffvld Even working in Android 12 (Realme 9 4g)

**Comment by kjozwiak** [comment]
Removed the `QA Pass` label as the above will need to be verified using `1.80.x` as it was uplifted as per https://github.com/brave/brave-browser/issues/43443#event-2846216053. Will require `1.80.125` as per https://github.com/brave/brave-browser/issues/43443#issuecomment-3129129324.

**Comment by kjozwiak** [comment]
Re-adding the `QA Pass` label as the above was reverted from `1.80.x` via https://github.com/brave/brave-core/pull/30361 as it was failing builds. We'll leave the above in `1.81.x` which was already tested/verified as per https://github.com/brave/brave-browser/issues/43443#issuecomment-3133439353.
