### ISSUE TITLE
Unable to delete custom system prompt

### ISSUE THREAD

**Issue by evanrgardner** [brave/brave-browser#43888]
### Description

If you create a custom system prompt you’re unable to delete it or revert back to the default system prompt.

### Steps to reproduce

1. Create custom prompt on BYOM (brave://settings/leo-ai)
2. Attempt to delete or remove the custom prompt
3. Click Save
4. Revisit 'Edit Model' details and view custom prompt still populated

### Actual result

https://github.com/user-attachments/assets/8d22cec2-3801-4768-92f5-cd83d9033a09

### Expected result

System Prompt should revert to default prompt and remove the custom prompt

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.75x

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by mattmcalister** [comment]
I believe that was fixed, but maybe I'm mistaken. Try upgrading your browser to the latest version.

**Comment by kirkins** [comment]
@mattmcalister still happens for me on

Brave is up to date
[Brave 1.89.39 (Official Build) nightly (arm64)](https://brave.com/latest/)
Chromium: 145.0.7632.76

**Comment by kirkins** [comment]
https://github.com/user-attachments/assets/d2031851-1671-4b4f-8f38-d333a2ae162a

**Comment by mattmcalister** [comment]
Oh, I see. thank you.

**Comment by kirkins** [comment]
@mattmcalister no problem simple fix, that I assume doesn't cause any issues as I built from scratch _(which took many hours)_ to test and I didn't see any new issues introduced.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.89.112 Chromium: 146.0.7680.76 (Official Build) beta (64-bit)
-- | --
Revision | 9abc96c071d1cc382057803479b0faa3f8e6d586
OS | Windows 11 Version 25H2 (Build 26200.7840)
```
Reproduced the issue in `1.89.39`

Verified the issue using the STR from https://github.com/brave/brave-browser/issues/43888#issue-2845949084

#### Confirmed custom prompt was removed and System Prompt restored 

https://github.com/user-attachments/assets/c000b78f-462d-4003-a50a-3778d049fb85
