### ISSUE TITLE
Users reports - screen is dimming & locking while videos are playing in Brave

### ISSUE THREAD

**Issue by hollons** [brave/brave-browser#44097]
### Description

Screen is dimming & locking for users while videos are playing in Brave. 

What we know: 

- Users that have replied say it is not reproducible in Chrome. 
- Not specific to any one site. 
- Disabling adaptive dimming does not resolve 

### Steps to reproduce

1. Play a video on Brave 
2. After a short time, screen dims and then locks 

### Actual result

Screen is locking for users reporting the issue. 

### Expected result

Video continues to play as expected without dimming and locking. 

### Reproduces how often

Intermittent issue

### Brave version

Bug introduced with 1.75.175. Many users are reporting that it's happening regularly, with others affected only intermittently. 

### Device

User 1: Android 14, Samsung S21FE, One UI ver: 6.1
User 2: 1 Galaxy S23 - OS unknown 
User 3 - Android 14, One UI 6.1.1, Kernal 5.10.209
User 4: Android 12; Build/SKQ1.211019.001 on MIUI 14 Xiaomi Redmi Note 9s.
User 5: Android 14, TECNO CK8n

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [x] with Brave Shields disabled
- [x] with Brave Rewards disabled
- [x] in the latest version of Chrome

### Miscellaneous information

https://community.brave.com/t/screen-turning-off-while-watching-videos-on-brave-after-the-new-update-the-screen-turns-off-when-watching-a-video-on-brave-i-dont-want-to-change-my-phone-settings-i-want-this-issue-to-be-fixed-within-the-app/597751/66

Misc User Notes: 

- Mixed results with Disabling Shields. Resolved for 1 user, not for another. 
- Clearing cache resolved for 1 user
- Changed the screen timeout in phone Settings> Display and noticed-
         a) 5 mins = Screen turns off after 5 mins of video play.
         b) 15 seconds = Screen turns off after 15 seconds of video play.
         c) Screen only turns off when you don't touch the phone (display ofcourse).

**Comment by AdrienD-PEFF-ASFR** [comment]
Hello,
Having the issue here too. It wasn't doing this in previous versions.
I'm on OnePlus 12, Android 15 and OxygenOS 15

Thanks

**Comment by ajsmith27** [comment]
Same issue for me on 2 devices:
- Samsung Galaxy Tab S8+
- Google Pixel 9 Pro

Both decides had an available update from 25/02 so will give this a try first, then explore the suggestions in this issue. I'll feedback what I find.

**Comment by osmkarim** [comment]
Same problem on OnePlus A6000

**Comment by fwernert** [comment]
Hello,
Same here : Samsung Galaxy S24+ very recently.
Impossible to watch a video. I can only listen to.

**Comment by julien-jacob** [comment]
Hello,
Same on lenovo m10 fhd plus

**Comment by ajsmith27** [comment]
> Same issue for me on 2 devices:
> 
> * Samsung Galaxy Tab S8+
> * Google Pixel 9 Pro
> 
> Both devices had an available update from 25/02 so will give this a try first, then explore the suggestions in this issue. I'll feedback what I find.
> 
> Edit: Looks good so far on the new update, not sure if that's because installation of it has cleared caches. Will keep monitoring and advise of any change.

Had looked good for a while, but seeing the issue again on the Pixel 9 Pro

**Comment by Songo-Ku** [comment]
Xiaomi 13 pro. After Update brave around 2 weeks ago We got this issue. After few days issue dissapeared. Then it came back 3-4 days again. It seems to exist randomly.

**Comment by LynQuigley** [comment]
Same for me - happens all the time
Samsung S22 Ultra
Android 14, One UI 6.1, Brave 1.76.75

**Comment by ryanbr** [comment]
Of any reports here, does disabling Shields/Ads& trackers help? There was new rules to counter YT ads, trying to work out if its related

**Comment by fwernert** [comment]
No one will resolve this? 
I was mainly using brave for youtube but now it becomes useless.

**Comment by AltanDaniel** [comment]
1. Same issue for me on my OnePlus 13 running Android 15 and OxygenOS 15.

**Comment by ryanbr** [comment]
> No one will resolve this?
> I was mainly using brave for youtube but now it becomes useless.

We're still trying to work out/repro the issue. No magic wand to fix it. 


Does enabling Experimental List in Settings/Privacy & security/Content filtering. Then reloading YT page.

**Comment by AltanDaniel** [comment]
Actually enabling the experimental block list in the filters seem to have fixed the screen turning off problem for now! For some reason though, still, the comments and thumbs up / thumbs down / video description / channel name section do not appear. Let's concerning though! This is of course on the YouTube mobile site, not the desktop mode which I never use.

**Comment by ryanbr** [comment]
Testing here:  (as of 27/03)

* Galaxy Fold 6
* Brave release (1.76.81)
* Android 14
* Non-logged in Youtube
* Playback of Lofi Girl (video channel)
* Using Experimental list 

Closed fold, screen completely dimmed. and Lofi music sound is still playing.

**Comment by ryanbr** [comment]
@deeppandya can you reproduce?

**Comment by Clementdigital** [comment]
Hello Folks,

From the french reddit, a fix that seemed to work for some users : (nobody reported it not working yet) : 

- Update app to the last version (probably not needed step)
- go to Appearance > Themes and select either clear or dark but not system
- Force close the app and restart it

Should work now.

**Comment by fwernert** [comment]
Tried just now and it seems that i can watch a full youtube video without my screen going to sleep mode.

Thank you!!!

**Comment by Clementdigital** [comment]
As long as it works for everyone who tries it, @ryanbr it might be the lead you are looking for to solve the issue.

**Comment by fwernert** [comment]
Finally the issue is still here.

**Comment by a-irsyad** [comment]
It might be related to "Background  play" feature as disabling it removes the bug (at least for me).

Settings -> Media -> Background play

**Comment by wkdpower** [comment]
Just to add to this, I had the same issue start a few days ago. Found this bug, and was able to fix it using a similar method others suggested worked.

I use the dark theme on Brave (not system default as mentioned in the above workaround).

I switched to light theme, restarted Brave, switched back to dark theme, and problem has been gone since.

(Android 14, Brave 1.79.118)

**Comment by Brave-Matt** [comment]
+1 from myself -- just started seeing this behavior on my end as well. 
Using a Samsung Galaxy S22+ running Android 15 and latest Brave build. Issue can be consistently reproduced.

**Comment by simoarpe** [comment]
@Brave-Matt can you reproduce the issue on Chrome too?
And if follow the steps from https://github.com/brave/brave-browser/issues/44097#issuecomment-2928164410 are you still able to observe it?
Do you confirm you were not power saving mode?

**Comment by headsvk** [comment]
Google Pixel 8 Pro on Android 16 here. Same issue fixed by not using the system theme.

**Comment by Brave-Matt** [comment]
@simoarpe to my great surprise this (https://github.com/brave/brave-browser/issues/44097#issuecomment-2928164410) did actually fix the issue (seemingly/for now). There are other users reporting this issue in the [main Community thread](https://community.brave.com/t/screen-turning-off-while-watching-videos-on-brave-after-the-new-update-the-screen-turns-off-when-watching-a-video-on-brave-i-dont-want-to-change-my-phone-settings-i-want-this-issue-to-be-fixed-within-the-app/597751/115) still -- I can suggest they try this but I suspect it will not resolve it for everyone.

**Comment by Brave-Matt** [comment]
@simoarpe @ryanbr @timchilds 
This issue is still occurring for many users and the issue also just reappeared for me, even after the fix [mentioned above](https://github.com/brave/brave-browser/issues/44097#issuecomment-2928164410) which is likely only temporary. Additionally, this issue does not occur in Chrome on Android -- tested in standard browsing, private browsing, landscape vs portrait mode and full length videos vs shorts as well. In Brave, the screen continues to dim after a while on YT regardless of how the content is being viewed.

Can we please take another pass at this?

**Comment by alemit** [comment]
I've noticed a pattern - the so called [fix above](https://github.com/brave/brave-browser/issues/44097#issuecomment-2928164410) with the Theme change works for me as well, until I open some of the Shorts videos (YouTube) -> then it starts again blacking out (lock) the screen. If I change the Theme again and only watch Videos it is working as expected and do not lock. With the first Shorts video I watch the "fix" stops working again. Idk if it is only on my device that way, but hopefully it may help reproducing the issue and to notice what is different for the two cases from Brave's perspective

**Comment by sachbearbeiter** [comment]
Same issue on Pixel 6a

**Comment by joey-wheeler99** [comment]
After trying all the fixes mentioned above. I found that the real action that takes effect is the restart. If Brave starts dmming/turn off the screen while playing video, just restart Brave. No need to change theme or other hacks. At least it what happens to me.

**Comment by LawnGnomeMan** [comment]
I am experiencing this issue as well on a Google Pixel 9A running Android 16, and it's consistent, not intermittent.

**Comment by Brave-Matt** [comment]
+1:
https://community.brave.app/t/screen-times-out-during-fullscreen-youtube-playback-on-android/642626/3

**Comment by Savicava** [comment]
> Hello Folks,
> 
> From the french reddit, a fix that seemed to work for some users : (nobody reported it not working yet) :
> 
> * Update app to the last version (probably not needed step)
> * go to Appearance > Themes and select either clear or dark but not system
> * Force close the app and restart it
> 
> Should work now. [@ryanbr](https://github.com/ryanbr) hope this helps.

This resolved it on a fully updated Xiaomi 13T . Thanks!

**Comment by simoarpe** [comment]
This is an intermittent issue affecting Chrome users too.
The main reason seems to be a wake lock that is not reset correctly when loading a new video and the previous one ends.

Some discussion of the same issue affecting Pixel phones on Chrome:
- https://support.google.com/android/thread/42696616/chrome-doesn-t-stay-on-when-watching-videos-on-my-smartphone?hl=en
- https://support.google.com/chrome/thread/40065004
- https://support.google.com/pixelphone/thread/150936786/screen-times-out-when-watching-video-on-chrome?hl=en
- https://support.google.com/pixelphone/thread/4329102/how-do-i-prevent-my-phone-from-sleeping-while-media-is-playing-in-chrome?hl=en

Links to Chromium issue tracker:
- https://issues.chromium.org/issues/41482981
- https://issues.chromium.org/issues/41458445


This issue should be fixed upstream, as the wake lock handling is not something we should manually touch.
As a mitigation we can do the following actions:
- Update Brave to the latest version
- Close Brave and restart the device
- Switch theme navigating to Media > Appearance > and pick a theme that is not system
- Close all open tabs and restart the device
- Clean cache
- Completely remove and reinstall Brave (only as last resort)

**Comment by sathishkumarc14** [comment]
Poco x6 5g also

**Comment by DeNohvo** [comment]
Easiest workaround is to disable background play then restart Brave, I do hope this is addressed as I like background play is very useful.

**Comment by flenzi** [comment]
I had this issue and it was fixed disabling settings->media->background play

**Comment by antislukas** [comment]
> Easiest workaround is to disable background play then restart Brave, I do hope this is addressed as I like background play is very useful.

> I had this issue and it was fixed disabling settings->media->background play

This issue is not connected to background play.

**Comment by vicsvx** [comment]
Just started happening to my P9P last OS update. Phone is fully updated as well as Brave.

**Comment by krutoileshii** [comment]
same here. still and issue. applies to chrome as well

**Comment by temportalflux** [comment]
> > Easiest workaround is to disable background play then restart Brave, I do hope this is addressed as I like background play is very useful.
> 
> > I had this issue and it was fixed disabling settings->media->background play
> 
> This issue is not connected to background play.

I'm still experiencing this issue on pixel 5, android 14. Disabling this setting successfully suppressed this bug for me.

Brave 1.84.136, Chromium 142.0.7444.138
Android 14; Build/UP1A.231105.001.B2

**Comment by vicsvx** [comment]
Disabling background play didn't change anything on my device either

**Comment by GeneXsus** [comment]
> > > Easiest workaround is to disable background play then restart Brave, I do hope this is addressed as I like background play is very useful.
> > 
> > 
> > > I had this issue and it was fixed disabling settings->media->background play
> > 
> > 
> > This issue is not connected to background play.
> 
> I'm still experiencing this issue on pixel 5, android 14. Disabling this setting successfully suppressed this bug for me.
> 
> Brave 1.84.136, Chromium 142.0.7444.138 Android 14; Build/UP1A.231105.001.B2

This worked for me. Thank you.

**Comment by hverrill** [comment]
> Disabling background play didn't change anything on my device either

Same here. Running Graphene OS on a pixel 6, and disabling background play did not fix the issue for me. I've had this issue for months now intermittently, but now it's constant. I cannot fathom how such a large user experience bug still exists. Is this seriously just an issue with upstream chrome and brave is powerless to fix anything? 

Edit, adding brave version.

Brave 1.84.139, Chromium 142.0.7444.163
Android 16; Build/BP2A.250605.031.A5

**Comment by bsclifton** [comment]
Thanks for your patience folks - this is a very difficult problem to reproduce. To help share the impact, I've had this too 3 times over my entire Android ownership (~3 years; on Pixel 6, Pixel 8, and most recently on Pixel 10 Pro). Each time it happened, I was on YouTube. The work-around I did was to close Brave entirely and re-open. It would then work fine.  Each time it happened, I wasn't in a position where I could plug my phone into a computer w/ USB and load the adb tools. Although, I'm not sure how much that would help.

I talked with @simoarpe today about this issue - I think we have a strategy to try and trap the error. Basically, Android should be using something called a WakeLock. If the application doesn't acquire it, the system will first dim the screen and then finally lock the device.  I suspect somewhere in the Chromium code, the lock is acquired and the code gets into a state where it releases the lock but still thinks it has the lock.

We'll be setting aside some time to timebox this and try to trap this condition. If we trap it, we can then perhaps write something to local state which has more information. That might be the final clues needed to uncover the root cause.

**Comment by schragesteven-png** [comment]
So I am likely late to this but you can fix the issue by closing brave completely, opening it back up and creating a new tab. For whatever reason all the old tabs will keep dimming. New tabs will not dim. 

Few notes, Galaxy 25, brave browser on youtube mobile site (occours for ever browser video). This trick has worked for the past 6 months on all the latest OS/browser updates. Also restarting the phone works half the time.

**Comment by sherpya** [comment]
it happens very often (lately worse) on my xiaomi mi pad pro 6, hyperos 2.0.212.0: force stop, clear cache, device reboot, going full screen, nothing helps

update: looks like pip mode changes something, went in pip mode and back, now isn't dimming anymore

**Comment by simoarpe** [comment]
Upon further investigation, I can confirm that this issue is **Chrome-related**, and **not caused by any Brave-specific features such as Background Playback or Picture-in-Picture**.

There is currently a race condition involving `WAKE_LOCK` in Chromium that breaks a tab's ability to keep the screen active.

This problem can also be reproduced on the latest Chrome app (as of today: `142.0.7444.171`).
**Watching YouTube Shorts appears to be the most reliable way to trigger this race condition, causing the affected tab to enter a corrupted state where the device's screen turns off after the normal system timeout.**

When a tab enters this corrupted state, there are two ways to restore correct behavior:
- Fully close the tab
- Restart the Brave app

Please note that these are temporary workarounds, and the issue may reoccur if YouTube Shorts are viewed frequently.

A more drastic, but more reliable solution is to **block YouTube Shorts entirely**.
Brave offers this option under:
`Settings → Media → Block YouTube Shorts`

<img width="501" height="997" alt="Image" src="https://github.com/user-attachments/assets/291aa993-f31d-4acf-be0f-1154e70bbd0f" />

Blocking Shorts appears to eliminate the dimming issue completely, even after prolonged use.
**We appreciate all the feedback from the community and will continue investigating as we work toward a long-term, stable fix.**

**Comment by schragesteven-png** [comment]
Oooh thank you Jesus. I found shorts annoying enough and I have been blocking the elements for months. This is going to kill 2 birds with one stone, had no idea this was a built in setting.

Testing this out now. 

-Edit

Gave it a day and blocking shorts did not help prevent dimming. Dimming seems just as consistent (consistent inconsistent?) as before. But it did help improve my my life.

Few things I tried below because they seem to help others facing this issue in the past. None of these have helped me yet, but maybe this works on a different device/OS.

-Definitely update if you have not already, OS and browser.
-Disable Night mode, not sure if this is worth living without.
-Conflicting reports that changing the theme to dark, light, or system default fixes things. Some are able to change it back without issue. 

I think the last 2 may have restarted Brave which fixes things 50% of the time for me anyway.

Closing brave completely and opening up a new tab is the only work around I have found to work 100% on galaxy 24. Old tabs will keep dimming most of the time unless I restart my phone.

**Comment by A-t-s-u-s-h-i** [comment]
This is from Play Store Review. It seems like YouTube Shorts doesn't matter to the issue, but restarting the browser fixes the issue temporarily.

> I don't watch YouTube Shorts, but it seems the display goes to sleep when I watch a YouTube video after viewing another tab. Quitting the browser and restarting it fixes the issue. So it's not that inconvenient, but it's still bothersome.

**Comment by taoceanz** [comment]
TL; DR: try change your Display > Screen timeout to 15 second then revert it back to your original setting. This seems to resolved my issue. 

I could reproduce this issue with these steps 

1. Open Brave and play the video,
2. Optional: send Brave to background, 
3. Lock the screen,
4. Unlock the screen, 
5. Leave the phone for the Screen timeout duration,
6. The screen dims then turns off. 

The dimming occurs only if you don't interact with the phone. If you touch the screen or tap a button the Screen timeout timer resets and the screen dimming is avoided. 

My temporary fix was to close and reopen Brave every time I lock my screen. Though in testing this, I updated my Screen timeout to 15 seconds and the issue disappeared.

**Comment by schragesteven-png** [comment]
@taoceanz My dude, changing it to 15 seconds worked.

... only took 1 hour and I broke it. I think its a temporary fix like closing brave and reopening it. For some reason videos are not disabling the dim feature at some point. 

Might atleast pin point some action. Maybe dimming is getting disabled for the first video but after that it never tracks future videos after an action. (Idk the action. Might be switching apps, or closing the phone.) 

Testing a few more things this weekend, wish me luck.

**Comment by iderekh** [comment]
I have a OnePlus 15 with dimming and lock issues in Brave. Changing the background activity setting from "smart mode" to "allow" resolved the problem.

![Image](https://github.com/user-attachments/assets/c6fb0b3e-9618-40af-8878-d7b65696f222)

**Comment by sherpya** [comment]
it's not related to shorts or at least not exclusively, I can trigger the bug by triggering the hover action (keeping pressed on a video thumbnail) that does the preview playback, shorts have more probabilities to trigger the video preview

**Comment by schragesteven-png** [comment]
@sherpya youtube setting allows you to disable previews. I have this disabled but still receive the dimming while watching videos.

Might still be worth trying depending on the phone you have.

**Comment by hollons** [comment]
Hi all, 

If you're still experiencing this issue, please try the following steps: 

- Disable `Tab Strip Group Drag Drop Android flag`. (this is enabled on a fresh install)
- Disable `Block screen fingerprinting flag`. (this is already disabled on a fresh install)
- Enable `Enables use of the screen parameter for requestFullscreen flag`. (this is disabled on a fresh install)

**Comment by schragesteven-png** [comment]
Edit: ooooff, worked for 6 hours. But I think Hollons recommendations did something. Normally I run into this every hour or 2.

Galaxy 25, 
Android 16; Build/BP2A.250605.031.A3
Brave 1.85.120, Chromium 143.0.7499.192

**Comment by schragesteven-png** [comment]
So I the dimming has definitely decreased after Disabling Tab Strip Group Drag Drop Android flag, and Enabling Enables use of the screen parameter for requestFullscreen flag. Finger printing was already disabled for me.

Background app settings may be causing this issue as well. Videos started to dim again after setting down my phone for a few minutes and opening new apps before going back to brave. In the past I would need to close brave completely and restart, but this time all I had to do was open a new tab and play a video, then go back to the original video.

Not sure what the technical term is but the system checking if a video is playing to keep the screen on is not allways checking when brave is restarted from sleeping in the background.

Also noticed dimming after the phone was placed battery saving mode. Which could be related to background app settings.

**Comment by vicsvx** [comment]
This issue has been intermittent for me recently. Not sure what changes when it decides to work properly. Today for a few hours it worked as it should... Video playing, no dim, no screen timeout and no need to interact with the screen to keep It awake. Then boom, it dims. Maybe battery charge? It was working from 100 to about 75 and now at 58 it dims. But maybe something else the phone/app is doing that we don't know about? Hmm

**Comment by taoceanz** [comment]
My simple manual fix is to add a new tab to the group, open the group, close the new tab, then go back to the original tab.
It resolves the issue 100% of the time.

Initially I thought the screen dimming to lock issue was triggered by bug during a user action. 
However, I've had this dimming to screen lock issue occur randomly on multiple occasions after around 20- 30 mins of video playback with no user interaction. 

Is it possible some of the security features that block certain things causes Brave to transition from foreground to background (perhaps not triggering some OS flag when it returns to foreground) which leads OS to start screen timeout count down?
