### ISSUE TITLE
[Gnome] After Gnome 48 upgrade, it always asks to Add Keyboard Shortcuts

### ISSUE THREAD

**Issue by francoism90** [brave/brave-browser#44886]
### Description

![Image](https://github.com/user-attachments/assets/42e69bd8-d91c-46f7-8b1e-5dd4d71cc6af)

This always popups on first launch.

### Steps to reproduce

1. Upgrade to Gnome 48
2. Open Brave

### Actual result

'Add Keyboard Shortcuts' window opens

### Expected result

Not showing the dialog.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
/app/brave/brave --enable-features=HistoryMoreSearchResults,UseMultiPlaneFormatForHardwareVideo,OneTimePermission,AcceleratedVideoEncoder,VaapiVideoDecoder,PlatformHEVCDecoderSupport,TouchpadOverscrollHistoryNavigation,OverlayScrollbar,AcceleratedVideoDecodeLinuxGL,AllowIncognitoPermissionInheritance,AcceleratedVideoDecodeLinuxZeroCopyGL,VaapiOnNvidiaGPUs,VaapiIgnoreDriverChecks --disable-features=WebAssemblyTrapHandler,DesktopPWAsRunOnOsLogin,UseChromeOSDirectVideoDecoder --use-cmd-decoder=passthrough --ignore-gpu-blocklist --enable-gpu-rasterization --enable-zero-copy --ozone-platform-hint=auto --gtk-version=4 --no-default-browser-check --disable-domain-reliability --enable-dom-distiller --enable-distillability-service --origin-trial-public-key==,/+/= --lso-url=https://no-thanks.invalid --sync-url=https://sync-v2.brave.com/v2 --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --flag-switches-end --ozone-platform=wayland --component-updater=url-source=https://go-updater.brave.com/extensions
```

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by alve90** [comment]
Add command-line option **--disable-features=GlobalShortcutsPortal**

**Comment by bsclifton** [comment]
cc: @fallaciousreasoning - have you seen this before?

**Comment by francoism90** [comment]
I don't know what actually fixed it, but after clicking 'Add' multiple times, it now finally doesn't seem to ask for global shortcuts anymore. :)

**Comment by fallaciousreasoning** [comment]
Hmmm, I'm still on Gnome 47 (with Ubuntu 24.10) - lets keep this open until 25.04 is out.

**Comment by Bubbelb** [comment]
Stumbled on this report, because I experience the same. Albeit with other Chrome/Chromium based browsers (Vivaldi, Chromium, Ungoogled Chromium). Looking at the shortcut keys, I assume it is connected with extensions, since I the Shift+Ctrl+L is used with my BitWarden extension.

So, I think it's not a Brave-specifc issue, but applies to all Chrome/Chromium-based browsers.

And fwiw, All the browser I use are Flatpak installs.

**Comment by fallaciousreasoning** [comment]
Hmmm, I wonder if its a Gnome bug or a Chromium bug :D

**Comment by Angxddeep** [comment]
A bit of clarification Shortcuts were a mess in Wayland there used to be a workaround passing shortcuts through x11 to make them work in Wayland, but now there is a GlobalShortcutsPortal which allows an application to provide the shortcuts it needs to listen too from the Desktop System

**Comment by Angxddeep** [comment]
#44505 This is the same issue, apparently it got fixed in upstream https://issues.chromium.org/issues/404298968

**Comment by fallaciousreasoning** [comment]
@Angxddeep thanks for digging into this - looks like this was caused by an upstream issue but I'm going to leave this open until we confirm this has fixed it in Brave

**Comment by morfyum** [comment]
Same issue in Chrome 😡

**Comment by Bubbelb** [comment]
The issue seems resolved now, at least for me. Since Manjaro (the distro I use) has updated Gnome to 48.1 this weekend, the dialog boxes are gone. I don't know if it is a Gnome, Manjaro, or Chrome/Chromium browser issue, because I didn't check what's updated and what not.

Coincidentally I saw a reference to this problem in a Manjaro blog post about a testing version of Manjaro. It was stated as a known issue. It seems in the stable version it is resolved. But I couldn't find any more info about this.

**Comment by bsclifton** [comment]
This should be fixed in Chromium 138 which we're planning to release tomorrow with Brave version 1.80
https://chromiumdash.appspot.com/commit/65642faa51ddc4f25594d80374354cc291c2a1bc

Once this new version becomes available maybe someone can retest it? You should already be able to test if you're using Beta or Nightly

**Comment by fallaciousreasoning** [comment]
As a temporary fix, I noticed that this doesn't seem to happen if you set your Ozone Platform to X11 in chrome://flags/#ozone-platform-hint

**Comment by YanEx13** [comment]
For some reason this doesn't happen in Brave Nightly Channel (but it still happens in Brave Release Channel).

Brave 1.80.113 (Official build) (64 bit)
Chromium: 138.0.7204.49

Brave 1.82.31 (Official build) nightly (64 bit)
Chromium: 138.0.7204.49

Fedora 42 KDE

![Image](https://github.com/user-attachments/assets/972d4494-1c31-44a4-b032-152a68d5a168)

**Comment by fallaciousreasoning** [comment]
I think there was an upstream bug for this and it did get fixed at one point - I wonder if maybe the fix is in 1.81. Do you mind checking @YanEx13 ?

**Comment by francoism90** [comment]
@YanEx13 If you hit 'OK', do you still get it the next time?

I believe it's fine it does ask this at the first time you're using the app (or upgraded your DE). My issue was that it kept re-appearing.

For me it has been fixed a while ago, and it doesn't happen anymore.

**Comment by YanEx13** [comment]
@fallaciousreasoning If you're referring to Brave-nightly, then rolling back to version 1.81 didn't change the situation — everything works, and the popup window doesn't appear.

@francoism90 If I click OK, the popup stops appearing for 1–2 launches, but then it comes back. If I disable all my extensions, the popup stops appearing entirely. HOWEVER, I couldn’t reproduce this behavior in Brave-nightly, even with the same set of extensions.

**Comment by fallaciousreasoning** [comment]
@YanEx13 just wanted to check whether 1.81 (Brave Beta) was working properly (sounds like it is). This might be getting caused by an upstream fix which hasn't trickled into 1.80 (Brave Release yet).

1.81 is scheduled to go to release pretty soon, so hopefully that fixes it for you :smile:

**Comment by NasirA1991** [comment]
same problem still im on nobara 42 using gnome

**Comment by ghost** [comment]
> This should be fixed in Chromium 138 which we're planning to release tomorrow with Brave version 1.80 https://chromiumdash.appspot.com/commit/65642faa51ddc4f25594d80374354cc291c2a1bc
> 
> Once this new version becomes available maybe someone can retest it? You should already be able to test if you're using Beta or Nightly

Looks like there is a new issue upstream with [Chromium](https://issues.chromium.org/issues/404298968). Can confirm affecting Brave, Chromium and Edge on Bluefin (Fedora Silverblue 42 Gnome 48)

**Comment by augmentedagent** [comment]
Still occurring on 1.83.118 (Official Build) on KDE/Wayland/Debian 12.

**Comment by fallaciousreasoning** [comment]
There seems to be something weird going on for me with this - for a while this was popping up every launch again but its stopped again.

I guess upstream is breaking/unbreaking this regularly. In the meantime, setting `ozone-platform` to `x11` in chrome://flags seems to fix it
