### ISSUE TITLE
cursor is bigger and alt gr keyboard button not recognized in ubuntu

### ISSUE THREAD

**Issue by michaelcozzolino** [brave/brave-browser#45229]
### Description

after last update
the cursor became 5 times bigger and the button alt gr is not recognized anymore, I'm using the italian keyboard and in order to use the "at" symbol i have to press alt gr + ò, but in brave it does not work, while in other apps it does. in the first image you can see the big cursor, in the second image you can see the standard cursor

![Image](https://github.com/user-attachments/assets/164b3dc8-db38-411a-81ea-494e612cc29d)

![Image](https://github.com/user-attachments/assets/55d028db-9cb5-4b54-bd73-f8c9a66e98c5)

### Steps to reproduce

1.  open brave in ubuntu 24
2. set the main keyboard as the italian(windows) one
3.  try to type the "at" symbol anywhere

### Actual result

the symbol is not typed, instead "ò" is typed 

### Expected result

the "at" symbol should be typed

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

[Version 1.77.95 Chromium: 135.0.7049.52 (Official Build) (64-bit)](https://brave.com/latest/)

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

# System Details Report
---

## Report details
- **Date generated:**                              2025-04-06 11:24:22

## Hardware Information:
- **Hardware Model:**                              ASUSTeK COMPUTER INC. X580VN
- **Memory:**                                      32,0 GiB
- **Processor:**                                   Intel® Core™ i7-7700HQ × 8
- **Graphics:**                                    Intel® HD Graphics 630 (KBL GT2)
- **Graphics 1:**                                  NVIDIA GeForce MX150
- **Disk Capacity:**                               1,5 TB

## Software Information:
- **Firmware Version:**                            X580VN.310
- **OS Name:**                                     Ubuntu 24.04.2 LTS
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.8.12-060812-generic

**Comment by plutzilla** [comment]
The modifier key (AltGr) related issue is likely caused by the recent Chromium update. I have the same issue in Chrome 135 on Ubuntu 24.04 (6.11 kernel, Gnome Shell 46, Wayland)

**Comment by sedax90** [comment]
same problem, I've downgraded my version...

**Comment by plutzilla** [comment]
I can't reproduce the issue on Brave (checked 1.77.95 via APT and Snap)

However, I found a weird workaround for the problem in Chrome browser. You might check if it works for your situation in Brave:

- Adding another keyboard layout (I use `English (US)`) makes AltGr work in Chrome. However, this works only if another language (Lithuanian in my case) it NOT the first on the list.
- This makes the number row work correctly (i.e. `AltGr` + `Shift` + `2` prints `@`), but other combinations don't work, i.e. `AltGr` + `e` does NOT print `€`)

**Comment by sedax90** [comment]
Now it's a public issue on chrome
https://issues.chromium.org/issues/408167436

**Comment by KarmaMonk** [comment]
same Problem with the AltGR key with swissgerman keyboard

**Comment by abbasnaqdi** [comment]
Hi, After updating to the latest version, I encountered an issue on my system:
OS: **Debian 12 (running on Wayland)**
Brave: **Version 1.77.95 (Chromium 135.0.7049.52 – Official Build – 64-bit)**
Display: 2880x1800 
DE: GNOME 43.9
WM: Mutter

**Comment by michaelcozzolino** [comment]
seems fixed in this version [Version 1.77.100 Chromium: 135.0.7049.100 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by abbasnaqdi** [comment]
@michaelcozzolino The problem still remains for me.
Brave: **[Version 1.77.101 Chromium: 135.0.7049.115 (Official Build) (64-bit)](https://brave.com/latest/)**
