### ISSUE TITLE
Brave Ad Block blocks DuckDuckGo ads but not Google search ads

### ISSUE THREAD

**Issue by mlavik1** [brave/brave-browser#4533]
## Description 
Ads are blocked by default, but according to your FAQ [you don't block ads on search engine results pages](https://brave.com/faq/#what-it-mean).
However, you seem to block ads on DuckDuckGo as long as Ad Block is enabled.
Is there a good reason for this?
It doesn't seem consistent, and I'd rather support DuckDuckGo than Google.

## Steps to Reproduce

   1. Enable Ad Block
   2. Go to duck.com and search for "dishwasher" => no ads
   3. Disable Ad Block
   4. Repeat step (2) => ads are shown
If you use Google instead of DuckDuckGo you will see ads in both cases

## Brave version (brave://version info)
Version 0.64.76 Chromium: 74.0.3729.157 (Official Build) (64-bit)

**Comment by jeroen7s** [comment]
that's weird, I still see ads on DuckDuckGo

**Comment by srirambv** [comment]
First party ads are not blocked either on Google or DDG. 

cc: @bsclifton @lukemulks

**Comment by mlavik1** [comment]
Sorry, maybe I wasn't clear enough: I'm talking about the "products" list that DDG shows when you search for a potential product. I'm pretty sure they earn money on that, and I'd like them to do so.

Comparison:
![ddg-ad](https://user-images.githubusercontent.com/6906872/58192912-1cc9d600-7cc2-11e9-9aab-5fd7c99cb0db.png)

**Comment by jeroen7s** [comment]
In that case, can confirm it blocks the products section here too.

**Comment by Brave-Matt** [comment]
+1 from reddit -- User is reporting the same behavior but references Startpage search results 1p ads blocked:
https://www.reddit.com/r/brave_browser/comments/btsen2/startpage_ads_are_blockt_when_the_shields_are_on/

**Comment by lukemulks** [comment]
Suggest we allow for the shopping links to display in Brave. 

DDG uses a similar service for product listings in search results to what they use for ads, which adheres to DDG privacy policy and aligns closely with our own at Brave.

**Comment by snyderp** [comment]
This should be fixed now with this https://github.com/brave/adblock-lists/pull/74

**Comment by bsclifton** [comment]
@mlavik1 would you mind re-checking the issue? 😄 Your browser should get an updated definition list shortly after launching. At that point, it should be resolved. Let us know! 😄

**Comment by mlavik1** [comment]
@bsclifton Hi! 😄 The products list still don't show for me. I also tried re-installing the latest version of Brave. (do I need a Beta version maybe?)
I tested with "samsung tv" and "volume rendering book", and the shopping links still don't show up.

**Comment by bsclifton** [comment]
@mlavik1 you're right- it's still not working for me

@snyderp can you check this out? Basically, it's not showing the `Products` tab for some reason. I'm on Nightly and I've manually updated my ad-block component. We do send a partner header to DDG, it's possible (but unlikely) they are hiding `Products` for Brave users

**Comment by bsclifton** [comment]
Chatted with @snyderp - let's give this one 24 hours and re-check. We have a scheduled task that runs once per day to update (and publish) ad-block definitions. It's likely just a matter of that running again 😄

**Comment by mlavik1** [comment]
It works now :+1: Great work! :)

**Comment by bsclifton** [comment]
@mlavik1 thanks for confirming! 😄
