### ISSUE TITLE
Bring back auto hide toolbar in full screen.

### ISSUE THREAD

**Issue by mario-grgic** [brave/brave-browser#47675]
### Description

Until very recently Brave Browser had experiment that allowed auto hiding toolbar in full screen (at least on macOS). Google Chrome has removed this flag and now Brave only shows native window controls on hover in full screen (no address bar, no tab bar).

Please note that Safari, Firefox and Chrome all have ability to hide toolbar in full screen and show it on mouse hover near the top of the screen.

Since Brave Browser had this ability as well until recently, it should be possible to bring it back with very little effort.

### Steps to reproduce

1. Turn off View/Always show toolbar in full screen
2. Enter full screen
3. Hover near the top of the screen 

### Actual result

On hover, only window titlebar is displayed.

### Expected result

On hover, full toobar is displayed with address bar, menubar.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave 1.80.120 (Official Build) (arm64)](https://brave.com/latest/)
Chromium: 138.0.7204.101

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

macOS 15.5 (24F74)

**Comment by SiLenCe-WB** [comment]
Any news on this?

**Comment by mario-grgic** [comment]
This is fixed on macOS. Not sure about other platforms.

**Comment by SiLenCe-WB** [comment]
Using full screen on Windows permanently hides tabs and toolbar :/

**Comment by skrabe** [comment]
> This is fixed on macOS. Not sure about other platforms.

Mind explaining how? I toggle the setting off on Brave and I reproduce the exact steps mentioned in body of this issue still.

**Comment by mario-grgic** [comment]
I didn't have to do anything, this started working in recent Brave versions. Not sure if this A/B test and I am in cohort where this is fixed, I hope not.
