### ISSUE TITLE
3rd-party cookie blocking causing website faults

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#4770]
## Description 
When debuging this https://twitter.com/johnnyryan/status/1137967756148649984 Noticed that the slideshow will only work if allcookies are allowed.

If enabling 3rd party cookie blocking, it'll prevent slideshare.net from working.

The options in firefox (nightly), has an option to block all 3rd-party cookies. the slideshow works fine here.

## Steps to Reproduce

   1. Enable Sheilds, with 3rd party cookie blocking.
   2. Visit https://twitter.com/johnnyryan/status/1137967756148649984
   3. Slideshow should still work.
   4. Repeat same task if need be in Firefox nightly, with 3rd-party cookies blocking enabled.
   5. Works fine in Firefox

## Actual result:
Slideshow navigation being blocked.

## Expected result:
Slideshow navigation shouldn't be blocked

## Reproduces how often: 
Occurs in Brave Nightly, and Release.

## Brave version (brave://version info)
Tested in Nightly; Version 0.68.26 Chromium: 75.0.3770.80 (Official Build) nightly (64-bit)
Release: Version 0.65.118 Chromium: 75.0.3770.80 (Official Build) (64-bit)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
Yes
- Does the issue resolve itself when disabling Brave Rewards?
Have not checked, probably not an issue.
- Is the issue reproducible on the latest version of Chrome? 
Chrome is also affected (if you set 3rd-party cookies to be blocked)

**Comment by ryanbr** [comment]
Wasn't sure to submit with Chrome or here, or both. I just submitted her for the moment.

**Comment by ryanbr** [comment]
More reports of 3rd-party cookie issues:
https://www.sfoutsidelands.com/lineup/
https://community.brave.com/t/vimeo-cookies-sorry-because-of-its-privacy-settings-this-video-cannot-be-played-here/61505

**Comment by ryanbr** [comment]
Related to the cookie issues: https://github.com/brave/brave-browser/issues/4285

**Comment by ryanbr** [comment]
Should be fixed now. closing report

**Comment by AndrewMorsillo** [comment]
This is not fixed. Sites still fail with 3rd party cookies blocked. Specifically https://app.tactiq.io/ works fine in other browsers but fails on Brave with 3rd party cookies blocked.

**Comment by bsclifton** [comment]
Thanks for raising, @AndrewMorsillo - I confirmed this is still a problem

The original steps of testing https://twitter.com/johnnyryan/status/1137967756148649984 and trying to navigate from the preview don't work on Brave but works on Chrome

**Comment by pes10k** [comment]
https://github.com/brave/brave-browser/issues/8514 will be the solution to this. I'm going to close this issue, but since the issues are linked, we can verify that this is no longer a problem after https://github.com/brave/brave-browser/issues/8514 lands. 

Thanks for the report!
