### ISSUE TITLE
Bookmarks Don't Show On Custom New Tab Page

### ISSUE THREAD

**Issue by scottwmaxwell** [brave/brave-browser#48419]
### Description

This is a bit niche, so it's understandable if this cannot be addressed.

This is specifically in regard to the `Show Bookmarks: Only on the new tab page` setting and when a chrome extension is setup to manage the new tab behavior.

### Steps to reproduce

1. Install [Bonjourr](https://chromewebstore.google.com/detail/bonjourr-%C2%B7-minimalist-sta/dlnejlppicbjfcfcedcflplfjajinajd) and agree to let it modify the new tab page behavior
2. In `brave://settings/appearance`, set `Show bookmarks` to `Only on the new tab page`
3. Open a new tab

### Actual result

The bookmarks bar does not appear in the omnibar within the new tab.
Note the URL of this tab is `chrome-extension://dlnejlppicbjfcfcedcflplfjajinajd/index.html`

### Expected result

The bookmarks bar does should appear in the omnibar within the new tab.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.81.131 Chromium: 139.0.7258.66 (Official Build) (arm64)
-- | --
Revision | 56d68d5aeaf931ec4abe57cd8eaceaeed6b14cdf
OS | macOS Version 15.6 (Build 24G84)

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by BookCatKid** [comment]
This is a very annoying issue, PLEASE FIX!

**Comment by OddyAte** [comment]
I would like to bump this issue as it's still not fixed.

**Comment by scottwmaxwell** [comment]
I just verified I can reproduce the issue in Google Chrome, so this issue would be more likely fixed by the Chromium team.
I've opened a ticket with them here: https://issues.chromium.org/issues/491027414. Feel free to upvote it there!  @OddyAte @BookCatKid

**Comment by Allasstar** [comment]
Still happening in 2026 on the latest version of Brave. Honestly, bugs like this make me regret switching from Edge to Brave.

**Comment by scottwmaxwell** [comment]
@Allasstar The issue is actually in chromium. See https://issues.chromium.org/issues/491027414

Brave could probably fix it too, but I was hoping to get a 3 setting functionality in Google Chrome, similar to what Brave already has.
