### ISSUE TITLE
White flash when opening/closing tabs even in dark mode

### ISSUE THREAD

**Issue by LegalizeNukes** [brave/brave-browser#48813]
### Description

When closing a tab (provided that it is the only tab that exists), closing that tab will create a white flash. If there are 2 or more tabs, I did not observe a white flash. 

Creating a new tab while one is already active will also create a white flash. This is made more visible when a site redirects you to a new tab and it takes a while to load.

### Steps to reproduce

1. Close a tab (must be the only tab).
2. Create a tab (either by user or by the site), while a other tab is active.

### Actual result

https://github.com/user-attachments/assets/b7eb4b1d-702d-4564-b4aa-96c203d7fd6a

https://github.com/user-attachments/assets/faa153f5-98c0-4b76-855d-7e1c937873c2

https://github.com/user-attachments/assets/9dfb5563-f016-4b4c-8fcd-72133cf5b6ab

### Expected result

If the user is using dark mode or night mode, there should be no white flash in any tab interaction. It should be black.

### Reproduces how often

Easily reproduced

### Brave version

Version 1.81 (134)

### Device/iOS version

iOS 18.6.2
iPhone 16 Pro

### Affected browser versions

- [x] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [x] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kylehickinson** [comment]
I believe this is already fixed by https://github.com/brave/brave-core/pull/30015 (upcoming 1.82 release)

**Comment by LegalizeNukes** [comment]
@kylehickinson I've updated to Version 1.82 (171) on iOS 26 using an iPhone 16 Pro and the white flash still persists when opening a tab. I've attached an example of the issue below.

https://github.com/user-attachments/assets/3e4aaeca-38cc-47c4-8ded-3aff361230f5

**Comment by kylehickinson** [comment]
That looks like a different issue entirely, I'll see if theres a solution to that

**Comment by kylehickinson** [comment]
@LegalizeNukes So this is because when a page opens a new tab it loads `about:blank` into that web view immediately then later the page starts loading. The `about:blank` page renders with a white background regardless of the background color we set on the web view itself. The reason why this is noticeable now is because we select the new tab immediately (https://github.com/brave/brave-core/pull/29217). I'll have to investigate further to see if there's anyway to remedy this without delaying the tab selection

**Comment by kylehickinson** [comment]
Opened to track: https://github.com/brave/brave-browser/issues/49510
