### ISSUE TITLE
Browser Crash

### ISSUE THREAD

**Issue by BlackPhantomDev** [brave/brave-browser#49276]
### Description

Today, I wanted to enter something in the search bar. And then—boom! The browser crashed. I reopened the browser. Same thing happened again.
Restarted the system. Same problem.

The problem occurs on the “New Tab” page and also when a website is already open and I want to enter something in the search bar.

But the browser doesn't crash when I paste text or a link from the clipboard!

My system (copied from os settings/about system):
Operating System: Kubuntu 25.04
KDE Plasma Version: 6.3.4
KDE Frameworks Version: 6.12.0
Qt Version: 6.8.3
Kernel Version: 6.14.0-29-generic (64-bit)
Graphics Platform: Wayland
Processors: 16 × Intel® Core™ Ultra 7 255H
Memory: 30.7 GiB of RAM
Graphics Processor: Intel® Graphics
Manufacturer: ASUSTeK COMPUTER INC.

### Steps to reproduce

1. Openend Browser
2. Wanted to type in the Searchbar
3. Crashed

### Actual result

The Browser crashed

### Expected result

No crash.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave: 1.82.166 Chromium: 140.0.7339.133 (Offizieller Build) (64-Bit) 
Revison: 38bf45887ca5336841cddb4200e6deee32ce45a8
OS: Linux

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by chaosrun** [comment]
I can confirm I’m experiencing the same issue.

Using fcitx5 + rime input method, Brave freezes for a few seconds and then crashes whenever I try to enter Chinese in the address/search bar. Typing in English works normally.

Uploaded Crash Report ID: cc1c0b00-b2c5-770e-0000-000000000000

**Comment by captainchaos1836** [comment]
I can also confirm:
Ubuntu 24.04 - just updated packages today
KDE Wayland

what's odd is that when I launch Brave, the KDE settings app also starts on the "Workspace Shortcuts" tab. This behavior is consistent. Reboot does not fix it, nor does command line run with usual testing flags.  I can click links etc, but as soon as I type a letter in the search bar it crashes

**Comment by bsclifton** [comment]
Possibly related: https://github.com/brave/brave-browser/issues/49242

**Comment by captainchaos1836** [comment]
As another datapoint, I logged out of my KDE wayland session and started KDE x-11.  Everything with Brave works fine, no crash.

**Comment by ericg3006-hash** [comment]
I will also add that, even within a Wayland session, starting brave with the **--ozone-platform=x11** switch also avoids the problem. This seems to work with both the normally installed brave-browser or the snap version.

**Comment by iraklisg** [comment]
On Manjaro linux using `--ozone-platform=x11` allow me to start the browser. Before that:
1. when I tried to run brave via desktop shortcut I run into the issue https://github.com/brave/brave-browser/issues/44886
2. when i tried to run via terminal like `brave [--disable-extensions] [--disable-features=GlobalShortcutsPortal]`  I got 
```
[11753:11753:0916/162603.899499:ERROR:chrome/browser/profiles/profile_attributes_storage.cc:1029] Failed to PNG encode the image.
[11753:11753:0916/162604.530495:ERROR:content/browser/gpu/gpu_process_host.cc:964] GPU process exited unexpectedly: exit_code=139
[11753:11753:0916/162605.263063:ERROR:content/browser/gpu/gpu_process_host.cc:964] GPU process exited unexpectedly: exit_code=139
[11753:11753:0916/162605.987037:ERROR:content/browser/gpu/gpu_process_host.cc:964] GPU process exited unexpectedly: exit_code=139
[11753:11753:0916/162606.821540:ERROR:content/browser/gpu/gpu_process_host.cc:964] GPU process exited unexpectedly: exit_code=139
[11753:11753:0916/162607.546875:ERROR:content/browser/gpu/gpu_process_host.cc:964] GPU process exited unexpectedly: exit_code=139
[11753:11753:0916/162608.296611:ERROR:content/browser/gpu/gpu_process_host.cc:964] GPU process exited unexpectedly: exit_code=139
[11753:11753:0916/162608.668849:ERROR:content/browser/gpu/gpu_process_host.cc:964] GPU process exited unexpectedly: exit_code=139
[11753:11753:0916/162609.081968:ERROR:content/browser/gpu/gpu_process_host.cc:964] GPU process exited unexpectedly: exit_code=139
[11753:11753:0916/162609.852837:ERROR:content/browser/gpu/gpu_process_host.cc:964] GPU process exited unexpectedly: exit_code=139
[11753:11753:0916/162609.852864:FATAL:content/browser/gpu/gpu_data_manager_impl_private.cc:415] GPU process isn't usable. Goodbye.
[0916/162609.861458:ERROR:third_party/crashpad/crashpad/snapshot/elf/elf_dynamic_array_reader.h:64] tag not found
[0916/162609.862241:ERROR:third_party/crashpad/crashpad/snapshot/elf/elf_dynamic_array_reader.h:64] tag not found
zsh: trace trap (core dumped)  brave --disable-extensions
```

**Comment by Nuscly** [comment]
Hello, my brave browser is also crashing with a SIGILL when I click on the bookmark menu.
In my case, I am using ubuntu 24.04 with Brave version 1.82.172 Chromium: 140.0.7339.207 (Build officiel) (64 bits) 

Booting the browser with `brave-browser --ozone-platform=x11` also solve the problem for me.

**Comment by Nuscly** [comment]
FYI, on my side the problem is solved with the new Brave version `1.83.109 Chromium: 141.0.7390.55 (Build officiel) (64 bits) `

**Comment by smb** [comment]
Hi,

See my comment https://github.com/brave/brave-browser/issues/49932#issuecomment-3380196997 in the other ticket - this still happens in release also on Windows.

But it seems to be related to the "new tab" page. I have disabled (= blank page only) the new tab 1 week ago and didn't experience a single crash.

related crash report: 926a0f0-217f-930e-0000-000000000000

**Comment by bsclifton** [comment]
@smb that crash report ID doesn't seem to be visible (getting a string parsing error). It seems to be missing at 1 character

Can you double check that is correct on brave://crashes? The field next to `Uploaded Crash Report ID`.

**Comment by bsclifton** [comment]
Going to close issue as the originally reported issue on Linux seems to be resolved

We can open a new issue with a full crash GUID if this happens on another platform (ex: Windows). Thanks 😄
