### ISSUE TITLE
[Windows] Users being logged out of sites (when closing or after a period of time)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#49300]
## Description
This is a new ticket tracking a problem on Windows originally reported with https://github.com/brave/brave-browser/issues/44789. That ticket has many recorded incidents and a lot of troubleshooting. 

For a Linux specific version of this issue, please see https://github.com/brave/brave-browser/issues/39758

## What happens
- Some people logged out of only Google site (ex: gmail)
- Others logged out of all sites

@lllIIIlll reported that when the issue happened, [cookies and local storage for those domains were deleted](https://github.com/brave/brave-browser/issues/44789#issuecomment-3015191901). For local storage, all the entries deleted.

Multiple people were seeing the following histogram reported when the data disappeared:
`Signin.BoundSessionCredentials.SessionTerminationTrigger`

For example:
```
- Histogram: Signin.BoundSessionCredentials.SessionTerminationTrigger recorded 2 samples, mean = 1.0 (flags = 0x41) [[#](chrome://histograms/#Signin.BoundSessionCredentials.SessionTerminationTrigger)]
0  O                                                                         (0 = 0.0%)
1  --O                                                                       (2 = 100.0%) {0.0%}
2  ...
```

## When it happens
Some folks report when closing the browser. Others report it happens w/ browser open after a certain amount of time.

## When did it start happening?
Issue was first reported when we introduced Chromium 135 in [Brave 1.77.95 (2 April 2025)](https://github.com/brave/brave-browser/releases/tag/v1.77.95).

@arch-btw helped narrow down a regression range in NIGHTLY when [we merged Chromium 135 into our code-base](https://github.com/brave/brave-core/pull/27522).
- [1.78.52](https://github.com/brave/brave-browser/releases/tag/v1.78.52) has the problem
- [1.78.51](https://github.com/brave/brave-browser/releases/tag/v1.78.51) does not have the problem

We started to receive even more reports when Chromium 140 was released with [Brave 1.82.x (4 September 2025)](https://github.com/brave/brave-browser/releases/tag/v1.82.161).

## Things that we've asked folks to check
These are things which could be giving the same symptom but it's a different root cause. 

If you haven't already checked these, you should:
- Is `Forget me when I close this site` enabled for site being visited? (click shields - the Brave logo next to omnibox). Disable this (NOTE: this is disabled by default).
- There is also a global `Forget me when I close this site` located at brave://settings/shields - set to disabled (NOTE: this is disabled by default).
- Try disabling extensions if you have any installed via `brave://extensions/`
- Make sure 3rd party software isn't tampering with cookies / etc (virus scanner, CCleaner, etc). That program may have a way to exclude the Brave profile directory which by default is located at `%LOCALAPPDATA%\BraveSoftware\Brave-Browser\User Data`.
- Make sure you don't have anything set to clear on exit (`brave://settings/clearBrowserData`)
- Make sure `Allow sites to save data on your device` is selected on `brave://settings/content/siteData`

It's worth noting: many people who are experiencing this issue have checked those and responded they are not applicable.

## Possible upstream reports

- https://issues.chromium.org/issues/391763852

**Comment by bsclifton** [comment]
From the last issue, @goodov had shared two troubleshooting steps folks can check

1. https://github.com/brave/brave-browser/issues/44789#issuecomment-3232772656
> We'd like you to help us debug this issue by toggling some features to the `Disabled` state on `brave://flags` and reporting if anything changes. **Please ensure you're on Brave v1.83.85 or newer.**
>
> Here are the flags to test at this stage:
>
> ```
> brave://flags/#brave-domain-block-1pes
> brave://flags/#brave-farbling
> brave://flags/#brave-first-party-ephemeral-storage
> brave://flags/#brave-provisional-tld-ephemeral-lifetime
>```
>
> **Testing Instructions:**
> 1. Toggle only **one feature at a time** to `Disabled`
> 2. Restart the browser completely
> 3. Test the functionality (login, restart, try multiple times)
> 4. Report back whether the issue persists
>
> This systematic approach will help us identify which specific feature might be causing the problem.


2. https://github.com/brave/brave-browser/issues/44789#issuecomment-3292511829
> That's very promising!
>
> People with the problem, please keep brave://flags/#enable-bound-session-credentials enabled and on logout event please open brave://histograms/Signin.BoundSessionCredentials and dump everything you got on this page here. I'm mostly curious if anyone of you got Signin.BoundSessionCredentials.SessionTerminationTrigger histogram and what the value it has in this case.


With those steps shared, folks there did seem to get this histogram logged. 

For examples of that output please see:
- @CoccodrillooXDS https://github.com/brave/brave-browser/issues/44789#issuecomment-3292770970
- @blueglyph https://github.com/brave/brave-browser/issues/44789#issuecomment-3293129007
- @Deshmukh-Omkar https://github.com/brave/brave-browser/issues/44789#issuecomment-3293699723
- @remd https://github.com/brave/brave-browser/issues/44789#issuecomment-3293742393
- @blitzio https://github.com/brave/brave-browser/issues/44789#issuecomment-3294472408

**Comment by Infi220** [comment]
@bsclifton If you have difficulty repro'ing this bug on your existing setup, here is my suggestion: uninstall Brave, delete all user data / profile, and do a clean install of the latest stable Brave. Then log into one or two google accounts, leave Brave open, and you will get logged out after 2 to 6 hours.

Would you mind also bumping up the priority of this issue?

**Comment by sistemforum** [comment]
Additionally, after performing a clean installation, you can also do the followings. Create 3-4 new profiles. You don't need to change any settings in these profiles. Log in to each one with a different Google accounts (I haven't tried if it works with the same account). Then close all tabs in those profiles, including Google. Then close the browser. After 3-4 hours, open the browser with those profiles. Your Google accounts will have logged out.

**Comment by blueglyph** [comment]
@bsclifton 
> [@arch-btw](https://github.com/arch-btw) helped narrow down a regression range in NIGHTLY when [we merged Chromium 135 into our code-base](https://github.com/brave/brave-core/pull/27522).
> 
> * [1.78.52](https://github.com/brave/brave-browser/releases/tag/v1.78.52) has the problem
> * [1.78.51](https://github.com/brave/brave-browser/releases/tag/v1.78.51) does not have the problem

But on the Linux issue, I see the version of the initial issue is 1.67.123 Chromium: 126.0.6478.126 (posted in July 2024). Either it was a different problem, or there's a chance it was already there before 1.78.52. It can take a long time before disconnecting, sometimes.

**Comment by SiLenCe-WB** [comment]
My problem seems to have been fixed. Yesterday I backed up my Brave config folder from a system where it was working fine (a virtual machine running Windows 11) and I imported it to my desktop computer where it was causing issues. This was the procedure:

- Copy fully working Brave config from VM.
- Import it on the system where it was causing issues. I did not delete anything from the previous config.
- I joined back the desktop Brave to my sync chain.


At first, I still had the same issue but after rebooting, the issue seems to be gone for good. I don't understand why, to be honest.

There is also one more detail that might be relevant: I deleted all the sync clients which I no longer needed, including one that was duplicated from a previous Window install where my machine hostname was same.

**Comment by blueglyph** [comment]
> There is also one more detail that might be relevant: I deleted all the sync clients which I no longer needed, including one that was duplicated from a previous Window install where my machine hostname was same.

Not sure. I've never used the sync feature on Windows or Linux, and
* on Windows, I'm logged out of Gmail in ~2 hours (1.82.166 and nightly with fresh settings)
* on Linux, it's been running for two days without any logout (1.82.166). Though it's an update from an old 1.70.117, so importing the settings from there might had an effect—I doubt it, but who knows.

EDIT: I could compare the settings, but I don't think there's any feature to export them, is there? Anyway, the Linux may still logout in a few hours.

**Comment by bsclifton** [comment]
Hi folks - happy to report that we have a potential fix on the table. Massive kudos to @goodov for the investigative work leading up to this and then digging in after the histogram data was shared. Thanks to everybody that helped characterize also.

A technical description of the problem can be seen at https://github.com/brave/brave-variations/pull/1504

Basically, a Chromium feature can conflict with the way we store cookies in Brave. Of course, not everybody affected - lots of variables here. But I think using a new clean profile and following steps under Testing in https://github.com/brave/brave-variations/pull/1504 should reproduce the issue.

Working to expedite this on our side. No new binary needs to be released - this is a change to our variations server (also called experiments server).  Our variations system is called [Griffin](https://griffin.brave.com/) and Chrome's is called Finch. Basically, experiments are defined which each configure a feature.  Clients are assigned a cohort when they contact the variations server and the experiment can be configured to distribute to a percentage of users based on cohort. This allows product team to roll out a feature. 

We'll shoot to get this out to Nightly first, then Beta, and finally Release channel. 

**I'll post an update here once we have the fix in Nightly - we can use help verifying the fix once it lands there**.

**Comment by obisco4u** [comment]
So what's the solution?

**Comment by UjsGit** [comment]
Encountering the issue from past one week, any solution yet?

**Comment by bsclifton** [comment]
@obisco4u the solution is to hang tight - apologies.  I believe we're close. We are qualifying the change and it will be live once we approve/merge the following pull request:
https://github.com/brave/brave-variations/pull/1504

Merging that will update the seed for our variation service (clients will get the update in an hour or two) on NIGHTLY.  

When that happens, I'll post here letting folks know. At that time, it'll be **really** important for folks using Nightly (1.84.x) to help us confirm the fix. When that looks good, we can move to Beta (1.83.x). And similar process moving to Release channel (1.82.x).

**Comment by SiLenCe-WB** [comment]
> but I don't think there's any feature to export them

Chat-GPT made the "feature" for me in powershell 😂 It built a script to backup and restore the config.

**Comment by szbly** [comment]
> So what's the solution?

I had a problem with google.com, it kicked my account out after a while but kept my account on youtube.com. I fixed it with a very simple way:
_brave://settings/shields : unblock everything it can block, allow 3rd party cookies, uncheck Easylist cookie
_brave://settings/privacy : don't delete cookies after exit, Diable "Prevent sites from fingerprinting me based on my language preferences", add google.com to "Shields status"

**Comment by johnny-official** [comment]
I found that downloading and installing the pre-release version resolves the logout problem.

<img width="859" height="374" alt="Image" src="https://github.com/user-attachments/assets/7e5dfdb5-2bda-4b65-9d50-8ebebc8b2671" />

**Comment by bsclifton** [comment]
OK folks - we have a fix merged for Nightly! 🎉 

**If you are reading this ticket and using the Nightly version of Brave, please restart your browser. When Brave starts up again, it should be contacting our variations server (Griffin).** 

You can then visit the `brave://version` page and search for `BTMGoogleAuthWorkaround`. You should find the experiment and it should be enabled:
`BTMGoogleAuthWorkaround:Enabled`

After you have confirmed you have this change, log back into the sites which were having the problem and let us know after a few hours.  Before, it was doing a cleanup (session terminate) within 2 hours of login. You don't need to close the browser. 

If we get good confirmation this fixes the issue we'll get this moving to Beta and Release.  @goodov will be looking at a better permanent solution.

**Comment by bsclifton** [comment]
@johnny-official:
> I found that downloading and installing the pre-release version resolves the logout problem.

Now that we have a fix for Nightly, you can download the regular public version again 😄

**Comment by webmube** [comment]
How long will it take until the full release? I'm a regular user with a regular Brave, and I'm so sick of relogging every 3-4 hours into all of my 4 accounts lol... Waiting that sweet update like Christmas...

**Comment by 404hex** [comment]
> How long will it take until the full release? I'm a regular user with a regular Brave, and I'm so sick of relogging every 3-4 hours into all of my 4 accounts lol... Waiting that sweet update like Christmas...

oh man i feel you, what I'm going through right now too, hopefully a full release soon!

**Comment by johnny-official** [comment]
> How long will it take until the full release? I'm a regular user with a regular Brave, and I'm so sick of relogging every 3-4 hours into all of my 4 accounts lol... Waiting that sweet update like Christmas...

I had the exact same problem with you, even though I tried many methods that they recommended; hopefully, they can fix it soon.

<img width="1010" height="590" alt="Image" src="https://github.com/user-attachments/assets/6cae007f-b6cf-4887-9d36-355194314792" />

**Comment by blueglyph** [comment]
> How long will it take until the full release? I'm a regular user with a regular Brave, and I'm so sick of relogging every 3-4 hours into all of my 4 accounts lol... Waiting that sweet update like Christmas...

@webmube Install the Nightly version and use it for the emails until it makes its way to the stable version. That way, you'll kill two birds with one stone: you don't have to login every 2-4 hours and you help by testing if the problem is indeed fixed (which it seems).

**Comment by goodov** [comment]
Reported upstream https://issues.chromium.org/issues/445561475

They also have this unexpected DBSC session termination, but because they keep 3p cookies for google auth, the auth is still kept.

**Comment by blueglyph** [comment]
@bsclifton @goodov 
Looking good: the Nightly version has kept my Gmail logins for ~4h30'~ ~8h~ 13h30 now, while the stable version has logged out after 2h15'. I've also closed the browser for a while (a few times), before checking again.

Nightly was installed from scratch, no change in the settings (Shields are on, no "allow" exception for JS, ...).

Windows 10 x64 22H2
Brave 1.84.72 (Official Build) nightly (64-bit) Chromium: 140.0.7339.133

PS: 
* **To those who install nightly**: please note that you need to restart it before the fix is in place. Yes, _even if you just downloaded it_. Do [the test above](https://github.com/brave/brave-browser/issues/49300#issuecomment-3301760262) to make sure before logging in.
* I'm not sure, but it looks like the fix would also work for the Linux version. "Unfortunately", my stable version of Brave has still the login after more than 54 hours, for some reason (see above for more details). So the Linux test wouldn't be relevant in my case.
* Thanks for your work on the fix!

**Comment by patomico5** [comment]
It's been 7 days with this problem. Remember until now there is no final fix yet.

So the problem is chromium and Google blocking brave (for stop using free youtube) and taking users back to chrome.

Please keep us updated.

**Comment by johnny-official** [comment]
> It's been 7 days with this problem. Remember until now there is no final fix yet.
> 
> So the problem is chromium and Google blocking brave (for stop using free youtube) and taking users back to chrome.
> 
> Please keep us updated.

Totally agree with you, finally I have to downgrade to [1.78.51](https://github.com/brave/brave-browser/releases/tag/v1.78.51), which does not have the problem, you could try this method. I swear I tried all of the methods on GitHub, and it can not be solved anyway..

<img width="724" height="247" alt="Image" src="https://github.com/user-attachments/assets/46bf402a-7124-4ad5-b7dc-ad13c3574121" />

**Comment by spa31** [comment]
> > It's been 7 days with this problem. Remember until now there is no final fix yet.
> > So the problem is chromium and Google blocking brave (for stop using free youtube) and taking users back to chrome.
> > Please keep us updated.
> 
> Totally agree with you, finally I have to downgrade to [1.78.51](https://github.com/brave/brave-browser/releases/tag/v1.78.51), which does not have the problem, you could try this method. I swear I tried all of the methods on GitHub, and it can not be solved anyway..
> 
> <img alt="Image" width="724" height="247" src="https://private-user-images.githubusercontent.com/93166599/490663495-46bf402a-7124-4ad5-b7dc-ad13c3574121.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTgxMjk2NDUsIm5iZiI6MTc1ODEyOTM0NSwicGF0aCI6Ii85MzE2NjU5OS80OTA2NjM0OTUtNDZiZjQwMmEtNzEyNC00YWQ1LWI3ZGMtYWQxM2MzNTc0MTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTE3VDE3MTU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNWU1MGZhMDIwZDNhZjM1OGYzODg2NjU4OTIzOTI3YzZmYTAxM2JiNzNhMWY0MTBiZTZkNDRjZjgwYmM3OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.K3hR8xuNVWfGkB1dUqq-KlY9rGTAIWUVmv2bxClMY6Q">

Hello, how did you managed to install this version without loosing all your data and brave rewards?

Could you share a procedure please?

Br,

**Comment by johnny-official** [comment]
> > > It's been 7 days with this problem. Remember until now there is no final fix yet.
> > > So the problem is chromium and Google blocking brave (for stop using free youtube) and taking users back to chrome.
> > > Please keep us updated.
> > 
> > 
> > Totally agree with you, finally I have to downgrade to [1.78.51](https://github.com/brave/brave-browser/releases/tag/v1.78.51), which does not have the problem, you could try this method. I swear I tried all of the methods on GitHub, and it can not be solved anyway..
> > <img alt="Image" width="724" height="247" src="https://private-user-images.githubusercontent.com/93166599/490663495-46bf402a-7124-4ad5-b7dc-ad13c3574121.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTgxMjk2NDUsIm5iZiI6MTc1ODEyOTM0NSwicGF0aCI6Ii85MzE2NjU5OS80OTA2NjM0OTUtNDZiZjQwMmEtNzEyNC00YWQ1LWI3ZGMtYWQxM2MzNTc0MTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTE3VDE3MTU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNWU1MGZhMDIwZDNhZjM1OGYzODg2NjU4OTIzOTI3YzZmYTAxM2JiNzNhMWY0MTBiZTZkNDRjZjgwYmM3OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.K3hR8xuNVWfGkB1dUqq-KlY9rGTAIWUVmv2bxClMY6Q">
> 
> Hello, how did you managed to install this version without loosing all your data and brave rewards?
> 
> Could you share a procedure please?
> 
> Br,

Hi @spa31 ! Here’s how I installed the new version without losing data or Brave Rewards:

1. Backup your Brave profile folder (you’ll find it in C:\Users$$YourName]\AppData\Local\BraveSoftware\Brave-Browser\User Data).
2. Download the version you want from the official Brave GitHub releases.
3. Close Brave completely.
4. Install the stable version [1.78.51](https://github.com/brave/brave-browser/releases/tag/v1.78.51)—just run the installer, your data should stay intact if you didn’t delete anything.
5. Launch Brave and verify that all your data and rewards are present.

Note: I’m not 100% sure this works for every situation, especially if you’re switching between very different versions. Always keep a backup just in case!

Hope this helps! 😊

**Comment by bsclifton** [comment]
I would highly recommend not reverting to an older version as a person above shared. You can lose your data (bookmarks, cookies, and more). As each Chromium version is released, there are schema changes to the sqlite database files and if these fail to load, you're entering undefined behavior territory. You could potentially lose your data.

I'm going to hide a few posts - I'm not trying to censor, you're welcome to read and try those. But these procedures are NOT recommended by Brave staff. 

We're going to [roll the fix out to BETA (1.83.x)](https://github.com/brave/brave-variations/pull/1507) soon (today; 17 September) as results have been good and then will be [rolling out for RELEASE (1.82.x)](https://github.com/brave/brave-variations/pull/1508) hopefully as early as tomorrow (18 September).

Thanks for your patience

**Comment by 3c7b1b91-0c9d-40a8-88bf-6e3c7f28b3e5** [comment]
I'm reporting that after testing the nightly build today, it seems the issue has been resolved. I've been using it throughout my entire commercial business working hours without a single logout. Previously, I used to be logged out every few hours from both Google and Microsoft.

Update: After almost 24 hours of usage, no logouts so far.

**Comment by AlaskanDruid** [comment]
Will the fix bring back the deleted groups, all the deleted passwords, and make the browser sync again?

**Comment by bsclifton** [comment]
@AlaskanDruid I'm a bit confused here - the bug in question here is where a person gets signed out of websites after 2 hours.

It sounds like you've ran into a data loss scenario, which is not related to this issue. 

Could you create a new issue describing what happened / symptoms / check `brave://crashes` for reported crash IDs / etc? The new issue template should ask you the important questions

Thanks

**Comment by bsclifton** [comment]
OK folks - we're now live on BETA (product version 1.83.x) with the fix 😄👍 

**If you are reading this ticket and using the Beta version of Brave, please restart your browser. When Brave starts up again, it should be contacting our variations server (Griffin).**

You can then visit the `brave://version` page and search for `BTMGoogleAuthWorkaround`. You should find the experiment and it should be enabled:
`BTMGoogleAuthWorkaround:Enabled`

After you have confirmed you have this change, log back into the sites which were having the problem and let us know after a few hours. Before, it was doing a cleanup (session terminate) within 2 hours of login. You don't need to close the browser.

We'll be watching over this thread and working with folks on the Brave Community site. If everything looks good, we'll look at getting the fix to the RELEASE channel next.

**Comment by bsclifton** [comment]
And we're now at 25% live with the fix on RELEASE (product version 1.82.x).

If you are reading this ticket and using the Release version of Brave, please restart your browser. When Brave starts up again, it should be contacting our variations server (Griffin).

You can check to see if you're included in that 25% by opening `brave://version` and searching for `BTMGoogleAuthWorkaroundRelease`.

When you see that in `brave://version`, you have the fix and should be good to go. If you don't see that yet, no worries. We'll be increasing to 50% and then to 100%.

Please keep us updated as this makes its way out there 😄 Thanks!

**Comment by blueglyph** [comment]
Here I see that variation set to `Default` (vs the variation on nightly and beta that was `Enabled`). I'll assume it just needs to be in the list and try Gmail right away. 😀

**Comment by popy2k14** [comment]
Got the value (also with `Default`) on two devices which had the logout issue.
Can report in few hours if the login will stick.

**Comment by blueglyph** [comment]
My release version just lost the login after 1 hour, despite `BTMGoogleAuthWorkaroundRelease` (set to `Default`, as already mentioned above).

```
- Histogram: Signin.BoundSessionCredentials.SessionTerminationTrigger recorded 2 samples, mean = 1.0 (flags = 0x41) [[#](chrome://histograms/#Signin.BoundSessionCredentials.SessionTerminationTrigger)]
0  O                                                                         (0 = 0.0%)
1  --O                                                                       (2 = 100.0%) {0.0%}
2  ...
```

The entire histogram is [here](https://pastebin.com/t8vCnUy6).

EDIT: I suspect that everyone has this variation in `brave:://version` but that it must show `Enabled`. @bsclifton could you please confirm?

**Comment by webmube** [comment]
Yes, I also have `BTMGoogleAuthWorkaroundRelease` set to Default and I've got the log out of Google services just about an hour ago.

**Comment by blueglyph** [comment]
I found the confirmation. You must see `BTMGoogleAuthWorkaroundRelease:Enabled` for the fix to be in your version:

<img width="316" height="240" alt="Image" src="https://github.com/user-attachments/assets/fb3f8dc0-dcba-4519-a6ce-a8e244b07162" />

**Comment by 3c7b1b91-0c9d-40a8-88bf-6e3c7f28b3e5** [comment]
> 25%

Hello.
Thanks for sharing this update. Does that means if I download again from Brave official website it will came updated already with this fix applied rather than just waiting for it to upgrade itself?

Thanks in advance
Best

**Comment by Saoiray** [comment]
@3c7b1b91-0c9d-40a8-88bf-6e3c7f28b3e5 What the screenshot shows is that the experiment `BTMGoogleAuthWorkaroundRelease` is currently being rolled out to 25% of users. The assignment is random and controlled by the rollout system.

Basically the 25% means up to 25% of all users are going to get access. It's something of a lottery within the system or who gets it and when. Whether you already have it installed or you're downloading and installing for the first time, it's still the same lottery. As they make the percentage higher, then more people get it. I'd just be patient for now.

**Comment by 3c7b1b91-0c9d-40a8-88bf-6e3c7f28b3e5** [comment]
> [@3c7b1b91-0c9d-40a8-88bf-6e3c7f28b3e5](https://github.com/3c7b1b91-0c9d-40a8-88bf-6e3c7f28b3e5) What the screenshot shows is that the experiment `BTMGoogleAuthWorkaroundRelease` is currently being rolled out to 25% of users. The assignment is random and controlled by the rollout system.
> 
> Basically the 25% means up to 25% of all users are going to get access. It's something of a lottery within the system or who gets it and when. Whether you already have it installed or you're downloading and installing for the first time, it's still the same lottery. As they make the percentage higher, then more people get it. I'd just be patient for now.

Thanks for sharing it.

**Comment by Saoiray** [comment]
@3c7b1b91-0c9d-40a8-88bf-6e3c7f28b3e5 to be clear on one thing though, it kind of checks for it whenever we launch Brave. So like when I replied to you last time, it wasn't available to me. I exited Brave and when I opened it again, it was there. I'm not saying that for people to spam it to try, but just to be clear about one of the ways it checks for it. 

The reason for the 25% aspect is they want to make sure those who are getting this experiment aren't going to see other things breaking. It would be bad to introduce a change to everyone all at once only to find out it might make something else worse.

**Comment by blueglyph** [comment]
For those who wish to understand what a _variation_ or a _seed_ means in this context, or are interested in how it works, see [this article](https://developer.chrome.com/docs/web-platform/chrome-variations). It's for Chrome but I believe the principle remains the same.

@Saoiray 
> So like when I replied to you last time, it wasn't available to me. I exited Brave and when I opened it again, it was there.

That's strange, I thought the experiment group you're in was persistent. From what I understand, but I could be wrong, the group assignment is stable for each browser, which means 25% of the clients currently have the `BTMGoogleAuthWorkaroundRelease` variation enabled, and that won't change until it switches to 50%, then 100% to activate more browsers (unless you uninstall it, scrub the config files, and then reinstall Brave).

I think it would be very unreliable if a gradual rollout could switch on and off on individual browsers several times, potentially every 30 minutes or whenever the browser is restarted. I assume you want a monotonic change in the subsets in order to get a reliable feedback, and more importantly, you want to limit the scope of a potential failure.

If it's correct, that means it's simply useless to try and restart the browser at all: the 75% remaining can only wait.

I have no idea when the switches to 50/100% are planned, but it can't be far off. You can see the current status [here](https://griffin.brave.com/?search=BTMGoogleAuthWorkaroundRelease).

**Comment by Archimetrix** [comment]
i am among those 25% and i assure that the problem is totally fixed as i am using it for more that 8 hours now and  no signouts till now , i restarted pc many times restart browser many time and also continusly using for 4 hours now . just wait 1 day i think within 1 day it will be available for all users . Thank you brave team for quickly solving this problem .❤️

**Comment by Saoiray** [comment]
@blueglyph I almost feel like I'm making too much noise (is what, my 3rd or so reply?) by answering about how Griffin/Finch works rather than having this be focused on the feedback from people having the issue and answering about improvements for those who have received it. So after this reply I'll try to stop. 

The way it works is it will kind of pre-emptively choose a batch of potential users. Then it ramps up. In other words, it typically won't just automatically be available to all 25%. The ramp time is determined by the devs. Otherwise the article you shared essentially highlights what I was trying to say: `"Every 30 minutes on desktop or mobile, or each time you start Chrome, the browser makes a request."` So it will automatically check over time or when you open Brave. 

My earlier phrasing could have been better but this is where there's a bit of randomness like I was referencing. One moment it might not be available to you but it can be available in the next, but only if you are on that chosen selection of users. And there is no way of knowing for sure if you're in that pre-selected group overall. But I see where my earlier reply could give a false assumption and have people keep trying to restart or something, so I'm glad you're bringing it up. 

Anyway, it's exciting to hear positive feedback from those getting the variation and that so far there's not been any negative reports from other types of issues. Hopefully won't be long for them to push more to 100%.

**Comment by bsclifton** [comment]
Thanks for confirming, @mdjubayerd1 😄 

And yes - apologies for not explaining what that value should be set to 😓 Folks with value set to `Enabled` are among the 25%. The ones who have `Default` don't have it yet.  I'll share the good news w/ the team

**Comment by bl1te** [comment]
I am on Brave 1.82.166 (Official build) (64-bit), Chromium 140.0.7339.133.
I have `BTMGoogleAuthWorkaroundRelease:Default` and it still logs me out of Google accounts.
Is it the correct line I'm looking at on `brave://version/`?

**Comment by SiLenCe-WB** [comment]
@bsclifton 

Any idea of how [this](https://github.com/brave/brave-browser/issues/49300#issuecomment-3299144333) could have fixed it for me? I'm still on v1.82.166.

**Comment by popy2k14** [comment]
> I am on Brave 1.82.166 (Official build) (64-bit), Chromium 140.0.7339.133. I have `BTMGoogleAuthWorkaroundRelease:Default` and it still logs me out of Google accounts. Is it the correct line I'm looking at on `brave://version/`?

You must have Enabled! Default means Disabled.
Just Wait until they rolled out this change on the servers for all. Currently just 25% Users of the release version have the fix (enabled). 

You don't have to install a new version. Your browser is contacting brave servers on startup or an interval to get the "update".

So just wait...
Hope the test runs good and we all get the fix soon.

**Comment by nastavoi** [comment]
I'm on latest Beta (Windows) and have this variation enabled since the announcement and so far so good, no log outs. Fingers crossed.

**Comment by spa31** [comment]
I am on 1.82.166 Chromium: 140.0.7339.133 (Official Build) (64-bit)  and I do not see the entire option BTMGoogleAuthWorkaroundRelease:Default

I have AllowCertainClientHintsStudy:Enabled and then the next one is BraveAdblockMobileNotificationsListDefault:Enabled but noting in between and nothing when I search for BTM.

**Comment by obisco4u** [comment]
I have the fix enabled on my browser, and I can confirm that so far I've not been logged out. Kudos to the dev team.

**Comment by blueglyph** [comment]
50% of browsers now, time for those who didn't have it to check again.

Also, I see that the version of Brave has also to 1.82.170 Chromium: 140.0.7339.186 (I suppose it's unrelated, though).

**Comment by bsclifton** [comment]
@SiLenCe-WB
> [@bsclifton](https://github.com/bsclifton)
> 
> Any idea of how [this](https://github.com/brave/brave-browser/issues/49300#issuecomment-3299144333) could have fixed it for me? I'm still on v1.82.166.

No unfortunately not - but glad you're fixed 😄 

If you have the fix, you'll see:
`BTMGoogleAuthWorkaroundRelease:Enabled`

Sorry I had left that out of the previous messages. And yes - good eye @blueglyph - we're up to 50% now 😄 
100% coming soon. Thanks for your patience

**Comment by CaseyLabs** [comment]
@bsclifton - Had high hopes, as at first it seemed it had worked. However, just rebooted and both Gmail and Github are now logged out (not just Google account impacting).

brave://version setting: `BTMGoogleAuthWorkaroundRelease:Enabled`
I'm on Brave Stable version: `1.82.166 Chromium: 140.0.7339.133 (Official Build) (64-bit)`

Is there any way I can provide debugging info? e.g. I've seen mentions of a histogram, but I'm uncertain how to set that up.

EDIT: I noticed earlier today that the flag was set to  `BTMGoogleAuthWorkaroundRelease:Default` for me, not sure if the change from Default to Enabled would have had an impact.

**Comment by bsclifton** [comment]
@CaseyLabs I think your most recent edit to the post helped share what the problem was

Having the value `Default` means fix is not enabled yet, I apologize; should have shared that. Now that you have `Enabled`, you should be good to go! 😄 You just need to sign in once again

When it comes to getting the information, you can open the following URL in Brave:
brave://histograms/Signin.BoundSessionCredentials

And then you can either download or just copy/paste.  What we'd see WITHOUT the fix was that ~2 hrs after a sign in happened a session terminate happened.

Keep us updated! I saw you posting a lot in the original thread. Thanks for all of your input through this process

**Comment by CaseyLabs** [comment]
@bsclifton - Gotcha! I've logged back in to Gmail/Github, will check in again tomorrow with the results. Thanks again for the follow-ups on this issue!

**Comment by johnny-official** [comment]
I'm so proud when I could become a part of 50%, thank Brave team.
<img width="898" height="291" alt="Image" src="https://github.com/user-attachments/assets/9d237b28-247e-45b6-9d81-04d3e7435b73" />

**Comment by szbly** [comment]
@bsclifton 
Can you please guide me to fix the "unable to connect to the internet" error when using the microphone? When I go to https://mictests.com/ it will show a microphone type selection panel and everything works fine but on other websites like google translate it gives an error because I can't select the microphone type.

**Comment by Saoiray** [comment]
@szbly this is not the appropriate place to ask on that. Please keep things on topic. There is an open Github at https://github.com/brave/brave-browser/issues/3725 related to your issue. Please keep this limited to the problem of Windows users that was getting logged out of sites.

**Comment by repulse-86** [comment]
i want to report the same thing. besides google.com, some websites i used to log in with google auth are also logged out everytime i close the browser except for youtube.com and facebook acc(which doesnt use google auth) which remain logged in

**Comment by CaseyLabs** [comment]
Follow-up ~9 hours later: booted up this morning, and Gmail/Github are still logged in. Looks like we may have a fix here! 🥳

@repulse-86 - check to see if this flag has been enabled yet in your browser:

- Browse to `brave://version`
- Search for `BTMGoogleAuthWorkaroundRelease`
  - If it is set to `Default`, the fix hasn't been rolled out to you yet
  - When it is set to `Enabled`, the issue should be resolved now

Status of the flag roll-out to users can be found here: https://griffin.brave.com/?search=BTMGoogleAuthWorkaroundRelease

**Comment by blueglyph** [comment]
Looks like it, indeed! The release with `BTMGoogleAuthWorkaroundRelease:Enabled` has kept my Gmail accounts for 4 hours, now.

**Comment by Fwindy** [comment]
Not yet 100% rolled out? This issue's impact is great, hoping for a full rollout as soon as possible.

**Comment by 3c7b1b91-0c9d-40a8-88bf-6e3c7f28b3e5** [comment]
> Not yet 100% rolled out? This issue's impact is great, hoping for a full rollout as soon as possible.

You can check it here in this status page: https://griffin.brave.com/?search=BTMGoogleAuthWorkaroundRelease

**Comment by ruukozuki** [comment]
I am being logged out of only Gmail
Windows 10 Pro
"Allow sites to save data on your device" CHECKED on brave://settings/content/siteData 
"Forget me when I close this site" NOT CHECKED on brave://settings/shields
Everything NOT CHECKED on brave://settings/clearBrowserData On Exit
Shields are DOWN on https://accounts.google.com
Shields are DOWN on https://mail.google.com

12:40pm Still logged in after restarting the browser
3pm Still logged in, PC shut down
6pm Logged out after booting PC 
7pm Still logged in after restarting PC
9pm still logged in after restarting the browser
10pm still logged in
11pm Logged out

**Comment by popy2k14** [comment]
> I am being logged out of only Gmail Windows 10 Pro "Allow sites to save data on your device" CHECKED on brave://settings/content/siteData "Forget me when I close this site" NOT CHECKED on brave://settings/shields Everything NOT CHECKED on brave://settings/clearBrowserData On Exit Shields are DOWN on https://accounts.google.com Shields are DOWN on https://mail.google.com
> 
> 12:40pm Still logged in after restarting the browser 3pm Still logged in, PC shut down 6pm Logged out after booting PC 7pm Still logged in after restarting PC 9pm still logged in after restarting the browser 10pm still logged in 11pm Logged out

Check the url `brave://version` if you have `BTMGoogleAuthWorkaroundRelease: Enabled`.
If not, wait.... It is a staged rollout.

**Comment by LiteraDev** [comment]
> It is a staged rollout.

Is there any estimate for when the rollout will increase and reach 100%? This issue is significantly inconvenient for many people.

**Comment by sky96111** [comment]
For those affected users assigned to the Default field trial, 
you can override Finch(Griffin) behavior by passing the parameter ``--force-fieldtrials=BTMGoogleAuthWorkaroundRelease/Enabled/`` to the program launch shortcut, until Brave team extends this parameter to all users.

**Comment by Fwindy** [comment]
> For those affected users assigned to the Default field trial, you can override Finch(Griffin) behavior by passing the parameter `--force-fieldtrials=BTMGoogleAuthWorkaroundRelease/Enabled/` to the program launch shortcut, until Brave team extends this parameter to all users.

I manually modified it a long time ago, but it didn't work, it still automatically logs out.

**Comment by blueglyph** [comment]
> For those affected users assigned to the Default field trial, you can override Finch(Griffin) behavior by passing the parameter `--force-fieldtrials=BTMGoogleAuthWorkaroundRelease/Enabled/` to the program launch shortcut, until Brave team extends this parameter to all users.

That goes against the idea of a progressive rollout, which is done to detect any potential issue, so definitely not a good advice.

**Comment by ruukozuki** [comment]
> For those affected users assigned to the Default field trial, you can override Finch(Griffin) behavior by passing the parameter `--force-fieldtrials=BTMGoogleAuthWorkaroundRelease/Enabled/` to the program launch shortcut, until Brave team extends this parameter to all users.

This caused it to be logged out more frequently

**Comment by johnny-official** [comment]
<img width="1076" height="379" alt="Image" src="https://github.com/user-attachments/assets/d43c0c56-00ac-4ec2-9656-dc27f18cbd69" />

<img width="323" height="252" alt="Image" src="https://github.com/user-attachments/assets/00eaa595-687d-4cd0-a11f-5b8700b6e75c" />

I'm so proud and happy to have been part of the 50% that could get out of that annoying problem. It worked for me, and I have not been logged out since yesterday til now.

Thank you, Brave team!

**Comment by 3c7b1b91-0c9d-40a8-88bf-6e3c7f28b3e5** [comment]
> For those affected users assigned to the Default field trial, you can override Finch(Griffin) behavior by passing the parameter `--force-fieldtrials=BTMGoogleAuthWorkaroundRelease/Enabled/` to the program launch shortcut, until Brave team extends this parameter to all users.

I understand that's not recommended after reading next comments, but I've done that without knowing it and it seems that the issue has been fixed by starting Brave with this shortcut.

**Comment by blueglyph** [comment]
> I understand that's not recommended after reading next comments,

To clarify: I just mean it's not a great idea to show that "trick" publicly. If a few individuals use it, it won't make the feedback useless, but since many users are impatient to get the fix a few hours earlier, ... 😅

So all I'm saying is, let the developers flip the switch when they think it's fine.

**Comment by bsclifton** [comment]
Thanks for the feedback so far! 😄 We are planning to expand this out to 100% today

The pull request to watch on GitHub is this one:
https://github.com/brave/brave-variations/pull/1510

Once this merges, we're live at 100% 😄 Kudos again to @goodov for finding the root cause - he's also working on a permanent fix (no experiment server input needed). Thanks also to everybody that helped diagnose and narrow down the issue.

Hopefully, it's shared some insight into how our experiment server (Griffin) works too 😃

**Comment by blueglyph** [comment]
> Hopefully, it's shared some insight into how our experiment server (Griffin) works too 😃

The bug itself wasn't too fun, but the process is indeed very interesting! To be frank, Griffin evoked something entirely different until I read the comments here and looked for more information.

Great job!

**Comment by jeffbeechg** [comment]
Thankyou to the smart Brave support gurus for fixing this.

**Comment by evilkingwc** [comment]
Thanks @goodov and @bsclifton for all your hard work in finding a solution for this. I’ve had this issue for months and still haven’t received the fix. I’m hoping it lands today. Please, when a permanent fix is in place, make sure to mention it in the changelog.

**Comment by Saoiray** [comment]
@evilkingwc this wouldn't be in the changelog typically because it's a fix on the backend overall. With the mention that this should be implemented today, I'd say fix should be completely out for everyone naturally. Assumption will be that some replies will be made by people here just to make sure it's known when it reaches 100%.

**Comment by bsclifton** [comment]
@evilkingwc we'll definitely create an issue to both 1) track the proper root cause and 2) track the permanent fix.  And that one will be captured in the release notes for sure 😄 Will leave that to @goodov who has been investigating.

This particular issue (fix w/ Griffin) can be closed once we hit 100%. Waiting to hear back from @kjozwiak - I think we have the approvals to roll it out. Thanks again for folks sharing feedback and bearing with us as it rolls out!

**Comment by harshDhiman3344** [comment]
Love to see y'all working on the issue for everyone, Thanks

**Comment by spa31** [comment]
Hello, did this fix has been rolled out at 100%?
Because the option is still in "default". 

<img width="533" height="55" alt="Image" src="https://github.com/user-attachments/assets/3747adfd-d9f0-460c-b99f-bef1efd4af0f" />

**Comment by blueglyph** [comment]
@spa31 Not yet. You can check the status there:
https://griffin.brave.com/?search=BTMGoogleAuthWorkaroundRelease

I suppose you'll need to wait for the US timezone.

**Comment by sky96111** [comment]
> That goes against the idea of a progressive rollout, which is done to detect any potential issue, so definitely not a good advice.

It depends. Of course, waiting for the 100% enable PR to be merged is the best solution.
https://github.com/brave/brave-variations/pull/1510

However, it is currently enabled at 50%. Unlike Griffin random assign, users can test and resolve issues more quickly and with greater scenario-specific focus.

People who searched for this issue and took action to override the field trial indicate that they have the ability to enable and disable it.




> This caused it to be logged out more frequently

This parameter only changes your field trial to ``BTMGoogleAuthWorkaroundRelease:Enabled``, it equals official solution.

If this does not work for you, then the fix provided by the brave team when expanding this parameter to 100% should also be ineffective for you.

**Comment by blueglyph** [comment]
> However, it is currently enabled at 50%. Unlike Griffin random assign, users can test and resolve issues more quickly and with greater scenario-specific focus.
> 
> People who searched for this issue and took action to override the field trial indicate that they have the ability to enable and disable it.

I think the idea behind is to collect feedback information and compare the sets of clients with and without the experiment, not only to see if it works but also if other symptoms appear. For that, a random selection works best.

So a few people forcing the experiment won't matter, but telling publicly to many lambda people how they can force it can potentially force it has greater chances to go against the process.

That being said, I'm surprised it's still at 50%. Either something came up or, more likely, they simply didn't have the time to analyze everything and make the decision in their timezone's yesterday.

**Comment by d-omkar0** [comment]
> Thanks for the feedback so far! 😄 We are planning to expand this out to 100% today
> 
> The pull request to watch on GitHub is this one: [brave/brave-variations#1510](https://github.com/brave/brave-variations/pull/1510)
> 
> Once this merges, we're live at 100% 😄 Kudos again to [@goodov](https://github.com/goodov) for finding the root cause - he's also working on a permanent fix (no experiment server input needed). Thanks also to everybody that helped diagnose and narrow down the issue.
> 
> Hopefully, it's shared some insight into how our experiment server (Griffin) works too 😃


I have received the flag as `BTMGoogleAuthWorkaroundRelease:Enabled` on my Brave instance and can confirm that the Google and other party accounts are all staying active. I have restarted the browser, kept it idle for 4hrs, restarted my workstation and the session is not terminating.

Thank you @bsclifton , @goodov and the Brave Team for fixing this issue and keeping the community updated at each step!

**Comment by Infi220** [comment]
How soon can we expect this fix rolled out to stable?

**Comment by 3c7b1b91-0c9d-40a8-88bf-6e3c7f28b3e5** [comment]
> > Thanks for the feedback so far! 😄 We are planning to expand this out to 100% today
> > The pull request to watch on GitHub is this one: [brave/brave-variations#1510](https://github.com/brave/brave-variations/pull/1510)
> > Once this merges, we're live at 100% 😄 Kudos again to [@goodov](https://github.com/goodov) for finding the root cause - he's also working on a permanent fix (no experiment server input needed). Thanks also to everybody that helped diagnose and narrow down the issue.
> > Hopefully, it's shared some insight into how our experiment server (Griffin) works too 😃
> 
> I have received the flag as `BTMGoogleAuthWorkaroundRelease:Enabled` on my Brave instance and can confirm that the Google and other party accounts are all staying active. I have restarted the browser, kept it idle for 4hrs, restarted my workstation and the session is not terminating.
> 
> Thank you [@bsclifton](https://github.com/bsclifton) , [@goodov](https://github.com/goodov) and the Brave Team for fixing this issue and keeping the community updated at each step!

Confirmed on my end as well, great work, team!

On my Mac, the issue never occurred. Interestingly, even on Windows (I use Mac, Windows, and Linux), my Google Workspace accounts (Enterprise, company domain) were unaffected. The bug only appeared in my personal Google accounts, and specifically on Linux and Windows. Professional accounts seem to have been entirely unaffected.

**Comment by webmube** [comment]
> How soon can we expect this fix rolled out to stable?

Yeah, I'm also the unlucky one still waiting for the feature. I guess nobody is gonna deploy it today, since it's Sunday.

**Comment by popy2k14** [comment]
Tested the fix with command line (yeah i know i should'nt but hey, a tester more).
I could report that the issue is gone for me. 
Still logged in, in my google account after a day.

**Comment by spa31** [comment]
> Tested the fix with command line (yeah i know i should'nt but hey, a tester more). I could report that the issue is gone for me. Still logged in, in my google account after a day.

Hello popy, could you please create a shared github page where you explain how to do this? Then plase add me on your page so it will be shared only with me and not in this page here, otherwise if you share it here it will be hidden.

I think I'm doing something wrong because it's not working when I add the option on the shortcut.

I'm tired to wait I have a lot of accounts for my work an other stuffs even my password handler all are completly insane requesting every 10 minutes to connect again as I use private keys to do that it's a complet nightmare. I need to get this working asap !

Thanks a lot !

**Comment by popy2k14** [comment]
@spa31 sorry dont have much time for a dedicated page, here is a screenshot of my windows shortcut:

<img width="545" height="696" alt="Image" src="https://github.com/user-attachments/assets/8c1cb884-09a3-494f-8278-df69d22f5bab" />

And in this post, you find the exact string to add (after the double quote, add a space!):

https://github.com/brave/brave-browser/issues/49300#issuecomment-3312464004

The full destination string is `"C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --force-fieldtrials=BTMGoogleAuthWorkaroundRelease/Enabled/`

After that, check with `brave://version`, the setting must be enabled `BTMGoogleAuthWorkaroundRelease:Enabled`

**Comment by spa31** [comment]
> [@spa31](https://github.com/spa31) sorry dont have much time for a dedicated page, here is a screenshot of my windows shortcut:
> 
> <img alt="Image" width="545" height="696" src="https://private-user-images.githubusercontent.com/6324597/492031723-8c1cb884-09a3-494f-8278-df69d22f5bab.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg0NzkwNDAsIm5iZiI6MTc1ODQ3ODc0MCwicGF0aCI6Ii82MzI0NTk3LzQ5MjAzMTcyMy04YzFjYjg4NC0wOWEzLTQ5NGYtODI3OC1kZjY5ZDIyZjViYWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDkyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA5MjFUMTgxOTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzBhNjEzNmMyYjhkZjI1NWQ3NGU3YWY5MDM0YWM3ZWViNjM4MmZiZDFjYjdlMzc1ZTIzNjI3OTgyYzM4ZDYwNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.IYhIymzf9Vg6KMt8c28nMxMtwN6dVvJ0YIKmnnX2l4c">
> Any in this post the exact string to add (after the double quote, add a space!):
> 
> The full destination string is `"C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --force-fieldtrials=BTMGoogleAuthWorkaroundRelease/Enabled/`
> 
> [#49300 (comment)](https://github.com/brave/brave-browser/issues/49300#issuecomment-3312464004)
> 
> After that check with `brave://version` the settings must be enabled `BTMGoogleAuthWorkaroundRelease:Enabled`

Thanks a lot it is working now... Schönen Sonntagsausklang :-)

**Comment by popy2k14** [comment]
@spa31 Nice to hear it's working.
Ebenfalls schönen Sonntag :-)

I hope they will roll out this workaround to all users soon, it's an rather annoying issue which affects a lot of users.

**Comment by bsclifton** [comment]
OK folks - it's rolled out to 100% now! 😄 Thanks for your patience - you should be able to close Brave + relaunch; then you'll be good to go.  If you had added the `--force-fieldtrials`, you can remove those

I'll keep this ticket open for a bit as folks start receiving the fix. Let us know how it goes!

**Comment by evilkingwc** [comment]
> [@evilkingwc](https://github.com/evilkingwc) we'll definitely create an issue to both 1) track the proper root cause and 2) track the permanent fix. And that one will be captured in the release notes for sure 😄 Will leave that to [@goodov](https://github.com/goodov) who has been investigating.
> 
> This particular issue (fix w/ Griffin) can be closed once we hit 100%. Waiting to hear back from [@kjozwiak](https://github.com/kjozwiak) - I think we have the approvals to roll it out. Thanks again for folks sharing feedback and bearing with us as it rolls out!

Thanks again! Could you please share the issue once it’s created so we can also keep track of it?
I’ve already received the fix on my end as well. Really appreciate the updates 🙏

**Comment by szbly** [comment]
After the update i returned everything to default and continued to be kicked out of google.com except youtube. what's even weirder is that i can use the microphone on youtube but on almost all other websites including google.com, google translate gives the error "cannot connect to the internet"

**Comment by 404hex** [comment]
here to update after the 100% roll out, I've been logged in for hours yesterday, closed the browser re-opened it still logged in, turned off the pc for the night, it's morning now and I'm still logged in, thank you for your efforts ❤️

**Comment by remd** [comment]
> here to update after the 100% roll out, I've been logged in for hours yesterday, closed the browser re-opened it still logged in, turned off the pc for the night, it's morning now and I'm still logged in, thank you for your efforts ❤️

Same here. Seems fixed for me so far.

Thanks for the hard work Brave team! ❤️

**Comment by CoccodrillooXDS** [comment]
Hello. Now that the rollout reached 100% and the flag was finally enabled on my browser, I wanted to confirm that I'm no longer getting logged out randomly or on browser re-open.

Thank you for fixing this issue

**Comment by spa31** [comment]
Hello, tried the official fix, it is working after 24 hours of closing brave, restarting my devices, cleaning cache. 

Thanks for the fix @brave-team

**Comment by sayeedjoy** [comment]
Thanks for the fix team, appreciate it

**Comment by ads-gpt** [comment]
Hi @bsclifton! The BTMGoogleAuth fix was enabled for my Brave installation when you rolled it to 50% of the users. Everything worked as intended, but I am not sure if this issue has crept in with the same update or something else, but except for the first account, all my other Gmail accounts are now signed out. When I try to log in again, I get this error as attached in the image. 

<img width="1343" height="729" alt="Image" src="https://github.com/user-attachments/assets/2cdb8bcd-204f-4e6d-a7a6-faf0276ffb77" />

I have cleared the site data, and again logging in with the accounts. I will update this with the result. I feel this is a related issue since it has happened after the previous update.

```
1.82.170 Chromium: 140.0.7339.186 (Official Build) (64-bit) 
BTMGoogleAuthWorkaroundRelease:Enabled
```

**Update 9 hours later: it is working as intended, still logged in. nothing to worry about. all good.**

**Comment by bsclifton** [comment]
OK folks - thanks again for bearing with us and reporting back as we rolled out the fix 😄 

I'm going to go ahead and close this issue as resolved.  As shared, we (@goodov @bsclifton) can create a new issue tracking a permanent fix.  We can share that information here when it's available so that folks can subscribe for info. Thanks!

**Comment by bsclifton** [comment]
OK folks - here's the issue where you can track a permanent fix 😄 

Turns out, this is an issue upstream in the Chromium code. @goodov created an issue which folks can track here:
https://issues.chromium.org/issues/445561475

Chromium does encounter the same root cause but the error is hidden from the customer. Basically, session is terminated too (ex: the histogram would fire on Chrome/Edge also) but there appears to be enough authorization information that the site (when sending cookies) can re-authorize and recreate a session. That leaves folks thinking they're still logged in.  Chromium team did assign this as a Priority 1 / Severity 2 and we've helped share more information with them 😄 

Let's use that issue to track. You can use the +1 button or the Star in Chromium's bug tracker to follow.

**Comment by bsclifton** [comment]
cc: @evilkingwc specifically on above w/ issue # ^^

**Comment by H644b** [comment]
I wanna say that this isn't just on windows I have this issue on mac as well running Brave 1.82.170

**Comment by rafaellirio85** [comment]
I'm using the Brave 1.82.172 and became impossible to use Facebook. It'll log me out after seconds. Google account issues are gone for now at least.

**Comment by bijkomune** [comment]
Hello,
The problem still hasn't been solved. The websites I've noticed are kick.com and google.com, the rest are working fine. 

Brave 1.82.172 (Official release) (64-bit)
Chromium: 140.0.7339.207

**Comment by hollons** [comment]
Thank you @H644b for reporting. @rafaellirio85 @bijkomune can you confirm your OS as well when convenient?

**Comment by rafaellirio85** [comment]
@hollons Win 11 Home 24H2 build 26100.6725

**Comment by sayeedjoy** [comment]
Hi, the issue is back again for Google Accounts. Hope you guys fix it soon

**Comment by bijkomune** [comment]
@hollons Windows 11 Pro build 26100.6584

**Comment by JMTIEM** [comment]
Hi, the issue is happening again.
I'm on Win 11 Pro v10.0.22631
Brave v1.82.172 with Chromium v140.0.7339.207

Hope you guys found a fix soon, thanks~

**Comment by UjsGit** [comment]
Solved now

**Comment by rafaellirio85** [comment]
@hollons @bsclifton after the update to the 1.83.109 yesterday the issue is back and worsened, now it'll immediately bump me out facebook after logging in. Worth to note, this update was a mess. Cleared all my configs, created several profiles that I've never used and was even preventing the browser to launch from the shortcut - I had to go to the folder and run Brave setup to fix it.

Edit: I've added facebook to the third-party cookies' exceptions and seems like it fixed but I don't feel comfortable doing so.

Edit2: Not working at all now. Can't even log in anymore.

**Comment by JMTIEM** [comment]
Now I can't even login to youtube, it redirects me to "/oops". What even did you break in last update lol

**Comment by goodov** [comment]
Can you please try to disable `Device Bound Session Credentials` and `Device Bound Session Credentials (Standard)` at

```
brave://flags/#enable-bound-session-credentials
brave://flags/#enable-standard-device-bound-session-credentials
```

and see if it helps?

**Comment by rafaellirio85** [comment]
Tried with no avail, @goodov. Facebook still booting me out with no reason.

**Comment by goodov** [comment]
This feels like unrelated issue.

**Comment by rafaellirio85** [comment]
It's the same issue that we're facing for weeks. We'll log in and after seconds we'll be logged out, having to log in again over and over, but now is happening with Facebook instead of Google accounts.

**Comment by goodov** [comment]
> It's the same issue that we're facing for weeks. We'll log in and after seconds we'll be logged out, having to log in again over and over, but now is happening with Facebook instead of Google accounts.

The fixed issue was about logging out after 2hrs of a perfectly valid session. The current immediate logout on FB/Google is another beast.

Please try to disable these features and see if anything helps:
```
brave://flags/#brave-domain-block-1pes
brave://flags/#brave-farbling
brave://flags/#brave-first-party-ephemeral-storage
brave://flags/#brave-provisional-tld-ephemeral-lifetime
```

**Comment by rafaellirio85** [comment]
I'll give it a try and let you know on the course of the day. Thanks @goodov

<img width="770" height="669" alt="Image" src="https://github.com/user-attachments/assets/17a6e633-a029-4564-96dd-58e48f8f9c45" />

As per your instructions, that's all that I have disabled at this moment.

**Comment by rafaellirio85** [comment]
Hi again @goodov. It worsened. 3 seconds after I click on my picture I'll redirected me to the login page. I have 2FA and my device is marked as safe so I just need to click on my pic to log in FYI.

**Comment by JMTIEM** [comment]
> Can you please try to disable `Device Bound Session Credentials` and `Device Bound Session Credentials (Standard)` at
> 
> ```
> brave://flags/#enable-bound-session-credentials
> brave://flags/#enable-standard-device-bound-session-credentials
> ```
> 
> and see if it helps?

I gave up and finally set Brave configs to default and it let me login to youtube and, apparently, has stopped logging out of sites. The thing is, though, that I hadnt changed any config in the last months of using brave, so there's no reason why it should've started acting weirdly other than a bug in a patch or something.

**Comment by rafaellirio85** [comment]
> I hadnt changed any config in the last months of using brave

Me neither, same config since day 0.

**Comment by rafaellirio85** [comment]
Hi @goodov. Seems like the issue is gone after disabling the 6 flags above.

**Comment by goodov** [comment]
> Hi [@goodov](https://github.com/goodov). Seems like the issue is gone after disabling the 6 flags above.

Would be nice if you can continue testing and restore them one by one and see which one triggers the issue.

**Comment by CaseyLabs** [comment]
@bsclifton @goodov - have there been any reports this week of this issue re-occuring? I've had the Gmail logout issue reoccur twice in the last 2 days (approximately after 24 hours), possibly after https://github.com/brave/brave-browser/issues/49977 was merged.

Current version:
Brave 1.83.112
Chromium: 141.0.7390.70

I tried running a histogram (`brave://histograms/Signin.BoundSessionCredentials`), but no data was produced:

<img width="1362" height="694" alt="Image" src="https://github.com/user-attachments/assets/753d8dfd-6070-4edd-bd9a-6d4152964a9d" />

**Comment by rafaellirio85** [comment]
> Would be nice if you can continue testing and restore them one by one

I would love to help but this will take me several hours as the issue may immediately happen or take a couple of hours.

**Comment by rafaellirio85** [comment]
@goodov, issue is back. Release 1.83.112, all flags above still disabled. I've noticed that this is happening after I wake up the computer from being idle. Didn't have the change to reenable the flags one by one yet either.

**Comment by bsclifton** [comment]
Definitely seems we have some more reoccurrences based on above... thanks @goodov for helping troubleshoot

Once we have enough to characterize, we should open a new issue. I believe the root cause will be something different this time as the Griffin fix is in place (`BTMGoogleAuthWorkaround:Enabled`) and we've also included the upstream fix at this point (see https://github.com/brave/brave-browser/issues/49837#issuecomment-3382386103)

**Comment by blueglyph** [comment]
Incidentally, this other bug #46876 has reappeared. I can't shake the idea the two are linked, but I couldn't get any response from the Brave team about that.

**Comment by rafaellirio85** [comment]
> I've noticed that this is happening after I wake up the computer from being idle.

Definitely is this what's triggering, just happened again today.

**Comment by rafaellirio85** [comment]
Now I'm running the 1.83.118 and the issue remains.
What I've noticed is that facebook is landing to this url when it fails to keep logged (https://www.facebook.com/login/device-based/login/?chrome_msite_lop=false&kaios_lop=false).

I hope this new info helps you guys to find a solution.
Cc @bsclifton @goodov

**Comment by goodov** [comment]
Please restore these flags into their default state:
```
brave://flags/#enable-bound-session-credentials
brave://flags/#enable-standard-device-bound-session-credentials
```

and on logout issue please look into `brave://histograms/Net.DeviceBoundSessions` histograms. If there's `Net.DeviceBoundSessions.DeletionReason`, would be nice to see it. If possible, you can dump all found histograms from this page, maybe something will highlight the issue..

My feeling now is that a non-prototype version of DBSC (the standardized one) is acting weird.

**Comment by rafaellirio85** [comment]
> and on logout issue please look into `brave://histograms/Net.DeviceBoundSessions` histograms. If there's `Net.DeviceBoundSessions.DeletionReason`, would be nice to see it.

That's what I'm seeing 

<img width="1101" height="332" alt="Image" src="https://github.com/user-attachments/assets/9fe7c0c3-c286-48f2-8093-7144fd87f147" />

**Comment by No-Oxygen** [comment]
Hi, 
I of course have the same issue than everyone here, but I juste noticed something, brave log me out of google accounts, plex etc... but also from the Brave Synchronisation. I'm getting logged out after my windows goes to Standby mode. Everytime I reopen my Laptop from sleep, i'm disconnected from every sites.

**Comment by CaseyLabs** [comment]
Encountered the issue again this morning, and my Histrograms is empty just like rafaellirio85's. Is there a way enable the histograms for report sharing?

**Comment by goodov** [comment]
Pls make sure to look into both of these histogram pages the moment logout happened (histograms are cleared on restart).

```
brave://histograms/Signin.BoundSessionCredentials
brave://histograms/Net.DeviceBoundSessions
```

**Comment by rafaellirio85** [comment]
Here, @goodov 

<img width="1507" height="914" alt="Image" src="https://github.com/user-attachments/assets/6f72459a-d576-4343-80dc-bf081e716b87" />

<img width="1415" height="932" alt="Image" src="https://github.com/user-attachments/assets/e2ed1082-aed9-4f12-aca3-1681cf555db5" />

<img width="1219" height="933" alt="Image" src="https://github.com/user-attachments/assets/9340a2c9-7ba7-4891-84ff-df67752c079b" />

**Comment by rafaellirio85** [comment]
Downloaded it too
```
- Histogram: Signin.BoundSessionCredentials.CookieRotationGenerateAssertionDuration recorded 41 samples, mean = 99.0 (flags = 0x41) [#]

0    ... 
41   -O                                                                        (1 = 2.4%) {0.0%}
52   O                                                                         (0 = 0.0%) {2.4%}
66   ----------O                                                               (10 = 24.4%) {2.4%}
84   ------------------O                                                       (18 = 43.9%) {26.8%}
107  ----------O                                                               (10 = 24.4%) {70.7%}
136  -O                                                                        (1 = 2.4%) {95.1%}
173  O                                                                         (0 = 0.0%) {97.6%}
220  -O                                                                        (1 = 2.4%) {97.6%}
280  ... 


- Histogram: Signin.BoundSessionCredentials.CookieRotationGenerateAssertionResult.Attempt0 recorded 41 samples, mean = 0.0 (flags = 0x41) [#]

0  -----------------------------------------O                                (41 = 100.0%)
1  ... 


- Histogram: Signin.BoundSessionCredentials.CookieRotationHttpResult.WithFreshChallenge recorded 41 samples (flags = 0x41) [#]

200  -----------------------------------------O                                (41 = 100.0%)


- Histogram: Signin.BoundSessionCredentials.CookieRotationHttpResult.WithoutChallenge recorded 43 samples (flags = 0x41) [#]

-2   --O                                                                       (2 = 4.7%)
401  -----------------------------------------O                                (41 = 95.3%)


- Histogram: Signin.BoundSessionCredentials.CookieRotationNetError recorded 2 samples (flags = 0x41) [#]

2  --O                                                                       (2 = 100.0%)


- Histogram: Signin.BoundSessionCredentials.CookieRotationResult recorded 43 samples, mean = 0.0 (flags = 0x41) [#]

0  -----------------------------------------O                                (41 = 95.3%)
1  --O                                                                       (2 = 4.7%) {95.3%}
2  ... 


- Histogram: Signin.BoundSessionCredentials.CookieRotationResult.BlockedRequest recorded 1 samples, mean = 0.0 (flags = 0x41) [#]

0  -O                                                                        (1 = 100.0%)
1  ... 


- Histogram: Signin.BoundSessionCredentials.CookieRotationResult.ConnectionChanged recorded 1 samples, mean = 0.0 (flags = 0x41) [#]

0  -O                                                                        (1 = 100.0%)
1  ... 


- Histogram: Signin.BoundSessionCredentials.CookieRotationResult.PreemptiveRefresh recorded 39 samples, mean = 0.0 (flags = 0x41) [#]

0  ---------------------------------------O                                  (39 = 100.0%)
1  ... 


- Histogram: Signin.BoundSessionCredentials.CookieRotationResult.Startup recorded 2 samples, mean = 1.0 (flags = 0x41) [#]

0  O                                                                         (0 = 0.0%)
1  --O                                                                       (2 = 100.0%) {0.0%}
2  ... 


- Histogram: Signin.BoundSessionCredentials.CookieRotationTotalDuration recorded 43 samples, mean = 635.9 (flags = 0x41) [#]

0    ... 
220  --O                                                                       (2 = 4.7%) {0.0%}
280  ... 
574  -------------------------------------O                                    (37 = 86.0%) {4.7%}
729  ----O                                                                     (4 = 9.3%) {90.7%}
926  ... 


- Histogram: Signin.BoundSessionCredentials.CookieRotationTotalDuration.BlockedRequest recorded 1 samples, mean = 850.0 (flags = 0x41) [#]

0    ... 
729  -O                                                                        (1 = 100.0%) {0.0%}
926  ... 


- Histogram: Signin.BoundSessionCredentials.CookieRotationTotalDuration.ConnectionChanged recorded 1 samples, mean = 674.0 (flags = 0x41) [#]

0    ... 
574  -O                                                                        (1 = 100.0%) {0.0%}
729  ... 


- Histogram: Signin.BoundSessionCredentials.CookieRotationTotalDuration.PreemptiveRefresh recorded 39 samples, mean = 648.0 (flags = 0x41) [#]

0    ... 
574  ------------------------------------O                                     (36 = 92.3%) {0.0%}
729  ---O                                                                      (3 = 7.7%) {92.3%}
926  ... 


- Histogram: Signin.BoundSessionCredentials.CookieRotationTotalDuration.Startup recorded 2 samples, mean = 273.5 (flags = 0x41) [#]

0    ... 
220  --O                                                                       (2 = 100.0%) {0.0%}
280  ... 


- Histogram: Signin.BoundSessionCredentials.CoveredNavigationRequestWasDeferred recorded 89 samples, mean = 0.0 (flags = 0x41) [#]

0  ------------------------------------------------------------------------O (89 = 100.0%)
1  ... 


- Histogram: Signin.BoundSessionCredentials.CoveredNavigationRequestWasDeferred.Success recorded 89 samples, mean = 0.0 (flags = 0x41) [#]

0  ------------------------------------------------------------------------O (89 = 100.0%)
1  ... 


- Histogram: Signin.BoundSessionCredentials.CoveredRequestWasDeferred recorded 9819 samples, mean = 0.0 (flags = 0x41) [#]

0  ------------------------------------------------------------------------O (9818 = 100.0%)
1  O                                                                         (1 = 0.0%) {100.0%}
2  O                                                                         (0 = 0.0%) {100.0%}


- Histogram: Signin.BoundSessionCredentials.CoveredRequestWasDeferred.Failure recorded 2883 samples, mean = 0.0 (flags = 0x41) [#]

0  ------------------------------------------------------------------------O (2883 = 100.0%)
1  ... 


- Histogram: Signin.BoundSessionCredentials.CoveredRequestWasDeferred.Success recorded 6936 samples, mean = 0.0 (flags = 0x41) [#]

0  ------------------------------------------------------------------------O (6935 = 100.0%)
1  O                                                                         (1 = 0.0%) {100.0%}
2  O                                                                         (0 = 0.0%) {100.0%}


- Histogram: Signin.BoundSessionCredentials.DeferredRequestDelay recorded 1 samples, mean = 1863.0 (flags = 0x41) [#]

0     ... 
1627  -O                                                                        (1 = 100.0%) {0.0%}
1996  ... 


- Histogram: Signin.BoundSessionCredentials.DeferredRequestUnblockTrigger.Success recorded 1 samples, mean = 0.0 (flags = 0x41) [#]

0  -O                                                                        (1 = 100.0%)
1  ... 


- Histogram: Signin.BoundSessionCredentials.ResumeThrottledRequestsTrigger recorded 1 samples, mean = 0.0 (flags = 0x41) [#]

0  -O                                                                        (1 = 100.0%)
1  ... 


- Histogram: Signin.BoundSessionCredentials.SessionCountOnInit recorded 1 samples, mean = 2.0 (flags = 0x41) [#]

0  ... 
2  -O                                                                        (1 = 100.0%) {0.0%}
3  ... 


- Histogram: Signin.BoundSessionCredentials.StorageReadError recorded 2 samples, mean = 0.0 (flags = 0x41) [#]

0  --O                                                                       (2 = 100.0%)
1  ... 
```

**Comment by No-Oxygen** [comment]
Hi again !

I found a way to get around the problem, I added a new user to my Windows 10 LTSC and switch to that user, since then, I no longer have the disconnection problem despite my PC going into sleep mode from time to time.

**Comment by rafaellirio85** [comment]
> despite my PC going into sleep mode from time to time.

Sadly this will not apply for me as Brave now is logging me out while I have it open and running.

**Comment by No-Oxygen** [comment]
> > despite my PC going into sleep mode from time to time.
> 
> Sadly this will not apply for me as Brave now is logging me out while I have it open and running.

It was the same for me before,
Now that I switch to a new user, I don't have the issue anymore. Despite restarting, stopping or wake up the pc.

**Comment by CaseyLabs** [comment]
Should we re-open this issue, or create a new issue?

**Comment by bsclifton** [comment]
@CaseyLabs can you please create a new issue and capture your findings there?

We can use that for tracking down the problem

**Comment by CaseyLabs** [comment]
@bsclifton - boom, done! 

https://github.com/brave/brave-browser/issues/50411

**Comment by khunpoom** [comment]
I still got this problem 2 minutes ago.

**Comment by yogabayusavira** [comment]
I've had this issue for about two months where Brave would randomly sign me out, especially all my Google accounts. A potential fix: my C: drive was almost full. Every time I opened Brave, it used around 3–5 GB of disk space and fill that gap. If I closed Brave with 0 bytes free on C:, I'd be logged out on the next launch. I've freed up space on C: and haven't seen the issue for a few days. Too early to confirm though, but it may be related.
