### ISSUE TITLE
Typing in the address bar of a new tab causes a segfault

### ISSUE THREAD

**Issue by DiamonDinoia** [brave/brave-browser#49486]
### Description

If I open a new tab and try to type any address in it, the browser closes. It seems to be a segfault.

Deleting the profile and starting over did not fix it. Disabling GPU does not fix it.

```
(brave:12576): dconf-WARNING **: 21:06:08.958: unable to open file '/etc/dconf/db/local': Failed to open file “/etc/dconf/db/local”: open() failed: No such file or directory; expect degraded performance
[12576:12576:0921/210609.514292:ERROR:dbus/object_proxy.cc:573] Failed to call method: org.kde.KWallet.isEnabled: object_path= /modules/kwalletd6: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
[12576:12576:0921/210609.514356:ERROR:components/os_crypt/sync/kwallet_dbus.cc:113] Error contacting kwalletd6 (isEnabled)
[12576:12576:0921/210609.515446:ERROR:dbus/object_proxy.cc:573] Failed to call method: org.kde.KLauncher.start_service_by_desktop_name: object_path= /KLauncher: org.freedesktop.DBus.Error.ServiceUnknown: The name org.kde.klauncher was not provided by any .service files
[12576:12576:0921/210609.515470:ERROR:components/os_crypt/sync/kwallet_dbus.cc:82] Error contacting klauncher to start kwalletd6
[12576:12576:0921/210609.740720:ERROR:dbus/object_proxy.cc:573] Failed to call method: org.kde.KWallet.close: object_path= /modules/kwalletd6: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
[12576:12576:0921/210609.740753:ERROR:components/os_crypt/sync/kwallet_dbus.cc:408] Error contacting kwalletd6 (close)
[12576:12576:0921/210610.368225:ERROR:components/dbus/xdg/request.cc:169] Request ended (non-user cancelled).
[12576:12576:0921/210610.430253:ERROR:components/sharing_message/sharing_service.cc:297] Device registration failed with fatal error
[0921/210617.156222:ERROR:third_party/crashpad/crashpad/snapshot/elf/elf_dynamic_array_reader.h:64] tag not found
[0921/210617.157152:ERROR:third_party/crashpad/crashpad/snapshot/elf/elf_dynamic_array_reader.h:64] tag not found
[0921/210617.157253:ERROR:third_party/crashpad/crashpad/snapshot/elf/elf_dynamic_array_reader.h:64] tag not found
[0921/210617.157325:ERROR:third_party/crashpad/crashpad/snapshot/elf/elf_dynamic_array_reader.h:64] tag not found
[0921/210617.160591:ERROR:third_party/crashpad/crashpad/snapshot/elf/elf_dynamic_array_reader.h:64] tag not found
[0921/210617.161627:ERROR:third_party/crashpad/crashpad/snapshot/elf/elf_dynamic_array_reader.h:64] tag not found
[0921/210617.161672:ERROR:third_party/crashpad/crashpad/snapshot/elf/elf_dynamic_array_reader.h:64] tag not found
[0921/210617.162043:ERROR:third_party/crashpad/crashpad/snapshot/elf/elf_dynamic_array_reader.h:64] tag not found
[0921/210617.162449:ERROR:third_party/crashpad/crashpad/util/process/process_memory_range.cc:75] read out of range
[0921/210617.162455:ERROR:third_party/crashpad/crashpad/util/process/process_memory_range.cc:75] read out of range
[0921/210617.176934:WARNING:third_party/crashpad/crashpad/snapshot/linux/process_reader_linux.cc:146] no stack mapping
[0921/210617.178357:ERROR:third_party/crashpad/crashpad/util/process/process_memory_range.cc:75] read out of range
[0921/210617.178368:ERROR:third_party/crashpad/crashpad/util/process/process_memory_range.cc:75] read out of range
[0921/210617.178381:ERROR:third_party/crashpad/crashpad/util/process/process_memory_range.cc:75] read out of range
[0921/210617.178385:ERROR:third_party/crashpad/crashpad/util/process/process_memory_range.cc:75] read out of range
/usr/bin/brave-browser: line 39: 12576 Segmentation fault         (core dumped) "$HERE/brave" "$@"
```

### Steps to reproduce

1. Open browser
2. type in address bar
3. CRASH!

### Actual result

Crash

### Expected result

no crash 

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.82.170 Chromium: 140.0.7339.186 (Official Build) (64-bit) 

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by ShivanKaul** [comment]
Can you send us a crash report and give us the crash report ID?

**Comment by DiamonDinoia** [comment]
Hi @ShivanKaul, the ID is: 5a380c00-bb02-810e-0000-000000000000

**Comment by k9janer** [comment]
I have a very similar problem with the latest version of Brave.

Brave crashes not just when typing into the address bar of a new tab - it crashes every time I type something into the address bar anywhere. However I can paste something into the address bar and open a URL that way.

```
jonas@localhost:~> brave-browser
[16855:16855:0923/165031.132437:ERROR:components/sharing_message/sharing_service.cc:297] Device registration failed with fatal error
[16927:16972:0923/165042.125147:ERROR:services/network/p2p/socket_manager.cc:137] Failed to resolve address for aa.online-metrix.net., errorcode: -105
[16927:16972:0923/165042.133267:ERROR:services/network/p2p/socket_manager.cc:137] Failed to resolve address for aa.online-metrix.net., errorcode: -105
[0923/165045.843056:ERROR:third_party/crashpad/crashpad/snapshot/elf/elf_dynamic_array_reader.h:64] tag not found
[0923/165045.844264:ERROR:third_party/crashpad/crashpad/snapshot/elf/elf_dynamic_array_reader.h:64] tag not found
[0923/165045.844384:ERROR:third_party/crashpad/crashpad/snapshot/elf/elf_dynamic_array_reader.h:64] tag not found
[0923/165045.844472:ERROR:third_party/crashpad/crashpad/snapshot/elf/elf_dynamic_array_reader.h:64] tag not found
[0923/165045.849042:ERROR:third_party/crashpad/crashpad/snapshot/elf/elf_dynamic_array_reader.h:64] tag not found
[0923/165045.849987:ERROR:third_party/crashpad/crashpad/snapshot/elf/elf_dynamic_array_reader.h:64] tag not found
[0923/165045.850172:ERROR:third_party/crashpad/crashpad/snapshot/elf/elf_dynamic_array_reader.h:64] tag not found
[0923/165045.850229:ERROR:third_party/crashpad/crashpad/snapshot/elf/elf_dynamic_array_reader.h:64] tag not found
[0923/165045.850960:ERROR:third_party/crashpad/crashpad/util/process/process_memory_range.cc:75] read out of range
[0923/165045.850971:ERROR:third_party/crashpad/crashpad/util/process/process_memory_range.cc:75] read out of range
[0923/165045.858938:WARNING:third_party/crashpad/crashpad/snapshot/linux/process_reader_linux.cc:146] no stack mapping
[0923/165045.860754:ERROR:third_party/crashpad/crashpad/util/process/process_memory_range.cc:75] read out of range
[0923/165045.860764:ERROR:third_party/crashpad/crashpad/util/process/process_memory_range.cc:75] read out of range
[0923/165045.860783:ERROR:third_party/crashpad/crashpad/util/process/process_memory_range.cc:75] read out of range
[0923/165045.860790:ERROR:third_party/crashpad/crashpad/util/process/process_memory_range.cc:75] read out of range
/usr/bin/brave-browser: line 39: 16855 Segmentation fault         (core dumped) "$HERE/brave" "$@"
jonas@localhost:~> 

```

This is with OpenSuse Slowroll using KDE Plasma.

Both the "Brave 1.82.170 (Official Build) (64-bit)" and the latest flatpak are affected

Operating System: openSUSE Tumbleweed-Slowroll 20250901
KDE Plasma Version: 6.4.5
KDE Frameworks Version: 6.17.0
Qt Version: 6.9.2
Kernel Version: 6.16.7-1.0.8.sr20250901-default (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 9 8945HS w/ Radeon 780M Graphics
Memory: 32 GiB of RAM (30,6 GiB usable)
Graphics Processor: AMD Radeon Graphics
Manufacturer: ASUSTeK COMPUTER INC.
Product Name: ASUS Vivobook S 15 M5506UA_M5506UA
System Version: 1.0

Uploaded Crash Report ID: 37750d00-bb02-810e-0000-000000000000

**Comment by k9janer** [comment]
The crashes don't happen anymore for me with the new version "Brave 1.82.172 (Official Build) (64-bit)/Chromium: 140.0.7339.207". 👍  Both the official build and the flatpak work fine now.

What about you @DiamonDinoia ?

**Comment by DiamonDinoia** [comment]
It seems it does not happen now. But I only tried opening tabs once. I will get back to it in a few days if this still happens.

**Comment by rebron** [comment]
Possibly fixed with https://github.com/brave/brave-browser/issues/49272 in 1.82.172

**Comment by kjozwiak** [comment]
@DiamonDinoia is the above still occurring once you've updated to `1.82.172` or higher? As @rebron pointed out via https://github.com/brave/brave-browser/issues/49486#issuecomment-3336673995, could be related to https://github.com/brave/brave-browser/issues/49272.

**Comment by DiamonDinoia** [comment]
It seems fixed now. I am not sure #49272 is the issue though. As I am not using anything else than US-ENG.

**Comment by kjozwiak** [comment]
> It seems fixed now. I am not sure [#49272](https://github.com/brave/brave-browser/issues/49272) is the issue though. As I am not using anything else than US-ENG.

Gotcha, thanks for the update @DiamonDinoia 👍 Looks like it has also been resolved for @k9janer as per https://github.com/brave/brave-browser/issues/49486#issuecomment-3324381737. I'll close this one off for now but please feel free to re-open a new issue if you run into any other crashes or the above starts occurring again.
