### ISSUE TITLE
YouTube videos show “Video unavailable” until hard reload (new player UI, Brave latest version)

### ISSUE THREAD

**Issue by YessBlack** [brave/brave-browser#50218]
### Description

Since a few days ago, YouTube appears to have rolled out a new player interface (with a different layout and updated controls).
Right after this change, YouTube videos on Brave started showing the following message:

> “Video unavailable. This content is not available. Please try again later.”

This occurs every time I open a YouTube video in a normal Brave window.

However:

- If I hard reload the page (⌘ + Shift + R), the video loads and plays normally.

- If I open the same video in Incognito mode, it also works fine.

- I’ve already cleared cache and cookies, and disabled all extensions (I only had two), but the issue persists.

- The issue only happens in Brave — YouTube works normally in other browsers on the same device.

- It seems to have started immediately after YouTube’s new player UI was introduced, so it may be related to how Brave’s Shields interacts with the updated video player.

- If I disable “Trackers & ads blocking” under Brave Shields, the videos load and play correctly, so the issue seems related to that specific Shield setting.

### Steps to reproduce

1. Open Brave (latest version).
2. Go to [youtube.com](https://youtube.com/)
3. Open any video
4. Observe that the message “Video unavailable” appears.
5. Press ⌘ + Shift + R → the video now loads properly.
6. Optionally, disable “Trackers & ads blocking” under Brave Shields → the video also loads normally.

<img width="1512" height="982" alt="Image" src="https://github.com/user-attachments/assets/98a3d416-dd6b-4ff5-a187-ef6632de931d" />

### Actual result

Videos show “Video unavailable” until a hard reload is performed.

### Expected result

YouTube videos should load and play immediately without requiring a hard reload.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

[Brave 1.83.118 (Official Build) (arm64)](https://brave.com/latest/)

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [x] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Disabling “Trackers & ads blocking” in Brave Shields makes the videos load normally.
The issue only occurs when Shields are enabled.
No related issues found.

**Comment by ryanbr** [comment]
We're aware of this, currently a fix in uBO experimental list. Waiitng on feedback. 

We can test in our experimental list also, can land a fix later today

**Comment by ryanbr** [comment]
Enable Experimental List in brave://settings/shields/filters and test in about a few hours.

Brave Experimental Adblock Rules - Version: 1.0.64 or better in `brave://components`

**Comment by ShivanKaul** [comment]
Is this fixed now @YessBlack and others?

**Comment by YessBlack** [comment]
Thanks, this issue is now resolved 🙌🏽

**Comment by howdev** [comment]
why? no, is not fixed. I have the latest brave. Need always reload

**Comment by mohdq123** [comment]
not yet solved ..help please??

**Comment by ryanbr** [comment]
Is it still occuring @mohdq123 ?

**Comment by mohdq123** [comment]
No i solve it with adblock rules modifications

**Comment by ryanbr** [comment]
Which modifcations?

**Comment by ifihaffto** [comment]
I'm getting it too.
Enabled the experimental adblock rules but no change.

Video says "this video is unavailable" with "Error code: 152 - 4"

Shields up or down, same result.

**Comment by mohdq123** [comment]
enable only easylist cookie :
settings > shields > content Filters

**Comment by ifihaffto** [comment]
No change unfortunately

**Comment by heyobscion** [comment]
Same here i still get the problem it was working fine till 5min ago

**Comment by ryanbr** [comment]
Resolved @heyobscion @ifihaffto @mohdq123 ? lots of changes upstream in the last 3-4 days
