### ISSUE TITLE
Change Brave font type or increase size to decrease chromium blurriness and jaggedy font rendering.

### ISSUE THREAD

**Issue by nhantrn** [brave/brave-browser#5032]
I'm on a Windows 10 machine and Chromium font rendering is pretty terrible. I'm hoping with Microsoft's incoming Edge, they'll help match the quality to that of CLearType and MacOS equivalent. But until then, please consider changing Brave's Muli font-type to another type that's better rendered for chromium. Or consider making the UI text size larger to prevent blurriness of bolded text and jaggedy of small text.

![brave font](https://user-images.githubusercontent.com/3202654/60060861-81a09380-96a7-11e9-85f1-8249bb5132f8.jpg)

You can see above the different of bold text. Brave chromium is just a blurry mess. The normal text on Edge and Firefox is also better rendered. It's more solid and readable whereas Brave chromium is thinly and jaggedy. The jaggedness is more apparent in smaller text sizes, for example in Brave setting page below:

![2019-06-24_172413__Bravesett](https://user-images.githubusercontent.com/3202654/60060998-13a89c00-96a8-11e9-9868-3fb9de3c601f.jpg)

It's just terrible to look at and hard to focus on the small text. Making the font size large would really help in the setting page. Please please improve it.

**Comment by bsclifton** [comment]
cc: @rossmoody @petemill

**Comment by rossmoody** [comment]
This would be a @jenn-rhim or @bradleyrichter call.

**Comment by VivaLaRobo** [comment]
I am also having this blurriness issue

**Comment by anacondaq** [comment]
Let me add several tips to blur fonts:
- this happens only on Windows 10, not linux distros, not macos on the same device (tested)
- turning off hardware accseleration will not help
- playing with different `flags://` will not help
- this happens on displays with not native resolution. I mean not 100% scaling. Mostly on laptops (any scale, 125%, 150%, 141% does not matter).
- turning off everything from drivers side - will not help too
- forcing to run browser on discreate GPU instead of integrated intel - will not fix the problem too
- using extensions for helping to fix the problem - will not help too.
- and last - Roboto font displayed very smooth and very good on all sites. While all others NOT so good.

What is really can fix the problem? 
Font rendering engine.

There is a browser called Cent Browser.
Cent browser has built-in feature to switch font rendering engine from GDI to DirectWrite (custom made flag by them)
This helps a lot.

![](https://i.imgur.com/qe15tJC.png)

This issue does not happen on many devices as far as I understand it after checking different devices.
Only laptops and very large displays with not 100% scaling.

On scale above 175% the issue not happened, because amount of pixels in resolution and scale factor is more than enough to fix all aliasing stuff.

**Comment by Snaxeko** [comment]
> 
> 
> Let me add several tips to blur fonts:
> 
>     * this happens only on Windows 10, not linux distros, not macos on the same device (tested)
> 
>     * turning off hardware accseleration will not help
> 
>     * playing with different `flags://` will not help
> 
>     * this happens on displays with not native resolution. I mean not 100% scaling. Mostly on laptops (any scale, 125%, 150%, 141% does not matter).
> 
>     * turning off everything from drivers side - will not help too
> 
>     * forcing to run browser on discreate GPU instead of integrated intel - will not fix the problem too
> 
>     * using extensions for helping to fix the problem - will not help too.
> 
>     * and last - Roboto font displayed very smooth and very good on all sites. While all others NOT so good.
> 
>     * the  issue not related to cleartype too.
> 
> 
> What is really can fix the problem?
> Font rendering engine.
> 
> There is a browser called Cent Browser.
> Cent browser has built-in feature to switch font rendering engine from GDI to DirectWrite (custom made flag by them)
> This helps a lot.
> 
> ![](https://camo.githubusercontent.com/bdb00e37260a9fcf6ae5d2f8ad9aaf0ba0d7f224/68747470733a2f2f692e696d6775722e636f6d2f71653135744a432e706e67)
> 
> This issue does not happen on many devices as far as I understand it after checking different devices.
> Only laptops and very large displays with not 100% scaling.
> 
> On scale above 175% the issue not happened, because amount of pixels in resolution and scale factor is more than enough to fix all aliasing stuff.

I also experience the issue at 100% scaling but 175 PPI (1080p 12.5" screen), the text is blurry especially while alt tabbing, it's probabl due to high DPI.

**Comment by LinusLeonard** [comment]
This is one of the two main issues I have with Brave, and the reason why Firefox will remain my default. Firefox UI font handling is perfect. It respects individual monitor DPI (I've got three monitors, they all have different DPI settings, and Firefox adjusts whenever I move a window from one monitor to another). Firefox UI also respects my ClearType settings. Brave doesn't.

**Comment by Snaxeko** [comment]
> This is one of the two main issues I have with Brave, and the reason why Firefox will remain my default. Firefox UI font handling is perfect. It respects individual monitor DPI (I've got three monitors, they all have different DPI settings, and Firefox adjusts whenever I move a window from one monitor to another). Firefox UI also respects my ClearType settings. Brave doesn't.

Chromium doesn't, I don't think the issue is related to Brave. I experienced the same with Vivaldi.

**Comment by jamesta696** [comment]
Any fix on this? 
I'm experiencing the same issues, Blurry Images & fonts/text on Brave Browser. I like this browser alot but being a developer and testing my work, it's not a good experience at all :( 

**Brave Version 1.19.88 Chromium: 88.0.4324.96 (Official Build) (64-bit)** - **Blurry**
![image](https://user-images.githubusercontent.com/14171094/106689428-d21aeb00-6584-11eb-8064-dd058a164572.png)

**FireFox** - **CLEAR**
![image](https://user-images.githubusercontent.com/14171094/106689520-f4146d80-6584-11eb-8d97-553114bd6937.png)

**Chrome** - **Blurry as well**
![image](https://user-images.githubusercontent.com/14171094/106689589-173f1d00-6585-11eb-80fe-4463ce58a1ed.png)

**Comment by monoblaine** [comment]
Here is the Chromium issue (from 2015):

https://bugs.chromium.org/p/chromium/issues/detail?id=534732

Since MS's new Edge is also Chromium based and suffering the same problem, I've got some hope that this problem will be fixed by them in a couple of months. or years.

**Comment by xsrvmy** [comment]
Edge has apparently fixed this.

**Comment by Ebemtb** [comment]
Today I wanted to use Brave as my default browser but I also have these blurry text and images on my external monitors of my laptop. The laptop screen is only occasionally used.

HP Dragonfly 13,3" Notebook (8MK86EA ) Windows 10 with notebook screen resolution = 3840 x 2160
Attached screens (daily use) via USBC dock: 2x QHD (2560 x 1440) resolution, notebook lit is closed (screen not active)

Tried several things but does not help, all other browsers (Chrome, Firefox, Edge) give sharp text and images.

Brave settings Hardware Acceleration on/off does not help
No relevant settinge found in Intel Graphics command Center
All drivers/bios, Brave up to date to latest version (Dec 20th 2021)

Hope there will be a solution soon. I will upgrade to Windows 11 in the next month, hope that W11 solves this issues.

**Comment by ValeZAA** [comment]
This is now fixed upstream.  https://issues.chromium.org/issues/40037624

**Comment by alvkn** [comment]
Does this item require any work from the Brave team after the upstream fix? I still see blurry fonts in Brave in some places, where Chrome does not have that issue.

Tested with Brave 1.76.73 (Chromium: 134.0.6998.45) and Chrome 134.0.6998.36 on Windows 11 with 125% scaling

**Comment by Ebemtb** [comment]
> Today I wanted to use Brave as my default browser but I also have these blurry text and images on my external monitors of my laptop. The laptop screen is only occasionally used.
> 
> HP Dragonfly 13,3" Notebook (8MK86EA ) Windows 10 with notebook screen resolution = 3840 x 2160 Attached screens (daily use) via USBC dock: 2x QHD (2560 x 1440) resolution, notebook lit is closed (screen not active)
> 
> Tried several things but does not help, all other browsers (Chrome, Firefox, Edge) give sharp text and images.
> 
> Brave settings Hardware Acceleration on/off does not help No relevant settinge found in Intel Graphics command Center All drivers/bios, Brave up to date to latest version (Dec 20th 2021)
> 
> Hope there will be a solution soon. I will upgrade to Windows 11 in the next month, hope that W11 solves this issues.

I haven't experienced any blurriness issues for a while now.

**Comment by ValeZAA** [comment]
> > Today I wanted to use Brave as my default browser but I also have these blurry text and images on my external monitors of my laptop. The laptop screen is only occasionally used.
> > HP Dragonfly 13,3" Notebook (8MK86EA ) Windows 10 with notebook screen resolution = 3840 x 2160 Attached screens (daily use) via USBC dock: 2x QHD (2560 x 1440) resolution, notebook lit is closed (screen not active)
> > Tried several things but does not help, all other browsers (Chrome, Firefox, Edge) give sharp text and images.
> > Brave settings Hardware Acceleration on/off does not help No relevant settinge found in Intel Graphics command Center All drivers/bios, Brave up to date to latest version (Dec 20th 2021)
> > Hope there will be a solution soon. I will upgrade to Windows 11 in the next month, hope that W11 solves this issues.
> 
> I haven't experienced any blurriness issues for a while now.

That is because Chromium fixed horrible bugs around ClearType and contrast formula. https://blogs.windows.com/msedgedev/2021/06/02/improving-font-rendering-in-microsoft-edge/

https://blogs.windows.com/msedgedev/2025/01/30/better-text-contrast-for-all-chromium-based-browsers-on-windows/

**Comment by xBounceIT** [comment]
i still do face this issue unfortunately

**Comment by zakius** [comment]
well, Chromium pulled the patch from Microsoft, but it only reduces the issue, never fixing it completely

I doubt it will ever get any better, especially with many devs and managers using high DPI screens and often non-windows machines overall
