### ISSUE TITLE
Can't sign in with firebase website with shields up

### ISSUE THREAD

**Issue by ericelliott** [brave/brave-browser#5075]
## Description 

We use Firebase for sign in with GitHub on [EricElliottJS.com](https://ericelliottjs.com). I'm unable to sign in with shields up in Brave. It works great with shields down.

## Steps to Reproduce

   1. Go to [EricElliottJS.com](https://ericelliottjs.com) and click "sign in" in the upper right hand corner.
   2. Make sure you have shields up.
   3. Click "Sign In with GitHub"

## Actual result:

Sign in fails and an error object is logged to the console:

```js
{
  code: "auth/web-storage-unsupported",
  message: "This browser is not supported or 3rd party cookies and data may be disabled."
}
```

## Expected result:

Delegated authentication is a common way to improve security and user privacy by reducing the available attack surface for nefarious collectors of usernames and passwords. I hope we can figure out how to enable commonly used authentication methods and still protect user privacy.

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

0.65.120 Chromium: 75.0.3770.90 (Official Build) (64-bit)
--
Revision | a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}
OS | Mac OS X

## Version/Channel Information:

Don't know. Don't have time to check.

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
Yes.

- Does the issue resolve itself when disabling Brave Rewards?
Don't know.

- Is the issue reproducible on the latest version of Chrome? 
No.

## Miscellaneous Information:

P.S. Using Brave as my default browser. Looking good. I have high hopes for the future of Brave and the BAT ecosystem.

**Comment by ryanbr** [comment]
Seems to have fixed itself

**Comment by rebron** [comment]
Closed, fixed by above commit.

**Comment by ryanbr** [comment]
Just a followup @ericelliott  enabling all cookies helps.

**Comment by btlechowski** [comment]
The issue is still reproducible with default shields settings.
![image](https://user-images.githubusercontent.com/34715963/61474977-0a9aaa00-a98a-11e9-986d-53024fcc9c80.png)

Note: Allowing all cookies fixes the issue.

Tested on

Brave | 0.67.110 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Ubuntu 18.04 LTS

**Comment by kjozwiak** [comment]
Reproduced on `macOS 10.14.5 x64` using the following build:

Brave | 0.67.117 Chromium: 76.0.3809.62 (Official Build) (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Mac OS X

**Comment by rebron** [comment]
@ryanbr Can you give this another look? Looks like an issue with something more than firebaseapp

**Comment by jcubic** [comment]
Not sure if this is the same but I've got error "The popup has been closed by the user before finalizing the operation." on https://terminal.jcubic.pl#chat when I try to login with GitHub using Firebase, I don't see anything in console.

**Comment by ryanbr** [comment]
Can you test in Brave-beta @jcubic ?

**Comment by ryanbr** [comment]
Not sure what causes it, but I could login via /login github in Brave-beta

**Comment by jcubic** [comment]
Tested on Brave beta, got the same error. But this time the popup was closed, in original brave (on Fedora) the popup remained open but without any visible stuff.

**Comment by ryanbr** [comment]
Okay, Just allow all cookies in sheilds. https://terminal.jcubic.pl/#chat

Related to blocking of cookies on coveralls.io.

**Comment by jcubic** [comment]
coveralls.io is just code coverage report, it's not related. The issue it with GitHub and Firebase. Only those, maybe some other domains from Firebase. Allowing 3rd party cookies is working, but it's not related to coveralls.io Google use lot of domains in their infrastructure.

Is it possible to enable 3rd party cookies for single domain? I've only one dropdown where you can enable or disable all or only 3rd party.

**Comment by jcubic** [comment]
For reference, maybe something will be able to rewrite Firebase login with this: [SO: Use Google Firebase Authentication without 3rd Party Cookies](https://stackoverflow.com/a/48781575/387194)

**Comment by indreklasn** [comment]
Any updates on the issue? I started getting this issue today when trying to login with Google auth with firebase. Works on Chrome.

**Comment by jcubic** [comment]
@indreklasn I think you need to enable 3rd party cookies for that page. The only solution I can think of is to have one global allow 3rd party cookie place where you can enable cookies from Google and/or Firebase. This may request to investigate what base domain firebase use that need 3rd party cookies, visit that domain and then enable 3rd party cookies so it will enable to use on all firebase websites. Maybe some extension (if brave allow extensions) that will enable Firebase login on any new website, without any other 3rd party cookie.

**Comment by indreklasn** [comment]
@jcubic I have already enabled cookies and disabled shields. :/

**Comment by ericelliott** [comment]
I'm seeing this now even with shields down. Signing in with Chrome works great.

**Comment by AoDev** [comment]
Facing the same issue here. I just want to link this issue from [firebase-js-sdk repo](https://github.com/firebase/firebase-js-sdk/issues/865).

**Comment by aormsby** [comment]
No idea if this helps, but here's a specific error message I recently got showing that seemingly all requests from 'googleapis.com' are blocked when shields are up. The site in question does use Firebase for authentication.

```
{"error":
    {"code":403,"message":"Requests from referer https://www.googleapis.com/ are blocked.","errors": 
       [{"message":"Requests from referer https://www.googleapis.com/ are 
            blocked.","domain":"global","reason":"forbidden"}],
    "status":"PERMISSION_DENIED"}}
```

I've recently been unable to sign in using google sign-in everywhere I've tried, and the browser even kicks me out of things I'm already signed into sometimes. :sad:

**Comment by bsclifton** [comment]
@aormsby do you have `Allow Google logins` enabled?  It's enabled by default, but you can check in brave://settings/socialBlocking

**Comment by aormsby** [comment]
Nope. I don't even see the option. Hopefully, I'm not missing some important detail here.

![Screen Shot 2020-01-09 at 18 22 39](https://user-images.githubusercontent.com/1312251/72063788-0fbf2d00-330d-11ea-9eb0-e5fccad58e5c.png)

![Screen Shot 2020-01-09 at 18 30 30](https://user-images.githubusercontent.com/1312251/72064280-2023d780-330e-11ea-9140-f5df48354724.png)

**Comment by bsclifton** [comment]
ah ok - that feature is only on 1.3 and newer (which is on our Beta channel)

**Comment by alexlouden** [comment]
> No idea if this helps, but here's a specific error message I recently got showing that seemingly all requests from 'googleapis.com' are blocked when shields are up. The site in question does use Firebase for authentication.

I just ran into this today, discovered that Brave changes the `referer` header on the request to googleapis.com (instead of myapp.com), so the referer restriction on the API key fails. See https://console.developers.google.com/apis/credentials under "Website restrictions". I'm just going to catch this error and show a message to the user explaining what's happening.

![image](https://user-images.githubusercontent.com/1332954/72414333-ed199200-37ac-11ea-95ee-f1757f1f9db0.png)

**Comment by gkgrepo** [comment]
I was getting a 403 error message as well as follows 
![Screenshot - 2_13_2020 , 2_18_48 PM](https://user-images.githubusercontent.com/59545567/74470085-d7f75800-4e6b-11ea-9410-01c320128c17.jpg).. 

I had to disable "blocking cross-site cookies" to allow all cookies to get this to work.. 

![Screenshot - 2_13_2020 , 2_13_31 PM](https://user-images.githubusercontent.com/59545567/74470191-0ecd6e00-4e6c-11ea-88cf-ea1731966b36.jpg)

![Screenshot - 2_13_2020 , 2_13_10 PM](https://user-images.githubusercontent.com/59545567/74470210-15f47c00-4e6c-11ea-8875-80f498c719d9.jpg)

**Comment by dginovker** [comment]
No longer works, here's a project you can test on as well to get the web-page's source code: https://github.com/armand1m/react-firebase-authentication-medium

**Comment by fmarier** [comment]
We've just made a change to how we modify the referrer on cross-origin `POST` requests (https://github.com/brave/brave-core/pull/5613). This might address the underlying issue here.

Would anybody be able to test again using [Brave Nightly](https://brave.com/download-nightly/)?

**Comment by jperasmus** [comment]
Only works for me if I change the default "Only block cross-site cookies" to "Allow cookies" in the brave://settings/shields settings. Obviously not ideal.

**Comment by fmarier** [comment]
Aside from the referrer problems (now fixed), there is also a problem due to third-party cookies: https://github.com/brave/brave-browser/issues/10367

**Comment by pes10k** [comment]
closed with https://github.com/brave/brave-core/pull/5952

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.12.104 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Windows 10 OS Version 1903 (Build 18362.959)

```
Reproduced issue in 1.11.x
![image](https://user-images.githubusercontent.com/38657976/88699349-dae9ba80-d124-11ea-9161-3942fe231c50.png)
```
Qi {code: "auth/web-storage-unsupported", message: "This browser is not supported or 3rd party cookies and data may be disabled."}
```

- Verified STR from the description able to log in the website with default shield settings and there is no `3rd party cookies and data may be disabled` message displayed in the console

![image](https://user-images.githubusercontent.com/38657976/88699528-1c7a6580-d125-11ea-8b73-96039136647f.png)
