### ISSUE TITLE
favicon for verified vimeo publisher is incorrect

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5720]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/4391

The favicon for a verified Vimeo publisher is incorrect in the panel, which means it is also incorrect in ac table and tips table. 

## Steps to Reproduce

   1. Navigate to a verified vimeo publisher.
   2. Open panel, view the favicon displayed in panel. Note, it does not match icon on verified publisher's page.
   3. View a video so that it gets added to your AC table.
   4. Tip the publisher.
   5. See same favicon on Tip and AC tables.

Note - if you repeat tests for unverified publisher, you correctly see generic vimeo favicon. This is expected.

## Actual result:
Favicon for verified vimeo publisher does not match icon on their page.

![Screen Shot 2019-08-19 at 10 39 19 AM](https://user-images.githubusercontent.com/28145373/63276543-947fb080-c271-11e9-9bf7-25d79e71bce1.png)

![Screen Shot 2019-08-19 at 10 44 01 AM](https://user-images.githubusercontent.com/28145373/63276555-96e20a80-c271-11e9-8385-8a179ceee386.png)

## Expected result:
Correct vimeo favicon on panel, ac, and tips tables.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.68.130 Chromium: 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? 0.67.x n/a, but 0.68.x (RC) yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? unsure, probably yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by LaurenWags** [comment]
examples:
https://vimeo.com/willchristiansen
https://vimeo.com/hawaii
https://vimeo.com/pandapoles

**Comment by LaurenWags** [comment]
per @NejcZdovc:
wrong icon is coming from https://i.vimeocdn.com/portrait/6979171_640x640.webp
which is this user https://vimeo.com/user6979171
which redirects to https://vimeo.com/willchristiansen - which uses this icon https://i.vimeocdn.com/portrait/6040298_640x640.webp

**Comment by NejcZdovc** [comment]
+1 from https://github.com/brave/brave-browser/issues/5752

**Comment by masparrow** [comment]
Nb. I have raised #6059 to describe the cached favicon change needed.

**Comment by emerick** [comment]
Fixed by https://github.com/brave/brave-core/pull/6955

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.18.57 Chromium: 87.0.4280.66 (Official Build) beta (64-bit)
-- | --
Revision | fd98a29dd59b36f71e4741332c9ad5bda42094bf-refs/branch-heads/4280@{#1432}
OS | Windows 10 OS Version 2004 (Build 19041.572)

```
- Issue is not fixed, logged a follow-up issue https://github.com/brave/brave-browser/issues/12781
