### ISSUE TITLE
Linux RPM repository doesn't provide updates

### ISSUE THREAD

**Issue by paulcarroty** [brave/brave-browser#6036]
## Description 

Release Channel v`0.68.138`, the version in repository - `0.68.132`. OS - Fedora 30.

## Steps to Reproduce
   1. https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux
   2. `# dnf update` 

## Actual result:

```
Name         : brave-browser
Version      : 0.68.132
Release      : 1
Architecture : x86_64
```

**Comment by NumDeP** [comment]
Hi @paulcarroty You have to state which particular distro you're using it on though I think it may be Fedora. I'm using it on OpenSuse and I don't know how soon the update came as I manually check for updates but look - 

![Screenshot 1](https://user-images.githubusercontent.com/31957540/65155033-6fbf5a00-da24-11e9-91ed-dcc62a7eee61.png)

**Comment by paulcarroty** [comment]
Thx @NumDeP, yeah, now it provide `0.68.138-1`. Let's test for newest version, then I'll close this.

**Comment by NumDeP** [comment]
There's one more issue left open for [0.69.x](https://github.com/brave/brave-browser/milestone/43), so yeah let's see how long it takes to arrive.

One other thing @paulcarroty you didn't state what the fault was. Did you have your OS set to download updates manually or do you reckon Brave just took that long to push the update to Linux?

**Comment by bsclifton** [comment]
cc: @mbacchi for info on why this may have taken a while to publish

**Comment by paulcarroty** [comment]
@NumDeP I've checked it manually 3-4 times, also OS downloads updates metadata automatically. It's definitely the Brave repository issue.

**Comment by mbacchi** [comment]
I use Fedora 30 as my primary OS, and was updated immediately to the latest (`v0.68.138`) on 9/16 which was when we released that version. You might try running `sudo dnf clean all && sudo dnf update brave-browser` to see if that downloads the latest.

**Comment by paulcarroty** [comment]
Got `139-1` update, seems like it works now.

**Comment by paulcarroty** [comment]
Latest release - `0.69.128`, `0.68.139` in Brave repository. So, this issue is still actual.

https://github.com/brave/brave-browser/releases/tag/v0.69.128

**Comment by NumDeP** [comment]
I wonder if it's because it's a pre-release for users to manually install and the automatic push happens on the weekdays. 

I imagine it's rather a laborious task for the persons who have to officially push this. I mean you have the nightly then you have the dev, then you have the beta then you have the pre-release, then you have the official release of the pre-release in case there's a few hotfixes. 

I figured if the beta version was to practically mitigate any major bugs, what's the point in have a pre-release of the "Release" version?

**Comment by rebron** [comment]
Closing. You have the latest. The one you're pointing to is coming soon.
