### ISSUE TITLE
Untranslated text on connect hardware screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#6037]
## Description 

Untranslated text on connect hardware screen

## Steps to Reproduce

   1. Create cryptowallet account
   2. Go to profile and connect hardware 
   3. Connect hardware screen has an untranslated text `[object Object]`

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/64987907-42de3c00-d898-11e9-95ad-ca479c9f4afc.png)

## Expected result:
All text should be translated

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.70.93 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by ryanml** [comment]
Awaiting deployment, fixed on dev:

<img width="435" alt="Screen Shot 2019-09-21 at 1 59 43 PM" src="https://user-images.githubusercontent.com/8732757/65379136-19e2f000-dc78-11e9-8f97-85ca38965eee.png">

**Comment by ryanml** [comment]
This is fixed on the latest release

**Comment by kjozwiak** [comment]
Verification **PASSSED** on `macOS 10.14.6 x64` using the following build:

Brave | 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)

Used `Crypto Wallets - Version: 1.0.9` for the following checks:

<img width="432" alt="Screen Shot 2019-10-07 at 1 47 54 AM" src="https://user-images.githubusercontent.com/2602313/66287779-00ab8780-e8a5-11e9-80b9-509a935fdcbe.png">
<img width="441" alt="Screen Shot 2019-10-07 at 1 47 49 AM" src="https://user-images.githubusercontent.com/2602313/66287780-00ab8780-e8a5-11e9-8f78-f50a0b7aac58.png">

**Comment by GeetaSarvadnya** [comment]
The issue is still reproducible in windows 10 x64 - `0.69.132`

![image](https://user-images.githubusercontent.com/38657976/66296366-06d44f00-e90b-11e9-90ab-7e683ddb842a.png)

**Comment by kjozwiak** [comment]
@GeetaSarvadnya can you include the STR you used? Can't seem to reproduce on my Win 10 x64 machine.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Linux

* Verified text is translated on `Crypto Wallets - Version: 1.0.9`
![image](https://user-images.githubusercontent.com/17010094/66346150-85d38280-e91f-11e9-9219-7c4a4cd44792.png)

**Comment by srirambv** [comment]
Can't reproduce on Windows. Looks fixed on `Crypto Wallets - Version: 1.0.9`
![image](https://user-images.githubusercontent.com/17010094/66349858-d4851a80-e927-11e9-885d-017fba574e00.png)
