### ISSUE TITLE
sometimes can't select wallets when connecting to ledger nano

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#6168]
## Description 

Sometimes when you connect the Ledger Nano via `brave://wallets`, you won't be able to select any of the accounts that are associated with the ledger. When you run into this issue, you'll basically need to `Forget this device`, close `brave://wallets` and attempt a connection again.

## Steps to Reproduce

   1. launch `0.69.128 CR: 77.0.3865.75` and open `brave://wallet`
   2. click on `Create` under `New Local Wallet`
   3. enter your password and click on `Remind me later` under `Secret Backup Phrase`
   4. click on the `My Accounts` avatar --> `Settings` --> `Connect Hardware Wallet`

The above is basically the STR to start the process of getting your device connected. However, this only happens sometimes so the STR are not 100%.

## Actual result:

![selectAccountWallet](https://user-images.githubusercontent.com/2602313/65624361-b3234680-df97-11e9-8327-a22a331eeee4.gif)

## Expected result:

Should be able to select your wallets via the ledger once connected.

## Reproduces how often: 

I've only ran into this ~3-4 times but it's definitely a bug that happening here and there.

## Brave version (brave://version info)

Brave | 0.69.128 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | macOS Version 10.14.6 (Build 18G95)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A` (not released on release)
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @brave/legacy_qa

**Comment by bbondy** [comment]
Same as metamask?

**Comment by kjozwiak** [comment]
@bbondy not sure as this is pretty hard to reproduce. I can spend sometime tomorrow and see if I can reproduce this on MM. CCing @srirambv in case he's seen the above on MM as he also mentioned he reproduced the above in Brave when going through Crypto Wallets.

**Comment by srirambv** [comment]
Reproduced on Linux

**Comment by kjozwiak** [comment]
> Reproduced on Linux

Using MM or CW?

**Comment by girino** [comment]
Same occurs here. OSX high sierra, Brave Version 0.70.121

**Comment by ethgasstation** [comment]
same problem here OSX, Brave V 1.0

**Comment by danielheyman** [comment]
Had the same problem with OSX Mojave, Brave v1.01. Forgetting the device and refreshing the page fixed the problem, but it isn't intuitive unless you find this Github thread.

**Comment by jakehemmerle** [comment]
Not perfect but was able to get this to work after a little while on my Ledger Nano X. Brave Dev Version 1.11.82

**Comment by lukemulks** [comment]
Reproduced this on Linux Fedora 

```
Brave | 1.12.87 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Linux
```

I was able to eventually unlock on my 3rd attempt to connect. 
In each attempt, I would try to select the address from my Nano. If I was unable to, I'd disconnect and forget the device, then reattempt. 

I do not recall doing anything special in order to get it to work on the 3rd attempt. 

Noticeable issue on hover in dark mode, with rows turning completely white (with the text being white, the address becomes hidden on hover). 

When selecting the address does not work, it appears that the feature is unable to register the click action, and that there's no keyboard equivalent to manually attempt to tab and select the radio button w/o the mouse.  

I did not do anything special on the 3rd attempt. It's a bit puzzling as the same steps were followed each time, but for some reason it just seemed to work on the 3rd try. 

This bug is pretty rough and I suspect has a high likelihood of negatively impacting user confidence and feature adoption if encountered during first run/setup. Might be a good candidate for UX polish/prioritization if/when cycles free up for that work.

**Comment by srirambv** [comment]
This is an annoying bug, especially while testing. Sometimes it takes me more than 10 attempts to select the address or needs multiple reconnects 

> Noticeable issue on hover in dark mode, with rows turning completely white (with the text being white, the address becomes hidden on hover).

@lukemulks  that's a known issue which should be fixed with the final dark theme updates

**Comment by KevinGabbert** [comment]
happens to me on Brave even now  You'd think this would be solved.  after about 7 tries still can't click it

**Comment by srirambv** [comment]
@ryanml any idea if this is fixed with MM V8 rebase?

**Comment by nestoregon** [comment]
Same, PopOS 20.04
