### ISSUE TITLE
Custom text isn't translated 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#6533]
## Description 

Follow up to #6289. Custom text implemented as part of #6485 isn't translated

## Steps to Reproduce

   1. Install component `0.1.17`
   2. Set device locale to French
   3. Disclosure message isn't translated
   4. `Choose a type to set up:` text isn't translated 
   5. `Back button` text isn't translated on create/restore wallet pages
   6. Password info message on create/restore wallet pages aren't translated
   

## Actual result:

Dislosure message
![image](https://user-images.githubusercontent.com/17010094/67047622-ab6f4180-f100-11e9-8933-1accd1a1c523.png)
`Choose a type to set up:`
![image](https://user-images.githubusercontent.com/17010094/67047642-b1fdb900-f100-11e9-9160-5e58d39586ed.png)
Back & password info message on create page
![image](https://user-images.githubusercontent.com/17010094/67047687-c477f280-f100-11e9-8f05-3f16f748174c.png)
Back & password info message on restore page
![image](https://user-images.githubusercontent.com/17010094/67047710-ce99f100-f100-11e9-8046-53f4813460ce.png)

## Expected result:
All custom text should be translated

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit)
-- | --
Revision | 416d6d8013e9adb6dd33b0c12e7614ff403d1a94-refs/branch-heads/3865@{#884}
OS | Linux

Ethereum component version `0.1.17`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bbondy** [comment]
I believe this was fixed via a localization order. Works for me.  I tried on Release channel too. 
<img width="781" alt="Capture d’écran 2020-12-15 à 3 09 39 PM" src="https://user-images.githubusercontent.com/831718/102267278-ab76f700-3ee7-11eb-8473-da9d76dc27f6.png">

I'm not sure at what point it was fixed but I'll just put it in the Beta Milestone so it gets verified by QA.

**Comment by srirambv** [comment]
This doesn't seem to fix all the custom text. Custom text on `Create Account` & `Restore Account` still has untranslated text


https://user-images.githubusercontent.com/17010094/103613360-59d9ef00-4f1e-11eb-95bf-ccb7b2897b68.mp4


Will log a follow up issue for the untranslated text in create and restore account page.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.19.74 Chromium: 87.0.4280.101 (Official Build) beta (64 Bit) | 1.19.74 Chromium: 87.0.4280.101 (Official Build) beta (x86_64) | 1.19.74 Chromium: 87.0.4280.101 (Official Build) beta (64 Bit)
-- | -- | -- | -- | 
Revision | `9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}` | `9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}` | `9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}`
OS | Windows 10 OS Version 2009 (Build 9042.685) | macOS Version 10.15.7 (Build 19H2) | Linux
Component | `1.0.24` | `1.0.24` | `1.0.24`
Screenshot| <img width="1046" alt="Screenshot 2021-01-05 at 10 23 14" src="https://user-images.githubusercontent.com/17010094/103636025-4e4bef80-4f41-11eb-8049-8390c3d650c8.png"> | <img width="1046" alt="Screenshot 2021-01-05 at 10 23 14" src="https://user-images.githubusercontent.com/17010094/103636305-b13d8680-4f41-11eb-94aa-25e993fae66a.png"> | <img width="1059" alt="Screenshot 2021-01-05 at 10 26 05" src="https://user-images.githubusercontent.com/17010094/103635997-4429f100-4f41-11eb-94a6-adf5a90ec97f.png">

------
Logged #13367 as a follow-up issue for missing translations
