### ISSUE TITLE
Windows - Missing quick taskbar actions

### ISSUE THREAD

**Issue by pilsnerbeer** [brave/brave-browser#6953]
## Description 
Brave doesn't seem to have taskbar options that other browsers do. Mainly, those are "new window/tab" and "new private window". I use them frequently and miss those in Brave.

Here are shortcuts in Firefox: (right click or swipe up on icon in taskbar)

![Screenshot_1](https://user-images.githubusercontent.com/36133540/68956536-930a4980-07c8-11ea-9693-d04289d87c94.png)

Brave only has this one, which opens up a new window:

![Screenshot_2](https://user-images.githubusercontent.com/36133540/68956573-a6b5b000-07c8-11ea-9e12-e4e974e9d4c0.png)

## Steps to Reproduce

   1. have brave in taskbar
   2. right click on the icon

## Actual result:
![Screenshot_2](https://user-images.githubusercontent.com/36133540/68956573-a6b5b000-07c8-11ea-9e12-e4e974e9d4c0.png)

## Expected result:
Have the usual shortcuts
![Screenshot_1](https://user-images.githubusercontent.com/36133540/68956536-930a4980-07c8-11ea-9693-d04289d87c94.png)

## Reproduces how often: 
always

## Brave version (brave://version info)

1.0.0 Chromium: 78.0.3904.97 (Official Build)
Windows 10 OS Version 1903

**Comment by TheAresjej** [comment]
Same on **Windows 10 1909** & **Brave 1.1.23**
![image](https://user-images.githubusercontent.com/19390797/71787235-a346e400-3015-11ea-939b-e47a133995c8.png)

**Comment by TheAresjej** [comment]
Fixed on **Windows 10 1909** & **Brave 1.2.41** @bsclifton 
![image](https://user-images.githubusercontent.com/19390797/71979710-a9f47780-321e-11ea-92c4-752f1e726fc6.png)

**Comment by bsclifton** [comment]
Thanks for confirming, @TheAresjej 😄 @pilsnerbeer can you verify too? If it looks good, we can close this issue out

**Comment by pilsnerbeer** [comment]
I'm still not able to see this on Brave Version 1.2.42 and Windows 1903 build.

**Comment by rebron** [comment]
@pilsnerbeer Can you try pinning and unpinning Brave? Does that resolve the issue?

**Comment by pilsnerbeer** [comment]
Yes it's working now! Thanks. The issue is fixed.
