### ISSUE TITLE
Brave.P3A.SentAnswersCount defaults to highest value

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#7261]
## Description 
Found while testing #6285 

While testing P3A on a clean profile, I noticed that `Brave.P3A.SentAnswersCount` defaults to 3 (which is the highest value) in local state. Per discussion with @iefremov this is a bug.

## Steps to Reproduce

   1. Launch 1.1.x with clean profile.
   2. Navigate to brave://local state.

## Actual result:
see something like this

```
         "Brave.P3A.SentAnswersCount": {
            "sent": false,
            "value": "3"
         },
```

3 corresponds to a response of `10 or more` per stats

## Expected result:
I'd expect it to default to the lowest value

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 1.1.18 Chromium: 79.0.3945.56 (Official Build) (64-bit)
-- | --
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
cc @iefremov @bsclifton @brave/legacy_qa

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/brave-core/pull/4145

(specifically, 1.1 was fixed with https://github.com/brave/brave-core/commit/1be245928a8c8f249254ebbbda4510ef37eb2cf0)

**Comment by LaurenWags** [comment]
Per discussion with @iefremov and @bsclifton since this issue is still occurring in 1.1.x, logged a follow up issue, https://github.com/brave/brave-browser/issues/7306, and marking this one as `QA/No`.
