### ISSUE TITLE
Rename Incognito to Private

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#738]
## Description 

Rename Incognito to Private tabs

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/43991369-75af95f2-9d39-11e8-89f6-54620274daa9.png)

Jump list needs to have a new icon as well
![image](https://user-images.githubusercontent.com/17010094/43991387-ae039b42-9d39-11e8-997e-aa3d8194bd4c.png)
Including incognito icon in a incognito tab
![image](https://user-images.githubusercontent.com/17010094/43991403-18648910-9d3a-11e8-8b90-aae54b56fb76.png)

## Expected result:
Should be Private tab similar to the recent changes on Android and to match current b-l naming convention

**Comment by rebron** [comment]
We're keeping the terminology 'Private Window' and is this a dupe of https://github.com/brave/brave-browser/issues/772

**Comment by tomlowenthal** [comment]
The Incognito window menu item needs to be changed in three places:
1. the File menu
2. the three-dots menu in the top right of the browser
3. the three-dots / alternate click menu on items in the bookmarks manager

Changing the hat-and-classes logo is tracked in #1385 (equivalent change for Tor windows was in #1384).
Launch UI (menu items & shortcuts) for private tabs with Tor is tracked in #1387.

**Comment by srirambv** [comment]
Tool tip needs to be updated as well

![image](https://user-images.githubusercontent.com/17010094/46749924-cfde4580-cc84-11e8-887f-cf35222d54a8.png)

**Comment by riastradh-brave** [comment]
Is it just the text strings that need to be updated in this issue?

**Comment by bbondy** [comment]
Yes but they have to be updated through a script and we need to process extra grd and grdp files which we don't yet. So it's a bit more involved.

**Comment by petemill** [comment]
Re-opening as the fix was reverted in https://github.com/brave/brave-core/pull/718

**Comment by petemill** [comment]
Er @jasonrsadler not sure what happened that this was closed by a commit in your fork. Re-opening as we reverted this and are yet to land a re-implementation. Please make sure you don't merge a PR that happens to have the now-reverted implementation.

**Comment by jasonrsadler** [comment]
I have no idea. I just resynced my master branch on my fork but I'm not working on anything related 😕

**Comment by bbondy** [comment]
This is all merged but there's still an issue with translated strings, I posted a follow up here:
https://github.com/brave/brave-browser/issues/2147

**Comment by bsclifton** [comment]
@bbondy where did this land?  Looks like it made it as far back as 0.57.x? Adjusting milestone 😄

**Comment by srirambv** [comment]
This is not completely fixed. Its only fixed in the hamburger menu
![screenshot from 2018-11-26 11-10-43](https://user-images.githubusercontent.com/17010094/48995057-71a1ef00-f16c-11e8-82f8-fc67cf083eb2.png)

Context menu option in taskbar and mouse over on private window icon still has `Incognito` mentioned
![screenshot from 2018-11-26 11-11-23](https://user-images.githubusercontent.com/17010094/48995077-82526500-f16c-11e8-8500-6d7b42a04b5d.png)
![screenshot from 2018-11-26 11-13-22](https://user-images.githubusercontent.com/17010094/48995085-87afaf80-f16c-11e8-836a-bf436de5997d.png)

@bbondy will the other two translation be fixed as part of #2147 ?

**Comment by tomlowenthal** [comment]
FWIW, I see the "private" rather than "incognito" text for the dock action on MacOS.

**Comment by bbondy** [comment]
let's just re-open this and put it back for triage.

**Comment by GeetaSarvadnya** [comment]
Jump list still have `Incognito` window instead of `Private` on `0.57.8`

![image](https://user-images.githubusercontent.com/38657976/49155307-9fd82800-f340-11e8-8a69-491d0d2103fc.png)

**Comment by bsclifton** [comment]
Moved to 1.x backlog per comment above
https://github.com/brave/brave-browser/issues/738#issuecomment-441890032

**Comment by aduh95** [comment]
I think we can close that since it has been fixed already.

**Comment by 2635599** [comment]
REALLY, nothing to do?  "Rename Incognito to Private" plenty of things that need fixing

**Comment by srirambv** [comment]
As it stands, on release version this is only happening on Linux. Windows and mac show `Private` as it should. Linux still shows `Incognito`. 

![Screenshot from 2019-07-29 08-53-59](https://user-images.githubusercontent.com/17010094/62050038-7f69b180-b1de-11e9-85bd-fa4af19b8c0a.png)
![image](https://user-images.githubusercontent.com/17010094/62050081-95777200-b1de-11e9-95c1-8ac5547c4209.png)


@rebron we should re-prioritize this as this has been in backlog for a long time

**Comment by srirambv** [comment]
+1 from @btlechowski  via https://github.com/brave/brave-browser/issues/6564

**Comment by srirambv** [comment]
As per https://github.com/brave/brave-browser/issues/6564#issuecomment-544512552 this issue doesn't seem to be platform/locale specific.

**Comment by petemill** [comment]
This was an issue with translations affecting everything except US English. It should now be fixed in the Release channel.
