### ISSUE TITLE
Reserved BAT text isn't displayed in Rewards summary section

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7635]
## Description 

Reserved BAT text isn't displayed in Rewards summary section
## Steps to Reproduce

   1. Clean profile staging env
   2. Claim UGP grants
   3. Send a one-time tip to an unverified pub https://google.com
   4. Open BR panel for google.com, reserved BAT text is displayed in panel summary
   5. 1 BAT reserved bat text isn't displayed in rewards summary section

## Actual result:

![Reserved BAT text display](https://user-images.githubusercontent.com/38657976/71909473-242ce980-3196-11ea-8653-e645c7ce7623.gif)

BR panel:
![image](https://user-images.githubusercontent.com/38657976/71909227-951fd180-3195-11ea-9021-5d9edf2bdba9.png)

Brave://rewards summary
![image](https://user-images.githubusercontent.com/38657976/71909283-b385cd00-3195-11ea-9d5a-8ee2a4509ca9.png)

## Expected result:
Reserved BAT text should be displayed in Rewards summary section
## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.3.85 Chromium: 79.0.3945.88 (Official Build) beta (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @rebron

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya is this solved with a reload?

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc Reload and browser restart didn't solve the issue.

**Comment by masparrow** [comment]
@GeetaSarvadnya 

Cannot reproduce with MacOSX or Windows 10, as of; 

Version 1.5.21 Chromium: 79.0.3945.117 (Developer Build) (64-bit)

Can you please verify - and if reproducible can you confirm the platform(s) it reproduces on? Thanks!

**Comment by LaurenWags** [comment]
Could not reproduce on macOS using

Brave | 1.3.90 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | macOS Version 10.14.6 (Build 18G103)

Could you try again as per @masparrow request above?

**Comment by GeetaSarvadnya** [comment]
@masparrow Issue is consistently reproducible in Windows 10 x64 - Bravebeta version `1.3.97`. Reload/ close or open rewards summary did not display reserved BAT text in the summary section. Do let me know if you need more details.

**Comment by GeetaSarvadnya** [comment]
@btlechowski Can you please check this issue on Linux if it's not reproducible, can you please add the label as windows only?

**Comment by btlechowski** [comment]
Not reproducible on Ubuntu

Brave | 1.3.97 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/72897591-966b0580-3d22-11ea-93eb-4d4e553a0be2.png)

**Comment by btlechowski** [comment]
Not reproducible on 1.5.57 on Windows 7 x64 and Windows 10 x64

![image](https://user-images.githubusercontent.com/34715963/73090204-2c945c80-3ed8-11ea-922a-11efab0b4010.png)
![image](https://user-images.githubusercontent.com/34715963/73090218-3c13a580-3ed8-11ea-838f-360e02e5b196.png)

Brave | 1.5.57 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Brave | 1.5.57 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1909

We should retest when https://github.com/brave/brave-core/pull/4372 and https://github.com/brave/brave-core/pull/4399 are uplifted.

**Comment by kjozwiak** [comment]
Believe we should be able to QA this now that https://github.com/brave/brave-core/pull/4372 and https://github.com/brave/brave-core/pull/4399 have been uplifted into `1.3.x` via:

* https://github.com/brave/brave-core/pull/4448
* https://github.com/brave/brave-core/pull/4438

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.3.110 Chromium: 80.0.3987.78 (Official Build) (64-bit)
-- | --
Revision | cb5aa81cb0a3a2c674b93bc7ffb34a86cd3b4802-refs/branch-heads/3987@{#752}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified STR from the description
- The issue is still not fixed and logged a follow-up issue https://github.com/brave/brave-browser/issues/8073
