### ISSUE TITLE
"Bat Ledger Service" causing 100% CPU usage

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#8846]
## Description 

We've been receiving several reports from our users that `Bat Ledger Service` causes the CPU to increase to 100% in some cases in `1.5.x` which causes performance issues. We've had a similar issue in `1.7.x` and `1.8.x` that we resolved via https://github.com/brave/brave-browser/issues/8691. However, this issue has been reported on `1.3.x`, `1.4.x` and `1.5.x` so it's a different problem.

@NejcZdovc has been debugging the issue a user and mentioned that the CPU dropped from 100% once the ballets object in `ledger_state` was removed.

Some links to users experiencing this issue:

* https://github.com/brave/brave-browser/issues/8779#issuecomment-602736059
* https://twitter.com/bvaivoda/status/1241240604257873921

There's other reports via https://community.brave.com regarding high CPU usage even after https://github.com/brave/brave-browser/issues/8691 and https://github.com/brave/brave-browser/issues/8779 have been fixed.

## Steps to Reproduce

* N/A (currently we don't really have any STR as @NejcZdovc still investigating)

## Actual result:

![77358097-3e974d80-6d17-11ea-88c8-1cf32258a4e0](https://user-images.githubusercontent.com/2602313/77480207-aae97e00-6df7-11ea-92d1-b355ddb7c645.png)

## Expected result:

"Bat Ledger Service" shouldn't be using 100% of the CPU.

## Reproduces how often: 

* N/A (we still don't know enough information but there's some users experiencing this)

## Brave version (brave://version info)

* This has been reported on `1.3.x`, `1.4.x` and the latest `1.5.x`. Assuming it's an issue on every channel and separate from https://github.com/brave/brave-browser/issues/8691.

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes, received reports from 1.5.x`
- Can you reproduce this issue with the beta channel? `Most likely also affected`
- Can you reproduce this issue with the dev channel? `Most likely also affected`
- Can you reproduce this issue with the nightly channel? `Most likely also affected`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `Most likely would resolve the issue`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @NejcZdovc @mandar-brave @bsclifton @rebron @jsecretan

**Comment by MinisterFister** [comment]
Issue started for me after the migration of everything into publisher_info_db file. I can tell because I open Resource monitor on windows, go in the disk activity section and see publisher_info_db is doing a lot of read/write operations causing CPU + drive activity to spike.  

I can reproduce this when I open several profiles at the same time that haven't been open for a few days and have ads enabled; this is when I take a noticeable hit (eg 100% usage on CPU and disk) for like 30 seconds until the r/w operations are done. Everything goes to normal though when whatever operations it needs to do finish. I don't remember this being as bad before the migration. I assume people with slower/less core CPUs or HDDs must take an even bigger hit. I have a quad core + an SSD and I still notice it.

**Comment by NejcZdovc** [comment]
@MinisterFister this is not related to db migration. It's operation that process publisher list. It normally takes 30s to complete. We are working on new mechanism that will solve it

**Comment by aleqx** [comment]
I neither did a db migration nor do I have multiple profiles. Issues still exists. One core is 100% utilized (regardless of your CPU).

**Comment by SephReed** [comment]
I'm getting this issue as well

**Comment by angsto** [comment]
I have also this problem. I'm waiting one week and I don't see any progress. Practically the browser is not usable now(when I open it my cooling fans start working on 100%). Very soon I'll be forced to uninstall Brave.

**Comment by NejcZdovc** [comment]
@aleqx @SephReed @angsto if you go to your user profile (directories listed bellow) and open `ledger_state` file, do you have any entries under `ballots`? If that is the case what I would suggest is that you do the following.

MacOS: `/Users/{username}/Library/Application Support/BraveSoftware/Default/ledger_state`
Windows: `%USERPROFILE%/AppData/Local/BraveSoftware/Brave-Browser/User Data/Default/ledger_state`

1. close browser
2. back up `ledger_statee` file
3. you delete everything that is in properties `ballots` like this

**before**:
```
....
"ballots": [{some data}, {some data}]
....
```

**after**:
```
....
"ballots": []
....
```

**Comment by mariow** [comment]
@NejcZdovc 
I've tried this on linux (by editing ~/.config/BraveSoftware/Brave-Browser/Default ) but unfortunately after restarting Brave the Bat Ledger Services immediately starts consumin 100% cpu again.

**Comment by NejcZdovc** [comment]
@mariow  could you please run brave from the terminal and add this flag at the end`--enable-logging=stderr `. Let me please know what you see

**Comment by angsto** [comment]
I open the file and I have ,"ballots":[],

**Comment by NejcZdovc** [comment]
@angsto could you also try from the terminal with logs like I suggested to @mariow?

**Comment by angsto** [comment]
[24284:27484:0402/125733.531:WARNING:account_consistency_mode_manager.cc(235)] Desktop Identity Consistency cannot be enabled as no OAuth client ID and client secret have been configured.
[24284:27484:0402/125733.536:INFO:ads_service_impl.cc(1181)] Migrating ads preferences
[24284:27484:0402/125733.537:INFO:ads_service_impl.cc(1207)] Ads preferences are up to date on version 7
[24284:27484:0402/125733.559:WARNING:push_messaging_service_factory.cc(37)] PushMessagingService could not be built because InstanceID is unexpectedly disabled
[24284:27484:0402/125733.560:WARNING:push_messaging_service_factory.cc(37)] PushMessagingService could not be built because InstanceID is unexpectedly disabled
[24284:27484:0402/125733.569:WARNING:push_messaging_service_factory.cc(37)] PushMessagingService could not be built because InstanceID is unexpectedly disabled
[24284:27484:0402/125733.576:WARNING:push_messaging_service_factory.cc(37)] PushMessagingService could not be built because InstanceID is unexpectedly disabled
[26440:30336:0402/125733.611:INFO:confirmations_impl.cc(61)] Initializing confirmations
[26440:30336:0402/125733.611:INFO:confirmations_impl.cc(769)] Loading confirmations state
[24284:27484:0402/125733.614:WARNING:push_messaging_service_factory.cc(37)] PushMessagingService could not be built because InstanceID is unexpectedly disabled
[26440:30336:0402/125733.688:INFO:confirmations_impl.cc(788)] Successfully loaded confirmations state
[26440:30336:0402/125733.688:INFO:confirmations_impl.cc(749)] Saving confirmations state
[26440:30336:0402/125733.689:INFO:confirmations_impl.cc(749)] Saving confirmations state
[26440:30336:0402/125733.690:INFO:confirmations_impl.cc(749)] Saving confirmations state
[26440:30336:0402/125733.712:INFO:confirmations_impl.cc(765)] Successfully saved confirmations state
[26440:30336:0402/125733.718:INFO:confirmations_impl.cc(765)] Successfully saved confirmations state
[24284:9896:0402/125733.722:WARNING:rewards_p3a.cc(185)] Bad ledger state
[26440:30336:0402/125733.725:INFO:confirmations_impl.cc(765)] Successfully saved confirmations state
[24284:27484:0402/125733.735:WARNING:CONSOLE(0)] "HTML Imports is deprecated and will be removed in M80, around February 2020. Please use ES modules instead. See https://www.chromestatus.com/features/5144752345317376 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.", source:  (0)
[26440:30336:0402/125733.740:VERBOSE1:ledger_impl.cc(424)]
[ REQUEST ]
> url: https://publishers-distro.basicattentiontoken.org/api/v3/public/channels
> method: UrlMethod::GET
> content:
> contentType:
> header: Accept-Encoding: gzip
[ END REQUEST ]
[26440:30336:0402/125733.740:INFO:contribution.cc(419)] Timer will start in 158
[26440:30336:0402/125733.745:INFO:contribution.cc(419)] Timer will start in 3
[26440:30336:0402/125733.747:INFO:contribution.cc(419)] Timer will start in 18
[26440:30336:0402/125733.755:INFO:confirmations_impl.cc(844)] SetWalletInfo:
[26440:30336:0402/125733.755:INFO:confirmations_impl.cc(845)]   Payment id: 8bc156b8-c7d2-48d8-8495-cf59fd1d13b2
[26440:30336:0402/125733.755:INFO:confirmations_impl.cc(846)]   Private key: ********
[26440:30336:0402/125733.755:INFO:confirmations_impl.cc(749)] Saving confirmations state
[26440:30336:0402/125733.756:INFO:ads_rewards.cc(54)] Fetch ads rewards
[26440:30336:0402/125733.756:INFO:ads_rewards.cc(114)] GetPaymentBalance
[26440:30336:0402/125733.756:INFO:ads_rewards.cc(116)] GET /v1/confirmation/payment/{payment_id}
[26440:30336:0402/125733.756:INFO:ads_rewards.cc(119)] URL Request:
[26440:30336:0402/125733.756:INFO:ads_rewards.cc(122)]   URL: https://ads-serve.brave.com/v1/confirmation/payment/8bc156b8-c7d2-48d8-8495-cf59fd1d13b2
[26440:30336:0402/125733.756:INFO:ads_rewards.cc(127)]   Body: {}
[26440:30336:0402/125733.758:INFO:ads_rewards.cc(130)]   Headers:
[26440:30336:0402/125733.759:INFO:ads_rewards.cc(132)]     digest: SHA-256=RBNvo1WzZ4oRRq0W9+hknpT7T8If536DEMBg9hyq/4o=
[26440:30336:0402/125733.759:INFO:ads_rewards.cc(132)]     signature: keyId="primary",algorithm="ed25519",headers="digest",signature="dmqX4W6Wtfxi7zpLauWWNTtbWBdfzJYNKSE7XtJwE5MxPBPPEclY2cYRl5SVlrGkskpsIGOxf/QfZlK/B682BQ=="
[26440:30336:0402/125733.759:INFO:ads_rewards.cc(132)]     accept: application/json
[26440:30336:0402/125733.759:INFO:ads_rewards.cc(136)]   Content_type: application/json
[26440:30336:0402/125733.759:INFO:confirmations_impl.cc(85)] Successfully initialized confirmations
[26440:30336:0402/125733.761:INFO:confirmations_impl.cc(1336)] Start paying out redeemed tokens in 31 seconds
[26440:30336:0402/125733.761:INFO:refill_tokens.cc(50)] Refill
[26440:30336:0402/125733.761:INFO:refill_tokens.cc(75)] RequestSignedTokens
[26440:30336:0402/125733.761:INFO:refill_tokens.cc(78)] No need to refill tokens as we already have 47 unblinded tokens which is above the minimum threshold of 20
[26440:30336:0402/125733.763:INFO:confirmations_impl.cc(1283)] Start retrying failed confirmations in 56 seconds
[26440:30336:0402/125733.763:INFO:confirmations_impl.cc(1190)] OnTimer:
  timer_id: 2
  retry_getting_signed_tokens_timer_id_: 0
  payout_redeemed_tokens_timer_id_: 5
[26440:30336:0402/125733.763:INFO:ads_rewards.cc(98)] OnTimer:
  timer_id: 2
  retry_timer_id_: 0

[26440:30336:0402/125733.763:INFO:uphold.cc(351)] OnTimer Uphold: 2
[26440:30336:0402/125733.764:VERBOSE1:ledger_impl.cc(424)]
[ REQUEST ]
> url: https://grant.rewards.brave.com/v1/promotions?migrate=true&paymentId=8bc156b8-c7d2-48d8-8495-cf59fd1d13b2&platform=windows
> method: UrlMethod::GET
> content:
> contentType:
[ END REQUEST ]
[26440:30336:0402/125733.764:INFO:promotion.cc(851)] Promotion corrupted 268fc4d1-235e-460c-9ad4-0983ddfcdf10
[26440:30336:0402/125733.766:VERBOSE1:ledger_impl.cc(424)]
[ REQUEST ]
> url: https://grant.rewards.brave.com/v1/promotions/reportclobberedclaims
> method: UrlMethod::POST
> content: {"claimIds":[""]}
> contentType: application/json; charset=utf-8
[ END REQUEST ]
[26440:30336:0402/125733.767:VERBOSE1:ledger_impl.cc(424)]
[ REQUEST ]
> url: https://grant.rewards.brave.com/v1/promotions/268fc4d1-235e-460c-9ad4-0983ddfcdf10/claims/
> method: UrlMethod::GET
> content:
> contentType:
[ END REQUEST ]
[26440:30336:0402/125733.772:INFO:confirmations_impl.cc(765)] Successfully saved confirmations state
[24284:27484:0402/125733.797:WARNING:CONSOLE(1)] "no tab id so cannot request shield data from window focus change!", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
[24284:27484:0402/125734.248:WARNING:CONSOLE(1)] "Invalid asm.js: Unexpected token", source: chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/bg-libs.js (1)

**Comment by NejcZdovc** [comment]
@angsto could you please have brave open for example 10min with this CPU problem? I see ` https://publishers-distro.basicattentiontoken.org/api/v3/public/channels` which is quite intensive operation. Wonder if this operation just didn't finish yet. We are working on new API v4 that should fix this problem

**Comment by mariow** [comment]
@NejcZdovc Sure - I had a few tabs open that were causing a lot of info to be dropped into the log (e.g. Google Mail with background processes), so I've closed all tabs exccept for this github issue and produced the attached log.
[brave.log](https://github.com/brave/brave-browser/files/4420422/brave.log)

Also, as per your other question to @angsto - despite the CPU usage I have continued using Brave as my standard browser and the issue has been around (at least) all day yesterday and today (several hours of usage)

**Comment by angsto** [comment]
Brave was opened for 20 min. with no tabs opened.
[Brave-20 min.txt](https://github.com/brave/brave-browser/files/4420452/Brave-20.min.txt)

**Comment by NejcZdovc** [comment]
@mariow @angsto thank you very much for sending logs, this is helping us a lot. Could I ask you for one more favor? Could run brave again with some more flags, so that I get even more detailed logs `--enable-logging=stderr --vmodule=*rewards*=6 --log-level=2 --v=1`. Thank you very much

**Comment by mariow** [comment]
Sure, please find attached. Hope it helps.
[brave-additional.log](https://github.com/brave/brave-browser/files/4421787/brave-additional.log)

**Comment by angsto** [comment]
Here is also mine.
[brave-more flagsl.log](https://github.com/brave/brave-browser/files/4422122/brave-more.flagsl.log)

**Comment by aleqx** [comment]
I don't mean to sound harsh but this is a pretty huge bug, and it persisted since 1.4 stable, and now 1.5 stable. Effectively users cannot win rewards nor pay rewards to content creators, so the latter bunch have be markedly affected.

May I ask what the status on this?

May I also suggest a more thorough testing for the stable releases and also a little less rush to release new major stable versions?

p.s. I'm aware that the current beta contains a fix for this bug, but users can't be expected to switch to beta when their entire profile has been setup for stable (plugins, settings, passwords, etc) given that the Beta and Stable use different profile dirs and compatibility between profile dirs isn't guaranteed (a simple copy back and forth may break things).

**Comment by mariow** [comment]
One more thing I just noticed while trying to see if anything changes the behavior: any interaction with the BAT wallet is broken while Bat Ledger Service is busy consuming CPU. I can't contribute/tip (neither automatic nor manual), cannot remove pending contributions, cannot disconnect from Uphold, recovery words are not visible. 
Setting up a new profile and switching to it does not resolve the issue - starting the browser fresh with the same new profile will keep the cpu usage down (until I switch to the "broken" profile once)
Recovering the wallet and uphold connection in the new profile does not reproduce the cpu usage, so I guess it has to be something in the history of that wallet.

**Comment by aleqx** [comment]
> I can't contribute/tip (neither automatic nor manual), cannot remove pending contributions, cannot disconnect from Uphold, recovery words are not visible.

That's what I was talking about in my post above as well (and in the forums and other tickets).

> I guess it has to be something in the history of that wallet.

No, it has nothing to do with the wallet. It's a bug in Brave since 1.4. it was fixed in beta so if you really want to use Brave with rewards right now then you need to install beta and then copy the "Default" folder from the stable profile to the beta (otherwise beta starts with a fresh profile). This is not actually advisable because beta will alter the profile and then if you want to revert the procedure and copy it back to stable then you might find various broken things - there is no guarantee.

**Comment by NejcZdovc** [comment]
@aleqx just so confirm, beta version is working correctly with the same profile that doesn't work in current release?

**Comment by aleqx** [comment]
@NejcZdovc see my message above for details. Only the "Default" subfolder is copied from stable (where it doesn't work) to beta (where it does work)

**Comment by NejcZdovc** [comment]
@aleqx we are releasing beta to release this week. Please let me know if version 1.7 will fix it for you. Thank you very much for helping us out

@mariow thank you for the update

**Comment by pihomeserver** [comment]
Not sure if it helps but i have the issue in Brave 1.5.123 After installing latest beta (1.8.65) it seems to be solved

**Comment by NejcZdovc** [comment]
@pihomeserver really glad that it's working now. Thank you for the update

**Comment by pihomeserver** [comment]
@NejcZdovc let's hope it will be integrated in the next release of the stable version. The bug raises in the last update only (for me)

**Comment by angsto** [comment]
@NejcZdovc  @emerick  When we can expect working official version? I really cant use this browser...

**Comment by NejcZdovc** [comment]
@angsto my hope is that we are releasing new version (1.7.x) today

**Comment by bsclifton** [comment]
Release pushed tentatively to Monday or Tuesday. But @angsto (others welcome too) you can give our release candidate a shot. You can download it from here:
https://github.com/brave/brave-browser/releases/tag/v1.7.90

If you're on Windows, the one you want is `BraveBrowserStandaloneSetup.exe`

**Comment by pihomeserver** [comment]
@bsclifton Hi. Tested and same issue for me. 1 core is used only for the BAT ledger
If you need specific information feel free to ask i will try to help

<img width="725" alt="Capture d’écran 2020-04-10 à 10 32 14" src="https://user-images.githubusercontent.com/3817578/78976506-9656f680-7b16-11ea-8667-4b2602183bac.png">

**Comment by NejcZdovc** [comment]
@pihomeserver ok so 1.7 doesn't fix it for you, but you said 1.8.x does?

**Comment by pihomeserver** [comment]
@NejcZdovc 1.8.65 fixed it. There is also another difference (could be or not important) : the dev release is a new install and does not share data with stable one. The RC version overrides the stable one so it shares previous installed files.

**Comment by NejcZdovc** [comment]
@pihomeserver this is important one for sure. We only see this problem on some affected profiles. So to really test this one you would need to duplicate your profile, append `-Beta` and then start 1.8

**Comment by pihomeserver** [comment]
1.8 is a fresh install with no data shared (favorites, configuration, etc.) 
The 1.7 opens with all previous configuration settings. I try to have it in a fresh install

**Comment by angsto** [comment]
> Release pushed tentatively to Monday or Tuesday. But @angsto (others welcome too) you can give our release candidate a shot. You can download it from here:
> https://github.com/brave/brave-browser/releases/tag/v1.7.90
> 
> If you're on Windows, the one you want is `BraveBrowserStandaloneSetup.exe`

OK. Now one hour use, it seems that 1.7.9 it fix my problem. Thanks

**Comment by pihomeserver** [comment]
@angsto during install you overrided previous version or installed it somewhere else ?

**Comment by angsto** [comment]
> @angsto during install you overrided previous version or installed it somewhere else ?

I just download BraveBrowserStandaloneSetup.exe and run it.

**Comment by pihomeserver** [comment]
Ok i moved configuration data in an old folder to start from scratch (folder `/Users/chris/Library/Application Support/BraveSoftware/Brave-Browser`)
And started the new version 1.7.90 
Now bug seems to be fixed
<img width="759" alt="Capture d’écran 2020-04-10 à 11 21 41" src="https://user-images.githubusercontent.com/3817578/78980207-bb9b3300-7b1d-11ea-8525-a6e44d1ea70c.png">

So i have to figure out how to get my configuration back without recreating the bug

**Comment by peeter123** [comment]
I had this issue in Brave 1.5.123 and previous versions. After installing latest 1.7.90 the problem seems to be resolved.

**Comment by bsclifton** [comment]
Huge thanks to you all that have tried the fix and came back to verify it appears to be resolved 😄  This is great feedback!

@pihomeserver with your profile in place, as you mentioned when testing 1.7.90, it seems you're still having the issue ☹️ New profiles (for example, you move the folder out of the way) may not experience this, as @NejcZdovc shared. So it might be specific to your profile

I have noticed that on affected profiles, sometimes the CPU usage for Bat Ledger is quite high... and then it goes back down to very small usage (1%, etc). I wonder if you need to use 1.7.90 with your profile for a bit longer to where it fetches the publisher list again?

**Comment by aleqx** [comment]
1.7.90 RC2 works for me as well with the profile that was problematic in 1.4 and 1.5 (but I already knew this as I reported above, since I have been using 1.7 while in Beta)

@NejcZdovc can you explain the `-Beta` flag? And is it for the stable version? I'm nto sure I understand what it's meant to be doing ...

**Comment by pihomeserver** [comment]
@bsclifton that works ! I switched back the old profile backup to the configuration folder of brave and after 3-4 minutes the CPU dropped to less than 20%

Thank you guys for the software, the support and reactivity !

**Comment by mariow** [comment]
Sorry for the delay: I can confirm that 1.7.90 (Linux) fixed the problem for me as well, thanks for all your work on this!

**Comment by aquaspy** [comment]
Is any update coming to stable? Thanks!

**Comment by SephReed** [comment]
Still broken.  Version 1.7.92 on MacOS
<img width="448" alt="Screen Shot 2020-04-14 at 6 32 45 PM" src="https://user-images.githubusercontent.com/14002040/79283755-5d07e900-7e7e-11ea-98db-ff6de868e385.png">

**Comment by NejcZdovc** [comment]
@aquaspy we released 1.7.x yesterday

**Comment by pihomeserver** [comment]
> Still broken. Version 1.7.92 on MacOS
> <img alt="Screen Shot 2020-04-14 at 6 32 45 PM" width="448" src="https://user-images.githubusercontent.com/14002040/79283755-5d07e900-7e7e-11ea-98db-ff6de868e385.png">

No issue here. The CPU goes up for few minutes and then comes back to nearly 2/3 %. I had to wait less than 5 minutes

**Comment by SephReed** [comment]
@pihomeserver I will try again.  As a thought, it might be nice if (when functional) it caps at ~25%.  Not sure how feasible that is, but I really dislike hearing my fans go into overdrive for this.  If it wasn't for my fans being loud, I wouldn't care, but it makes this particular utility really obnoxious.

**Comment by NejcZdovc** [comment]
closing for now as it looks like 1.7 fixed it. Please let us know if you still see this problem

**Comment by aleqx** [comment]
Not sure if this is related but my Brave Beta just upgraded itself to 1.9.45 and when it came back up it now says the wallet is disconnected. Is this known?

I have a feeling that Brave got more and more unreliable lately :(

**Comment by mandar-brave** [comment]
hey @aleqx if you have never connected your Uphold wallet, just ignore that button. Nothing should have changed in terms of functionality. Hope this helps.

**Comment by aleqx** [comment]
Of course I had it connected before, and it had worked fine, receiving rewards, sending tips, etc. As I said in my post, Brave upgraded itself to 1.9.45 and immediately afterwards said the wallet is disconnected, and now it shows a grey "disconnected" button and if I try to click it to reconnect, it sends me to Uphold to verify my id (which I don't want and which is not needed) ... so I can't reconnect it (and it shouldn't have disconnected in the first place).

**Comment by mandar-brave** [comment]
@aleqx the wallet disconnects for two reasons -- a) if your authentication token has expired -- 90 days in Brave/Uphold case (this is very common with all logins) and b) if you have contributed more than 250 BAT. In both cases, the goal to disconnect is security and to protect your account.

To reconnect, you do not have to go through any KYC and ID check, etc. All you need is your login credentials (username/password) with Uphold when you are redirected to their site. Once done, the same wallet will be connected back to your browser.

**Comment by aleqx** [comment]
Hmm, I never had an Uphold account. That is, I never registered on Uphold. I didn't contribute more than 250 BAT but I do think it's been around 3 months since I started using Brave so that could be it.

Are you saying that I need to register an account on Uphold to restore access to my wallet, which had BAT in it? 

I believe this sort of stuff should be in an info box to the user (I don't recall seeing it anywhere). If it's indeed one of two reasons, then why doesn't it tell the user upon disconnecting the wallet? "Your wallet was disconnected because you used for more than 90 days, as specified in the T&Cs" or "Your wallet was disconnected because you contributed more than 250 BAT as stated in the T&Cs" (is it even in the T&Cs?). At least the user would know and avoid wasting their and your time.

At the same time, I don't understand this "feature". Surely it doesn't add anything to security if all that's required to reconnect is to login on Uphold with some anonymous account. Bots would still happily use it for 3 months or 250 BAT and then automate the Uphold login as well (or even do that step manually). But the bigger issue is letting the user know why and what to do when it happens rather than cutting their wallet off, wouldn't you agree?

**Comment by mandar-brave** [comment]
@aleqx Some at Brave Support or I can help do this with you over voice and/or an easier way to communication to and fro. 

1. I do not disagree on all of your feedback; never been done is hard but agree we have a long way to go before we get it right. 
2. The 250 BAT is meant for user risk; it does not do anything else but ensures that if someone got hold of your token (by error), the risk is mitigated to 250 BAT. This is true for any banking operations - we are a little more concerned and we will keep increasing the limits as we learn more

Now lets talk about Disconnecting; Disconnecting is like you need to re-login. Protection and Security is part of the solution. I mean this Github repo that I am responding on logs me out within 3 days so it is very common. If you have an Uphold login, it is the same process - we are just ensuring you are the owner of the account (90 days may be too much and hence the issue).

Re: Botting
This is not so much about Botting as validating that you are you (Govt ID), like you would at a Bank, that this is your account. Just that it is digitized and we are not doing this in person at a retail outlet.

In any case, all feedback received and understood. Really appreciate the detail and the frustration.

**Comment by aleqx** [comment]
Actually, that's good point about spoofing/phishing/hacking someone's legitimate wallet. I forgot that some Brave users actually receive a fair bit of income and as such limiting exposure by capping spending is a simple and usual approach. 

I guess I'll need to create an Uphold account, though I must admit I'm not really fond of the idea of having Uphold see/infer any of my wallet activity. A portion of privacy, even if small, is directed at/via a company whom I don't want in the loop at all. I'm sure you guys thought about this during the design process, and including Uphold in the loop made some sense somewhere, but from where I'm sitting I don't see it as a necessity: the Brave wallet could be just another ERC20 wallet, which can receive and send funds to and from any other ERC20 wallet without the need for a 3rd party exchange. I'm aware I'm not obliged to use Brave, so this isn't a complaint per-se.

**Comment by SephReed** [comment]
Still not fixed

<img width="477" alt="Screen Shot 2020-05-01 at 7 21 48 PM" src="https://user-images.githubusercontent.com/14002040/80850403-47feba00-8be1-11ea-8b66-d14d51ee1346.png">


Brave | 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)
-- | --
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | macOS Version 10.14.3 (Build 18D109)
JavaScript | V8 8.1.307.28

**Comment by SephReed** [comment]
Updated again, it's still broken:
<img width="602" alt="Screen Shot 2020-05-01 at 7 28 59 PM" src="https://user-images.githubusercontent.com/14002040/80850569-176b5000-8be2-11ea-8929-7d2951efa3ca.png">

**Comment by SephReed** [comment]
Left it for an hour to see if maybe it was doing something.  Still 100% CPU.

**Comment by victorelec14** [comment]
Version 1.8.90 Chromium: 81.0.4044.129 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/543450/81441480-23bb5400-9172-11ea-863d-568bb88d0166.png)

**Comment by NejcZdovc** [comment]
@victorelec14 @SephReed this one should fix the final thing using CPU https://github.com/brave/brave-browser/issues/9607

**Comment by SephReed** [comment]
Still broken

<img width="692" alt="Screen Shot 2020-05-12 at 10 12 47 PM" src="https://user-images.githubusercontent.com/14002040/81767351-ca1e9680-949d-11ea-893f-9b928b03df55.png">

**Comment by SephReed** [comment]
Still unusable.

<img width="510" alt="Screen Shot 2020-05-27 at 9 52 41 PM" src="https://user-images.githubusercontent.com/14002040/83093130-79459b00-a064-11ea-95ef-05145965e92b.png">

**Comment by SephReed** [comment]
Literally just deleted Brave off my computer, then reinstalled it:

<img width="631" alt="Screen Shot 2020-05-27 at 9 56 51 PM" src="https://user-images.githubusercontent.com/14002040/83093422-08eb4980-a065-11ea-9191-93c8c098eb04.png">

Whatever the Bat Ledger Service is, it needs to die.  I don't want it running on my computer ever again.

**Comment by SephReed** [comment]
What do I need to delete from here to make this go away?  I don't want to lose all of my logins.

<img width="530" alt="Screen Shot 2020-05-27 at 10 02 40 PM" src="https://user-images.githubusercontent.com/14002040/83093858-df7eed80-a065-11ea-95fc-91018ccdcef5.png">

**Comment by MinisterFister** [comment]
> What do I need to delete from here to make this go away? I don't want to lose all of my logins.

Not a part of the team but if you don't care about your BAT you can try this: Make sure the browser is closed. Go in Default folder and rename the publisher_info_db file to publisher_info_db_backup. Rename also the ads_service folder to ads_service_backup and rewards_service folder to rewards_service_backup. Then reopening the browser should have Brave rewards disabled (afaik). 

To recover your BAT, before doing whatever I wrote above, you can go to brave://rewards-internals/ , copy the info and send it to the team through PM to see if they can do anything to recover your funds to another address (not sure what they do tbh, but might be worth a try). 

Your issues will be fixed when this https://github.com/brave/brave-core/pull/5568 is pushed to release. No ETA afaik

**Comment by SephReed** [comment]
I guess Brave is dead.

<img width="714" alt="Screen Shot 2020-06-12 at 4 42 46 PM" src="https://user-images.githubusercontent.com/14002040/84548713-f0696900-accb-11ea-8a97-302cea8e8366.png">

**Comment by SephReed** [comment]
Unfortunately, renaming all of those files did not make the cursed BAT Ledger Service go away.

At this point, I think there's no option but to give up on Brave, and make sure to tell everyone I know to give up on it too.  I don't want a 100% CPU using BAT Ledger computing program.  I was a Browser.  Maybe next time, let a user opt out?

**Comment by bsclifton** [comment]
@SephReed I think your profile is corrupt unfortunately. The best step to take would be to export your bookmarks and other data, then clear your profile directory. On macOS, this will be at `~/Library/Application Support/BraveSoftware/Brave-Browser`

Re-import your bookmarks and you'll be on a fresh profile which should work great. Without having your profile, diagnosing the issue would be hard. But exporting bookmarks as HTML (and exporting passwords if needed too) and re-importing on a fresh profile should resolve the issue completely

**Comment by NejcZdovc** [comment]
@SephReed before you do that, please try with version 1.10 that will be released beginning of next week. I have a feeling that 1.10 will fix it for you. If that will not work, you can migrate to new profile like @bsclifton said. Thank you for you patients

**Comment by 05K4R** [comment]
1.10 finally fixed this for me, I can finally use my laptop on my lap!

**Comment by SephReed** [comment]
I had to delete everything and reinstall.  Lost my BAT, but that's okay I guess.

**Comment by bsclifton** [comment]
@SephReed rewards does have a way to back up your wallet - you get keywords basically which (on a fresh profile) you can type in to restore/import your wallet. Alternatively, you can go through the KYC process and verify your wallet and then any new instances you'd just be reconnecting (logging in)
