### ISSUE TITLE
cosmetic filtering causes a layout re-flow during page-load - follow up to #8197

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#9051]
## Description 
Found while testing #8197 

Issue as originally described in above issue is still occurring. If I navigate to articles on latimes.com (with cosmetic blocking enabled), page content jumps around. If I disable cosmetic blocking, page content does not jump around.

## Steps to Reproduce

   1. Visit latimes.com
   2. Visit some articles (with cosmetic blocking enabled by default)

## Actual result:

Content jumps (content jumps when cosmetic blocking is on/default)
![cosmetic-blk-on](https://user-images.githubusercontent.com/28145373/78601656-24836200-7823-11ea-9bbd-ab70f0420f44.gif)

## Expected result:
Content should not jump (it does not jump when cosmetic blocking is disabled)
![cosmetic-blk-off](https://user-images.githubusercontent.com/28145373/78601667-29481600-7823-11ea-95eb-61cd6a2a26d7.gif)

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.7.86 Chromium: 80.0.3987.163 (Official Build) (64-bit)
-- | --
Revision | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? not on 1.5.x with cosmetic blocking off (default value on this version)
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @brave/legacy_qa

**Comment by btlechowski** [comment]
Reproduced on Ubuntu 

Brave | 1.7.86 Chromium: 80.0.3987.163 (Official Build) (64-bit)
-- | --
Revision | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS | Ubuntu 18.04 LTS

**Comment by rebron** [comment]
cc: @pes10k @antonok-edm can you take a look?

**Comment by pes10k** [comment]
In general, this isn't a bug, its a necessary part of the "distinguish 1p vs 3p ads" requirement.  We hide everything and then unhide things the algorithm thinks is a 1p ad.  Unfortunately, that will cause somethings to jump around as the "party-ness" of it changes.

However, in this specific case, i dont know why the ad would be classified as 1p…

It looks like uBO uses scriptlets to clean up this page.  A fix for scriptlets should be incoming shortly (re @antonok-edm).  If that doesn't address the problem here, lets re-visit then

**Comment by rebron** [comment]
@antonok-edm related issue? #9496 or resolved with https://github.com/brave/brave-core/pull/5402?

**Comment by antonok-edm** [comment]
@rebron Still seeing similar jumping around the advertisement slots using the latest Nightly. I don't think the scriptlets actually touch any of those elements.

**Comment by ryanbr** [comment]
Looking good here, tested on latimes.com  @LaurenWags  Feel free to re-open if its still an issue,
