### ISSUE TITLE
[Android] Github publishers do not show 'on GitHub' on Rewards panel

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#9696]
## Description 
On desktop when you visit a github page/profile and open the Rewards panel it says "someuser on GitHub". Android doesn't show the "on GitHub" part.

## Steps to reproduce 

   1. Have Rewards enabled
   2. Navigate to a page like github.com/laurenwags (doesn't matter if the publisher is verified or not)
   3. Open panel

## Actual result 
no 'on GitHub'
![android-GH](https://user-images.githubusercontent.com/28145373/81447777-4128f780-914b-11ea-8b03-b46172a1517c.png)

## Expected result
should show 'on GitHub' as desktop does
<img width="977" alt="Screen Shot 2020-05-08 at 4 17 08 PM" src="https://user-images.githubusercontent.com/28145373/81447675-13dc4980-914b-11ea-9a5a-cf6e7d6a1f89.png">

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? yes
   - Beta build? yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.8.93 (Beta), 1.10.39 (Nightly), 1.7.102 (Release)

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by Miyayes** [comment]
solved in 1.35 new panel

**Comment by LaurenWags** [comment]
@Miyayes this still reproduces on 1.36.x Nightly

![Screenshot_20220124-155039](https://user-images.githubusercontent.com/28145373/150862633-613bd4c8-59a4-4865-9afd-e5cc0d167275.png)

**Comment by Miyayes** [comment]
@GeetaSarvadnya Will check.

**Comment by GeetaSarvadnya** [comment]
@Miyayes The issue is NOT reproducible anymore. It's behaving same as Desktop. Verified on `Vivo x70 Pro version 12` running `Bravemonoarm64.apk_1.51.114`

Desktop  | Android
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/f494355d-92c0-4318-8c4f-60f76a986611) | ![Screenshot_20230517_213739](https://github.com/brave/brave-browser/assets/38657976/61912ff6-d1ee-4c2b-84a7-ca5a3d8b3a25)

**Comment by LaurenWags** [comment]
@GeetaSarvadnya  you visited laurenwags.github.io not github.com/laurenwags (or similar page). Can you try with visiting a page like github.com/laurenwags?

**Comment by Miyayes** [comment]
GitHub creators no longer supported.
