### ISSUE TITLE
1Password does not work

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#980]
## Description
1Password extension is installed and enabled. It works great with the Muon based browser. However, with 0.55.1, it is not working:
- Shortcut (ex: <kbd>cmd</kbd> + <kbd> \ </kbd> ) is not working
- Right clicking a login text field and picking `1Password` is not working
- 1Password extension is blinking
- Clicking the extension icon and picking `1Password` does not work

When inspecting the background page, I see the following happen over and over (which corresponds with the blinking):
```
Finished loading auth configuration. Processing callbacks.
global.min.js:247 [CHROME:NM] Port <[object Object]> disconnected: Native host has exited.
global.min.js:100 [AGENT] Connection [object NativeMessagingConnection] disconnected.
connectionDidDisconnect.fc @ global.min.js:100
(anonymous) @ global.min.js:85
D.disconnect @ global.min.js:88
(anonymous) @ global.min.js:87
D.pause.pause @ global.min.js:87
(anonymous) @ global.min.js:94
a @ global.min.js:247
global.min.js:247 1Password detected a high number of disconnections from the browser extension to the main application between Wed Sep 05 2018 22:41:21 GMT-0700 (Mountain Standard Time) and Wed Sep 05 2018 22:43:23 GMT-0700 (Mountain Standard Time)
a @ global.min.js:247
global.min.js:100 [AGENT] Connection [object NativeMessagingConnection] disconnected.
connectionDidDisconnect.fc @ global.min.js:100
(anonymous) @ global.min.js:85
(anonymous) @ global.min.js:87
global.min.js:100 [AGENT] Connection [object NativeMessagingConnection] disconnected.
```

**Comment by NejcZdovc** [comment]
+1 from me

**Comment by srirambv** [comment]
Works fine on Windows (0.55.1). Keyboard shortcut <kbd>Ctrl+\</kbd> brings up 1Password app and unlocking it autofills and signs in correctly. Could be mac specific issue

**Comment by kevinschaich** [comment]
**+1 from me on Brave Core 0.55.2 for Mac.**

I tried both the standalone 1Password extension (requiring Desktop companion) and 1Password X.

The standalone version gives me similar behavior as @bsclifton. 1Password X installs and logs in correctly but crashes any time I try to fill a password. A balloon pops up but nothing in console.

![image](https://user-images.githubusercontent.com/9244728/45251106-6b327280-b2f5-11e8-9187-8d0afe6dc54d.png)

**Comment by bbondy** [comment]
I tried reaching out via email to several members there that we were in contact with previously, but not getting a response for the past month :(

**Comment by bbondy** [comment]
Got a response from 1Password tonight.
The good news is that it looks like 1Password 7.2 will have the fix.
The bad news is that it looks like that won't be until the end of October.

**Comment by kevinschaich** [comment]
@bbondy thank you for following up with 1P team!

Can you elaborate on where the problem is arising from? Would have assumed the problem stems from the Brave side if 1P/1PX if we experience no problems in Chrome and Brave Core is running Chromium.

**Comment by bbondy** [comment]
I think the problem is just we have new app IDs for this new browser, and 1Password only whitelists itself to talk to certain app IDs.

com.brave.Browser.dev is already live
com.brave.Browser.beta will be near Sept 24th.
com.brave.Browser will be near Oct 16th.

We might or might not ever create a nightly updateable build channel, that App ID is: com.brave.Browser.nightly

**Comment by bbondy** [comment]
Moved to 1.0 milestone because it's out of our hands, we're just using this as a holder for when 1Password whitelists the app ids.  I'll move it back here if they complete it in time.

**Comment by rudyrichter** [comment]
I installed the .dev build and it seems that Brave is no longer embedding the 1Password browser extension? is this intended to be the case when this ships the beta and release versions as well?

**Comment by roustem** [comment]
If you have 1Password account then you could also try the new 1Password X extension that does not require the desktop app:

https://chrome.google.com/webstore/detail/1password-x-beta-%E2%80%93-passwo/khgocmkkpikpnmmkgmdnfckapcdkgfaf

**Comment by bbondy** [comment]
Good news, our biz dev team got us in contact with the right people and it looks like we'll have this support soon!

**Comment by roustem** [comment]
This should be fixed in 1Password 7.1.2: 
https://app-updates.agilebits.com/product_history/OPM7

It will also be available in 1Password 7.2 beta soon.

**Comment by bbondy** [comment]
Works like a charm with 7.1.2. Thanks again for your help @roustem!
Closing this issue.

**Comment by notDavid** [comment]
@roustem note that this issue is NOT fixed yet in the non-subscription version of 1Password, currently version 6.8.9: https://app-updates.agilebits.com/product_history/OPM4

Will it be fixed there also?

**Comment by roustem** [comment]
@notDavid When it comes to client apps, there is a single 1Password binary. It can be used with both a license and a subscription. 

1Password 6 is in maintenance mode and we did not plan adding new features there.

**Comment by notDavid** [comment]
> When it comes to client apps, there is a single 1Password binary. It can be used with both a license and a subscription.

Ahhh didn't realise that, thanks!

**Comment by LaurenWags** [comment]
Verification Pass with

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Mac OS X
