### ISSUE TITLE
Don't know why https://dovewallet.com is blocked

### ISSUE THREAD

**Issue by redred77** [brave/brave-browser#9802]
## Description 
Can't view dovewallet.com from brave shield mode.

## Steps to Reproduce
   1. visit dovewallet.com
   2. blocked. circle rotating infinitely.

## Actual result:
![image](https://user-images.githubusercontent.com/680980/82117945-c7c68000-97ae-11ea-8c9a-b523aca47cda.png)

## Expected result:
![image](https://user-images.githubusercontent.com/680980/82117961-e0369a80-97ae-11ea-94e5-c6da94051be7.png)

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave | 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1909 (Build 18363.836)

- Does the issue resolve itself when disabling Brave Shields?
yes

- Does the issue resolve itself when disabling Brave Rewards?
Not sure. didn't try.

- Is the issue reproducible on the latest version of Chrome? 
Nope. brave shield is causing some compatibility issue.

## Miscellaneous Information:

Hi
This site is using
- cloudflare
- google analytics
- nuxt.js (vue.js framework)

Any idea about it?

**Comment by bsclifton** [comment]
cc: @ryanbr is this blocked via EasyList?

**Comment by ryanbr** [comment]
Fixed, not sure why it was blocked. Apologies.

**Comment by bsclifton** [comment]
@redred77 can you please re-test? I'll close issue but please let us know if it works OK now 😄

**Comment by redred77** [comment]
@bsclifton @ryanbr 
I still can't connect.

![image](https://user-images.githubusercontent.com/680980/82271975-50fad400-99b4-11ea-97d1-dba481cdda16.png)

Is Easylist updated regularly? How can I force update the list?

**Comment by bsclifton** [comment]
ah - it might take 24 hours before the list is updated (after the change is made). Let's check back tomorrow
