### ISSUE TITLE
Ledger Nano S won't connect to "Brave Wallets" but WILL connect to other Ledger wallets

### ISSUE THREAD

**Issue by dimyself** [brave/brave-browser#9925]
## Description 

I can connect and use Nano S using Ledger Live and it works fine, and I can connect to other Ledger wallets in Brave browser such as myetherwallet.com. Myetherwallet through Brave can connect to Ledger and find my ETH just fine. Only going through Brave settings -> crypto wallets -> connect Ledger, it just spins when I click on connect. No errors, no logs, no settings available, no idea the problem because there's no options or warnings/msgs

## Steps to Reproduce

   1. Settings -> crypto wallets
   2. My accounts -> Connect hardware wallet -> Ledger -> Connect
   3. It just spins

## Reproduces how often: 

every time

## Brave version (brave://version info)

Brave	1.9.72 Chromium: 81.0.4044.138 (Official Build) unknown (64-bit)
Revision	8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS	Linux
JavaScript	V8 8.1.307.32

## Version/Channel Information:

This problem occurred on previous brave version and updated version

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

Since I added my Ledger into "crypto wallets" in Brave, there is no option for Metamask or other wallets??? Where can I find this option?? If I link Ledger Nano into Brave, I want to also be able to access other wallet extension options such as Metamask. Is this available? The option was there before I added Ledger into Brave crypto wallets. 

Also, how can I delete accounts I create through brave crypto wallets? There's no option to delete accounts?? I want to delete the account I created. The only options I see are connect to hardware, import, restore account. No delete/remove acoount?

***UPDATE So, I tried accessing through Metamask, and it uses the same access method as brave crypto wallets. It has the same exact interface and does the exact same thing, just spins when trying to connect to hardware Ledger wallet. But again, I CAN connect to Ledger going through Brave using independent site like myetherwallet.com...and Ledger Live application works as well. 

Its just the built in Brave crypto wallet access that doesn't work

Thanks you

**Comment by dimyself** [comment]
Just as a followup, I did find this info that Brave wallets is built on Metamask source code, and that Brave wallet code isn't updated by Metamask. Here: https://metamask.zendesk.com/hc/en-us/articles/360038596792-Issues-using-Metamask-in-Brave-browser

So, I'm wondering when I enabled the Brave crypto wallets it messed something up with Metamask or there's some kind of conflict?

As per the article, I was trying to turn off/disable Brave crypto wallet , but there's only the option to use Metamask, use Brave, or "Ask" which to use. Even if I choose Metamask, it still just spins and does the same thing. 

Any ideas? Thank you!

**Comment by amaredeus** [comment]
I'm having the same issue with latest version of ledger nano X

**Comment by guttermonk** [comment]
Tried uninstalling MetaMask, clearing my cache, rebooting, connecting my Ledger, starting Brave, opened Crypto Wallets, and tried to "Connect Hardware Wallet" ...still getting the eternal spinner of death.

**Comment by marshall** [comment]
Could be related to https://github.com/brave/brave-browser/issues/6168

**Comment by nkyms** [comment]
Same problem here. I have tried this on 3 separate PC's and I get the same thing with Brave. On chrome, not getting the problem.

**Comment by srirambv** [comment]
As a workaround, you can logout from your current wallet session, close browser and restart OS and try again. I run into this issue quite often during testing and usually end up nuking profile and trying again. But sometimes just a system restart fixes it (no guarantee's that it will work all the time)

**Comment by pastafazool** [comment]
fixed. you have to be in the Ethereum app in the ledger before connecting to brave.

**Comment by digitalronin** [comment]
Not fixed for me. I just ran into this problem after having used Brave wallet with my Ledger Nano S just fine for months.

**Comment by bbondy** [comment]
There may still be an issue on linux tracked in https://github.com/brave/brave-browser/issues/16082 but otherwise I don't think there's still an issue since we moved to the webHID transport.

**Comment by guttermonk** [comment]
Just tried connecting my Ledger on OSX and, when I press connect, nothing happens. Running version 1.26.77.
